### ISSUE TITLE
Unable to Edit Model Training Parameters

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub#10]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Training

### Bug

I'm not able to edit training parameters here. When I click the edit icon the fields become editable, but then when I click the cursor in the edit field the field disappears and is replaced with the text value.

<img width="1423" alt="Screen Shot 2022-01-11 at 2 01 21 PM" src="https://user-images.githubusercontent.com/26833433/149040565-5823f2d7-5e5b-452a-843f-6a699f6ad02f.png">

### Environment

Ultralytics HUB Version
v0.1.10-beta.2
Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Operating System
MacIntel
Browser Window Size
1311 x 705
Server Timestamp
1641945930

### Additional

First reported in https://github.com/ultralytics/hub/discussions/9

**Comment by kalenmike** [comment]
@glenn-jocher Thanks for submitting this bug. It has been confirmed on our end and we are working on a fix for the next release.

**Comment by kalenmike** [comment]
Deployed in version v0.1.10-beta.3

**Comment by glenn-jocher** [comment]
Great!
