### ISSUE TITLE
Black camera after login

### ISSUE THREAD

**Issue by Fedefirewall** [ultralytics/hub#100]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

Black screen on detection after login, if i dont login, everything is fine
![Screenshot_20221018-185638](https://user-images.githubusercontent.com/61513937/196496191-477ebe56-4147-4dc2-8b2a-e36ce8f813af.png)

### Environment

-Smartphone: pixel 6 pro
-os: Android 13

### Minimal Reproducible Example

1. Login 
2. Go to detect

**Comment by glenn-jocher** [comment]
@Fedefirewall thanks for the bug report! We have an Android update due to be released in the next few days that may resolve this issue.

@sergiossm could you tell us about our Android app status? Thanks!

**Comment by Fedefirewall** [comment]
@sergiossm thanks for the fast answer!
Hope the update Will be rolled out soon!
