### ISSUE TITLE
Remove Default Settings Warning Notification

### ISSUE THREAD

**Issue by pderrenger** [ultralytics/hub#106]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Default Settings Warning Notification should disappear once changes have been saved. 

There is a box that says "Default settings have been optimized for best results in most use cases. Change only if you are an expert user." with an option to reset or save. If "save" is selected, the box should disappear. 

<img width="1380" alt="Screenshot 2022-10-21 at 17 03 19" src="https://user-images.githubusercontent.com/107626595/197237595-8d9a00e1-4cd6-47a7-8b58-baebd24dddc3.png">

### Use case

This feature change would improve user experience.

**Comment by kalenmike** [comment]
@pderrenger The box remains so that the user has the option to reset back to the default options.
