### ISSUE TITLE
Can I get an output of image coordinates of the detected objects with unique id and corresponding frame number in a text file or excel file?

### ISSUE THREAD

**Issue by zsefvbhu** [ultralytics/hub#108]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Can I get an output of image coordinates of the detected objects with a unique id and corresponding frame number in a text file or excel file? ClearML gives the output of training results, but I want output of detections detected in a video.

**Comment by kalenmike** [comment]
@zsefvbhu Thanks for the question. Currently the only way would be to split your video into frames and run inference on each frame. This sounds like an interesting task and I will look into it more, perhaps we can handle everything for you on the server and just send back the results from your uploaded video.

**Comment by glenn-jocher** [comment]
@zsefvbhu you can't do this in HUB yet, but you can download your HUB model and use it with the YOLOv5 repo, i.e. with detect.py for videos using --save-txt to output to text file, or using PyTorch Hub inference for the most flexibility (recommended).

YOLOv5 🚀 [PyTorch Hub](https://github.com/ultralytics/yolov5/issues/36) models allow for simple model loading and inference in a pure python environment without using `detect.py`. 

### Simple Inference Example

This example loads a pretrained YOLOv5s model from PyTorch Hub as `model` and passes an image for inference. `'yolov5s'` is the YOLOv5 'small' model. For details on all available models please see the [README](https://github.com/ultralytics/yolov5#pretrained-checkpoints). Custom models can also be loaded, including custom trained PyTorch models and their [exported](https://github.com/ultralytics/yolov5/issues/251) variants, i.e. ONNX, TensorRT, TensorFlow, OpenVINO YOLOv5 models.

```python
import torch

# Model
model = torch.hub.load('ultralytics/yolov5', 'yolov5s')  # yolov5n - yolov5x6 official model
#                                            'custom', 'path/to/best.pt')  # custom model

# Images
im = 'https://ultralytics.com/images/zidane.jpg'  # or file, Path, URL, PIL, OpenCV, numpy, list

# Inference
results = model(im)

# Results
results.print()  # or .show(), .save(), .crop(), .pandas(), etc.
results.xyxy[0]  # im predictions (tensor)

results.pandas().xyxy[0]  # im predictions (pandas)
#      xmin    ymin    xmax   ymax  confidence  class    name
# 0  749.50   43.50  1148.0  704.5    0.874023      0  person
# 2  114.75  195.75  1095.0  708.0    0.624512      0  person
# 3  986.00  304.00  1028.0  420.0    0.286865     27     tie

results.pandas().xyxy[0].value_counts('name')  # class counts (pandas)
# person    2
# tie       1
```
<img width="550" src="https://user-images.githubusercontent.com/26833433/149679662-b2021c78-59b2-4f52-b768-1e5161537c85.png">

See [YOLOv5 PyTorch Hub Tutorial](https://github.com/ultralytics/yolov5/issues/36) for details.

Good luck 🍀 and let us know if you have any other questions!

**Comment by zsefvbhu** [comment]
How can i run this model in a video file?

**Comment by kalenmike** [comment]
@zsefvbhu Using YOLOv5 you just need to use the correct arguments.
```
python detect.py --source 0  # webcam
                          img.jpg  # image
                          vid.mp4  # video
                          screen  # screenshot
                          path/  # directory
                          'path/*.jpg'  # glob
                          'https://youtu.be/Zgi9g1ksQHc'  # YouTube
                          'rtsp://example.com/media.mp4'  # RTSP, RTMP, HTTP stream
```

**Comment by zsefvbhu** [comment]
no loop through frame is required?

**Comment by kalenmike** [comment]
@zsefvbhu Sorry I misunderstood you, this will generate frames with the bounding boxes overlayed. It will not return the data for plotting.

**Comment by zsefvbhu** [comment]
Ok, I actually need those pixel coordinates like Xmin, Ymin, Xmax, Ymax for those detection bounding boxes

**Comment by UltralyticsAssistant** [comment]
@zsefvbhu you can run inference on a video file with the YOLOv5 PyTorch Hub model to obtain the bounding box coordinates for each detection. After loading your model using the `torch.hub.load()` method, you can process the video by iterating through each frame, running inference, and extracting the `results.xyxy` tensor, which contains the bounding box coordinates.

For processing the video, you would typically use either OpenCV or a similar library to read the video frame by frame, perform inference on each frame using the model, and then collect the results. The `results.xyxy` tensor for each frame will give you the bounding boxes with the [xmin, ymin, xmax, ymax, confidence, class] format. You can then save these results to a text file or convert them to a format suitable for Excel.

Remember that iterating through video frames and processing them is not a feature directly provided by YOLOv5's PyTorch Hub interface but can be accomplished with additional coding. You have to extract and handle the video frames and the loop mechanism in your script. The `results.xyxy` tensor will provide the bounding box coordinates that you require.
