### ISSUE TITLE
Dataset processing 

### ISSUE THREAD

**Issue by UnkoC0wbOy** [ultralytics/hub#11]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Processing times are over 48 hours to upload relatively small datasets <500 images. Datasets have been downloaded straight from Roboflow using the YOLOv5 PyTorch option. I have had to manually change the .YAML file name to match the dataset and zipped file name. While trying to trouble shoot the issue I noticed that the downloaded file from Roboflow has a different file structure than the COCO6 dataset used as an example of what our dataset should look like.  I understand that Ultralytics has no control over how the Roboflow datasets are configured.... 

Correcting the file structure would take manual file dragging and dropping while requiring edits to the .YAML file. If this is what is required I will just have to suck it up.. Perhaps I am missing something right in front of my face at the same time... 

### Environment

Ultralytics HUB Version
v0.1.10-beta.2
Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.2 Safari/605.1.15
Operating System
MacIntel
Browser Window Size
1850 x 878
Server Timestamp
1641964834

**Comment by kalenmike** [comment]
@UnkoC0wbOy Thank you for submitting this bug. The dataset you are trying to upload is not formatted correctly, both the YAML and the folder structure of the zip are incorrect. I have corrected the format and attach the zip here for you to use as reference. 

[Sheds.zip](https://github.com/ultralytics/hub/files/7856676/Sheds.zip)

I have also replaced your last attempt with the correctly formatted dataset which you should now be able to preview in your Ultralytics HUB account. The processing took less than 5 minutes if you would like to try again with the correctly formatted zip file.

We did identify a bug that prevented the dataset moving from processing to failed when submitted incorrectly. We will address this for the next release.

Let me know if there is anything else we can do to help.

**Comment by kalenmike** [comment]
Smaller datasets are now validated before upload (> v0.1.10-beta.3). An error message is displayed if the the dataset is formated incorrectly to help with debugging.

**Comment by glenn-jocher** [comment]
@kalenmike awesome, nice work!!
