### ISSUE TITLE
How do I increase my rate limit?  

### ISSUE THREAD

**Issue by gblikas** [ultralytics/hub#110]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I'm using Google Colab to run the Ultralytics API, through the provided workflow, via hub.ultralytics.com. And, I'm trying to train my own inference using a provided Dataset, and the YOLOv5n model. However, after a while, the training stopped, and when I re-connected to my runtime, I tried running `ultralytics.start` (as per the Colab Notebook). However, _Google Colab produced no helpful output, and did not start training_; I had to write a script to debug it, and it produced the following output: 

```shell
Ultralytics: Rate limit reached. Try again later or increase your rate limit at https://hub.ultralytics.com
```

I went to https://hub.ultralytics.com in order to increase my rate limit, however, there is no such option. The closest thing seems to be https://ultralytics.com/pricing, however, 2/3 options don't have a consumer-facing option to correct the issue. 

### Additional

```python
%pip install ultralytics  # install
import ultralytics
ultralytics.checks()
```

produced, 

```shell
Ultralytics 🚀 0.0.35 Python-3.7.15 torch-1.12.1+cu113 CUDA:0 (A100-SXM4-40GB, 40536MiB)
Setup complete ✅ (12 CPUs, 83.5 GB RAM, 22.9/166.8 GB disk)
```

**Comment by glenn-jocher** [comment]
@gblikas hi, thanks for the bug report! We may have set rate limits a bit too strict, we will take a look at loosening these a bit. In the meantime if you wait 15 minutes you should be able to try again. Let me know if this works for you, thanks!

@kalenmike @AyushExel

**Comment by gblikas** [comment]
> @gblikas hi, thanks for the bug report! We may have set rate limits a bit too strict, we will take a look at loosening these. In the meantime if you wait 15 minutes you should be able to try again. Let me know if this works for you, thanks!
> 
> @kalenmike @AyushExel

@glenn-jocher A timer/count-down would be helpful as well! Also, some documentation or tutorial links about how rates are calculated would be helpful: what part are we limiting against, etc..

**Comment by gblikas** [comment]
@kalenmike @AyushExel  @glenn-jocher Update: I've waited roughly 20min, and the model still hasn't resumed training

**Comment by AyushExel** [comment]
@gblikas were you able to run a few times before the rate limit error within these 2 hours?
If that's not the case then I might be the culprit here. I might've started and interrupted too many runs which caused something with the server.

**Comment by gblikas** [comment]
> @gblikas were you able to run a few times before the rate limit error within these 2 hours?

@AyushExel Last successful run was 3ish hours ago, 

<img align="center" width="1626" alt="Screen Shot 2022-10-29 at 3 03 39 PM" src="https://user-images.githubusercontent.com/13577108/198854016-e8cb31f6-a423-4f7b-81a8-9568db3ad2fe.png">

**Comment by AyushExel** [comment]
No no 😆  .. started and interrupted training runs from hub client

**Comment by gblikas** [comment]
> No no 😆 .. started and interrupted training runs from hub client. Let me know whenever it starts working again for you

@AyushExel So I am supposed to wait... Not a super satisfying answer... what is the typical rate-limit timeout? Also, if the issue is from starting and stopping things from the client, how do I know it will re-connect - are there troubleshooting steps I can take to guarantee it re-connects?

**Comment by AyushExel** [comment]
@gblikas hey I'm not the developer please wait for Kalen to respond, it's midnight in his timezone. I was also just trying HUB today. I'm just guessing here. I asked you to let me know because I wanted to confirm from my end too.

**Comment by gblikas** [comment]
@AyushExel  Apologies! Will do!

**Comment by glenn-jocher** [comment]
@AyushExel seems like we have LOGGER issues in Colab also. Error message is not visible in Colab, but appears locally in PyCharm, i.e.

<img width="771" alt="Screenshot 2022-10-30 at 01 49 05" src="https://user-images.githubusercontent.com/26833433/198856627-2ab65db0-ac9a-4c64-86f6-40e4417c425b.png">

**Comment by gblikas** [comment]
> @AyushExel seems like we have LOGGER issues in Colab also. Error message is not visible in Colab, but appears locally in PyCharm, i.e.

@glenn-jocher Your statement is consistent with my findings as well; The error(s) appears only when the command(s) are run from the terminal, rather than the Colab Notebook.

**Comment by gblikas** [comment]
@AyushExel @glenn-jocher Just tried now, and it is working again - roughly 6 to 8 hours later.

**Comment by glenn-jocher** [comment]
@gblikas thanks for the info! We'll keep looking into this, please let us know if the issue returns.

**Comment by kalenmike** [comment]
@gblikas We have rate limits applied for seconds, minutes, hours, and days. If you reach your cap in any of these windows then you need to wait the same amount of time before your request will be accepted again.

You can check the status of your applied rate limiting by checking the response header as shown in the attached picture.

![image](https://user-images.githubusercontent.com/25989362/199079072-0836477e-286b-4298-81c9-d4e9a80782d2.png)

**X-RateLimit-Limit:** The request limit applied to the current window
**X-RateLimit-Remaining:** The remaining requests in the current window
**X-RateLimit-Reset:** The timestamp when the current window resets
*window refers to which limits are currently applied (second, minute, hour, day, month)

Rate limits can be increased by switching to a paid plan. We have not rolled out the paid plans globally, if you are interested in upgrading before the public release let me know and we can get in touch about the available options.

**Comment by gblikas** [comment]
@kalenmike Thanks for getting back to me on this! 

> We have rate limits applied for seconds, minutes, hours, and days.

I'm still not sure what features of the API I'm getting rate-limited against... This information would be helpful to avoid this problem in the future. 

>  You can check the status of your applied rate limiting by checking the response header as shown in the attached picture.

I'm using Colab; how do I do this? 

> Rate limits can be increased by switching to a paid plan. We have not rolled out the paid plans globally, if you are interested in upgrading before the public release let me know and we can get in touch about the available options.

I'm not sure if I need to go on the paid plan, but also, don't have enough information to determine. Given your explanation, it seems like any time the Colab was put into the background or perhaps disconnected _once_, a user would need to upgrade to a paid plan; given the price, this might be expensive. Let's [DM on Twitter](https://twitter.com/gblikas_ceo) to discuss more.

**Comment by kalenmike** [comment]
@gblikas Hopefully I can clear up some of the confusion.

The rate limits are applied to any request to our servers as the connection is via a third party (Colab or Your Local Agent). During training there are several requests to the server to fetch information and then to upload the metrics and checkpoints back up. All of these count against your request limits.

Your account limits are currently set as:
`2/seconds, 10/minute, 50/hour, 100/day`

You can paste this command into Colab to see the headers in your request (this counts as one request):
`!curl --head -X POST https://api.ultralytics.com`
*The lowest limit will always show up

We are also going to show the timestamp in the 'Rate Limit Reached' message you were seeing before which should help you. This will come in a future release of the pip package.

If your Colab instance disconnects it will not affect your rate limits. There is only one request to start training, one per epoch to send back the metrics, and one at calculated intervals to send back weights for resuming. The quickest way to reach your request limit is to train a small model on a small dataset as it would complete each epoch very quickly.

**Comment by gblikas** [comment]
@kalenmike Thank you much for the feed back! Regarding, 

> Your account limits are currently set as:
2/seconds, 10/minute, 50/hour, 100/day

How do these Rate-Limits work, when the default Epoch count is set to 300? It sounds like with the default Hub settings, it would take 3 days to train with the default settings. Is that the case?

**Comment by glenn-jocher** [comment]
@gblikas 1 usage == 1 training. So theoretically you could train up to 100 models per day.

**Comment by gblikas** [comment]
> @gblikas 1 usage == 1 training. So theoretically you could train up to 100 models per day.

@glenn-jocher , @kalenmike had said this, 

> There is only one request to start training, one per epoch to send back the metrics, and one at calculated intervals to send back weights for resuming. 

This implies that there is one "usage" per Epoch; @glenn-jocher Are you saying that is not the case?

**Comment by kalenmike** [comment]
@gblikas Correct, the the limits are applied per epoch not per training. You can currently train up to 100 epochs per day, depending on the speed of training.

**Comment by glenn-jocher** [comment]
@gblikas sorry for the confusion. We've updated rate limits accordingly so you should be able to train many models per day to 300 epochs each. This should be in effect now using `ultralytics==0.0.37`.

Please let us know if you have any other issues or feedback for improving HUB!

**Comment by kalenmike** [comment]
@gblikas We gave it some thought and move a few things around. You will be happy to hear that this allowed us to increase our limits.
The new default limits are:
`2/seconds, 62/minute, 400/hour, 6200/day`

**Comment by gblikas** [comment]
> @gblikas We gave it some thought and moved a few things around. You will be happy to hear that this allowed us to increase our limits. The new default limits are: `2/seconds, 62/minute, 400/hour, 6200/day`
> 
> As @glenn-jocher mentioned you should be able to train many smaller models per day with these new limits.

@kalenmike I'll give this a shot soon; perhaps we can close the issue... Unfortunately, I need more compute units to make the training viable. It would be _awesome_ ,if ya'll did a promotion for computer units with GCP/Colab 😏

**Comment by glenn-jocher** [comment]
@gblikas that's not a bad idea... but ya unfortunately Google started capping Colab usage on faster GPUs. I'm on the Pro+ plan for $50/mo and it looks like I have as much T4 time as I want, but V100 time seems rationed with the units now.

**Comment by gblikas** [comment]
> but ya unfortunately Google started capping Colab usage on faster GPUs.

I think you can buy 100 compute units in 10$ chunks as much as you want, giving you access to V100 - albeit expensively 🤣

**Comment by glenn-jocher** [comment]
@gblikas yeah I don't know if it's that different than just straight GCP pricing. Let me see what GCP shows. Ok V100 would be $2.00/hr on demand, $0.82/hr spot price.

How many hours does $10 of credits buy you?

**Comment by gblikas** [comment]
> @gblikas yeah I don't know if it's that different than just straight GCP pricing. Let me see what GCP shows. Ok V100 would be $2.00/hr on demand, $0.82/hr spot price.
> 
> How many hours does $10 of credits buy you?

Via Colab pricing, $10 - 100 compute units - is ~200 Epoch worth of computing with my models; VisDrone in YOLOv5n. So, it doesn't quite train a full model - it seemed to take around 8 hours to do the ~200 epochs.

**Comment by glenn-jocher** [comment]
@gblikas ok, so halfway between spot and on demand pricing. If you're training mostly Colab make sure you are using RAM or Disk caching here, this will likely speed up your training. Try RAM first, then disk if you run out of RAM.

<img width="1367" alt="Screenshot 2022-11-01 at 19 50 28" src="https://user-images.githubusercontent.com/26833433/199314520-9dd068f0-b363-4b64-a778-5d79ff883568.png">

**Comment by gblikas** [comment]
> If you're training mostly Colab make sure you are using RAM or Disk caching here, this will likely speed up your training. 

@glenn-jocher Yes, I was uing RAM cache.

**Comment by gblikas** [comment]
@kalenmike This was marked as completed, but there is no PR showing that it was "solved", as such, it probably shouldn't be marked as completed without linking to an actual fix?

**Comment by glenn-jocher** [comment]
@gblikas hi, sorry I think we assumed the issue was resolved due to our above changes. Are you still experiencing rate limit issues with the latest ultralytics package?

We'll be open-sourcing the ultralytics pip package repository in January 2023, and then we'll be able to better link PRs to issues.
