### ISSUE TITLE
Make Model API Key, Or URL, Available For Easy Colab Setup, Post Training

### ISSUE THREAD

**Issue by gblikas** [ultralytics/hub#112]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Currently, once a custom model is done training, the API key that you insert into Colab is gone from the hub UI, 

<img width="1805" alt="Screen Shot 2022-10-31 at 11 17 26 AM" src="https://user-images.githubusercontent.com/13577108/199080873-86ec52a7-3db5-42e7-84af-bbfc244f121d.png">

It would be ideal to ideal to leave the API key up or provide the URLs for the trained models' weights/export available; re-downloading (exporting) the weights each time is cumbersome, and uploading them directly to persistent cloud storage seems like duplication of data. 

### Use case

Ultralytics Hub currently defaults to using Colab, in order to launch the training step. This works out well for training, but once training is complete, the only way to access the inference is to go through the "Export" UI.  When using Colab, the typical user-flow is a non-persistent one; when it comes to just using the inference, i.e. running `detect.py`, we need to auto-download the inference (weight) (exported) file. 

Much like the training process, having the ability to reference, a URL, or API key to easily reference and download the given target export would make the Colab flow more consistent, and convenient; the "Export" UI is already doing something like this in the background, exposing it to end-users would be nice.

**Comment by kalenmike** [comment]
@gblikas Thanks for the feedback! We are currently working on exposing all of the API's via the PIP package. When this code is finished and released you will be able to choose between using the GUI interface or using python/bash for all tasks.

**Comment by gblikas** [comment]
> @gblikas Thanks for the feedback! We are currently working on exposing all of the API's via the PIP package. When this code is finished and released you will be able to choose between using the GUI interface or using python/bash for all tasks.

@kalenmike  My feature request might be wrapped up in this, but it seems like it is already there, however, disappears after training is complete. How come not just persist the API key? 

> Have you had a chance to try out our iOS and Android app for inference yet?

Tried it, and the iOS/Android app is a _very_ helpful tool! However,  that doesn't help my Colab use-case.

**Comment by kalenmike** [comment]
@gblikas At the moment we hide the API key because it has no use after training. The API key we show you for training is a concatenation of your accounts API key and the model ID.

You can get your API key from https://hub.ultralytics.com/settings by clicking on the API Key tabs.

You can get your model id by opening the model and looking at the address bar it is the string after `models/`
https://hub.ultralytics.com/models/znkucaCwqSGSfOzONecT would be znkucaCwqSGSfOzONecT

These are then joined with an underscore. `API_MODEL`

Once training is completed, the model cannot be trained again and using the original key will result in an 'already trained' notice.

**Comment by gblikas** [comment]
> @gblikas At the moment we hide the API key because it has no use after training. The API key we show you for training is a concatenation of your accounts API key and the model ID.
> 
> You can get your API key from https://hub.ultralytics.com/settings by clicking on the API Key tabs.
> 
> You can get your model id by opening the model and looking at the address bar it is the string after `models/` https://hub.ultralytics.com/models/znkucaCwqSGSfOzONecT would be znkucaCwqSGSfOzONecT
> 
> These are then joined with an underscore. `API_MODEL`

@kalenmike Thanks! This is what I wanted to know. Apologies, if I missed this in the documentation somewhere!
