### ISSUE TITLE
Optimizer selection

### ISSUE THREAD

**Issue by lakyfarky** [ultralytics/hub#113]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi, is there a possibility to change the optimizer during the training via google colab API?

**Comment by glenn-jocher** [comment]
@lakyfarky in any AI application training settings are defined prior to training start and are not modified once training starts.

**Comment by lakyfarky** [comment]
Oh my bad... I thought "before the training". I didn't see optimizer settings on the hub so I changed default optimizer in train.py before train with API in colab.
