### ISSUE TITLE
How to create a NODE in the HUB for sharing within an organization?

### ISSUE THREAD

**Issue by rspandolfi** [ultralytics/hub#116]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

At Kashmir World Foundation, we have students, interns, academics, and professionals from around the world collaborating on use of YOLOv5 to protect endangered species. We are looking for options within the Ultralytics HUB to enable sharing access among the Team. Is it possible to set up a Team account?

**Comment by kalenmike** [comment]
@rspandolfi Thanks for the question. We are currently working on releasing a teams feature that will allow you to do everything you need. Its the current active feature and will be the next one out the door.

**Comment by glenn-jocher** [comment]
@rspandolfi yes as Kalen mentioned we're currently working on a Teams feature. 

Could you tell us a little more about your teams? i.e. would you want one team for your entire organization, or several smaller teams? Might users be present in multiple teams?

**Comment by rspandolfi** [comment]
Hi Glenn,

The taxonomy within Kashmir World Foundation is somewhat complex. The
larger project we will be deploying on your hub is Trinity. Under that are
Andromeda, Centaurus, Draco, Orion, and Pegasus. Of these, only Draco will
be involved with YOLOv5. Draco is split between two internal teams, but
they will all be sharing the same information.

If you are creating a HUB that supports complex taxonomies, then ours will
be KwF at the highest level, Trinity next level down, and Draco next level
down. All initial members will be in Draco.

Thanks,

Ron



Ronald Pandolfi, Ph.D.
Director, TACP-Network
CTO, Kashmir-Robotics,
a division of Kashmir World Foundation
www.KashmirWorldFoundation.org <http://www.kashmirworldfoundation.org/>

**Comment by glenn-jocher** [comment]
@rspandolfi thanks for the info! We'll try to keep the teams flexible to allow users to join multiple teams :)
