### ISSUE TITLE
Сan't upload a 2 GB dataset to Ultralytics HUB, the download freezes at 9%.

### ISSUE THREAD

**Issue by DonkeySmall** [ultralytics/hub#118]
Сan't upload a 2 GB dataset to Ultralytics HUB, the download freezes at 9%.

**Comment by glenn-jocher** [comment]
@DonkeySmall hi, thanks for the bug report! You should be able to upload 2GB datasets without any problems. Can you share the dataset zip with us to help us reproduce the issue? If you'd like to share privately you can email glenn.jocher@ultralytics.com
