### ISSUE TITLE
2x attempts on scheduled CI

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub#121]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Run CI a second time after a first fail, only apply to scheduled runs. @kalenmike 

### Use case

Mitigate false alarms, i.e. network failures, unreproducible errors.

**Comment by kalenmike** [comment]
CI has been significantly improved recently.
