### ISSUE TITLE
How to upload locally trained model files?

### ISSUE THREAD

**Issue by c-eckert** [ultralytics/hub#122]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi there,

is there a way to upload my yolov5 models, which are already trained locally without connection to ultralytics HUB?
My goal is, to check the inference of my models with my Smartphone, but I didn't find a way, without retrain my whole model, like shown in https://github.com/ultralytics/hub/issues/31#issuecomment-1143387635 ?

**Comment by glenn-jocher** [comment]
@c-eckert thanks for the feature request! We have this feature in our roadmap and are planning to release this sometime in Q1 2023.

**Comment by c-eckert** [comment]
Okay great, thanks for the response❤️

**Comment by UltralyticsAssistant** [comment]
@c-eckert you're welcome! I'm glad I could help. Keep an eye on our updates for when this feature becomes available. If you have more questions or need further assistance in the future, feel free to reach out. Remember, the YOLO community and the Ultralytics team are here to support you.
