### ISSUE TITLE
Group account to enable collaboration on projects

### ISSUE THREAD

**Issue by rspandolfi** [ultralytics/hub#124]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is there a way to create a group account or otherwise enable collaboration on projects without public access?

**Comment by glenn-jocher** [comment]
@rspandolfi they'll be separate, but I think one Ultralytics team will have access to all of the same shared Roboflow datasets.
