### ISSUE TITLE
Inport model

### ISSUE THREAD

**Issue by Mateusvision** [ultralytics/hub#126]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

how can i use a model trained by me?

**Comment by kalenmike** [comment]
@Mateusvision We currently only support models trained using the Ultralytics HUB. In mid January we will allow models trained locally to be imported into the Ultralytics HUB however this will only apply to models trained after the new release.
