### ISSUE TITLE
CVAT integration

### ISSUE THREAD

**Issue by Inthuch95** [ultralytics/hub#127]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Import dataset from CVAT and train the model

### Use case

My team uses CVAT to label data so it would be nice to be able to import dataset from CVAT

**Comment by kalenmike** [comment]
@Inthuch95 Thanks for the feedback. Are you currently able to manually export your data from CVAT and import it into the Ultralytics HUB?

**Comment by kalenmike** [comment]
@Inthuch95 Got you! We can look at integrating directly but this may take some time if we need work done on their end. Perhaps in the meantime we can create an import tool for you. Could you send me a small dataset (2 images in each set) in the CVAT export format?

**Comment by Inthuch95** [comment]
[sample-dataset.zip](https://github.com/ultralytics/hub/files/10183831/sample-dataset.zip)
I usually export in this format then:

- Split train/val/test
- Convert to yolov5 structure (separate images and labels folders)

**Comment by kalenmike** [comment]
@Inthuch95 Ok thanks, I will take a look and see what we can do to speed up your workflow.
