### ISSUE TITLE
Integration deployment my yolov5 model in ultralytics app

### ISSUE THREAD

**Issue by HripsimeS** [ultralytics/hub#128]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

@glenn-jocher @AyushExel @kalenmike @sergiossm @sergiuwaxmann  Hello Ultralytics team!

I have trained my dataset with yolov5s model on ultralytics hub and my model is saved in **Models**. Please can you let me know how I can integrate/deploy my trained model in ultralytics app to be able to check the object detection with my phone. 

Look forward to hearing from you!

**Comment by sergiossm** [comment]
Hey @HripsimeS! You simply need to download our app, sign in and navigate to your HUB project. You'll see a list of trained models, just click the top right button on the model list tile to start the download. Then, select it and that's it!

Let us know if you encounter any issues. Thank you!

> ### Search before asking
> 
> - [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.
> 
> 
> ### Description
> 
> @glenn-jocher @AyushExel @kalenmike @sergiossm @sergiuwaxmann  Hello Ultralytics team!
> 
> 
> 
> I have trained my dataset with yolov5s model on ultralytics hub and my model is saved in **Models**. Please can you let me know how I can integrate/deploy my trained model in ultralytics app to be able to check the object detection with my phone. 
> 
> 
> 
> Look forward to hearing from you!
> 
> ### Use case
> 
> _No response_
> 
> ### Additional
> 
> _No response_

**Comment by HripsimeS** [comment]
@sergiossm it worked perfectly, thanks! I will close this issue 🥇
