### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by BHAVYASHAHM123** [ultralytics/hub#129]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Not able to login into the mobile app.
after training the model in this ultralytics I downloaded the model for mobile so where to add that model and how?

**Comment by BHAVYASHAHM123** [comment]
How to use my model in the Android app?

**Comment by kalenmike** [comment]
Hi @BHAVYASHAHM123 are you having trouble signing into your account on the mobile app?

https://github.com/ultralytics/hub/issues/128#issuecomment-1344379134
