### ISSUE TITLE
tensorflow.js model

### ISSUE THREAD

**Issue by hakmesyo** [ultralytics/hub#130]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have just converted my yolov5 trained model to tensorflow.js model and then i downloaded it. What should i do next? Please could you provide simple javascript code to run my tfjs model. Thanks in advance.

**Comment by glenn-jocher** [comment]
@hakmesyo you can use your TF.js model like this:

```python
# YOLOv5 TensorFlow.js Usage 
$ cd .. && git clone https://github.com/zldrobit/tfjs-yolov5-example.git && cd tfjs-yolov5-example
$ npm install
$ ln -s ../../yolov5/yolov5s_web_model public/yolov5s_web_model
$ npm start
```
