### ISSUE TITLE
The code does not run

### ISSUE THREAD

**Issue by SMSajadi99** [ultralytics/hub#132]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects, Training, API Key

### Bug

**WARNING:ultralytics:Ultralytics: Unhandled server error. Retrying 3x for 30s. If this issue persists please visit https://github.com/ultralytics/hub/issues for assistance. (500 #0)**

I run it in google collab with the code that the site gives me, but it gives me this error, what should I do?

![bug_code](https://user-images.githubusercontent.com/69210109/209483316-710cbe9a-947f-46b4-9b64-a6de74a00814.png)

**Comment by SMSajadi99** [comment]
> 👋 Hello @SMSajadi99, thank you for raising an issue about [Ultralytics HUB](https://ultralytics.com/hub) 🚀! Please visit https://ultralytics.com/hub to learn more, and see our ⭐️ [HUB Guidelines](https://github.com/ultralytics/hub) to quickly get started uploading datasets and training YOLOv5 models.
> 
> If this is a 🐛 Bug Report, please provide screenshots and steps to recreate your problem to help us get started working on a fix.
> 
> If this is a ❓ Question, please provide as much information as possible, including dataset, model, environment details etc. so that we might provide the most helpful response.
> 
> We try to respond to all issues as promptly as possible. Thank you for your patience!

**Comment by glenn-jocher** [comment]
@SMSajadi99 hi! I'm sorry to see you are having problems. Is this still happening for you?

**Comment by glenn-jocher** [comment]
@SMSajadi99 I just tried training now and everything works well for me. Can you try again and let us know if this issue persists for you? Thanks!

<img width="1337" alt="Screenshot 2022-12-27 at 14 40 29" src="https://user-images.githubusercontent.com/26833433/209675098-d4eec2d6-7887-4247-8e91-2abba9aab456.png">

**Comment by SMSajadi99** [comment]
> @SMSajadi99 I just tried training now and everything works well for me. Can you try again and let us know if this issue persists for you? Thanks!
> 
> <img alt="Screenshot 2022-12-27 at 14 40 29" width="1337" src="https://user-images.githubusercontent.com/26833433/209675098-d4eec2d6-7887-4247-8e91-2abba9aab456.png">

Hi
Unfortunately, I just now understood where the problem comes from...
When we select the model on the site, if we turn on the previously train-mode to run from the beginning, we will encounter this problem.
But if that button is on, there is no problem and it will run
I got two codes from the site, one for Google colab:
70e53a3ca9386b486074dd132ee540b326db4367fa_eRW57eHtWrOVhxlQBxp7

And another on my system:
70e53a3ca9386b486074dd132ee540b326db4367fa_cKwKjQ9x8aFUhzHQQAzk

Thank you for helping me how to use the code without first training.

**Comment by SMSajadi99** [comment]
Hi
Unfortunately, I just now understood where the problem comes from...
When we select the model on the site, if we turn on the previously train-mode to run from the beginning, we will encounter this problem.
But if that button is on, there is no problem and it will run
I got two codes from the site, one for Google colab:
70e53a3ca9386b486074dd132ee540b326db4367fa_eRW57eHtWrOVhxlQBxp7

And another on my system:
70e53a3ca9386b486074dd132ee540b326db4367fa_cKwKjQ9x8aFUhzHQQAzk

Thank you for helping me how to use the code without first training.

**Comment by SMSajadi99** [comment]
The following code is for the mode without previous training:

![after](https://user-images.githubusercontent.com/69210109/209691556-3c589bf8-4aad-4b83-9cd5-c01ed5ccbe59.png)


The following code is for the mode with the previous training:

![before](https://user-images.githubusercontent.com/69210109/209691588-da8b6273-3c2a-493e-8476-3addf0fcd416.png)

**Comment by kalenmike** [comment]
@SMSajadi99 Thanks for raising this, we confirmed your error and are releasing a fix today.

**Comment by SMSajadi99** [comment]
> 

Thank you very much, it is an honor to help you.

**Comment by kalenmike** [comment]
The patch has been released, training without pretrained weights is working again.
