### ISSUE TITLE
Incorrect display (validate)

### ISSUE THREAD

**Issue by NeuralAIM** [ultralytics/hub#133]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets, Training

### Bug

![image](https://user-images.githubusercontent.com/75082388/210113294-8db2b04b-b848-468f-9665-6770c6828e38.png)

### Additional

On the model training page in the dataset visualization window, the validate icon in the bottom

**Comment by kalenmike** [comment]
@NeuralAIM Thanks for raising this. We will look into the frontend. Do you might sharing the information on your support tab?
![image](https://user-images.githubusercontent.com/25989362/210228843-3a803891-b0b4-489c-a352-95da79b294fd.png)

**Comment by NeuralAIM** [comment]
Ultralytics HUB Version
v0.1.17-beta.1
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
2048 x 1034
Server Timestamp
1672680717

**Comment by kalenmike** [comment]
This is noted on our internal issue tracker and work is pending to resolve this bug.
