### ISSUE TITLE
Rate limit reached (0/400). Please retry after

### ISSUE THREAD

**Issue by NeuralAIM** [ultralytics/hub#134]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I started training a model (for the first time), but 200 epochs later I get it:

![image](https://user-images.githubusercontent.com/75082388/210113468-004bf780-a51f-40ae-8c28-56e9c658edbe.png)

![image](https://user-images.githubusercontent.com/75082388/210113503-534d4839-d08d-4272-93f1-cf0d1745f369.png)

**Comment by kalenmike** [comment]
@NeuralAIM Thanks for raising this question. It looks like the model might be training too fast and it getting rate limited. Can you share the base model you are using and how many images are in your dataset?

**Comment by lalitjoshi1989** [comment]
@NeuralAIM I am getting the same issue, so reverting back to the same thread. I am trying to train **YOLOv5s** on my custom dataset with **621** images.

![image](https://user-images.githubusercontent.com/83167348/211813690-d76a8017-d503-4ff4-82da-80b89a5e9f69.png)

![image](https://user-images.githubusercontent.com/83167348/211813767-d1ce7419-f1c0-450a-b82a-4d04f60ea554.png)

**Comment by kalenmike** [comment]
@lalitjoshi1989 Thank you for bringing this to our attention. We are investigating the limitations and exploring ways to increase them. This may cause some delay in the updating of your metrics on the Ultralytics HUB, but it will not affect the ability to train your models.
