### ISSUE TITLE
Ultralytics Android doesn't export 

### ISSUE THREAD

**Issue by endersonO** [ultralytics/hub#136]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

I had been training a model in Ultralytics hub. And when I try to export in Android support it doesn't work. It was exporting in IOS, and TensorFlow format but it doesn't work with Android format

**Comment by kalenmike** [comment]
@endersonO Thanks for reaching out. Are you attempting the export from the App or the Web? Could you send me the URL from your model page so that I can look into this further?

**Comment by endersonO** [comment]
Hello this is the url from my model
https://hub.ultralytics.com/models/ZRHsFLSHCvl7ohvNt7eD

**Comment by endersonO** [comment]
![image](https://user-images.githubusercontent.com/42153113/210896942-3150b19a-a547-4f6a-aa3a-eebbcf3fb992.png)
every time it say me this

**Comment by kalenmike** [comment]
@endersonO Ok, thanks for the URL. I will take a look at your model and see if I can see what is going on.
