### ISSUE TITLE
how to install Ultralytics on my VPS?

### ISSUE THREAD

**Issue by nichiporets** [ultralytics/hub#137]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! A quick q.

I try running :

pip install -U ultralytics

And I get this error:

Looking in indexes: http://mirrors.tencentyun.com/pypi/simple
ERROR: Could not find a version that satisfies the requirement ultralytics (from versions: none)
ERROR: No matching distribution found for ultralytics

Please advise how can I still install it :)

**Comment by kalenmike** [comment]
@nichiporets Thanks for the question. The command you specified should work without fail, so it seems there is an issue with your VPS. There are a few things that could be going wrong here. Here are some things you can try.

1. Make sure that you have the latest version of pip installed. You can update pip by running pip install --upgrade pip
2. If you are using a corporate firewall or proxy, make sure that it is not blocking access to the package index or the package itself.
3. Check that the mirror you are using is working.
4. Try using the --trusted-host flag to specify the package index that you want to use. For example: pip install --trusted-host mirrors.tencentyun.com ultralytics

**Comment by nichiporets** [comment]
thank you. turned out I need python 3.7+

**Comment by UltralyticsAssistant** [comment]
@y-arrow you're welcome! I'm glad to hear you resolved the issue. It's important to ensure that your Python version meets the requirements for the Ultralytics package. If you have any more questions or need further assistance, feel free to check the Ultralytics HUB Docs or reach out. Happy coding!
