### ISSUE TITLE
Object Detection Models Deployment

### ISSUE THREAD

**Issue by Umar-Arshad-Janjua** [ultralytics/hub#138]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I want to deploy models trained on google colab files

### Use case

I want to export my custom detection models in some format which can be used to detet object in an image in an app.

**Comment by kalenmike** [comment]
@Umar-Arshad-Janjua Thanks for reaching out. Have you seen the Ultralytics App? Using our free companion app you can preview your custom model in real time.

https://ultralytics.com/app

**Comment by Umar-Arshad-Janjua** [comment]
Hi, thanks for your reply. I just want to confirm that, is it possible that
I use my own generated weights(that are in .pt) to be used in deployment? I
already have them and I have no need to train again.

**Comment by kalenmike** [comment]
@Umar-Arshad-Janjua We do not currently support uploading weights trained outside of Ultralytics HUB.
