### ISSUE TITLE
Unable to upload dataset

### ISSUE THREAD

**Issue by aarmijo** [ultralytics/hub#14]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

After selecting a custom dataset "custom.zip" or the sample one "coco6.zip" included in the tutorial [create a dataset](https://github.com/ultralytics/hub#1-create-a-dataset), a dialog screen appears with this content: **Datasets must be uploaded as a zip or yaml file!**

### Environment

Ultralytics HUB Version
**v0.1.13-beta.2**
Client User Agent
**Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36**
Operating System
**Win32**
Browser Window Size
**1366 x 657**
Server Timestamp
**1649275461**

### Minimal Reproducible Example

Steps to reproduce the problem:

1. Sign in to HUB 
2. Click on the Datasets tab. 
3. Click 'Upload Dataset'
4. Select the file coco6.zip

**Comment by glenn-jocher** [comment]
@aarmijo thanks for the bug report! I'll take a look.

**Comment by kalenmike** [comment]
@aarmijo Thank you for reporting this bug and providing the required information. This was reproduced on Windows 10 running Chrome 100 and has now been resolved with HUB v0.1.13-beta.3

**Comment by aarmijo** [comment]
@kalenmike @glenn-jocher  Now it is working correctly. Thank you for your help!
