### ISSUE TITLE
How to used .pt File ?

### ISSUE THREAD

**Issue by richedperson1** [ultralytics/hub#143]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How I Used .pt file when training of model is completed  in local machine? I try with torch.load model as well  but every time getting error about dimention. I try with 416,416 shape and (1,16,7,7) format as well but getting error as following 

![errorWhileLoadingImg](https://user-images.githubusercontent.com/62417643/211492325-a2dd8de3-b1e9-43b9-b183-a2d0c1e59ecc.PNG)

when changing the shape folling error 

![dee8e61c-1cfb-43ff-99a0-8bcc349618a7](https://user-images.githubusercontent.com/62417643/211493035-3fb35c4b-d8ba-4700-9676-ff7c95e8a104.PNG)

my code will be
![f5dea8c2-b046-4784-8a9a-cde0f8b04572](https://user-images.githubusercontent.com/62417643/211493223-a180065b-0806-4a0a-b12e-352e97f60ade.PNG)

**Comment by richedperson1** [comment]
We can Used .pt file by following

import torch 


model = torch.hub.load('ultralytics_yolov5_master', 'custom', path='best.pt', source='local') 

#torch.hub.load('Clone repository', 'custom', path='your model which come up with .pt file, source='local') 

img = cv2.imread("path of image")

results = model(img)
ans = results.pandas().xyxy[0]

now ans will contained coordinate of model output


Thank you so much
If you have any quection let me know!
Thank you.

**Comment by UltralyticsAssistant** [comment]
@richedperson1 it seems you already found a solution using `torch.hub.load` to load your `.pt` file. Your approach is correct; you specify the path to your trained model's `.pt` file and use the 'custom' argument to load a custom model not included in the pre-trained models provided by Ultralytics.

To use your `.pt` file, you can follow the syntax you've outlined, making sure that `'ultralytics_yolov5_master'` correctly points to the YOLOv5 repository and `'best.pt'` is the correct path to your trained model file.

If you encounter errors related to dimensions, ensure that the input image is preprocessed correctly to match the input size expected by your model. The YOLOv5 model expects images in batches, so even if you're processing a single image, it must be wrapped in a batch dimension.

For additional details and methods available for the model and results, please refer to the Ultralytics HUB Docs. If you face any further issues or have questions regarding the usage of the .pt file in a different context, please feel free to ask, and provide as much detail as possible to help in diagnosing the problem.
