### ISSUE TITLE
Auto Sign Not Loading next page

### ISSUE THREAD

**Issue by allandclive** [ultralytics/hub#144]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

![Screenshot 01-10-2023 19 00 56](https://user-images.githubusercontent.com/43777357/211601364-42cf8548-810d-4083-abba-f2ea59ed9161.png)

I can't sign in. It's stuck on this page. It's applying auto sign in but can't go pass this page

### Environment

Windows 10
Microsoft Edge
Version 108.0.1462.76 (Official build) (64-bit)

**Comment by kalenmike** [comment]
@allandclive Thanks for raising the issue. We had some big changes deployed today, its possible that you have some cache issues. Can you try to reset your cache for https://hub.ultralytics.com and see if that helps?

**Comment by allandclive** [comment]
No luck. nothing as changed, stuck on the same screen

**Comment by kalenmike** [comment]
@allandclive Please open your browser's console, refresh the page, and take a screenshot of any messages that appear in the console. Once you have the screenshot, please send it to us for further analysis.

To open the console in Microsoft Edge, you can use the keyboard shortcut F12 or right-click on the page and select "Inspect Element." This will open the developer tools pane at the bottom of the browser window. The console will be located in the "Console" tab within the developer tools.

**Comment by allandclive** [comment]
[image: Screenshot 01-10-2023 22.43.47.png]

**Comment by kalenmike** [comment]
@allandclive It looks like the screenshot did not upload.

**Comment by kalenmike** [comment]
@allandclive We just released a fix for a bug related to our Roboflow integration. Hopefully this will also solve the problem that you were facing. Would you try again and let me know how it goes?

**Comment by allandclive** [comment]
It's working now.
