### ISSUE TITLE
Is it possible to train a model for Instance Segmentation?

### ISSUE THREAD

**Issue by initdebugs** [ultralytics/hub#146]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Ofcourse it's possible to train a model for object detection, but I can't seem to find the option for Instance Segmentation. Is this feature not (yet) supported or am I blind ;)

**Comment by kalenmike** [comment]
@initdebugs Thank you for your question. We are currently in the process of integrating YOLOv8 with the Ultralytics HUB, which will add both classification and segmentation training. At this time, it is not possible to train YOLOv5 segmentation models using the Ultralytics HUB.
