### ISSUE TITLE
Unacceptable Character #x0003 when training by "bring own agent"

### ISSUE THREAD

**Issue by awetzel-lionpower** [ultralytics/hub#147]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I am attempting to train a model locally (bring your own agent) I get this error:

```
C:\Users\andrew\Desktop>python` train_hub.py
Ultralytics: 0.209 GB dataset, 49.5/255.5 GB free disk space
train: weights=yolov5n.pt, cfg=, data=https://storage.googleapis.com/ultralytics-hub.appspot.com/users/3SgFduVknUexy70niwkSLEaZ1Qm1/datasets/S7TeyAurfQOidDgm2WNq/hub.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20230117%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230117T212722Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=7c77728e846fa6673a9a38394345377d1e8c9fa90aac581ea7e84ee6e2ccb0ad0f8f00cf71580aa479a7ec7dfc7c9c80cffc95574aff7f63825dea52c5febd69022d24c11f77cc46a010621985b093fea3d68ce4e334ce6224f8635c7bd07fa5af7dfcb730f76daeb0bb375e7976c5aca32bc0ea8c9e81764f356e4547af65a803d259f8d65a793074fae93f990f9a2331eb564c97dd4ee1e7c54b29b0dc5d7db70b36f64cdbfca7b07d7adc51af65f23c6c2de8d92199081d7a77aa1e6b6261b65db4b2bbf0d6b73ff365d34f501a4517130b16c83dd28e06bbe0f65b11eb6c46019f93339f913384befc190337f94b5838311dc359618efcf8be7021f00e74, hyp=..\AppData\Local\Programs\Python\Python39\Lib\site-packages\yolov5\data\hyps\hyp.scratch-low.yaml, epochs=200, batch_size=96, imgsz=576, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, mmdet_tags=False, entity=None, bbox_interval=-1, artifact_alias=latest, neptune_token=None, neptune_project=None, s3_upload_dir=None, upload_dataset=False, id=ZNZLvOGPCrOQMCBawaN7, status=new
requirements: C:\Users\andrew\AppData\Local\Programs\Python\Python39\Lib\site-packages\yolov5\requirements.txt not found, check failed.
Found https://storage.googleapis.com/ultralytics-hub.appspot.com/users/3SgFduVknUexy70niwkSLEaZ1Qm1/datasets/S7TeyAurfQOidDgm2WNq/hub.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20230117%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230117T212722Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=7c77728e846fa6673a9a38394345377d1e8c9fa90aac581ea7e84ee6e2ccb0ad0f8f00cf71580aa479a7ec7dfc7c9c80cffc95574aff7f63825dea52c5febd69022d24c11f77cc46a010621985b093fea3d68ce4e334ce6224f8635c7bd07fa5af7dfcb730f76daeb0bb375e7976c5aca32bc0ea8c9e81764f356e4547af65a803d259f8d65a793074fae93f990f9a2331eb564c97dd4ee1e7c54b29b0dc5d7db70b36f64cdbfca7b07d7adc51af65f23c6c2de8d92199081d7a77aa1e6b6261b65db4b2bbf0d6b73ff365d34f501a4517130b16c83dd28e06bbe0f65b11eb6c46019f93339f913384befc190337f94b5838311dc359618efcf8be7021f00e74 locally at hub.zip
YOLOv5  2022-11-16 Python-3.9.13 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3090, 24576MiB)

Ultralytics: unacceptable character #x0003: special characters are not allowed
  in "hub.zip", position 2
```

I am able to train the same model fine (but slower) using the Google Colab Notebook.

### Environment

Windows 10

### Minimal Reproducible Example

Uploaded a dataset by following the instructions.
Trained the model on yolov5n.

**Comment by kalenmike** [comment]
@awetzel-lionpower Thank you for raising this bug. We will look into it and get back to yo.

**Comment by kalenmike** [comment]
@awetzel-lionpower Has this happened to you multiple times? We cannot seem to replicate this. Training is working fine on our end.

**Comment by awetzel-lionpower** [comment]
Yes, I just tried running it again and appeared to have the same issue 

'''
C:\Users\andrew\Desktop>python test.py
Ultralytics: 0.209 GB dataset, 86.3/255.5 GB free disk space
train: weights=yolov5n.pt, cfg=, data=https://storage.googleapis.com/ultralytics-hub.appspot.com/users/3SgFduVknUexy70niwkSLEaZ1Qm1/datasets/S7TeyAurfQOidDgm2WNq/hub.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20230118%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230118T164636Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=3c715f2e09668f55bddffccccdca4ff27a531f6148ca5eda7283d6aafdc4a38ac73efa4315e1d0c59a1fa3816814bd93f8b737f2828197bb2f64f8317801472f7f486284b397c8b71a2d7381c6e73cad958eda43d3ffdcc0650855665b402d85d042b57966473683ccdd7e3d69d9de5894768146357b0bcdc42412f940914e90079cff29cff0bade25e698f02aebadd402c39bd7782f24e3e63a9eea208032ab27b141aaed054f972c42ee3fc3084f6b097567033e1e5b86bcb2b207f995d6df4291b49c8c36d2f10ef83f7d5a27b35aaca8dd5bd07ff53f905b81ce833a4a206245a9e95896f61e73b1f69650e76b15b73ca0c24fb6c973560f4df1bfe3b0df, hyp=..\AppData\Local\Programs\Python\Python39\Lib\site-packages\yolov5\data\hyps\hyp.scratch-low.yaml, epochs=600, batch_size=-1, imgsz=576, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=cpu, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, mmdet_tags=False, entity=None, bbox_interval=-1, artifact_alias=latest, neptune_token=None, neptune_project=None, s3_upload_dir=None, upload_dataset=False, id=TBishjrc9SMsMP2EgetA, status=new
requirements: C:\Users\andrew\AppData\Local\Programs\Python\Python39\Lib\site-packages\yolov5\requirements.txt not found, check failed.
Found https://storage.googleapis.com/ultralytics-hub.appspot.com/users/3SgFduVknUexy70niwkSLEaZ1Qm1/datasets/S7TeyAurfQOidDgm2WNq/hub.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20230118%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230118T164636Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=3c715f2e09668f55bddffccccdca4ff27a531f6148ca5eda7283d6aafdc4a38ac73efa4315e1d0c59a1fa3816814bd93f8b737f2828197bb2f64f8317801472f7f486284b397c8b71a2d7381c6e73cad958eda43d3ffdcc0650855665b402d85d042b57966473683ccdd7e3d69d9de5894768146357b0bcdc42412f940914e90079cff29cff0bade25e698f02aebadd402c39bd7782f24e3e63a9eea208032ab27b141aaed054f972c42ee3fc3084f6b097567033e1e5b86bcb2b207f995d6df4291b49c8c36d2f10ef83f7d5a27b35aaca8dd5bd07ff53f905b81ce833a4a206245a9e95896f61e73b1f69650e76b15b73ca0c24fb6c973560f4df1bfe3b0df locally at hub.zip
YOLOv5  2022-11-16 Python-3.9.13 torch-1.13.0+cu117 CPU

Ultralytics: unacceptable character #x0003: special characters are not allowed
  in "hub.zip", position 2
'''

**Comment by awetzel-lionpower** [comment]
That error looks like it may be thrown something in the yaml file.

This is my yaml file, is there anything wrong with it:

```
path:
train: images/train
val: images/val
test:

# Classes
names:
  0: plate
  1: dm
```

**Comment by glenn-jocher** [comment]
@awetzel-lionpower if you'd like to train locally I'd recommend training inside our Docker image for the best compatibility, i.e. try https://hub.docker.com/r/ultralytics/yolov5

After you install docker you can run this with:
```
t=ultralytics/ultralytics:latest && sudo docker pull $t && sudo docker run -it --ipc=host --gpus all $t
```

**Comment by glenn-jocher** [comment]
@kalenmike once we've updated the ultralytics package we should probably add a Docker tab or link since `ultralytics` is installed by default in https://hub.docker.com/r/ultralytics/ultralytics

**Comment by awetzel-lionpower** [comment]
Looks good. Thanks
