### ISSUE TITLE
Downloading Datasets

### ISSUE THREAD

**Issue by awetzel-lionpower** [ultralytics/hub#149]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is there any way to download private or public datasets?

**Comment by kalenmike** [comment]
@awetzel-lionpower Thanks for the question. Datasets are automatically downloaded when training a model. However there is no way to download weights for other reasons. What are your reasons for this use case?

**Comment by awetzel-lionpower** [comment]
I was curious if I could download datasets and then use a subset of the classes for a separate model

**Comment by kalenmike** [comment]
@awetzel-lionpower Great example of a use case. We are working on allowing datasets to be chopped up and combined within the Ultralytics HUB.
