### ISSUE TITLE
Can not train in colab: Ultralytics: Invalid CUDA '--device gpu' requested, use '--device cpu' or pass valid CUDA device(s)

### ISSUE THREAD

**Issue by Banhalmi** [ultralytics/hub#150]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

**train: weights=yolov5/yolov5s.pt, cfg=yolov5n.yaml,** data=https://storage.googleapis.com/ultralytics-hub.appspot.com/users/vCSIk0Usn1MwyY95bC0Qlh4aWIf1/datasets..., hyp=yolov5/data/hyps/hyp.scratch-low.yaml, epochs=100, batch_size=-1, imgsz=640, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, noplots=False, evolve=None, bucket=, cache=ram, image_weights=False, device=GPU, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=yolov5/runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, seed=0, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest, id=b8GFFSqo1DaQxOk9tOOv, status=new
Ultralytics: 0.633 GB dataset, 54.0/78.2 GB free disk space
github: up to date with https://github.com/ultralytics/yolov5 ✅
Found https://storage.googleapis.com/ultralytics-hub.appspot.com/users/...
**Ultralytics: Invalid CUDA '--device gpu' requested, use '--device cpu' or pass valid CUDA device(s)**

Stops, does not train.
Another thing, it is ok, that weights config is yolov5s, but cfg=yolov5n?

### Environment

Chrome  108.0.5359.125

### Minimal Reproducible Example

1. login
2. select liceince_plate_1 dataset
3. select models, create model, select yolov5n, then colab, copy the key, and run

**Comment by kalenmike** [comment]
@Banhalmi Thanks for raising this bug. Its obvious to me what the issue is here. I will get it fixed quick and get back to you when you can start training.

**Comment by kalenmike** [comment]
@Banhalmi I have corrected this bug and updated any models that were effected. You should now be able to train your model without any problems. I am still looking into the weights/cfg issue you raised.
