### ISSUE TITLE
100% train but i can't use preview and deploy

### ISSUE THREAD

**Issue by HoangNho** [ultralytics/hub#151]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

![image](https://user-images.githubusercontent.com/83911880/215344341-3cb8c1bb-a0f0-40f3-babf-835825d78a85.png)

I have trained my model

![image](https://user-images.githubusercontent.com/83911880/215344386-4e74555d-4516-4f17-bfbd-3bba582cb29f.png)
![image](https://user-images.githubusercontent.com/83911880/215344398-c1ca7936-85f4-4084-8b34-445d511bd5ed.png)

**Comment by HoangNho** [comment]
> @HoangNho Thank you for raising this, would you please share your model id with me so I can look into what happened here. You can get the id from the URL when navigating to your model. `https://hub.ultralytics.com/models/MODEL_ID`

Here is my model: https://hub.ultralytics.com/models/dv3MSAtedPYaIBQCN5AB

**Comment by az-guardian** [comment]
I have the same issue. It says "disconnected", but training finished. Maybe it does not recognize epoch 19 as being the last epoch of 20 epochs? 

https://hub.ultralytics.com/models/33Rc834aidlKnVcDdyNN

**Comment by kalenmike** [comment]
@az-guardian Thanks for confirming. We have a bug at the moment that is preventing the optimizer from being stripped if the final epoch is not the best. We are looking into getting this sorted ASAP.
