### ISSUE TITLE
Upload custom model

### ISSUE THREAD

**Issue by MrKhan96** [ultralytics/hub#152]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi, I have trained a custom yolov5n model and I wanted to know how to upload it into hub? I trained it using your yolov5 repo.

**Comment by kalenmike** [comment]
@MrKhan96 Thanks for asking the question. Currently models trained outside of HUB cannot be uploaded. We are working to add this option to our YOLOv8 integration.
