### ISSUE TITLE
Can not export model to Pytorch

### ISSUE THREAD

**Issue by banser** [ultralytics/hub#153]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

I can not export/download the .pt weights of a model. I get a "0% Downloaded" that doesn't change.

After I click the export button in the Pytorch option, the following request triggers:
GET https://firebasestorage.googleapis.com/v0/b/ultralytics-hub.appspot.com/o/users%2FV0u8Vy65RZZkBqaXagm7Vor1KwE2%2Fmodels%2FEBFiedoJKhbYdXLFtH3V%2Fbest.pt

Response is:
Status 404 Not Found

**Comment by kalenmike** [comment]
@banser Thanks for raising this. I am looking into this now. Did your model train all the way through or did you have to resume training at some point?

**Comment by banser** [comment]
Thanks @kalenmike. The model ran all the way through, I can even use the preview feature OK. thanks

**Comment by kalenmike** [comment]
@banser I am looking into what went wrong so we can prevent it from happening again. For the moment I have solved your particular case, you should now be able to download your model.

**Comment by banser** [comment]
@kalenmike thanks. I confirm I can download the model now.
