### ISSUE TITLE
TensorFlow Lite Export image size

### ISSUE THREAD

**Issue by serael** [ultralytics/hub#154]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

When converting a model trained with an image size of 416 to tflite, it was confirmed as 640, and an error occurred when inputting an input size of 416 in android.

![01](https://user-images.githubusercontent.com/18001197/216499147-89359156-a017-4773-a56d-585fc5a1ff8f.PNG)
![02](https://user-images.githubusercontent.com/18001197/216499263-54ed9273-d374-473a-bd08-806d66c1d79a.PNG)
![03](https://user-images.githubusercontent.com/18001197/216499472-e3388d6d-932f-4182-883f-f3ee7f7053b2.PNG)

**Comment by kalenmike** [comment]
@serael Thanks for asking this question. Our TFLite export currently applies 640 regardless of the image size the model was trained on. It's something that is being addressed in YOLOv8, but we will make the relevant changes in HUB as well.
