### ISSUE TITLE
How to change parameters?

### ISSUE THREAD

**Issue by ponwik** [ultralytics/hub#158]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have a quick question. How do I change the parameters before training a model? I want to change the number of epochs because my dataset is rather big and colab doesn't allow me to train that long.

I saw an old solved bug report about changing parameters but it doesn't seem to apply to the current version of Ultralytics hub?

**Comment by kalenmike** [comment]
@ponwik Thanks for the question. The training parameters cannot be changed after a model is created in HUB. We intended training to start immediately after model creation. Our current view is that a new model should be created if different configuration is required.

This is something we can look at introducing provided enough people show interest.

**Comment by ponwik** [comment]
Yes that was my problem. I didn't see the advanced options when I created my model the first time. I recreated it with the number and epochs I wanted.

Thank you very much for answering my question @kalenmike.
