### ISSUE TITLE
Upload Models Trained Outside of HUB

### ISSUE THREAD

**Issue by Panpro999** [ultralytics/hub#159]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Can I directly use the model trained by YOLO v8 (I mean upload model directly)?

**Comment by kalenmike** [comment]
@Panpro999 Thanks for the question. HUB does not currently support uploading models trained without a connection. We are working to make this available in the future.
