### ISSUE TITLE
Upload trained YOLOv5 model to HUB

### ISSUE THREAD

**Issue by ShpihanVlad** [ultralytics/hub#161]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is this possible to upload already trained weights for deployment, skipping training in Google Colab? Thanks

**Comment by kalenmike** [comment]
@ShpihanVlad Thanks for the question. HUB does not support this. We are working to allow this for models trained using the YOLOv8 engine (including YOLOv5u models), but we do not have plans to support this with the original YOLOv5 models.

**Comment by bankxi** [comment]
> @ShpihanVlad Thanks for the question. HUB does not support this. We are working to allow this for models trained using the YOLOv8 engine (including YOLOv5u models), but we do not have plans to support this with the original YOLOv5 models.

Hi!When can i upload the trained yolov8 model to HUB

**Comment by kalenmike** [comment]
@bankxi We are currently working on our updating the Ultralytics App to work with YOLOv8, once that work is completed we will finalize the YOLOv8 code in the web.
