### ISSUE TITLE
Ultralytics package update

### ISSUE THREAD

**Issue by Forfy-code** [ultralytics/hub#162]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I want to train a model with my dataset in my own agent and I'm finding some problems with it. But today I updated the Ultralytics package because the terminal told me I needed to update it and I've found the next error text:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ultralytics' has no attribute 'start'

### Additional

Yesterday i open other issue question with the problem i had before this. Thank you very much.

**Comment by kalenmike** [comment]
@Forfy-code Thanks for the question. The code snippet for training with HUB is for version v0.0.44. Typically major updates will include breaking changes. The snippet we show on HUB is not compatible with Ultralytics > v8.0.0. From v8 of the pip package we are using YOLOv8, so it will be possible to train YOLOv5u models, which perform better than the original YOLOv5 models, however we have not enabled this on HUB yet.
