### ISSUE TITLE
How can I finalize and download checkpoint

### ISSUE THREAD

**Issue by aperveyev** [ultralytics/hub#163]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

My model happened too resource costly to complete on Collab but I want to estimate result (use best/last checkpoint for detect) locally.
How to do it ?
There were no "advanced options" but "use pretrained model" so I fall into 100 epoches and can't change it during resume.

**Comment by kalenmike** [comment]
@aperveyev Thanks for asking the question. On the HUB the very last step allows you to set the advanced options, including the total epochs to train for.

**Comment by aperveyev** [comment]
Thank you. My fault. I found "advanced options" on step 2 but miss ones on step 3.

**Comment by UltralyticsAssistant** [comment]
@aperveyev no problem at all! It's great to hear that you've located the advanced options. If you need further guidance or have any more questions as you work with checkpoints or any other features of the HUB, feel free to check the documentation or reach out again. Happy experimenting with your models!
