### ISSUE TITLE
Unhandled server error. Retrying 10x for 3600s.

### ISSUE THREAD

**Issue by 0-1-2-4-AU** [ultralytics/hub#164]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

...
Ultralytics: Training completed successfully ✅
Ultralytics: Uploading final KwAbgJCZRMH4VdKUGBba
Ultralytics: View model at https://hub.ultralytics.com/models/KwAbgJCZRMH4VdKUGBba 🚀
Ultralytics: Unhandled server error. Retrying 10x for 3600s. If this issue persists please visit https://github.com/ultralytics/hub/issues for assistance. (500 #4)
Results saved to yolov5/runs/train/exp

### Minimal Reproducible Example

Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   obj_loss   cls_loss  Instances       Size
      99/99      13.1G   0.008904    0.02243   0.002232        855        640: 100%|██████████| 55/55 01:37
                 Class     Images  Instances          P          R      mAP50   mAP50-95: 100%|██████████| 3/3 00:09
                   all        623       3735      0.981      0.984      0.974      0.641

1 epochs completed in 0.030 hours.
Optimizer stripped from yolov5/runs/train/exp/weights/last.pt, 6.6MB
Ultralytics: Training completed successfully ✅
Ultralytics: Uploading final KwAbgJCZRMH4VdKUGBba
Ultralytics: View model at https://hub.ultralytics.com/models/KwAbgJCZRMH4VdKUGBba 🚀
**Ultralytics: Unhandled server error. Retrying 10x for 3600s. If this issue persists please visit https://github.com/ultralytics/hub/issues for assistance. (500 #4)**
Results saved to yolov5/runs/train/exp

### Additional

Help my

**Comment by kalenmike** [comment]
@0-1-2-4-AU Thanks for raising this issue. Would you please confirm which version of the Ultralytics package you are using?

**Comment by 0-1-2-4-AU** [comment]
Ultralytics 🚀 0.0.44 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4,
15110MiB) Setup complete ✅ (2 CPUs, 12.7 GB RAM, 24.4/78.2 GB disk)
------------------------------------------------------
















вс, 19 февр. 2023 г. в 13:33, Kalen Michael ***@***.***>:

**Comment by 0-1-2-4-AU** [comment]
Hello @kalenmike, old version 0.0.37 very good...
Ultralytics 🚀 0.0.37 Python-3.8.10 torch-1.13.1+cu116 CUDA:0 (Tesla T4, 15110MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 24.4/78.2 GB disk)
...
Ultralytics: Training completed successfully ✅
Ultralytics: Uploading final KwAbgJCZRMH4VdKUGBba
Ultralytics: View model at https://hub.ultralytics.com/models/KwAbgJCZRMH4VdKUGBba 🚀
Results saved to yolov5/runs/train/exp
...
Thanks @kalenmike
