### ISSUE TITLE
add ability to change epochs parameter during --resume

### ISSUE THREAD

**Issue by aperveyev** [ultralytics/hub#165]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

useful (for training shortening) and simple to implement
MAYBE -  include into core ultralitics CLI ?

**Comment by kalenmike** [comment]
@aperveyev You can control the model training using the advanced options in HUB. Here the total epochs can be set and you can set the patience which will cause your model to stop training early if there has been no improvements. 
![image](https://user-images.githubusercontent.com/25989362/219942474-fa6da027-ec1d-4123-a9ad-3793b30ce547.png)

We are also working to add in the option to initiate training directly from the CLI and sync up the results with the HUB.

**Comment by aperveyev** [comment]
Thank you. I miss advances options for step 3 of model creation

**Comment by UltralyticsAssistant** [comment]
@aperveyev you're welcome! The advanced options available in the HUB during model creation should allow you to customize the training process according to your requirements. If you’re looking to adjust the epochs parameter during a resume operation, current HUB workflows are configured before the training begins. The ability to modify training parameters on the fly during a resume is not yet available in the HUB. We value your suggestion and will consider it for future updates. For now, please make sure to configure the desired training settings before initiating your training session. If you need further information on how to set up your training with the HUB, please refer to the Ultralytics HUB Docs.
