### ISSUE TITLE
how to test best.pt file in android mobile for object decetions

### ISSUE THREAD

**Issue by dsbhat23** [ultralytics/hub#166]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

i created using yolov8x custom model and the best.pt file is output. now how to use in android mobile for detection testing ?

### Additional

same above

**Comment by kalenmike** [comment]
@dsbhat23 Thanks for the question. You can download the Ultralytics App from the android store and once logged in you will be able to select and run inference using your custom model.
