### ISSUE TITLE
YAML Not Found - Issue when uploading data

### ISSUE THREAD

**Issue by sinasoccer** [ultralytics/hub#167]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello,

I am trying to upload a dataset of images I found on the internet. When I go to upload the files it states "YAML Not Found". How do I resolve this issue? The images are in JPEG format.

Thanks,

Sina

**Comment by kalenmike** [comment]
@sinasoccer Thanks for asking the question. Does your dataset contain a YAML file? You can see how a dataset should be formatted using our [example dataset](https://github.com/ultralytics/hub/blob/master/coco6.zip)

**Comment by UltralyticsAssistant** [comment]
@Forfy-code hello Sina,

The "YAML Not Found" message typically means that you need to include a YAML file with your dataset, which specifies paths to your train/val/test data and other configurations. The YAML file acts as a manifest for your dataset and is necessary for the proper functioning of the system when you are training models or performing other tasks.

Please ensure that you create a YAML file according to the required format and include it at the root of your dataset directory. The file should define the dataset structure, including paths to the images and labels for training, validation, and testing, if applicable. An example of the structure and contents of this file can be found in the documentation on the Ultralytics HUB Docs page.

Once you have created and included a properly formatted YAML file, try uploading your dataset again.

If you need guidance on the specific contents and formatting of the YAML file, please refer to the documentation. It will provide you with the necessary details to create a compatible YAML for your dataset.
