### ISSUE TITLE
Export to Ultralytics Android App and TFlite Failing with Roboflow Datasets

### ISSUE THREAD

**Issue by pedrostefanogv** [ultralytics/hub#168]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

When trying to export model to Android application, it does not run. Occurs for other models like TensorFlowLite as well

https://imgur.com/imuUapX.png

### Environment

OS Zorin OS (Ubtuntu)
Chrome and Firefox

**Comment by kalenmike** [comment]
@pedrostefanogv Thanks for raising this issue. We are currently working to address this.

**Comment by pedrostefanogv** [comment]
identificador do projeto 

https://hub.ultralytics.com/models/Fhxzpdbdy0BGzfKGBBAY?tab=deploy
