### ISSUE TITLE
Upload dataset

### ISSUE THREAD

**Issue by dhunjoshi** [ultralytics/hub#17]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Dataset upload shows error. but what error not clear. make dataset as per coco6 example. coco6 is uploading correct but , other could not be upload.

**Comment by dhunjoshi** [comment]
[latch.zip](https://github.com/ultralytics/hub/files/8511085/latch.zip)
sample dataset.

**Comment by kalenmike** [comment]
@dhunjoshi Thanks for raising a question. I reviewed your dataset and in your yaml you are refering to images with a lower case i, while the folder has an upper case I. Which is the reason this error shows that the images cannot be found.

![image](https://user-images.githubusercontent.com/25989362/163984703-730f44a8-fafd-4887-a00f-80d5909c24ae.png)

If you rename the folder to lowercase 'i' and the upload will work. 

If you have any more issues please let me know.

**Comment by dhunjoshi** [comment]
i have change that but still not working.

> @dhunjoshi Thanks for raising a question. I reviewed your dataset and in your yaml you are refering to images with a lower case i, while the folder has an upper case I. Which is the reason this error shows that the images cannot be found.
> 
> ![image](https://user-images.githubusercontent.com/25989362/163984703-730f44a8-fafd-4887-a00f-80d5909c24ae.png)
> 
> If you rename the folder to lowercase 'i', the upload will work.
> 
> If you have any more issues please let me know.

i have change but still got error.

**Comment by dhunjoshi** [comment]
> [latch.zip](https://github.com/ultralytics/hub/files/8511085/latch.zip) sample dataset.

After adding more images. error comes again.

**Comment by kalenmike** [comment]
@dhunjoshi Its because you still have the same error in your dataset. The names are case sensitive.
![image](https://user-images.githubusercontent.com/25989362/164022621-781297eb-c91b-4ba7-9355-63efd2f24a48.png)
![image](https://user-images.githubusercontent.com/25989362/164022669-b62b7c1b-8419-4f95-9bf5-79ed8584c3f3.png)
