### ISSUE TITLE
How to resume training if colab failed?

### ISSUE THREAD

**Issue by hiperriper** [ultralytics/hub#170]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How to resume training if colab failed?

I do not know how to continue training from check point using ultralytics. module|

**Comment by kalenmike** [comment]
@hiperriper Thanks for the question. If your model saved a checkpoint you will be able to resume by running the same code you use to train a model initially. Training needs to have been at least longer than 15 minutes for any checkpoints to be saved.
