### ISSUE TITLE
Where is the v8 model?

### ISSUE THREAD

**Issue by vip404** [ultralytics/hub#171]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Where is the v8 model?  all i can see only v5

**Comment by glenn-jocher** [comment]
@vip404 hi thanks for asking! We are adding YOLOv8 support soon. I can't give you an exact date but we'd like to have this completed by early March :)

**Comment by vip404** [comment]
ha! thanks for your answering !  I thought I missed it somewhere, This is an excellent good project， and thank you all.

**Comment by UltralyticsAssistant** [comment]
@vip404 you're welcome, and thank you for the kind words! The credit goes to the entire YOLO community and the Ultralytics team who are working hard to make the project better. Keep an eye on the GitHub repository for updates on YOLOv8 support, and feel free to reach out if you have any more questions in the future. For detailed documentation and updates, you can always refer to the Ultralytics HUB Docs.
