### ISSUE TITLE
Raspberry pi feedback question (using Yolov8 for instance segmentation)

### ISSUE THREAD

**Issue by Jason1-2** [ultralytics/hub#174]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I need some help for a project I'm doing. My project is to have my raspberry pi camera detect objects using Ultralytics Yolov8 for instance segmentation. I'm using Thonny for the python code and everything works very well. My python code looks like this:

from ultralytics import YOLO
model=YOLO('best.pt')
model.predict(source=0,show=True)

My camera can successfully detect objects on a live camera. I can see frames are getting printed on the bottom of the code saying 0: 480x640 1 Bottle, 2330.8ms

My question is how can I take the data meaning (0: 480x640 1 Bottle, 2330.8ms) and apply it to send an output signal from my raspberry pi. 

Another question would be, where is (0: 480x640 1 Bottle, 2330.8ms) coming from? I don't think it's data coming from a folder I have. 

I need the information on each frame to send signals but I don't know where to look. If you know anything or know someone that can help me please let me know. Also, if you have any questions for me please let me know too. Thank you so much!

**Comment by glenn-jocher** [comment]
@Jason1-2 you can output `results` and handle them however you see fit, i.e. `results = model(image)`

see https://docs.ultralytics.com/tasks/segmentation/ for examples

**Comment by Jason1-2** [comment]
@glenn-jocher would I need to create coding for "results"? I saw examples of Class Results on https://docs.ultralytics.com/reference/results/?h=results 

Do I need to create my coding similar to the ones that are shown under "Source code in ultralytics/yolo/engine/results.py"? 
Also, thank you for responding
