### ISSUE TITLE
Forklifts

### ISSUE THREAD

**Issue by PaduGC** [ultralytics/hub#175]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

.

### Use case

.

### Additional

.

**Comment by kalenmike** [comment]
@PaduGC Could you clarify what you are requesting as an enhancement here?

**Comment by PaduGC** [comment]
Hi Kalen.

Sorry for that, I intended to search not to “complain”…

I am a complete newbie trying to make a dashboard, import video footages, select, “mark”, train and finally, detect and prevent a vehicle from running over a pedestrian.

Thanks and once again, sorry,

BRGds,

 

Paulo Eduardo | F: +55 15 98133-8777

 

 

 

 

De: Kalen Michael ***@***.***> 
Enviada em: sexta-feira, 3 de março de 2023 08:17
Para: ultralytics/hub ***@***.***>
Cc: Paulo Eduardo ***@***.***>; Mention ***@***.***>
Assunto: Re: [ultralytics/hub] Forklifts (Issue #175)

 

@PaduGC <https://github.com/PaduGC>  Could you clarify what you are requesting as an enhancement here?

**Comment by UltralyticsAssistant** [comment]
@PaduGC hello Paulo Eduardo,

No worries at all! We're here to help. 😊

For your project on detecting and preventing vehicles from running over pedestrians, you'll want to start by creating a dataset of annotated images or video frames that include forklifts and pedestrians. Once you have your dataset, you can use it to train a custom object detection model.

The Ultralytics HUB provides tools for importing video footage, annotating data, training models, and deploying them for inference. You can create a dashboard to manage your project and monitor the performance of your model.

For detailed guidance on each step of the process, please refer to the Ultralytics HUB Docs. They will walk you through importing your data, annotating it, training your model, and finally deploying it for real-time detection.

If you have any specific questions or run into any issues along the way, feel free to reach out here, and we'll be happy to assist you.

Best regards and good luck with your project! 🚀

— Ultralytics Assistant
