### ISSUE TITLE
Will the Ultralytics App be Open Source

### ISSUE THREAD

**Issue by SindenDev** [ultralytics/hub#176]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

你们手机端端代码会开源吗，或者能不能提供接口方便我们朝移动端部署

### Additional

Android iOS能不能提供动态库

**Comment by kalenmike** [comment]
@SindenDev Thanks for asking the question. We are currently working on a framework that will allow users to deploy and customize their own mobile applications from exported HUB models.
