### ISSUE TITLE
Creating your own Yaml Models

### ISSUE THREAD

**Issue by fonsofhervella** [ultralytics/hub#177]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! First of all, many thanks for your time

I have been trying to search for an answer on several sites but I have not been able to find it (sorry if it exists)

What I want is the following:

 I have created a model for YoloV8. I have personalised the model creating a yaml, and then using Yolov8m.

I want to deploy the model for using it through the phone, and I have seen that Ultralytics Hub provides a simple way to do so. 

I know that I can use YoloV5, but when I am creating my model, I configure it through the front and then I get the API Key, open it in colab and run it. 

It is possible to train, in the Colab notebook, a yaml model for Yolov5, or to import my own Yolov5 model?

If no, how can I get simmilar results?

Many thanks in advance

**Comment by kalenmike** [comment]
@fonsofhervella Thank you for your question. We are currently in the process of finalizing the integration of YOLOv8 with the Ultralytics HUB. With this new feature, you will be able to create and connect a custom model to the Ultralytics HUB using your Python code or CLI on your local agent. This will enable you to train models with personalized architectures, providing you with greater flexibility in your machine learning workflows.
