### ISSUE TITLE
iOS app stop detecting when phone is horizontal 

### ISSUE THREAD

**Issue by Joyphish** [ultralytics/hub#179]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

The iOS app works when the phone is held vertically, but it stops detection when it is held horizontally. It is difficult to detect an object on a table. 

### Environment

iOS

**Comment by glenn-jocher** [comment]
@Joyphish thanks for the bug report!

CNN's are rotationally invariant, so the model will not recognize objects as easily sideways since it is not trained on sideways objects, just like you can't read a book very well upside-down because you never studied upside books in school.

**Comment by Joyphish** [comment]
Thank you for the reply. I understand what you are saying. What I meat is to hold the screen parallel to ground. However the image is still in the right orientation in the screen. Imagine you have an object on a table and you have to scan it from a top view. Once the phone screen is facing up, the app stops detecting. Isn’t that weird. Le YuOn Mar 8, 2023, at 6:45 PM, Glenn Jocher ***@***.***> wrote:﻿
@Joyphish thanks for the bug report!
CNN's are rotationally invariant, so the model will not recognize objects as easily sideways since it is not trained on sideways objects, just like you can't read a book very well upside-down because you never studied upside books in school.

**Comment by glenn-jocher** [comment]
Oh I see what you are saying now. Yes the iOS app has a power saving mode to disable inference if the phone is placed facedown on a table for example. I think Android lacks this.

Is this causing problems for you?

@sergiossm is our mobile developer who can offer more details.

**Comment by Joyphish** [comment]
It stops detecting with screen facing up, not down. If the screen is about 45 degree tilted from facing up, it starts to stop. I have to hold an object against a wall and hold the phone vertically to do detection. That’s awkward and is not normally how we use the app. Le YuOn Mar 9, 2023, at 12:10 AM, Glenn Jocher ***@***.***> wrote:﻿
Oh I see what you are saying now. Yes the iOS app has a power saving mode to disable inference if the phone is placed facedown on a table for example. I think Android lacks this.
Is this causing problems for you?
@sergiossm is our mobile developer who can offer more details.

**Comment by glenn-jocher** [comment]
Yea I agree, just tested it myself and the 45 deg cutoff is kind of annoying.

@sergiossm we should remove the angle cutoff on the iOS app per above user request.

**Comment by glenn-jocher** [comment]
@sergiossm please update the iOS to remove the orientation shutoff (i.e. we want to keep inference running at any phone orientation).

**Comment by glenn-jocher** [comment]
@sergiossm hi buddy, what's the status on this? Can you update this issue please? Also update our social icons on settings page, thanks!

**Comment by kalenmike** [comment]
We have a rebuild of the app launching in the next few days. This is flagged for testing.
