### ISSUE TITLE
Automatically cache dataset

### ISSUE THREAD

**Issue by Powercube7** [ultralytics/hub#18]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I have found myself training a model in Google Colab without any caching strategy enabled. The model trains quite slow, and I have also found myself with about 20GB of free disk space and 9GB of free RAM. From my point of view, making an automatic choice for caching when available would be quite useful instead of keeping the default off

### Use case

This feature would be used by people that want to train their models faster

**Comment by glenn-jocher** [comment]
@Powercube7 that's a great idea! We check available RAM and HDD space in YOLOv5 here. The main question is how to estimate a cached dataset size. Maybe we could attempt to cache 1% of the dataset and exrapolate the full requirements from there, and proceed to cache if they extrapolation estimates <80% RAM or <50% HDD usage.

If we apply this to the base YOLOv5 repo then HUB trainings will naturally inherit this.

**Comment by glenn-jocher** [comment]
@Powercube7 if you'd like to start a PR on this that would be a huge help!

Please see our ✅ [Contributing Guide](https://github.com/ultralytics/yolov5/blob/master/CONTRIBUTING.md) to get started.

**Comment by Powercube7** [comment]
@glenn-jocher I don't know if I will manage to, but I will try my best to help!

**Comment by glenn-jocher** [comment]
@Powercube7 awesome, thanks!
