### ISSUE TITLE
when creating a new project, the project dialog should close after clicking CREATE button

### ISSUE THREAD

**Issue by cyrfer** [ultralytics/hub#182]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

After I filled out the form to create a new project, I clicked the`Create` button several times until I realized there was an issue. I opened the developer console and noticed the API calls were succeeding, so I think the issue is simply that the dialog needs to close after the API call succeeds. I had created several projects with the same details. I easily deleted the duplicates.

### Minimal Reproducible Example

1. log into HUB
2. make sure you are on the home page
3. click tile `Create Project >`
4. fill out the form
5. click `Create` button
6. notice the dialog does not close and you can easily click `Create` again. click it again.
7. close the dialog. notice you have more than one new project.

**Comment by kalenmike** [comment]
@cyrfer Thanks for the bug report. We will take a look and see what is happening here. This has been addressed previously, could you confirm the browser you are having this issue on?

**Comment by cyrfer** [comment]
@kalenmike funny, I remember GitHub captured that but I don't see it listed in the issue.

Chrome 110.0.5481.177
OSX Ventura 13.2.1
