### ISSUE TITLE
reloading browser on /projects navigates to /signin

### ISSUE THREAD

**Issue by cyrfer** [ultralytics/hub#183]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I am confused when I see a login prompt after reloading the page. When I was on the /projects page, and something looked wrong, I clicked the browser's reload button. Looking at the URL address to understand what is happening, I see /signin in the path.

To your credit the page does realize that I previously signed in. So its just a little annoying that I need to wait for the login form to go through its animation. Eventually the page navigates back to /projects.

### Minimal Reproducible Example

1. log into hub.
2. navigate to /projects.
3. reload browser.
4. notice the path is /signin.
5. Resist the urge to sign in and wait for animations to complete.

### Additional

I think it would be better to show a screen like,
> We know you want to view your projects but we need to verify your login first.

**Comment by kalenmike** [comment]
@cyrfer Thanks for the bug report. We have confirmed this bug and will work to address the issue.

**Comment by kalenmike** [comment]
@cyrfer We have added an authenticating message on reload.
