### ISSUE TITLE
Training failed on google colab using VisDrone dataset and yolov5n

### ISSUE THREAD

**Issue by drakshayanidesai** [ultralytics/hub#185]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Training failed on google colab using VisDrone dataset and yolov5n

**Comment by drakshayanidesai** [comment]
Hi 

I  tried with hub.ultralytics with VisDrone dataset with yolovV5m6. It is done but it is throwing error 
while converting to blob files using tools.luxonis.com(The sheet attached shows the errors). 
Then I tried with yolov5n model on the same dataset but it is showing error while executing in google 
colab notebook. Please see the errors in the attached sheet. Suggestions?



Thanks
Drakshayani

On Thu, 16 Mar 2023 12:17:15 +0530 "github-actions[bot]"  wrote
>
👋 Hello @drakshayanidesai, thank you for raising an issue about Ultralytics HUB 🚀! Please visit 
https://ultralytics.com/hub to learn more, and see our ⭐️ HUB Guidelines to quickly get started 
uploading datasets and training YOLOv5 models.
If this is a 🐛 Bug Report, please provide screenshots and steps to recreate your problem to help us 
get started working on a fix.
If this is a ❓ Question, please provide as much information as possible, including dataset, model, 
environment details etc. so that we might provide the most helpful response.
We try to respond to all issues as promptly as possible. Thank you for your patience!

**Comment by glenn-jocher** [comment]
@drakshayanidesai if the error is generated by a 3rd party tool then please raise a bug report directly with the author of that tool.
