### ISSUE TITLE
downloaded model does not contain metadata

### ISSUE THREAD

**Issue by burhancetinkaya** [ultralytics/hub#187]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

When i downloaded the tensorflow lite model, it doesnt contain metadata. So I can't use it on my android app. How can i export the tflite model with metadata?

Thanks in adnvance

**Comment by sergiossm** [comment]
Hi @burhancetinkaya, thank you for your feedback. We have developed an Ultralytics library for Android, iOS, and Flutter, which will enable you to create your own apps using models trained on HUB. The release is imminent, so stay tuned!

**Comment by burhancetinkaya** [comment]
Hi Sergio,

Thanks for your reply. Our app is developing with react native. Do you have react-native support in your release backlog?

Thanks in advance.


Burhan Çetinkaya
Co-Founder & CTO |  lenasoftware.com |+90 216 504 60 38
***@***.*** | +90 538 241 44 54

**Comment by UltralyticsAssistant** [comment]
@burhancetinkaya hello Burhan,

As of now, we don't have a dedicated React Native library in our immediate release schedule. However, we appreciate you bringing this to our attention, and we'll certainly consider it for our future roadmap. Your interest in React Native support is valuable to us, and we'll keep the community updated on any developments in this area. Stay tuned to our updates, and thank you for being part of the YOLO community! 🚀
