### ISSUE TITLE
Not all models are available for training

### ISSUE THREAD

**Issue by Pro100rus32** [ultralytics/hub#19]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I can't train the models: YOLOv5n6, YOLOv5s6, YOLOv5m6, YOLOv5l6, YOLOv5x6
![image](https://user-images.githubusercontent.com/64806740/164785141-07bda38b-609c-4811-91a1-634702e83519.png)

**Comment by glenn-jocher** [comment]
@Pro100rus32 thanks for the feedback! Yes you are right, all the P6 models are missing. We are working on many updates to HUB that should be rolling out in the next few weeks, and we'll try to include the additional models missing here as well.

@sergiossm @kalenmike

**Comment by kalenmike** [comment]
@Pro100rus32 Thanks for voting up the importance of having all models available for training. We have added in the P6 models. If anything else comes to mind on how we can improve your training experience please let us know!

Thanks again.
