### ISSUE TITLE
How to start training using custom agent after connecting?

### ISSUE THREAD

**Issue by EricTelekom** [ultralytics/hub#190]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I followed the instructions to train a model on a custom agent (linux server) and it shows me i am connected and the model is training. On my server nothing is happening, how do i start the actual training process?

**Comment by kalenmike** [comment]
@EricTelekom Thanks for the question. What was the output after you started training? Also are you using the Roboflow integration to train this model?

**Comment by kalenmike** [comment]
@EricTelekom Could you provide me the model id so I can take a deeper look into this? You can get the ID from the URL when navigating into the model via HUB. https://hub.ultralytics.com/models/MODEL_ID
