### ISSUE TITLE
where did my project go

### ISSUE THREAD

**Issue by TravelGravel** [ultralytics/hub#193]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I am getting familiar with roboflow and ultralytics.  I created a test project, trained several images and got to the step where it said a "model" link will be sent via email in about 15 minutes.  

As I wait, I want to look at my labeled images for reference.  they are not in the project folder and I have nothing under my account.  did I lose the labeled training set   (like 7 images only)?  if not, under what button click/tab is it?  i cannot find it.

Jerry

**Comment by kalenmike** [comment]
@TravelGravel Thanks for raising a question here. Am I correct in understanding that your project is missing in Roboflow? We do not provide support for Roboflow you will need to raise an issue with them directly. We can only support you with the integration in Ultralytics HUB.

Let me know if I misunderstood and you are having issues with Ultralytics HUB.
