### ISSUE TITLE
can YOLO send detected objects into SMS or email?

### ISSUE THREAD

**Issue by Danjen27** [ultralytics/hub#195]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is there a function or code that I can use to automatically send images of a detected object with its bounding box to sms or any messaging app as notification?

**Comment by glenn-jocher** [comment]
Yes, you can use Twilio to send images via SMS or MMS. First, you need to sign up for a Twilio account (https://www.twilio.com/try-twilio) and obtain your Twilio phone number, account SID, and auth token.
