### ISSUE TITLE
The android app could not open the USB camera.

### ISSUE THREAD

**Issue by kmqzst** [ultralytics/hub#196]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

nothing

### Environment

android khadas edge2 platform
ultralystics app

**Comment by sergiossm** [comment]
Hey @kmqzst 

Thanks for reporting this issue. To help us address it, could you please provide more information about the problem you're experiencing? Any screenshots would also be helpful.

**Comment by kmqzst** [comment]
Hi SergioThanks for your reply.The attachment is the screenshot of myapplication.I use the rock chip 3588s platform(edge2) designed by KHADAS. The system is android 12. I attempted to use other app such us common uvc camera,it could open the usb camera normally. But the ultralytics app couldn't open it.My English is very bad ,I hope you can understand what i mean.Thank you very much.发自我的手机-------- 原始邮件 --------发件人： Sergio Sánchez ***@***.***>日期： 2023年4月3日周一 22:30收件人： ultralytics/hub ***@***.***>抄送： kmqzst ***@***.***>, Mention ***@***.***>主    题： Re: [ultralytics/hub] The android app could not open the USB camera. (Issue #196)
Hey @kmqzst
Thanks for reporting this issue. To help us address it, could you please provide more information about the problem you're experiencing? Any screenshots would also be helpful.

**Comment by sergiossm** [comment]
@kmqzst I don't see any attachments. 

But it looks like you're trying to use an external USB camera with the Ultralytics HUB app, right? In that case, we, unfortunately, don't have the resources to troubleshoot this specific issue at the moment.

However, we're currently working on releasing a mobile library that will let you develop your own apps using YOLOv5u and YOLOv8 models. This may be a more convenient alternative for you to explore. We hope to have this library available soon and we'll keep you updated on its progress.
