### ISSUE TITLE
Agent Training Bug with yolov8 Export from Roboflow

### ISSUE THREAD

**Issue by jquaglia-uss** [ultralytics/hub#199]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I am getting a .yaml error when trying to train on a Roboflow exported dataset.  Can someone take a look at the error below?

### Additional

Traceback (most recent call last):
  File "C:\Users\James\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 123, in __init__
    self.data = check_det_dataset(self.args.data)
  File "C:\Users\James\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\yolo\data\utils.py", line 200, in check_det_dataset
    data = next((DATASETS_DIR / new_dir).rglob('*.yaml'))
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\James\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\yolo\engine\model.py", line 347, in train
    self.trainer = TASK_MAP[self.task][1](overrides=overrides)
  File "C:\Users\James\AppData\Local\Programs\Python\Python38\lib\site-packages\ultralytics\yolo\engine\trainer.py", line 127, in __init__
    raise RuntimeError(emojis(f"Dataset '{self.args.data}' error ❌ {e}")) from e
RuntimeError: Dataset 'https://storage.googleapis.com/ultralytics-hub.appspot.com/users/Nxvqve5rpLMyrT2Vs1NT2ujmbsJ3/datasets/N1Lf95A1qUEENjJxuhvE/human.v12i.yolov8.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20230406%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230406T125047Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=94b70d42bdb646aa270c7e6412b4ea8cd8cfff444b2abc0003a54da867250f2ba6ec057428249e2b7f6b9997d6b72c8a3f627405e7edf514d78e20a22ccc8fcc2170f06f0c660967f68395eac0c55354b68722f70cddc10f0b162f8b4c934c12cd171e1daa1424c7c9f7abc7b0694b7cdf14844f51c11aef083440de04ae7440c4cfa1f8fa88bcead6d64e00888a7fa91b841b69fb052acdca32ed1bc4c2e99e3cec101d6c6076b28966d12dcb1f2f0134e85898195049fbb25f101146f4207f56c68b7f7f8e92706a48e7745fff845ec6866eb56c963d2c9be20943dfee50b4637357909c1807ba31945a5d09c6e0f60a6ac7fc7b2f78bedf098de768cf2cb8' error

**Comment by kalenmike** [comment]
@jquaglia-uss Thanks for raising this. To reproduce this could you let us know what code you are using to initiate training?

**Comment by jquaglia-uss** [comment]
Here is the code:

from ultralytics import YOLO, checks, hub

checks()
hub.login('419a32a77d6b2144ac6f5a7d370d094a68dd400030')

model = YOLO('https://hub.ultralytics.com/models/awLsqAHCTSZYyZ9xGP0D')
model.train()

Regards,

James Quaglia
CTO


*Turnkey Machine Vision Solutions*
248-345-3678
***@***.***

**Comment by glenn-jocher** [comment]
@jquaglia-uss thank you for letting us know about this bug. We have reproduced and fixed this in https://github.com/ultralytics/ultralytics/pull/1871 which we just published to `ultralytics 8.0.67` now. Please update your ultraltyics package with `pip install -U ultralytics` and try to train again. 

Let us know if this resolves your issue, and feel free to tell us of any other ideas or problems you find!

**Comment by glenn-jocher** [comment]
@jquaglia-uss can you verify if the works for you please? Thanks!

**Comment by jquaglia-uss** [comment]
Just getting off a plane. I will confirm asap

**Comment by jquaglia-uss** [comment]
Sorry for the delay!

Confirmed it works!

Regards,

James Quaglia
CTO


*Turnkey Machine Vision Solutions*
248-345-3678
***@***.***
