### ISSUE TITLE
colab cannot resume after disconnect

### ISSUE THREAD

**Issue by fypgp03** [ultralytics/hub#207]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Here is my ultralytics model: https://hub.ultralytics.com/models/efx6t4OOARGufB4jWC6p

I try to resume the training using these codes:

hub.login('xxx')

model = YOLO('https://hub.ultralytics.com/models/efx6t4OOARGufB4jWC6p')
model.train()

But throw out following error:

Ultralytics HUB: Authenticated ✅
data:  {'data': 'https://storage.googleapis.com/ultralytics-hub.appspot.com/users/NNvsvVpCJndbDPeFYr2LikxbFaG3/datasets/5VQO12Ntf0Xh9hZ9rZ9k/fyp.v1i.yolov5pytorch_mixed_all_0409.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20230410%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230410T154228Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=xxx', 'id': 'efx6t4OOARGufB4jWC6p', 'resume': 'https://storage.googleapis.com/ultralytics-hub.appspot.com/users/NNvsvVpCJndbDPeFYr2LikxbFaG3/models/efx6t4OOARGufB4jWC6p/epoch-74.pt?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20230410%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230410T154228Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=xxx', 'status': 'training'}
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-8-93710743a0be>](https://localhost:8080/#) in <cell line: 3>()
      1 hub.login('xxx')
      2 
----> 3 model = YOLO('https://hub.ultralytics.com/models/efx6t4OOARGufB4jWC6p')
      4 model.train()

2 frames
[/usr/local/lib/python3.9/dist-packages/ultralytics/hub/session.py](https://localhost:8080/#) in _get_model(self)
    116 
    117             self.train_args = {
--> 118                 'batch': data['batch_size'],
    119                 'epochs': data['epochs'],
    120                 'imgsz': data['imgsz'],

KeyError: 'batch_size'

### Environment

colab

**Comment by glenn-jocher** [comment]
@fypgp03 hi there! To resume a model please try this code. Also remember to update to the latest version of `ultralytics`:

Upgrade:
```commandline
pip install -U ultralytics
```

Resume:
```python
from ultralytics import YOLO

model = YOLO("last.pt")
model.train(resume=True)
```

See Docs for details at https://docs.ultralytics.com/usage/python/#train

**Comment by fypgp03** [comment]
It doesn't work. It seem that the ultralytics backend stuck 'status': 'training'.

**Comment by glenn-jocher** [comment]
@fypgp03 ok hold on, I think your error may also be due to a lacking 'batch' key in the received file. We are taking a look at this and releasing an updated 8.0.73 later today which may resolve this issue.

We recently did a major update from YOLOv5 to YOLOv8 with HUB, so not all features are operating correctly yet, but we are working hard to get everything up and running as soon as we can.

**Comment by glenn-jocher** [comment]
@fypgp03 good news! Resume is now working correctly in `ultralytics 8.0.74` after merging https://github.com/ultralytics/ultralytics/pull/1956. To receive this update just `pip install -U ultralytics` and then try to resume again. Then you can resume using the same code that you started your training with, i.e:

```python
hub.login('API_KEY')

# Model to resume from
model = YOLO('https://hub.ultralytics.com/models/MODEL_ID')
model.train()
```

**Comment by Floul1** [comment]
I'm also having this issue now with 8.0.76 on colab, `
FileNotFoundError                         Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    121             elif self.args.data.endswith('.yaml') or self.args.task in ('detect', 'segment'):
--> 122                 self.data = check_det_dataset(self.args.data)
    123                 if 'yaml_file' in self.data:

4 frames

FileNotFoundError: '/content/datasets/New-Cards-3/New-Cards-3/data.yaml' does not exist


The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)

[/usr/local/lib/python3.9/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    124                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    125         except Exception as e:
--> 126             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    127 
    128         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset '/content/datasets/New-Cards-3/New-Cards-3/data.yaml' error ❌ '/content/datasets/New-Cards-3/New-Cards-3/data.yaml' does not exist`

**Comment by kalenmike** [comment]
@Floul1 I have moved your last comment into a separate issue.
