### ISSUE TITLE
Ultralytics HUB dataset YAMLs require updating to YOLOv8 format

### ISSUE THREAD

**Issue by tienhoang1094** [ultralytics/hub#208]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

![image](https://user-images.githubusercontent.com/58082063/231133206-9da4041c-489f-42b2-8d92-e75d9c1560e3.png)

**Comment by kalenmike** [comment]
@tienhoang1094 Thanks for raising this. Can you check that your Colab has the latest ultralytics package by running this in the first cell and then trying again:

`pip install -U ultralytics`

**Comment by tienhoang1094** [comment]
![image](https://user-images.githubusercontent.com/58082063/231383747-1e74e3d3-b32e-4434-a6a3-3005a7b18a1f.png)
it already newest and still fail

**Comment by kalenmike** [comment]
@tienhoang1094 The Colab notebook will not carry across its state to a new user. I see that you have deleted this model? Are you still having issues?

**Comment by glenn-jocher** [comment]
@tienhoang1094 hi there! Thanks for the reproducible example. I'm able to reproduce this error in Colab also using your code. This seems to be an issue in the `ultralytics` package autodownload code for Visdrone. I'll prioritize a fix for this.
<img width="1287" alt="Screenshot 2023-04-12 at 19 39 33" src="https://user-images.githubusercontent.com/26833433/231539580-d59642a0-d119-4a5b-9b49-1adc5c5b0a72.png">

**Comment by glenn-jocher** [comment]
@tienhoang1094 ok after investigating I found the cause is simply out-of-date HUB Dataset YAMLs. We recently switched over to using the `ultralytics` repo for YOLOv8 models in HUB, and we forgot to update our dataset YAMLs accordingly.

@kalenmike will update these and let you know when everything is fixed!
