### ISSUE TITLE
Plugin Request

### ISSUE THREAD

**Issue by Naeem-SahiL** [ultralytics/hub#209]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

do you have any plan for releasing ultralytics plugin for flutter for mobile native use of these models?

**Comment by glenn-jocher** [comment]
@Naeem-SahiL yes, we are working on Android and iOS libraries for use with YOLO models! We are hard at work on this and should be releasing these in the coming months.

@sergiossm is our lead mobile developer on this effort :)

**Comment by glenn-jocher** [comment]
@Naeem-SahiL, you're welcome! We are excited about bringing YOLO models to mobile, and making advanced AI accessible to developers. Thank you for your support. If you have any more questions or feedback, feel free to reach out to us.
