### ISSUE TITLE
unable to sign in - ios app

### ISSUE THREAD

**Issue by madhan5000** [ultralytics/hub#210]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

the screen goes blank (Grey color) when I tried to hit sign in button in the profile page

### Environment

Iphone Xs
IOS version 16.3.1

<img src="https://user-images.githubusercontent.com/12514153/231835129-6684cefc-0a3e-4cdf-95a5-575686bd1b40.PNG" width="25%" height="25%">

### Minimal Reproducible Example

1. Download App from app store
2. Go to profile page
3. hit sign in button

**Comment by sergiossm** [comment]
@madhan5000 Thanks for reporting. Fixed, going live in version 0.5.5
