### ISSUE TITLE
Edge TPU export bug

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub#217]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

Edge TPU export is failing in nightly CI.
https://github.com/ultralytics/hub/actions/runs/4711050988/jobs/8355180534

<img width="1408" alt="Screenshot 2023-04-16 at 15 03 42" src="https://user-images.githubusercontent.com/26833433/232313313-7404553a-2b14-4b2a-9f6a-455d3baff1fb.png">

**Comment by kalenmike** [comment]
@glenn-jocher Merged and tested.
