### ISSUE TITLE
How to pass training hyps as input to HUB model?

### ISSUE THREAD

**Issue by nicobrb** [ultralytics/hub#218]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have to ask: how do i pass custom hyps for training (like lr0, augment=True, degrees, shear) to the not pretrained HUB model? I try to pass them like this:
![image](https://user-images.githubusercontent.com/39137998/232319884-ab7b5c27-db3d-4259-b155-ad54a52b7b08.png)

This warning is raised:
![image](https://user-images.githubusercontent.com/39137998/232319829-70df4aa4-b3a3-4f5c-a3d6-5932974d7e0c.png)

Sorry for the trivial question, i couldn't find anything online.

**Comment by glenn-jocher** [comment]
@nicobrb hi and thanks for reaching out! We appreciate your input and are always working to improve the HUB experience. We understand that customizing hyperparameters is important for many users, and we are actively working on HUB updates to provide more flexible argument settings, including the ability to adjust hyperparameters like lr0, momentum, degrees, shear, etc.

In the meantime, please stay tuned for updates on our [GitHub issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) pages. We'll make sure to keep our community informed as we implement these enhancements. If you have any other questions or suggestions, feel free to reach out.

We apologize for any inconvenience and appreciate your patience as we work on improving the HUB.
