### ISSUE TITLE
Not starting the record

### ISSUE THREAD

**Issue by SaKon06** [ultralytics/hub#222]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

I don't start the scaning on my phone

### Environment

Android 13

**Comment by glenn-jocher** [comment]
@SaKon06 hi thanks for the bug report! Can you make sure you are using the very latest version of Ultralytics HUB App and see if the problems persists?

If the problem persists please let @sergiossm, our mobile app developer in charge of handling bugs what make and model of phone you have, and a screenshot if you can. Thank you!

**Comment by sergiossm** [comment]
@SaKon06 latest version of Ultralytics HUB app is 0.5.6

**Comment by SaKon06** [comment]
I use latest version, but app don't starting detecting from phone camera
![Screenshot_20230418-215552_Ultralytics HUB](https://user-images.githubusercontent.com/111135948/232853732-698b0b52-e1f6-46d0-ac53-9fa886a99f70.png)
![Screenshot_20230418-215545_Ultralytics HUB](https://user-images.githubusercontent.com/111135948/232853779-7b3cfd6c-5e85-46d6-9cff-a776ce8e7728.png)

**Comment by SaKon06** [comment]
I give for app all permissions

**Comment by sergiossm** [comment]
@SaKon06 make sure you granted all permissions in the app's Android Settings page. Then, restart the app and you should be good to go.
