### ISSUE TITLE
How to develop own model on Ultralytics hub

### ISSUE THREAD

**Issue by myasser63** [ultralytics/hub#223]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have trained YOLOv5s on my own custom dataset. How do I implement my own in form of a phone app using the Hub?

**Comment by kalenmike** [comment]
@myasser63 Thank you for your request to deploy the app! We are glad to inform you that we are actively working on our app libraries for both iOS and Android. These libraries will enable you to embed YOLO models in your own apps. Our mobile developer, @sergiossm, is leading this effort and we are working hard to make the libraries available as soon as possible. We don't have a specific release date yet, but we hope to share it with you soon. We appreciate your patience and look forward to sharing our progress with you!
