### ISSUE TITLE
How do I use Utralytics HUB to train yolov8 instance segmentation models?

### ISSUE THREAD

**Issue by saschwarz** [ultralytics/hub#224]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I didn't see in the options where I could choose between training for detection and segmentation, is it possible?
Thanks!

**Comment by kalenmike** [comment]
@saschwarz Thanks for asking the question. Ultralytics HUB currently only supports object detection, we plan to release classification and segmentation in the future.
