### ISSUE TITLE
How to put my own model into the app

### ISSUE THREAD

**Issue by luliyaoLeo** [ultralytics/hub#225]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have trained a YOLOv8 model, and I want to put this model into the app and test it with the detection function in the app. What do I need to do?

### Additional

If it is convenient, I would also like to ask how to convert the trained .pt model into a .onxx model. I remember that your document mentioned that there is a direct conversion method in the yolov8 project, but I did not find it.

**Comment by kalenmike** [comment]
@luliyaoLeo, thank you for your question. Have you trained the model using HUB? If so, with a HUB account, you will have access to all of our export options, as well as our HUB app. However, currently, we do not support using models trained outside of HUB, even if they were trained with YOLOv8. We understand the importance of having this feature available and are actively working on releasing it in the near future. We appreciate your patience and will keep you updated on our progress.

![image](https://user-images.githubusercontent.com/25989362/233325594-ae79f19e-a61e-4d78-9293-d09b95dd0e2e.png)

**Comment by luliyaoLeo** [comment]
Thanks a lot for your answer~ I think I know what to do.

**Comment by Busterfake** [comment]
@kalenmike any update on this ? i have trained a model on my computer that i would like to test on my phone (.mlmodel). I looked into it but didn't find a way to try it on hub. 
I have my own implementation app to test it but the performances are poor and the problem might be the model itself or my implemetation that does not perform well. and start to be kinda outdated. Do you know any app where i can fastly try my model ? 
Thank you ! :)

**Comment by kalenmike** [comment]
@Busterfake At this time this is not available with Ultralytics HUB. Your best option currently is to train a model using the Ultralytics HUB.
