### ISSUE TITLE
Train YOLOv5s Model

### ISSUE THREAD

**Issue by bortpro** [ultralytics/hub#226]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How do I specifically train a 'YOLOv5s' model using Ultralytics HUB and not one of the other YOLOv5 model? I may specifically need the YOLOv5s model for conversion downstream to another format.

**Comment by kalenmike** [comment]
Thank you for your question, @bortpro. We're excited to share that we've made significant improvements to the YOLOv5s model, resulting in the new and enhanced YOLOv5su model. Please note that the Ultralytics HUB is designed to work with the latest versions of our models, so training an older version is not possible.
