### ISSUE TITLE
add instance segmentation 

### ISSUE THREAD

**Issue by davidbenoot** [ultralytics/hub#234]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description
can you add the possibility to integrate models in segmentation instance 

thx

**Comment by kalenmike** [comment]
@davidbenoot Thanks for the enhancement request. We are currently working on adding classification, once that is complete we plan to add in segmentation and pose.

**Comment by mqxi** [comment]
I'm looking forward to use segmentation models via the hub!

**Comment by IndShiv** [comment]
Hi there. Has the segmentation models been added ?

**Comment by IndShiv** [comment]
> @davidbenoot Thanks for the enhancement request. We are currently working on adding classification, once that is complete we plan to add in segmentation and pose.

Hi David, Just curious on when the segmentation models will be added ?

**Comment by kalenmike** [comment]
@IndShiv @mqxi @davidbenoot We have just released instance segmentation in HUB. Along with classification and pose. Have a play around and let us know what we can improve.

**Comment by IndShiv** [comment]
@kalenmike I have yet to see it on the hub? Am I missing something? Apologies in advance if I am.

**Comment by kalenmike** [comment]
@IndShiv Perhaps you do not have any segmentation datasets? The model task is determined by the dataset that is selected.

When you upload a new dataset you can set the task:

![image](https://github.com/ultralytics/hub/assets/25989362/a8694a11-c633-470d-bacf-a9a1a851a449)

**Comment by IndShiv** [comment]
Hi @kalenmike thanks but I was assuming that there were pretrained instance segmentation models that I could call via API. Does this mean I would have to train and create my own project/model?
