### ISSUE TITLE
EdgeTpu Export model inference

### ISSUE THREAD

**Issue by dhunjoshi** [ultralytics/hub#24]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How can we use Exported edgetpu model for inference. In windows 10 with google coral usb accelerator.

**Comment by glenn-jocher** [comment]
@dhunjoshi good question! The official YOLOv5 export code provides the following Usage examples on exported EdgeTPU models:
```bash
...
Edge TPU: export success, saved as yolov5s-int8_edgetpu.tflite (8.4 MB)

Export complete (223.52s)
Results saved to /content/yolov5
Detect:          python detect.py --weights yolov5s-int8_edgetpu.tflite
PyTorch Hub:     model = torch.hub.load('ultralytics/yolov5', 'custom', 'yolov5s-int8_edgetpu.tflite')
Validate:        python val.py --weights yolov5s-int8_edgetpu.tflite
Visualize:       https://netron.app/
```

Official EdgeTPU inference examples are not yet available, but if you post your question on the YOLOv5 repo you may be able to get community feedback for EdgeTPU inference:
https://github.com/ultralytics/yolov5
