### ISSUE TITLE
tflite

### ISSUE THREAD

**Issue by haowuliaodenie** [ultralytics/hub#240]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I want to deploy mask wearing recognition on imx6ull, so I exported the model to tflite format. However, when I run inference using tflite, the result obtained is a matrix, and I cannot determine whether the result is correct. What should I do

[question.zip](https://github.com/ultralytics/hub/files/11328861/question.zip)

**Comment by glenn-jocher** [comment]
@haowuliaodenie you can see output shapes using a viewer like netron. Here's yolov8n.onnx for example. The output dimensions are (Batch, Channels, Points), witch Channels being (xywh, confidence). The width-height are compressed into the 3rd dimension.

You can run inference with your TFLite model using the ultralytics package to test it. See https://docs.ultralytics.com/modes/export

<img width="1136" alt="Screenshot 2023-04-28 at 00 27 32" src="https://user-images.githubusercontent.com/26833433/235004581-0d3de174-dfe1-40e3-8e0b-3daf82a46f43.png">
