### ISSUE TITLE
Camera not opening 

### ISSUE THREAD

**Issue by Mateusvision** [ultralytics/hub#242]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

A câmera não está abrindo nessa nova atualização

### Environment

Androide: Redmi note 10 pro max miui 14

### Minimal Reproducible Example

Câmera

**Comment by glenn-jocher** [comment]
@Mateusvision hello! Thank you for reaching out and letting us know about this issue. In order for us to help you, could you please provide more details such as what version of the Ultralytics HUB you are using and steps to reproduce the problem? This will help us identify the issue and provide a solution. Thank you!

**Comment by sergiossm** [comment]
@Mateusvision thanks for reporting! Could you also make sure that the app has camera and read and write external storage permissions?

**Comment by sergiossm** [comment]
@Mateusvision Thank you for reporting. This issue is now solved in version 0.6.3
