### ISSUE TITLE
Create Button Missing in Dataset Uplaod

### ISSUE THREAD

**Issue by EA17-ai** [ultralytics/hub#250]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

<img width="576" alt="image" src="https://user-images.githubusercontent.com/89613171/235449378-e2afc67a-1be6-4452-a492-de48d8832217.png">
<img width="919" alt="image" src="https://user-images.githubusercontent.com/89613171/235449456-a3afaff9-e890-4000-8c64-6d3f78a014ce.png">

### Environment

Windows, App:Chrome

### Minimal Reproducible Example

1.Login
2.Upload Datasets
3.Add .zip file
4.Create Button Dissapears

**Comment by glenn-jocher** [comment]
Hello @EA17-ai,

Thank you for reporting this issue. It appears that you're experiencing a bug when uploading a dataset to the Ultralytics HUB. We appreciate you taking the time to provide detailed information such as your environment and the steps to reproduce the error.

Our development team will investigate this issue and provide a fix as soon as possible. In the meantime, we suggest trying a different browser or clearing your cache to see if this resolves the issue. 

If you have any additional questions or concerns, please don't hesitate to let us know.

Thank you for using the Ultralytics HUB!

**Comment by EA17-ai** [comment]
Hi @glenn-jocher i did try other browsers .i got the same results.thanks for the quick reply

**Comment by kalenmike** [comment]
@EA17-ai Thanks for raising this. It looks like its a responsive issue. Can you share your browser resolution?

**Comment by EA17-ai** [comment]
Thanks @kalenmike  yeah it seems i need to zoom out and now i can upload a dataset.Thank you very much

**Comment by glenn-jocher** [comment]
You're welcome, @EA17-ai! I'm glad to hear that zooming out resolved the issue and that you can now upload your dataset successfully. If you have any other questions or concerns, don't hesitate to reach out to us. Thank you for using the Ultralytics HUB!
