### ISSUE TITLE
Train dataset with custom model

### ISSUE THREAD

**Issue by djxy** [ultralytics/hub#252]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hey guys,

I have a dataset of 12k images all labelled and I trained a model on it. It works well and I would like to add more classes to my dataset.

Do I have to create a new model that will train on my new dataset containing my old and new classes or I can use my old model as a starting point?

I'm asking, because from the UI I can't choose my current model with my new dataset and I'm new to the Yolo environment.

Thanks

**Comment by kalenmike** [comment]
@djxy Thanks for the question. Did you train the first model using the Ultralyitcs HUB?

**Comment by djxy** [comment]
Hey @kalenmike, yes I used the Ultralytics HUB to train my model. I see my model in the list of models. When I try to train my other dataset, I only see the default Yolov8 an v5 models.

Also I can't change my model name, it has the default name: Model - 2 May 2023 0:06

**Comment by kalenmike** [comment]
@djxy Thanks for the quick reply. On the UI we currently only allow a model to be trained from one of our base models or architectures. However you can use your model as a base model using the `ultralytics` package directly.

We had previously thought about introducing this feature into the UI but it has been sidelined for the moment.

What issue are you having with renaming the model?

**Comment by djxy** [comment]
I will check it with the `ultralytics` package.

When I edit the name of the model, it returns this message: `Unable to Update Model`
