### ISSUE TITLE
Dataset Not Uploading - Unable to Reach Server

### ISSUE THREAD

**Issue by gambobill** [ultralytics/hub#254]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Dear Sir or madam,

I upload the datasets zip file and then coming up the error "unable to reach server"

**Comment by kalenmike** [comment]
@gambobill Thank you for raising this bug. This is confirmed issue that came up in the latest version. We are working to fix this now.

**Comment by gambobill** [comment]
Take your time thanks

**Comment by kalenmike** [comment]
@gambobill @theincrediblerexThis is now resolved. Please let me know if you are still having issues.

**Comment by Busterfake** [comment]
Hello ! i try to upload a dataset and same problem here :/ 
The upload goes up to 100% and then i have the error : _**failed Unable to Reach Server**_

**Comment by kalenmike** [comment]
@Busterfake It is possible that you lost internet connection during the upload. How large is the dataset you are trying to upload?

**Comment by Busterfake** [comment]
I don't think so, it about 20 Go.

**Comment by glenn-jocher** [comment]
@Busterfake Thank you for your response. We recommend using a stable internet connection to prevent any interruptions during the upload process, especially for large datasets like yours. If the issue persists, please let us know, and we will investigate further. Thank you for using Ultralytics HUB!

**Comment by Busterfake** [comment]
Thanks, i have managed to upload it. I reached the scanning stage and it stayed like this for hours. But now i have a new error: 
_**Failed   Unknown Error**_

**Comment by UltralyticsAssistant** [comment]
@Busterfake I apologize for the inconvenience. The "Unknown Error" typically indicates a processing issue on our end after the upload has completed. Our team will look into it. Meanwhile, please ensure that your dataset is formatted correctly according to our documentation. If you continue to experience difficulties, don’t hesitate to reach out again.
