### ISSUE TITLE
Failed to reach server while uploading

### ISSUE THREAD

**Issue by theincrediblerex** [ultralytics/hub#255]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

<img width="367" alt="image" src="https://user-images.githubusercontent.com/124577324/235954296-c96e6b62-706f-441c-a77e-9268eddd0120.png">

**Comment by kalenmike** [comment]
@theincrediblerex Thanks for raising this, it has been reported here #254. We are working to get this fixed.
