### ISSUE TITLE
Ultralytics HUB Rotating Pictures in my Dataset / Not Loading at All

### ISSUE THREAD

**Issue by bortpro** [ultralytics/hub#258]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

![Screen Shot 2023-05-04 at 1 29 33 AM](https://user-images.githubusercontent.com/70864791/236151426-83d70929-d643-4f9f-b9ac-1b8a2e53fe9e.png)

![Screen Shot 2023-05-04 at 1 30 08 AM](https://user-images.githubusercontent.com/70864791/236151540-9bd11834-a462-4e53-9eb9-bcac2a51c5a9.png)

Picture 1: Endless loading of a dataset, does not open and allow me to train a model on it

Picture 2: The pictures are rotated 90 degrees counter-clockwise, yet the original pictures are correct and right side up. This is affecting all the labels, unfortunately, and not allowing to train models

### Environment

Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

### Minimal Reproducible Example

1. Login to Hub
2. Click on Datasets
3. Upload Datasets
4. Observe that Dataset in Pic 1 does not load
5. Observe that Dataset in Pic 2 does not load correctly, with rotated pictures

**Comment by kalenmike** [comment]
@bortpro Thanks for taking to raise this bug. Could you share your dataset id with me so we can look into what is happening? You can find the id in the URL.

https://hub.ultralytics.com/datasets/DATASET_ID

**Comment by bortpro** [comment]
The dataset ID is Cj8TtSSIlRg0aRvejHmI.

The other dataset that does not load does not let me provide an ID, as it continues to show "Scanning".

**Comment by kalenmike** [comment]
@bortpro Thanks for sending this. I can confirm the rotation issue and will look into what is happening to get this resolved. With the second dataset that is stuck on scanning, something went wrong during the upload and the fallback fail time has not passed yet. Can you delete that dataset and upload it again?

**Comment by bortpro** [comment]
Thank you. If the first rotation issue gets resolved, that should be sufficient to train the model I'm interested in.

Unfortunately since the second dataset is stuck scanning, it does not give me the option (unlike the other datasets) to delete this dataset.

**Comment by kalenmike** [comment]
@bortpro For the rotated images I found this in your metadata, we are respecting this and that is why the images are rotated.

```
Orientation
    Rotate 90 CW
```

To fix this you can strip the metadata from your images.

**Comment by bortpro** [comment]
Thank you! This helped fixed the problem and I was able to create a new dataset that fixed this problem completely. I think I transferred these pictures from iPhone to my computer, and some sort of conversion must have unknowingly happened.

I was also able to delete the other dataset successfully.

**Comment by glenn-jocher** [comment]
@bortpro I'm glad that we were able to resolve the issue for you. Please feel free to reach out to us if you have any further questions or issues. We are always here to help! Thank you for using Ultralytics HUB.
