### ISSUE TITLE
NMS for CoreML model export 

### ISSUE THREAD

**Issue by gambobill** [ultralytics/hub#260]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

Why export CoreML model which is missing Non Maximum Suppression?

**Comment by kalenmike** [comment]
@gambobill Thanks for raising this. We are working to release the option to set advanced export options. For the moment the default CoreML models do not have nms enabled. The Ultralytics CoreML model does have nms enabled.

**Comment by glenn-jocher** [comment]
Hi @gambobill, thanks for your interest in advanced export options. We don't have a specific timeline for the release of this feature but we are actively working on it. We'll keep the community updated as soon as we have more information. Please let us know if you have any other questions or if there's anything else we can help you with.

**Comment by kalenmike** [comment]
@gambobill For the moment you can do this manually using the ultralytics package, by downloading the pyTorch model and then running these commands.

```bash
pip install ultralytics
```

```python
from ultralytics import YOLO

# Load a model
model = YOLO('path/to/weights.pt')  

# Export the model
model.export(format='coreml', nms=True)
```

You can find the available arguments here:
https://docs.ultralytics.com/modes/export/#arguments

**Comment by gambobill** [comment]
Dear Kalemike,

you did a nice job for export the apple ml model with advance feature

**Comment by glenn-jocher** [comment]
Thank you for your kind words, @gambobill. We are glad you found the CoreML export with NMS feature helpful. Please let us know if you have any issues or if there's anything else we can assist you with. We strive to provide the best support for the community.
