### ISSUE TITLE
Error message when training data after session expiration on Ultralytics Hub using Google Colab.

### ISSUE THREAD

**Issue by upsightDev** [ultralytics/hub#264]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

![image](https://user-images.githubusercontent.com/117809409/236718820-a24d1034-892f-439a-b612-006b0a896c8e.png)

After logging in to Ultralytics Hub using Google Colab, if you attempt to train using training data that previously caused a session to expire, you may encounter the error 'RuntimeError: Dataset '/content/datasets/CrackNet.v5-removed-contrast-added-greyscale-blur.yolov5pytorch/data.yaml' error ❌ '/content/datasets/CrackNet.v5-removed-contrast-added-greyscale-blur.yolov5pytorch/data.yaml' does not exist'.

**Comment by kalenmike** [comment]
@upsightDev Thanks for raising this bug. We will look into this and see what is going on.

**Comment by glenn-jocher** [comment]
@upsightDev thanks for the bug report! Do you see the same error if you CTRL+C your training and then try to continue with model.train()?

How can we reproduce this error on our end?
