### ISSUE TITLE
Storage not allowing access on my phone 

### ISSUE THREAD

**Issue by Felipefabricio25** [ultralytics/hub#269]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Heya! I've been trying to use the Ultralytics HUB app on my Android, but I'm having an issue. In the "detect" section, it asks me for camera and storage permission and refuses to start the detection. The camera is allowed just fine, but the storage is asking me to be allowed.

However, nothing I do allows the storage. There is a button "allow" next to it, but it doesn't do anything. No permissions on my phone even mention asking for storage permission. What am I doing wrong? Thanks a lot!

**Comment by sergiossm** [comment]
@Felipefabricio25 Thank you for reporting the issue. We're having some problems with the library we use for handling permissions on Android, we're working on a fix. 

Sorry for the inconvenience.

**Comment by sergiossm** [comment]
@Felipefabricio25 Issue resolved in version 0.6.4. Sorry for the delay, I'm out of the office and have struggled to find time to fix it.
