### ISSUE TITLE
Dataset not downloading when resuming training

### ISSUE THREAD

**Issue by rsemihkoca** [ultralytics/hub#270]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/hub/assets/82779464/b90c09d9-b0f1-40c4-a7ac-aa830e5820c9)

While I was training the model, it was interrupted due to internet outage. It seems to have received 18 checkpoints, but I keep getting file not found error. I didn't see a button to continue training on interface. In such a case, should we start the train again or is there an alternative way?

### Environment

- Linux Ubuntu 20.04
- Browser Mozilla
- Hp elitebook g8

### Minimal Reproducible Example

Steps to reproduce the problem:
1. Login
2. Edit api key/model id and start  training
3. Between 10-20 epochs disconnect ethernet
4. After restart open browser and run colab notebook

**Comment by kalenmike** [comment]
@rsemihkoca Thanks for raising this bug. Your model has a checkpoint saved for epoch 17, so you should be able to resume training from that epoch. When you run the same training code it should automatically resume training, but it looks like the dataset is not getting downloaded again. We will look into getting this resolved.

A similair bug was reported here #264 

@sergiuwaxmann Can we check to make sure that the resume code is shown again on the Frontend.

**Comment by rsemihkoca** [comment]
@kalenmike 
![image](https://github.com/ultralytics/hub/assets/82779464/7028feab-bee1-4ffc-ac23-f5623907c77b)
Disconnected from colab and closed browser and this resume button showed up but same error raised

**Comment by kalenmike** [comment]
@rsemihkoca Ok thanks for the update. So the Frontend is working fine, but the dataset is not getting downloaded on resume. I will look into this now and hopefully we can publish a fix soon.

**Comment by glenn-jocher** [comment]
@kalenmike @rsemihkoca bug is fixed in https://github.com/ultralytics/ultralytics/pull/2566

This will be part of `ultralytics 8.0.99` later today.
