### ISSUE TITLE
ONNX export for jetson inference 

### ISSUE THREAD

**Issue by MorcretteApside** [ultralytics/hub#274]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello,

I have a jetson nano working on python 3.6 and I use the librairie jetson inference.
I want to launch a onnx model that i pre-trained on ultralytics and i found out that the onnx model is not the same as the onnx exemple used in the jetson nano tutorial. They have 2 output for the model and you juste have 1.
Do you know how can I export it in the right model or used this model for jetson nano?

Thanks

### Additional

Your model
![image](https://github.com/ultralytics/hub/assets/128390402/aee3cf4f-232b-4bff-a069-0bb10f539bfb)
The model used in the tutorial
![Screenshot from 2023-05-12 14-57-10](https://github.com/ultralytics/hub/assets/128390402/db0efd93-a595-41ed-814d-d40c201cb7ca)

**Comment by glenn-jocher** [comment]
@MorcretteApside see https://wiki.seeedstudio.com/YOLOv8-DeepStream-TRT-Jetson/ for a full guide on deploying YOLOv8 to Jetson nano.
