### ISSUE TITLE
Uploading only models

### ISSUE THREAD

**Issue by zakenobi** [ultralytics/hub#275]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi I was trying to find a way to upload models that I've trained localy but I didn't find a way to do that. Is this somehow possible or comming in the futur ?

**Comment by glenn-jocher** [comment]
@zakenobi hi, thank you for your interest in the Ultralytics HUB! Yes, you can definitely upload locally trained models to the HUB. Here are the steps:

1. Navigate to your local model directory and locate the `.pt` file for the model you want to upload.
2. Drag and drop the `.pt` file onto the HUB upload page, like you would with any other dataset or model.
3. Fill in all the required information, such as the model name, version, and description.
4. Click 'Upload' to add your model to the HUB!

Let us know if you have any other questions or concerns, we're happy to assist you further.

**Comment by zakenobi** [comment]
Thanks for the feed back! I feel like this should be simple but the website wont let me upload anything other than a zip file, can you send me the link of where can upload or a screenshot of the page I'm looking for ?
![image](https://github.com/ultralytics/hub/assets/54433310/95ce70c9-bdc4-430e-b03e-0bf7ab9c64ed)

**Comment by pbartosek** [comment]
I'm having the same issue as well. There is no "Upload" tab at the top of the HUB homepage. The only upload link says "Upload Dataset"

Is this feature not available for free plans?

**Comment by glenn-jocher** [comment]
@pbartosek @zakenobi ah yes apologies, model upload is a future feature. It's in our roadmap for later this year, but I can't provide a definite timeline yet.

**Comment by SimonBaumgaertner** [comment]
Hey!
Is uploading your own models implemented or planned?
I did not find anything online. Cheers

**Comment by pderrenger** [comment]
Hey there! 😊 Uploading your own models is indeed planned for a future update of the Ultralytics HUB. Currently, it's one of the features we're actively working on. Stay tuned for updates! Cheers!

**Comment by akash-harijan** [comment]
Hi, have you guys implemented this very important feature? if yes then can you lead to any documentation related to it?

**Comment by pderrenger** [comment]
@akash-harijan thank you for your question! 🙌 Model upload functionality is indeed an important feature that's currently in active development. While our SDK includes technical implementations for model upload capabilities (as seen in the [HUB SDK Model Upload documentation](https://docs.ultralytics.com/hub/sdk/reference/modules/models/)), this feature hasn't yet been fully exposed in the Ultralytics HUB web interface. 

We appreciate your patience as we work to implement this properly. For the latest updates on feature releases, we recommend:
1. Starring ⭐ our [HUB GitHub repo](https://github.com/ultralytics/hub) to get release notifications
2. Joining our [Discord community](https://discord.gg/ultralytics) where we announce new features first
3. Checking our [HUB Documentation](https://docs.ultralytics.com/hub/) for future updates

While manual model uploads aren't available yet, you can currently train custom models directly in HUB using your own datasets through our [Cloud Training solution](https://docs.ultralytics.com/hub/cloud-training/). Would this workflow potentially meet your needs in the interim?
