### ISSUE TITLE
Android app detection not working

### ISSUE THREAD

**Issue by kuldeepaher01** [ultralytics/hub#277]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

I trained a model using the hub api and tried to deploy using Hub app on android but nothing is getting detected. 

### Environment

-Android 13
- Apk verison 0.6.6
- Snapdragon 855
Device - Poco X3 Pro

**Comment by sergiossm** [comment]
Hey @kuldeepaher01 can you share the id of the model? 
Do the bundled models work (YOLOv8n, s, and m)?

**Comment by kuldeepaher01** [comment]
@sergiossm No bundled models are also not working.

**Comment by sergiossm** [comment]
@kuldeepaher01 does the camera preview work?

**Comment by sergiossm** [comment]
@S7eezy Android 13 as well?

**Comment by S7eezy** [comment]
> @S7eezy Android 13 as well?

Android 12

**Comment by sergiossm** [comment]
@kuldeepaher01 @S7eezy Thanks, I'm looking into it

**Comment by sergiossm** [comment]
@S7eezy what device are you using?

**Comment by sergiossm** [comment]
@kuldeepaher01 @S7eezy Fixed in version 0.6.67. Thanks for reporting!

**Comment by S7eezy** [comment]
> @kuldeepaher01 @S7eezy Fixed in version 0.6.67. Thanks for reporting!

Nice job ! 🚀

**Comment by glenn-jocher** [comment]
Thank you for reporting the issue @kuldeepaher01 and @S7eezy. We apologize for the inconvenience and we're glad to hear that the issue has been resolved in the latest version (0.6.67) of the Ultralytics HUB. Please let us know if you encounter any further issues or if you have any other questions. Keep up the great work with YOLO and the HUB! 🚀

**Comment by S7eezy** [comment]
@glenn-jocher It is fixed since the update ! Nice job

**Comment by glenn-jocher** [comment]
@S7eezy thank you for confirming that the issue has been resolved with the latest update. We appreciate your feedback and are glad to hear that the problem has been solved. If you have any further questions or issues, please don't hesitate to reach out to us. Thank you for using YOLO and the Ultralytics HUB! 🤖🚀
