### ISSUE TITLE
Downloadable graphs

### ISSUE THREAD

**Issue by kuldeepaher01** [ultralytics/hub#278]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

The graphs produced while training if had a option to download would be very helpful. 

### Use case

In case who are using free version of colab these graphs wont be available for them as colab disconnects them automatically.

**Comment by glenn-jocher** [comment]
@kuldeepaher01 thank you for your suggestion. The ability to download training graphs could potentially be a useful feature for our users who are using Colab's free version. We will consider implementing it in a future update. In the meantime, one workaround could be to regularly save snapshots of the training graphs manually during your training process to ensure you don't lose any important data.
