### ISSUE TITLE
Remaining time is not correct 

### ISSUE THREAD

**Issue by kuldeepaher01** [ultralytics/hub#279]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

When model is being trained the remaining time is sort of inaccurate it shows 1 minute even for 50 or even 90 epochs

**Comment by glenn-jocher** [comment]
@kuldeepaher01 thanks for the bug report! 

@sergiuwaxmann if you know about this please take a look, otherwise we can wait untill Kalen returns.
