### ISSUE TITLE
Error Uploading a new dataset on ultralytics 

### ISSUE THREAD

**Issue by tininha94** [ultralytics/hub#28]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello,
I am having problems uploading a dataset on the hub. I followed the steps on this link https://github.com/ultralytics/hub#1-create-a-dataset to create my dataset with roboflow but I tried to upload several times and this error appears: 

![a](https://user-images.githubusercontent.com/82990476/167746765-c4487b33-048d-4df6-b7bb-20225b4cb5a7.PNG)

this is the last dataset that I tried to upload:
[projeto.zip](https://github.com/ultralytics/hub/files/8665749/projeto.zip)

**Comment by tininha94** [comment]
The problem was solved by arrending the folders and the yams file. Thanks! :)

**Comment by kalenmike** [comment]
@tininha94 Glad you were able to resolve this. We are currently working on detecting and resolving well known dataset configuration errors such as this automatically. The aim is to make it as easy as possible to upload a custom dataset.

Thanks for using the Ultralytics HUB and feel free to reach out if you need any other support or would like to offer some feature suggestions.
