### ISSUE TITLE
After 100 epochs, I got an error saying results.csv doesn't exist...

### ISSUE THREAD

**Issue by jhp21c-dev** [ultralytics/hub#281]
![setup](https://github.com/ultralytics/hub/assets/113663639/7d814a8e-8302-4d3b-bd11-0610e185b281)
![start1](https://github.com/ultralytics/hub/assets/113663639/0f5a8b0f-6a92-4de3-b3a4-2868e3a199e5)
![start2](https://github.com/ultralytics/hub/assets/113663639/1a73a6b0-fb09-45bb-81e6-8fae94963d3a)
![start3](https://github.com/ultralytics/hub/assets/113663639/70a3cd82-e98b-4bcb-bb5c-51b6c3044233)
![start4](https://github.com/ultralytics/hub/assets/113663639/0a408f65-33d9-4e02-b935-2b52af33cdec)
![start5](https://github.com/ultralytics/hub/assets/113663639/6402ed1c-3118-4028-91e7-b977f13c0b17)
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I trained a custom dataset with yolo v8 model. It went fine, but after 100 epochs, I got an error saying results.csv doesn't exist...
I think that after the 100th epoch, the collapse stopped at about 25% of the way through some process, but the next time it runs, it skips this process and gives an error.

This is an error message.

1 epochs completed in 0.000 hours.
AssertionError Traceback (most recent call last)
in <cell line: 4>()
2
3 model = YOLO('https://hub.ultralytics.com/models/4LzYHx47aChBnpjAl24L')
----> 4 model.train()

5 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/plotting.py](https://localhost:8080/#) in plot_results(file, dir, segment, pose, classify, on_plot)
447 ax = ax.ravel()
448 files = list(save_dir.glob('results*.csv'))
--> 449 assert len(files), f'No results.csv files found in {save_dir.resolve()}, nothing to plot.'
450 for f in files:
451 try:

AssertionError: No results.csv files found in /content/runs/detect/train, nothing to plot.`

### Environment

- Computer : Lenovo Legion 5 pro
- OS : Windows 11
- Using Colab

### Minimal Reproducible Example

1. login to hub 
2. I copied the link and pasted it into a collab
3. Normal training up to 100 epochs.
4. After running up to 100 epochs, I got to a certain percentage, maybe 25%, and then the runtime froze.
5. I then initialize the runtime, run it again, and it says results.csv doesn't exist.

### Additional

Ultralytics HUB Version
v0.1.18-beta.19
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Whale/3.20.182.14 Safari/537.36
Operating System
Win32
Browser Window Size
1874 x 929
Server Timestamp
1684595607

https://hub.ultralytics.com/models/4LzYHx47aChBnpjAl24L

**Comment by glenn-jocher** [comment]
@jhp21c-dev hello! Sorry to hear that you are having issues with your training. From the error message you provided, it seems that the script is not able to find the `results.csv` file in the `train` folder. This may happen if the file was not created during training or if it was moved or deleted. 

To troubleshoot this, you can try re-running the script and checking whether the `results.csv` file is being created during training. If the file is created, it should be located in the `train` folder. If not, you can try modifying your training script to log the training metrics to a file. This should ensure that the `results.csv` file is created during training. 

If you are still experiencing issues, please let me know and provide me with more details about your training process. Also, please ensure that you are running the latest version of Ultralytics HUB and that your dependencies are up to date.

**Comment by jhp21c-dev** [comment]
Okay, I'll run the model again and get back to you.

**Comment by jhp21c-dev** [comment]
I ran it again and got the same error. Can you tell me how to modify the training script to write the training metrics to a file?
(I am running the latest version of Ultralytics HUB and using google colab)

**Comment by jhp21c-dev** [comment]
Here is my colab code. https://colab.research.google.com/drive/1dYY8e0GXjMqVY00TbqyQgWWTPZTob8Ko?usp=sharing

**Comment by glenn-jocher** [comment]
@jhp21c-dev thanks for the details. It seems like your model is already fully trained, i.e. you requested 100 epochs and the model is already trained for 100 epochs, so there appears to be nothing to resume. In this case it appears the error is connected with attempting to resume a fully trained model.

**Comment by jhp21c-dev** [comment]
Then, when I tried to view the model preview on https://hub.ultralytics.com/models/4LzYHx47aChBnpjAl24L?tab=preview, I got the error "Model Not Trained!"
"Finish training your model to run real time inference using our API", how can I fix this?

**Comment by glenn-jocher** [comment]
@jhp21c-dev, thanks for your question. The error message you are seeing on the model preview page "Model Not Trained!" indicates that your model has not yet been fully trained, therefore, you will not be able to run real-time inference using our API until the model has been trained.


To fix this, you would need to train the model further until it reaches a suitable performance level. You can increase the number of epochs or adjust the other hyperparameters to improve the model's performance. Once the model has been fully trained, you should be able to run real-time inference on it using our API. 

Please let me know if you have any further questions or need any more help with the Ultralytics HUB platform.
