### ISSUE TITLE
multi GPU train

### ISSUE THREAD

**Issue by modu82** [ultralytics/hub#282]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I have multiple GPUs, but when using Ultralytics, only one graphics card was called, which forced me to choose other methods to train the model

### Use case

I have multiple GPUs, but when using Ultralytics, only one graphics card was called, which forced me to choose other methods to train the model

### Additional

n

**Comment by glenn-jocher** [comment]
@modu82 thank you for your question about utilizing multiple GPUs in Ultralytics HUB. By default, YOLOv3 and YOLOv5 can support training on multiple GPUs with data parallelism and model parallelism. 

To train on multiple GPUs with data parallelism, you can set the `batch_size` parameter to be the total batch size across all GPUs. Ultralytics' `--multi-scale` training flag automatically scales the input image size for improved performance, which can be used in combination with multiple GPUs as well. 

To train on multiple GPUs with model parallelism, you can use the `--device` flag to specify which GPUs to train on and which parts of the model to place on each GPU.

Please let us know if you have any further questions, and we appreciate your interest in our HUB!
