### ISSUE TITLE
please help ; Yolov5 and Yolov5nu give me problems when loading the model in python

### ISSUE THREAD

**Issue by cristoferJaimez** [ultralytics/hub#285]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

In the Yolov5 version, you could load the .pt models in the following way:
#model = torch.hub.load('ultralytics/yolov5', 'custom', path='model_- 24 May 2023 16 04.pt'); .pt models are now generated Yolov5nu; and generates the following error:
Exception: 'Detect' object has no attribute 'grid'. Cache may be out of date, try `force_reload=True` or see https://docs.ultralytics.com/yolov5/tutorials/pytorch_hub_model_loading for help. aid :(

### Environment

Python 3.9.16 (main, Jan 11 2023, 16:16:36) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.31.1 -- An enhanced Interactive Python.

### Minimal Reproducible Example

not

### Additional

not

**Comment by cristoferJaimez** [comment]
es un problema por que no me deja cargar los modelos trastornos

**Comment by cristoferJaimez** [comment]
It is a problem because it does not let me load the disorder models with

**Comment by glenn-jocher** [comment]
@cristoferJaimez the usage you describe is the older YOLOv5 usage. See python Docs to usage examples of loading trained models with `ultralytics`: 

https://docs.ultralytics.com/usage/python/
