### ISSUE TITLE
HUB export and inference API errors from 31 May

### ISSUE THREAD

**Issue by glenn-jocher** [ultralytics/hub#288]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export, Inference

### Bug

Export and inference API are failing starting 31 May, caught in that day's HUB export CI and also reported on Discord #hub-web channel. 
<img width="1562" alt="Screenshot 2023-05-31 at 19 42 15" src="https://github.com/ultralytics/hub/assets/26833433/c477848f-76da-4df6-9100-f83828802afd">
<img width="1562" alt="Screenshot 2023-05-31 at 19 41 00" src="https://github.com/ultralytics/hub/assets/26833433/757c000c-2d0f-408b-823d-919d90d33815">

### Environment

Ultralytics HUB Version
v0.1.18-beta.19
Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Operating System
MacIntel
Browser Window Size
1450 x 958
Server Timestamp
1685555620

### Minimal Reproducible Example

Train on COCO8 with all default settings. After model uploads unable to run inference API or export correctly.

### Additional

Error currently in https://hub.ultralytics.com/models/jpeUwlseEjHEwSrCQRME

**Comment by glenn-jocher** [comment]
Update: It looks like this may be due to a change in the `ultralytics` package versions. Tested with 8.0.100 and inference API works correctly. 

- 8.0.100 good
- 8.0.111 error

**Comment by glenn-jocher** [comment]
@kalenmike ok among the PRs between 8.0.110 and 8.0.111 causing issues I see https://github.com/ultralytics/ultralytics/pull/2874 has updated architecture to allow for simpler RT-DETR implementation in the `ultralytics` package. 

I think what's happening is that newly trained 8.0.111 models are being passed to older versions for inference, which is what caused problems before. Can you update the server to run 8.0.111?

**Comment by kalenmike** [comment]
@glenn-jocher The server is now running the latest ultralytics package.
