### ISSUE TITLE
When Are Classifcation and Segmentation Models Coming?

### ISSUE THREAD

**Issue by imdafei** [ultralytics/hub#289]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

when can add seg and cls models and train and deploy? Waiting for you. Come on!

**Comment by glenn-jocher** [comment]
@imdafei hi there! Thank you for your interest in our HUB platform and for reaching out. We appreciate your patience while we continue to develop and improve the HUB for our users. 

As for your question about adding seg and cls models, we are actively working on supporting these model types. We will make sure to announce any updates on our HUB or GitHub pages as soon as they become available. 

Thank you again for your support and please don't hesitate to reach out if you have any further questions or concerns!
