### ISSUE TITLE
Model won’t complete download on app

### ISSUE THREAD

**Issue by UnkoC0wbOy** [ultralytics/hub#29]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Export

### Bug

I have the Ultralytics app downloaded on an iOS device running iOS 15.1. The app works great when running the Ultralytics demo models. But when I try to download my own trained model the model seems to stall out repeatedly when  3/4 of the way complete and eventually a red exclamation point appears. I have checked the available memory on my device and should have plenty available.
![AD91DAD9-D650-4D3A-823E-CA8ED39EBCDB](https://user-images.githubusercontent.com/89663444/167750533-6bc0e333-84e8-45cb-895f-ba1f326efe64.jpeg)

### Environment

-mobile device iPhone XR RUNNING iOS 15.1 

### Minimal Reproducible Example

Download Ultralytics app from AppStore sign into my Ultralytics hub account and download custom model. This is where I eventually stall out.

### Additional

Keep up the awesome work!

**Comment by sergiossm** [comment]
Hi @UnkoC0wbOy, thanks for your feedback!

We're looking into it. We'll let you when it's fixed.

**Comment by sergiossm** [comment]
@UnkoC0wbOy after several tests we can confirm that the model download feature is working with no errors on iOS in the latest version of our app. Please, follow these steps and get back to us if the issue persists:
1. Sign out from the app
2. Uninstall the app
3. Download the latest version [here](https://apps.apple.com/us/app/ultralytics/id1583935240). Make sure it's version 0.1.1+21 (app version can be found on Settings screen)
4. Sign back in and try to download the model again
