### ISSUE TITLE
Tensorflow saved model use

### ISSUE THREAD

**Issue by MorcretteApside** [ultralytics/hub#290]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi, 

I have download the tensorflow Saved model after training my model,
But i dont know how to deploy it. 
I want to deploy this on my jetson nano B01 if its possible

Thanks

**Comment by glenn-jocher** [comment]
@MorcretteApside hello,

Deploying a TensorFlow saved model on Jetson Nano B01 is possible. You can use TensorFlow C++ API to deploy the model.

Please note that the Ultralytics HUB primarily deals with object detection tasks using the YOLO family of models and PyTorch framework. As such, we may not be able to provide extensive guidance on TensorFlow saved model deployment. 

I recommend checking out TensorFlow's documentation regarding C++ API usage for deployment. Additionally, there are many online resources and forums where you can find guidance on deploying TensorFlow saved models on Jetson Nano.

Let me know if you have any further questions. 

Best regards.
