### ISSUE TITLE
Using the Inference API

### ISSUE THREAD

**Issue by CemHaligur** [ultralytics/hub#291]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Hey,

I was trying to use the API to inference images in my notebook, but when i try to print my 'response' variable i have this : <Response [400]>.
I guess the API don't work, how can i handle this ?

Kind regards !

**Comment by kalenmike** [comment]
Hi @CemHaligur, the response suggests that your request is invalid. Can you give us an example of a request you are sending?

**Comment by kalenmike** [comment]
Hi @CemHaligur, the response suggests that your request is invalid. Can you give us an example of a request you are sending?

**Comment by CemHaligur** [comment]
This is an example of the code : 

url = "https://api.ultralytics.com/v1/predict/XXXX"

headers = {

    "Content-Type": "multipart/form-data",

    "x-api-key": "XXX"
}

files = {

    "file": ("image", open("./data/Raw/V-00488_2023_02_03_09-23-51.jpeg", "rb"), "image/jpeg")
}

data = {

    "size": 640,

    "confidence": 0.20,

    "iou": 0.45
}

response = requests.post(url, headers=headers, files=files, data=data) 

And i try to print the json file i have this : 

{'data': {},
 'message': 'An image file or URL must be submitted.',
 'success': False}
 
 but i have the right path to my file

**Comment by kalenmike** [comment]
@CemHaligur There is an issue with your files, I can see the same issue on our example code on HUB. We will get this updated. For now you can [follow the docs](https://docs.ultralytics.com/hub/inference_api/).

The change needed is here:

```
files = {
"image": open("./data/Raw/V-00488_2023_02_03_09-23-51.jpeg", "rb")
}
```

**Comment by ape75** [comment]
Hi.
I have also tried to use the API with some images from my computer and I keep getting the same error as @CemHaligur. I have tried various ways to send the image and also noticed some differences between HUB example code and documentation. 

API returns the 400 - Bad Request response status code :
{'data': {}, 'message': 'An image file or URL must be submitted.', 'success': False}

Here is my code:

`import requests

url = "https://api.ultralytics.com/v1/predict/XXXXXXXXXXXXXXXXX"
headers = {
	"Content-Type": "multipart/form-data",
	"x-api-key": "*********************************************************"
}
files = {
	"image": open("image2.jpg", "rb")
}
data = {
	"size": 640,
	"confidence": 0.25,
	"iou": 0.45
}
response = requests.post(url, headers=headers, files=files, data=data)

print(response.json())`

**Comment by CemHaligur** [comment]
> 

Same issue with this doc : 

import requests

# API URL, use actual MODEL_ID
url = f"https://api.ultralytics.com/v1/predict/XXXXXXXXXX"

# Headers, use actual API_KEY
headers = {"x-api-key": "XXXXX"}

# Inference arguments (optional)
data = {"size": 640, "confidence": 0.20, "iou": 0.45}

# Load image and send request
with open("./data/Raw/V-00476_2023_02_03_09-50-04.jpeg", "rb") as image_file:
    files = {"image": image_file}
    response = requests.post(url, headers=headers, files=files, data=data)

print(response.json())

-> {'data': {}, 'message': 'Unknown', 'success': False}

**Comment by glenn-jocher** [comment]
@CemHaligur and @CemHaligur, there seems to be an issue when using specific versions of requests package, which prevents multipart/form-data from being set up correctly. Please make sure you are using requests version 2.22.0 or newer by running `!pip install --upgrade requests` in your notebook. 

If you still face the same error after upgrading the requests package, please try sending the image as bytes instead of a file, as in the following example:

```
import requests

url = "https://api.ultralytics.com/v1/predict/XXXXXXXXX"
headers = {
    "Content-Type": "multipart/form-data",
    "x-api-key": "XXXXXXXXXXXXXXXXXXXXX",
}
with open("image.jpg", "rb") as f:
    image_data = f.read()
data = {"size": 640, "confidence": 0.25, "iou": 0.45}
response = requests.post(
    url, headers=headers, data=data, files={"image": ("image.jpg", image_data)}
)
print(response.json())
```

Please let us know if this helps!

**Comment by ape75** [comment]
Hi.
I updated the requests package and tried also your example code, but the problem still remains the same.

{'data': {}, 'message': 'An image file or URL must be submitted.', 'success': False}

**Comment by kalenmike** [comment]
@CemHaligur We found an issue that was causing the `Unknown` response when not setting the normalize option. Your last example should work now since the fix.

@ape75 Do not set the content type but allow requests to set it so that a boundary can be set.

```
import requests

url = "https://api.ultralytics.com/v1/predict/XXXXXXXXX"
headers = {
	"x-api-key": "XXXXXXXXXXXXXXXXXXXXX",
}

data = {
	"size": 640,
	"confidence": 0.25,
	"iou": 0.45
}

files={
	"image": open("image2.jpg", "rb")
}

response = requests.post(url, headers=headers, files=files, data=data)

print(response.json())
```

**Comment by ape75** [comment]
Now it is working fine. 👍 
Thank you for the quick response.

**Comment by glenn-jocher** [comment]
@ape75 you're welcome! We're glad to hear that the issue has been resolved. If you have any other questions or concerns, please don't hesitate to reach out to us. We're always here to help. Thank you for using Ultralytics HUB!
