### ISSUE TITLE
Front Facing Camera

### ISSUE THREAD

**Issue by Klinefelters** [ultralytics/hub#293]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Hey! I absolutely love all the work you've been doing! I wanted to ask if we could get a way to switch to the front facing camera on the app. It would be an easy way to demonstrate detecting people.

### Use case

It would be helpful when demoing the capabilities of Ultralytics, specifically yolov8.

**Comment by sergiossm** [comment]
Hey @Klinefelters,thanks for your feedback. We're actually working on it right now,it might be ready next week.

**Comment by Klinefelters** [comment]
That's awesome news, I can't wait to see it!

**Comment by glenn-jocher** [comment]
Thank you for your enthusiasm, @Klinefelters! We are excited to deliver this feature and hope it exceeds your expectations. We will update the repository as soon as it's ready. Stay tuned!
