### ISSUE TITLE
Automatic batch selection is incorrect

### ISSUE THREAD

**Issue by SenchaBrest** [ultralytics/hub#297]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/utils/tal.py in select_candidates_in_gts(xy_centers, gt_bboxes, eps)
     22     bs, n_boxes, _ = gt_bboxes.shape
     23     lt, rb = gt_bboxes.view(-1, 1, 4).chunk(2, 2)  # left-top, right-bottom
---> 24     bbox_deltas = torch.cat((xy_centers[None] - lt, rb - xy_centers[None]), dim=2).view(bs, n_boxes, n_anchors, -1)
     25     # return (bbox_deltas.min(3)[0] > eps).to(gt_bboxes.dtype)
     26     return bbox_deltas.amin(3).gt_(eps)

OutOfMemoryError: CUDA out of memory. Tried to allocate 4.98 GiB (GPU 0; 14.75 GiB total capacity; 12.11 GiB already allocated; 1.03 GiB free; 12.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

Just on colab

### Additional

When launched in the application, it advises you to take an automatic batch. And then it turns out that there can be more than a hundred photos in this automatic batch. And this error comes out

**Comment by glenn-jocher** [comment]
@SenchaBrest thanks for the feedback! This feature can sometimes fail, especially for smaller graphics cards or if your system is utilized by other processes at the time of training. If this happens you may need to manually specify a batch size before training starts.
