### ISSUE TITLE
Models not in iPhone app

### ISSUE THREAD

**Issue by wadeiam** [ultralytics/hub#298]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Export model
Login to app on iPhone
Sometimes no models at all and no projects or datasets. Sometimes just the default models. Sometimes my models.

### Environment

iPhone 12 latest iOS

### Minimal Reproducible Example

Export model
Login to app on iPhone
Sometimes no models at all and no projects or datasets. Sometimes just the default models. Sometimes my models.

### Additional

Na

**Comment by sergiossm** [comment]
@wadeiam thank you for reporting. I submitted a new version that fixes that issue. It should be live by tomorrow.

**Comment by wadeiam** [comment]
That was fast.  Looks good so far.

Thanks, Sergio.

**Comment by UltralyticsAssistant** [comment]
@wadeiam i'm glad to hear the update is working well for you! If you encounter any more issues or have further feedback, don't hesitate to reach out. Thanks for being a part of the YOLO community, and a big shoutout to the entire Ultralytics team for their continuous efforts! 😊🚀
