### ISSUE TITLE
Slow Inference on XIAOMI 11T Pro

### ISSUE THREAD

**Issue by Marcof64** [ultralytics/hub#30]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Hello, we purchased a XIAOMI 11T pro in order to replicate the tests that you have perfomrmed and for which you sent a video https://user-images.githubusercontent.com/26566365/165805393-5e632cb1-7bbb-4b7e-8489-cfcef6341a1e.mp4 

However on our XIAOMI 11T pro we get slower inferences and no indication on inference time:
https://drive.google.com/file/d/1-4GuUWYiGMX5ztwgE6G-0QMEz-xn7ecL/view?usp=sharing

 what could it be due to?

The phone is the same and the app is from the play store.

Note that on a Pixel 3i and another Pixel 4x we do get to see the inference time

Thaks

### Environment

XIAOMI 11T pro

### Minimal Reproducible Example

See video

### Additional

None

**Comment by sergiossm** [comment]
Hi @Marcof64, please contact me at sergio.sanchez@ultralytics.com.
