### ISSUE TITLE
How can I change batch size during the training?

### ISSUE THREAD

**Issue by SenchaBrest** [ultralytics/hub#300]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

If I stop training the model, can I somehow change the batch size and continue training?

**Comment by glenn-jocher** [comment]
@SenchaBrest no, this is not recommended. Resuming training relies on the same exact arguments as what you used to start training, otherwise uncertain outcomes may occur.
