### ISSUE TITLE
images not found(train)

### ISSUE THREAD

**Issue by Artachanidisjohn** [ultralytics/hub#304]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

When i m going to upload dataset i have this error. images not found(train)

**Comment by glenn-jocher** [comment]
@Artachanidisjohn we just developed an offline dataset verification tool that you can use before uploading. Please try the following code:

```python
from ultralytics.hub import check_dataset

check_dataset('path/to/coco8.zip', task='detect')  # detect dataset
check_dataset('path/to/coco8-seg.zip', task='segment')  # segment dataset
check_dataset('path/to/coco8-pose.zip', task='pose')  # pose dataset
```
