### ISSUE TITLE
RuntimeError: Dataset 'xView.yaml' error

### ISSUE THREAD

**Issue by jeffreyianwilson** [ultralytics/hub#305]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Google Collab and Local both produce the same error when trying to train xView dataset

Ultralytics HUB: Authenticated ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/TAj4BtBzlFk7hVkaODoq 🚀
Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to yolov8n.pt...
100%|██████████| 6.23M/6.23M [00:00<00:00, 17.7MB/s]
Ultralytics YOLOv8.0.118 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=xView.yaml, epochs=100, patience=100, batch=-1, imgsz=640, save=True, save_period=-1, cache=ram, device=, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=0, resume=False, amp=True, fraction=1.0, profile=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, vid_stride=1, line_width=None, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, tracker=botsort.yaml, save_dir=runs/detect/train2

Dataset 'xView.yaml' images not found ⚠️, missing paths ['/content/datasets/xView/images/autosplit_val.txt']
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    122             elif self.args.data.endswith('.yaml') or self.args.task in ('detect', 'segment'):
--> 123                 self.data = check_det_dataset(self.args.data)
    124                 if 'yaml_file' in self.data:

3 frames
<string> in <module>

<string> in convert_labels(fname)

FileNotFoundError: [Errno 2] No such file or directory: '/content/datasets/xView/xView_train.geojson'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/yolo/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    125                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    126         except Exception as e:
--> 127             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    128 
    129         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'xView.yaml' error ❌ [Errno 2] No such file or directory: '/content/datasets/xView/xView_train.geojson'

### Environment

Alienware M18 i9 64gb ram, RTX4090 GPU Win11 Pro

### Minimal Reproducible Example

1. Log Into Hub
2. Select Datasets
3. Select xView Dataset
4. Select Train (neither yolov8n or yolov8x work)
5. Run in Collab and local agent

**Comment by jeffreyianwilson** [comment]
Forgot to put dataset in correct path..  Closing Issue

**Comment by glenn-jocher** [comment]
@jeffreyianwilson thank you for bringing this issue to our attention. It appears that the dataset for the xView training was not placed in the correct path. To resolve this issue, please make sure to move the dataset to the appropriate location and retry the training process. If you still encounter any difficulties, please feel free to reopen the issue and provide any additional details or error messages. We are here to assist you.
