### ISSUE TITLE
Keep force close when use YOLOV8x custom dataset in untralytics hub app

### ISSUE THREAD

**Issue by Azer2401** [ultralytics/hub#307]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

when I want to use my model that has been exported on ultralytics hub android or iOS, the application suddenly force closes. Do you have any solution about this problem?

**Comment by Azer2401** [comment]
> @Azer2401 Thank you for reporting, we're aware of the issue and we're working to solve it. YOLOv8x a very large model for the mobile app, in the meantime I'd suggest training a YOLOv8n model if you intend to use the model in a mobile device

oh ok thank you for your suggestion, I will try again with YOLOv8n. how about yolov8s or yolov8m, can these two model run on mobile?

**Comment by sergiossm** [comment]
@Azer2401 on iOS they will, we're working on larger model's performance on Android devices.
