### ISSUE TITLE
false prediction

### ISSUE THREAD

**Issue by Artachanidisjohn** [ultralytics/hub#309]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello Sir, I will be happy if you help me. i use the api for road damage detection.do you know why in many cases it shows me the damage not on the road but on the sky or on the rocks next to the road.??do you know any way I can solve it? this happens with whatever api i use.

**Comment by kalenmike** [comment]
@Artachanidisjohn Thanks for raising this question. Can you provide us some more information?

- What API's are you using?
- Are you using HUB to render the boxes or are you rendering the boxes yourself?
- Can you give us some example images?

**Comment by Artachanidisjohn** [comment]
thank you for your response sir! i have used different API's and their datasets like this https://universe.roboflow.com/objectdetection-3epsj/works-2msry/model/1 or this https://universe.roboflow.com/ee5900/pothole-detection-for-diverse-terrain/model/1 . this is an example 
![annotated_IMJ_SEQ__seq-81026-2022-11-16_102909003-10_01073_blur](https://github.com/ultralytics/hub/assets/82318135/d0a03324-821a-44e1-ad48-226b9e25dfbe)

**Comment by Artachanidisjohn** [comment]
Now i m trying to use your API..can i display the image with the annotation? And something else plz. At ultralytics at the preview it displays many times the damage on the rocks or at the sky and not on the road!  Should i find a different dataset for training? Cause i tried different datasets and i have again and again this issue. Thanks in advance

**Comment by kalenmike** [comment]
@Artachanidisjohn Without access to your dataset or model it is difficult to tell you what is going wrong. My initial guess would be that your dataset is of low quality, but it is also possible that your models are being trained for too few or too many epochs.

I would suggest you look through your dataset with a visualization tool like the one we have in HUB and confirm that your labels are accurate.
