### ISSUE TITLE
Dataset keeps unzipping every run, even though nothing changes

### ISSUE THREAD

**Issue by AmirAvonic** [ultralytics/hub#310]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I am testing out a couple of runs, and I'm doing so using the same project, model and dataset. I'm just making sure all memory is allocated properly and the environment is set. The first time, it downloaded the dataset from the Hub and started unzipping and all was fine. However, during each consecutive run, it keeps unzipping the downloaded file, even though I can see that after the first time, the files were all there unzipped. Is there a way to prevent the hub from unzipping it and simply pointing it to the dataset?

**Comment by kalenmike** [comment]
@AmirAvonic Thank you for bringing this up. We appreciate your feedback. Currently, our implementation for datasets in zip format does not include a check for whether the unzip process has already occurred. We understand the importance of this feature and its potential benefits. Although it is not currently scheduled, we will definitely consider adding it to our list of potential changes. Your input is valuable to us as we continue to enhance the ultralytics package.

**Comment by kalenmike** [comment]
We have a fix pending merge: 
https://github.com/ultralytics/ultralytics/pull/3413

**Comment by glenn-jocher** [comment]
@AmirAvonic great news 😃! Your original issue may now be resolved ✅ in PR https://github.com/ultralytics/ultralytics/pull/3423 and is deployed live now in `ultralytics` 8.0.124.

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics"><img src="https://assets.paperspace.io/img/gradient-badge.svg" alt="Run on Gradient"></a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"></a> <a href="https://www.kaggle.com/ultralytics/yolov8"><img src="https://kaggle.com/static/images/open-in-kaggle.svg" alt="Open In Kaggle"></a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics"><img src="https://img.shields.io/docker/pulls/ultralytics/ultralytics?logo=docker" alt="Docker Pulls"></a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Comment by AmirAvonic** [comment]
Amazing! Thank you for the quick feedback and implementation!

**Comment by glenn-jocher** [comment]
@AmirAvonic you're welcome! We're glad to hear that you're happy with the quick response and implementation. We strive to provide prompt support and continuously improve the Ultralytics HUB. If you have any further questions or need assistance, please feel free to ask. Happy training with the Ultralytics HUB!
