### ISSUE TITLE
Access to bounding box predictions on app

### ISSUE THREAD

**Issue by hchlhwang** [ultralytics/hub#311]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is there a way to access the bounding box predictions while using the mobile (IOS/Android) app? Thank you.

**Comment by kalenmike** [comment]
@hchlhwang Thanks for asking the question. The mobile app does not provide the predictions it only renders them. You can use the inference API provided on the preview tab of your model if you want access to the predictions.
