### ISSUE TITLE
How to export the data 

### ISSUE THREAD

**Issue by Artachanidisjohn** [ultralytics/hub#313]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello sir, while using the camera at ultralytics,can i save the detected image or to save the detected image with coordinates? Or to record while using the ultralytics app?? Thanks in advance 🙏

**Comment by kalenmike** [comment]
@Artachanidisjohn Thank you for your inquiry! At the moment, our app doesn't support image or video sharing capabilities. However, we appreciate your interest, and we are actively exploring options to incorporate this functionality in the future updates. We understand the value of such features and their impact on user experience.

In the meantime, to achieve what you're looking for, you can utilize the built-in screenshot or screen recording features available on your device. These options will allow you to capture and share visual content from within the app.

We appreciate your understanding and patience as we work towards enhancing our app's features to better meet your needs. Stay tuned for updates and exciting additions in the future!

If you have any further questions or suggestions, please feel free to reach out. We're here to assist you.

Thank you again for your interest and support!
