### ISSUE TITLE
Model search

### ISSUE THREAD

**Issue by dolmajean** [ultralytics/hub#315]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How can I discover or build a model for automobiles?

**Comment by glenn-jocher** [comment]
Hi @dolmajean, 

To discover or build a model for automobiles using Ultralytics HUB, you have a few options. 

1. **Use a pre-trained model**: Ultralytics HUB provides pre-trained models that are capable of detecting a wide range of objects, including automobiles. You can explore the pre-trained models in the [Models section](https://hub.ultralytics.com/models) of the HUB website. These models are ready to use out of the box and only require the addition of your specific dataset.

2. **Train a custom model**: If you have a dataset of images that includes automobile annotations, you can train a custom model using YOLOv5 or YOLOv8. The HUB provides documentation on how to [prepare and upload datasets](https://docs.ultralytics.com/hub/datasets) and [train and export models](https://docs.ultralytics.com/hub/models) that you can follow to train a model specifically for automobiles.

By following these approaches, you should be able to discover or build a model for automobiles. If you have any further questions or need more guidance, please don't hesitate to reach out.

Best regards,
Glenn Jocher
