### ISSUE TITLE
Can't Login in Android App Ultralytics

### ISSUE THREAD

**Issue by rouye123** [ultralytics/hub#32]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I can't log in my acc in gmail and also github acc. My log in details are correct, I'm sure.  Can you help me please?

![280092802_1070239823604009_693940214641229170_n](https://user-images.githubusercontent.com/105448498/168195395-ac2d20c2-6b01-4280-9068-c951530f3e9f.png)

**Comment by sergiossm** [comment]
Hi @rouye123, thanks for your feedback!

Please, answer these questions so we can try and find the issue:
1. What Android device are you using? 
2. What's the Android version on your device?
3. What version of the Ultralytics app is installed on your device? You can find it at the end of the settings screen

**Comment by sergiossm** [comment]
@rouye123 we think we may have solved the issue. The fix is included in version 0.1.2, which has been submitted to Google Play and is now in review. Download the app again tomorrow and get back to us if the issue persists.

Follow these steps to make sure you get a clean install:
1. Clear app cache and storage from Android settings
2. Uninstall the app
3. Download and install from [Google Play](https://play.google.com/store/apps/details?id=com.ultralytics.ultralytics_app)

**Comment by rouye123** [comment]
> 

Hello, 
1. I am using 360 N6 Pro 
2. 8.1.0
3. Latest 0.1.2

I am sorry but I still can't log in using the created account and using github account

These are the screenshots

![Screenshot_2022-05-13-09-50-16](https://user-images.githubusercontent.com/105448498/168317598-aaedc904-1fdf-4c60-a2b2-d3a1e3d70165.png)
![Screenshot_2022-05-13-23-29-37](https://user-images.githubusercontent.com/105448498/168317623-63543a77-97aa-468c-befb-b786c4d5c134.png)
![Screenshot_2022-05-13-23-30-09](https://user-images.githubusercontent.com/105448498/168317639-6ed79db6-970b-40ef-a0a5-d44dc4268704.png)

**Comment by sergiossm** [comment]
Sorry about that @rouye123, Google Sign In seemed to be working on our end. Can you provide the accounts you're attempting the login with?

**Comment by rouye123** [comment]
> Sorry about that @rouye123, Google Sign In seemed to be working on our end. Can you provide the accounts you're attempting the login with?

andreibsllt@gmail.com

**Comment by rouye123** [comment]
Hello, I asked mg friend to download ultralytics via playstore then create account, after creating account, she successfully logged in then when she sign out the account amd log in again, she can't log in again. The same error above shows. Thanks.

**Comment by sergiossm** [comment]
Hi @rouye123, can you try updating the app again? Please make sure the version you download is 0.1.3. Thanks for your patience!

**Comment by rouye123** [comment]
> Hi @rouye123, can you try updating the app again? Please make sure the version you download is 0.1.3. Thanks for your patience!

Thank you! It is working now. Thank you for resolving my concern.

**Comment by glenn-jocher** [comment]
@rouye123 great! Let us know if you have any other issues or if there's any features you'd like to see added :)
