### ISSUE TITLE
FileNotFoundError      

### ISSUE THREAD

**Issue by ckseok** [ultralytics/hub#320]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects, Training

### Bug

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-3-7355a4e5df11> in <cell line: 4>()
      2
      3 model = YOLO('https://hub.ultralytics.com/models/4vhiktyy5byYefmQ3Qm7')
----> 4 model.train()

5 frames
/usr/local/lib/python3.10/dist-packages/torch/serialization.py in __init__(self, name, mode)
    250 class _open_file(_opener):
    251     def __init__(self, name, mode):
--> 252         super().__init__(open(name, mode))
    253
    254     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: 'runs/detect/train/weights/[best.pt](http://best.pt/)'

### Environment

corap

**Comment by glenn-jocher** [comment]
Hi @ckseok, thank you for reaching out regarding the FileNotFoundError you encountered when training a model on the Ultralytics HUB. 

The error message suggests that the file 'best.pt' cannot be found in the 'runs/detect/train/weights/' directory. This file is typically generated during the training process and contains the best weights of the model after each epoch. 

To resolve this issue, please ensure that you have properly configured the training script to save the 'best.pt' file in the expected directory. Additionally, make sure that you have the correct file path specified when attempting to load the model for training.

If you need further assistance, please provide any additional information or code snippets that can help us understand the context and reproduce the issue. We will be happy to help you troubleshoot and find a solution.
