### ISSUE TITLE
Uploading a model is very slow. 

### ISSUE THREAD

**Issue by huhuang03** [ultralytics/hub#322]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Uplaod a model is very slow, maybe a better upload experience.

Maybe:
- can upload a folder(not a zip), and show the uploading process(like aliyun oss file upload).
- can provide a desktop client to sync the local file.

**Comment by huhuang03** [comment]
Looks like I misunderstanding the upload model. So I will close this issue for now.

**Comment by glenn-jocher** [comment]
Hi @huhuang03, 

No worries! It happens sometimes. If you have any more questions or need assistance in the future, feel free to open a new issue. We're here to help. 

Thank you for reaching out and have a great day!
