### ISSUE TITLE
TensorFlow Saved Model - Signature Key

### ISSUE THREAD

**Issue by kwadhwasony** [ultralytics/hub#324]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

What is the easiest way to use TensorFlow Saved Models that is exported? 
I can export, it but some actions require 'signature' associated with the model, which I can not seem to find any.

If needed, I can provide a simple code that converts Saved Model to TFLite. Also there are no concrete functions associated as well.

**Comment by glenn-jocher** [comment]
@kwadhwasony hi there! Thank you for reaching out and sorry for the delayed response.

To use TensorFlow Saved Models exported from HUB, you'll need to specify the signature key associated with the model. The signature key represents an entry point to the model and specifies the input and output tensors.

You can find the signature key by inspecting the saved model using the TensorFlow SavedModel CLI tool (`saved_model_cli`). This tool allows you to view the available signatures and their associated input and output tensors.

For example, you can use the following command to view the signatures of a saved model:

```
saved_model_cli show --dir /path/to/saved_model --all
```

Once you have identified the signature key, you can use it in your code to load and use the saved model. The specific functions you'll need to use will depend on your use case, but with the signature key, you can access the input and output tensors of the model and perform the desired actions.

If you can provide the code you mentioned that converts the Saved Model to TFLite, we can help you further with integrating the signature key into your code.

Let me know if you have any further questions or need additional assistance!
