### ISSUE TITLE
I need use mocel for usb camera on android phone via OTG

### ISSUE THREAD

**Issue by HoangBee102** [ultralytics/hub#325]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I need use mocel for usb camera on android phone via OTG

**Comment by glenn-jocher** [comment]
Hi @HoangBee102,

Thank you for reaching out. 

To use an external USB camera on an Android phone via OTG with Ultralytics HUB, you can follow these general steps:

1. Connect the USB camera to your Android phone using an appropriate OTG cable or adapter.

2. Open the Ultralytics HUB App on your Android phone.

3. In the Ultralytics HUB App, go to the camera settings or preferences.

4. Look for an option to select the input source for the camera. The USB camera should be listed as an available input source.

5. Select the USB camera as the input source.

6. You should now be able to use the USB camera as the primary camera in the Ultralytics HUB App for tasks such as object detection.

Please note that the availability of this feature depends on the capabilities of your Android phone and the Ultralytics HUB App. You may need to consult the app's documentation or reach out to the app's support team for more specific guidance.

I hope this helps! Let me know if you have any further questions.
