### ISSUE TITLE
Tools to label data

### ISSUE THREAD

**Issue by hupo376787** [ultralytics/hub#327]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi, I'm a newbie in AI. I found that this platform can train models using existing datasets, that's a great job.
But where does the dataset text come from? I have a lot of images, so what tool do I need to label?

Any advice is welcome.

![image](https://github.com/ultralytics/hub/assets/14960168/27e776e0-7eb6-4cac-9c35-9dfa5e278db1)

**Comment by hupo376787** [comment]
Found it.
[YoloLabel](https://github.com/developer0hye/Yolo_Label)

**Comment by glenn-jocher** [comment]
@hupo376787 i'm glad you found a tool for your needs!

Your mentioned tool, YoloLabel, is indeed a widely used tool for data labeling in YOLO format. It allows users to draw bounding boxes around objects of interest in images and generates corresponding annotation files. This makes it a helpful utility when creating labeled datasets for training YOLO models.

Before you go ahead, I would like to suggest you check the quality of your labels regularly during the labeling process, especially if you are new to this. Accurate and consistent labels are very important for training a reliable model. Also, be sure to split your labeled images into training, validation, and testing datasets, so you can effectively train and evaluate your model.

Happy labeling and best of luck with your AI journey! If you have any more questions down the line, feel free to reach out.

**Comment by hupo376787** [comment]
> 

Hi, Glenn. Thanks for your advice. I used YoloLabel for a while and found that it can only draw bounding boxes. This makes it an efficient tool. And I also heard that using a brush to paint is more accurate to train models. But it takes a little more time for a label engineer. 

So do you have any brush label tools recommended?

Thanks.

**Comment by hupo376787** [comment]
> 

Hi, Glenn.

I found that different label tools generate different label data formats.
Like Yolo Label, its JSON data is 
```
0 0.675585 0.690574 0.434783 0.520492
1 0.408584 0.262295 0.299889 0.418033
```
But for Labelme, the data is like 
```
{
  "version": "4.5.9",
  "flags": {},
  "shapes": [
    {
      "label": "1",
      "points": [
        [
          244.2686567164179,
          232.25373134328356
        ],
        [
          579.3432835820895,
          471.8059701492537
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    },
    {
      "label": "2",
      "points": [
        [
          144.2686567164179,
          18.07462686567164
        ],
        [
          386.0597014925373,
          243.44776119402985
        ]
      ],
      "group_id": null,
      "shape_type": "rectangle",
      "flags": {}
    }
  ],
  "imagePath": "000000000009.jpg",
  "imageData": "",
  "imageHeight": 480,
  "imageWidth": 640
}
```

So If I use the Ultralytics hub to train data, it requires special data formats. So I can only use Yolo Label.
![image](https://github.com/ultralytics/hub/assets/14960168/0ab5be4b-769f-40a8-b38b-82bf0a128e64)


Am I correct?

**Comment by glenn-jocher** [comment]
@hupo376787 hello!

That's right! The Ultralytics hub primarily supports the YOLO format for annotated training data. As a result, label tools such as YoloLabel that produce this desired output are suitable. However, this does not make other tools unusable. 

Tools like Labelme generate output in their own distinct format, as you've pointed out. However, the important point is that the raw information (object class, object coordinates etc.) remains the same, it's just organised differently. 

If you decide to use a tool like Labelme, you would have to convert the Labelme annotations to the YOLO format before you can feed it into the Ultralytics hub for training. This switch from one annotation format to another could be accomplished programmatically via a script. 

I hope this answers your question. If you have more, feel free to reach out!

**Comment by hupo376787** [comment]
> 

Understood, thanks for your reply.

**Comment by glenn-jocher** [comment]
@hupo376787, you're welcome! I'm glad to hear that you found the information helpful. If you have any other questions in the future related to data labeling, model training, or anything else about Ultralytics HUB, don't hesitate to ask. Good luck with your work!

**Comment by hupo376787** [comment]
Understood, thanks @glenn-jocher

**Comment by glenn-jocher** [comment]
@hupo376787, you're welcome! I'm glad I could help. If you have any other questions or concerns in the future, don't hesitate to reach out. Best of luck with your AI projects!
