### ISSUE TITLE
exporting to tensorflow lite

### ISSUE THREAD

**Issue by samus114** [ultralytics/hub#329]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

when exporting to tflite, it gets stuck on exporting. It stays this way for multiple hours.

### Environment

 - computer: Mac M1 2020
 - OS: Ventura 13.0.1
 - Browser: Chrome Version 114.0.5735.198 (Official Build) (arm64)

### Minimal Reproducible Example

1. login
2. go to models
3. try and export as a tflite model.

**Comment by glenn-jocher** [comment]
@samus114 thanks for the bug report! 

We recently updated the `ultralytics` package but have not yet updated the server with the same updates, causing this issue. We should have this updated soon and then you'll be able to export. In the meantime thank you for your patience.
