### ISSUE TITLE
Upload dataset failed.

### ISSUE THREAD

**Issue by linmeimei0512** [ultralytics/hub#332]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I upload coco8 dataset that download by example_datasets, but show 'Processing Error'.  
How can I solve it?  
![image](https://github.com/ultralytics/hub/assets/14798636/af3d8f2b-f5ce-4cca-a671-e275a7c8bd0f)

THX!!

**Comment by kalenmike** [comment]
@linmeimei0512 Thanks for raising this. I have confirmed this issue on my end. We will look into getting this resolved as soon as possible.

**Comment by linmeimei0512** [comment]
> @linmeimei0512 Thanks for raising this. I have confirmed this issue on my end. We will look into getting this resolved as soon as possible.

OK, thanks for the trouble.

**Comment by kalenmike** [comment]
@linmeimei0512 Thanks for your patience. This has now been fixed. You should now be able to upload this dataset.
