### ISSUE TITLE
Can you add a ip camera, like input URL textbar, so it could work on other cameras

### ISSUE THREAD

**Issue by Muhammadbugaje** [ultralytics/hub#336]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

url textbar, to use other cameras 

### Use case

To provide ultralytrics capabilities on ip cameras too for surveillance

**Comment by glenn-jocher** [comment]
@Muhammadbugaje hello,

Thank you for sharing your feature request to add an IP camera input feature. This sounds like an interesting idea and could indeed expand the capabilities of the Ultralytics HUB. I can certainly see how this would be beneficial in surveillance cases.

Please note that currently, the primary focus of the Ultralytics HUB is training and deploying AI models. That being said, your request for IP camera integration opens the possibility for a real-time application of these models, which is a great suggestion.

While we cannot promise an immediate implementation, rest assured that your suggestion will be considered by our development team as we aim to make the HUB as versatile as possible. We greatly appreciate insights from users like yourself, as they can contribute significantly to the evolution and improvement of Ultralytics HUB.

Thank you for your input and stay tuned for updates.
