### ISSUE TITLE
Export Failed for All Model Types With YOLOv5

### ISSUE THREAD

**Issue by bherbruck** [ultralytics/hub#337]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

Exports are failing for all model types. this is specifically on all my models trained on the `YOLOv5` _non-u_ version (`YOLOv5s`, `YOLOv5m`, etc). I'm not sure if this is for all `YOLOv5` versions because I don't have any trained on `YOLOv5su`. It is working on `YOLOv8`. 

![ezgif-1-31ec881086](https://github.com/ultralytics/hub/assets/5258126/914c4bbb-fd49-422c-87c4-4aa1b1b0e3bf)

**Comment by kalenmike** [comment]
@bherbruck Thanks for raising this bug, it has been confirmed. We are working to get this resolved.

**Comment by kalenmike** [comment]
@bherbruck Thank you for your patience, we have just deployed a fix. Please try again and let me know if you have any more trouble.

**Comment by bherbruck** [comment]
It is now working! Thanks! Y'all are on top of things!

**Comment by glenn-jocher** [comment]
@bherbruck thank you for your feedback! I'm glad to hear that everything is working well now. It's our top priority to ensure that the hub runs smoothly for all users. Please don't hesitate to reach out if there are any other issues or questions in the future. And remember, the YOLO community and the Ultralytics team are always here to help.
