### ISSUE TITLE
MPS GPU Support

### ISSUE THREAD

**Issue by awilbourn** [ultralytics/hub#338]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I would be great if hub would support the mac GPU using the MPS. Seems that only Nvidia GPU is supported if you want to run on a local machine.

### Use case

Allow the setup to detect the MPS GPU and use it.

**Comment by awilbourn** [comment]
Supporting similar instructions from https://docs.ultralytics.com/modes/train/#apple-m1-and-m2-mps-training

**Comment by glenn-jocher** [comment]
@awilbourn thanks for the feedback! MPS training is experimentally supported with the `ultralytics` package, so this may just be a question of adding this to the HUB training settings.

It is not used by default on macOS though, it requires an opt-in via `device=mps`, and it may not work correctly for all models.

We don't currently have MPS CI in place since GitHub's macOS runners use Intel hardware.

**Comment by awilbourn** [comment]
Yes, I understand it needs to be setup, but it would just make the training
go faster. I find that even for not using HUB the code as is has issues for
MPS. I think the versions of the libraries may be something needed to
specify. I will look to raise that to the core Ultralytics pip library as
that is not working for me on a newly installed virtual environment and is
for m2 processor.

**Comment by glenn-jocher** [comment]
Thank you for your insights, @awilbourn. I understand your perspective on improving training speed via MPS. The Ultralytics team appreciates your input and your exploration of this issue.

If you're experiencing problems implementing MPS, it would be beneficial to raise this with the core Ultralytics pip library. Please ensure to provide all details including your environment setup and the exact issues you're encountering. This will help the Ultralytics team to further understand the problem and hence provide a more effective solution.

Keep in mind that MPS is still an experimental feature and may not be fully compatible with all setups. However, your feedback is valuable in improving it for the wider YOLO community. We appreciate your patience and involvement in this.

**Comment by kalenmike** [comment]
@awilbourn We are closing this until we have a stable option in [ultralytics](https://github.com/ultralytics/ultralytics).
