### ISSUE TITLE
Datasets Processing Error

### ISSUE THREAD

**Issue by ShailinXia** [ultralytics/hub#34]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

@Ultralytics HUB Recently,I have uploaded my custom dataset completely.But it can't be unzipped and is shown failed,processing error.I wanna to konw what leads to fail.Meanwhile,I tried to prepare my custom datasets correctly.But the result is still failed.

![Snipaste_2022-05-18_01-49-45](https://user-images.githubusercontent.com/67199145/168877959-f6f2cc71-25e4-4d8f-a066-c77f1c9afd83.jpg)

### Environment

Environment
Ultralytics HUB Version
v0.1.14-beta.1
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Operating System
Win32
Browser Window Size
1536 x 746
Server Timestamp
1652809519

**Comment by glenn-jocher** [comment]
@ShailinXia the easiest way to create your own dataset is to start from the example shown in https://github.com/ultralytics/hub/tree/master/coco6, which is zipped as https://github.com/ultralytics/hub/blob/master/coco6.zip.

coco6.zip uploads correctly, so start from there and modify as required to create your custom dataset, which should then also load correctly.

**Comment by ShailinXia** [comment]
@glenn-jocher Thank you to response my issue.I have tried to imitate the construction of coco6 to restructure my custom datasets.But the consequence isn't my anticipate. Can you help me to modify my datasets in the Ultralytics HUB? I'll really appreciate it.

**Comment by kalenmike** [comment]
@ShailinXia YAML files are very strict. You can use [this site](https://yamlchecker.com/) to validate the format of your YAML file.
