### ISSUE TITLE
Custom data-set format

### ISSUE THREAD

**Issue by aminrezaabbasi** [ultralytics/hub#341]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have a question about the needed format of the dataset if we want to train a model by using custom dataset.

I have a dataset of the wheat head segmentation which I have used instance segmentation for the annotation. In my dataset, there are 100 masks with .nrrd extension, and I have 100 images of the wheat heads with .jpg extension. Is it possible for you to tell me I should convert the masks format to which extension/thing? and I noticed that somehow we need to have the coordinate of each segmentation, how can I get this coordinates?

**Comment by aminrezaabbasi** [comment]
Yes, I want to upload it using that. Is there any other way that I can train my custom dataset and train it by using YOLOv8?

**Comment by glenn-jocher** [comment]
@aminrezaabbasi, at the current moment, YOLO models are designed for object detection tasks, and do not directly support semantic or instance segmentation. This means that they don't take masks or pixel-level annotations as input, rather they use bounding boxes. Your dataset should be in the YOLO format, which basically consists of images and corresponding label files, one for each image. The labels are represented as text files containing one row per object present in the image. Each row includes the object class (as an integer), and the normalized bounding box coordinates (x, y, width, height). 

For instance segmentation tasks, you could consider trying other models that are specifically designed for this task, like Mask R-CNN, U-Net, etc. However, if you're interested in bounding box prediction (object detection), you could convert your instance masks into bounding boxes and then train a YOLO model. Keep in mind that you would lose the per-pixel segmentation information in this process.

Finally, to convert your instance masks to bounding box coordinates, there are several ways - a common approach being to find the smallest rectangle (bounding box) that encloses all the ‘1’ pixels (the mask) in your binary instance mask. 

I hope this clarifies things a bit!

**Comment by kalenmike** [comment]
@aminrezaabbasi We have just released segmentation in HUB. You will now be able to upload your segmentation models in YOLO format.
