### ISSUE TITLE
Misplaced boxes in Hub app on Pixel 7 Pro

### ISSUE THREAD

**Issue by alexbrickwedde** [ultralytics/hub#342]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

On my Pixel 7 Pro the boxes are not on the correct position:
![image](https://github.com/ultralytics/hub/assets/396286/7553a3e2-d211-417b-bad5-aa30f6218c1a)

### Environment

- Pixel 7 Pro
- Android 13 (latest Google image)

### Minimal Reproducible Example

I just started detection with one of the integrated models.

**Comment by glenn-jocher** [comment]
@alexbrickwedde thank you for bringing this to our attention and providing a detailed description of the issue, including your device and Android version. It certainly helps us pinpoint the issue more effectively.

From your description, it appears that the bounding boxes are not being placed correctly during model inference on your Pixel 7 Pro. This could be related to how the bounding box coordinates are scaled or transformed relative to the image size or screen resolution. 

Your device being a latest model, it's also possible that we may need to make some adaptations to handle a new screen size, aspect ratio, or updated Android functionalities that could be affecting the inference rendering. 

The information you've provided will be invaluable in troubleshooting this issue. Our development team will look into this issue promptly.

We appreciate your patience and support. Please do not hesitate to report any other issues or concerns you may have.

**Comment by alexbrickwedde** [comment]
@glenn-jocher DisplayMetrics is {density=3.5, width=1440, height=2892, scaledDensity=3.5, xdpi=515.154, ydpi=511.277}

**Comment by kalenmike** [comment]
@alexbrickwedde Does the model work correctly when running inference with the Web Interface?

**Comment by alexbrickwedde** [comment]
> @alexbrickwedde Does the model work correctly when running inference with the Web Interface?

It's the Ultralytics yolov8n pretrained models i chose - i didn't try, but I hope so ;)
In fact in the Hub Model Preview it doesn't work right now: ![image](https://github.com/ultralytics/hub/assets/396286/4c083fc0-aca7-4116-b73e-84f0d1936da1)

I just installed the app on my Samsung Tab S8+ also. Didn't login, the app starts detection automatically and it looks weird:
https://youtube.com/shorts/a-iqHBGbzAE

In fact i'm working on a -seg variant. The yolov8n-seg pretrained model (yolov8n-seg.pt), directly converted to tflite, used in my own app, detects objects correctly and shows correct boxes on both devices: (ignore the labels, it's using mine there)
https://youtube.com/shorts/zi7mJjqqphU (But as you can see, I'm struggling with the map calculation...)

**Comment by alexbrickwedde** [comment]
Just started the app on my wife's old OnePlus7T, works perfectly.

**Comment by glenn-jocher** [comment]
@alexbrickwedde, thank you for testing it out on different devices. It's interesting that it works correctly on the OnePlus 7T but not on the other devices. We will need to dig deeper into the potential differences between the devices, such as screen resolution, Android version, or subtle differences in how the devices handle graphics and UI rendering. This issue could also be related to Android version-specific nuances, as software updates often come with changes that might affect app behaviour. Our team will continue investigating, and we appreciate your patience and help in diagnosing this issue.

**Comment by UltralyticsAssistant** [comment]
@kevinrigot hi, thank you for your input. This indeed helps us with the investigation. The information about the app working fine prior to the update is particularly valuable. We suspect this issue might be related to recent changes in the app or OS level updates. Our development team is actively looking into this and actively exploring potential solutions for this issue. We appreciate your patience and understanding as we work to resolve this. Thank you for your support!

**Comment by kalenmike** [comment]
We are releasing a rebuild of the HUB App in the next few days. This is flagged for testing.

**Comment by kevinrigot** [comment]
Hi @kalenmike !
It's working better for yolov8n and yolov8s. But it's still having this issue on yolov8m. I haven't tried the bigger models.

Regards,
Kevin

**Comment by UltralyticsAssistant** [comment]
Hi @kevinrigot,

Thank you for testing the models and providing this valuable feedback! It's curious that the issue persists for yolov8m while it's better for yolov8n and yolov8s. It could potentially be related to how the different models handle object detection at different resolutions and sizes.

Our development team is still investigating this and also considering potential device-specific factors. We appreciate your patience and we'll keep you updated with any developments. We're dedicated to resolving this issue as efficiently as possible.

Best Regards,
Ultralytics Team
