### ISSUE TITLE
Connection broken issue while training using api

### ISSUE THREAD

**Issue by kuldeepaher01** [ultralytics/hub#343]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

When training a custom model using hub api, an error message is shown I don't know as to how that affects my training as model and its data is getting uploaded to hub. 
I am using a custom server I think that due to this error after sometime connection is lost because inspite of server being available 24*7 hub disconnects after 30-40 epochs. I am not sure if this issue is because of the connection error show below:
![image](https://github.com/ultralytics/hub/assets/76651819/562026b3-749c-4e33-acd8-cd939155ec85)

### Environment

-Linux server

### Minimal Reproducible Example

1. train model for 100-200 epochs
2. You can see this error after some 30-40 epochs

**Comment by kuldeepaher01** [comment]
> @kuldeepaher01 Thanks for raising this. It looks like your checkpoints are not being uploaded fully. Can you give me your model id so I can look into this further?

I don't know how to find model id. Is it the link of my model?

**Comment by kuldeepaher01** [comment]
> @kuldeepaher01, yes, the model ID is a unique identifier assigned to your model when you start training it. You can usually find it in the model's URL in the Ultralytics HUB. It's the alphanumeric string after '/run/'. For instance, if your model URL in the Ultralytics HUB is `https://hub.ultralytics.com/run/1234abcd`, then `1234abcd` is your model ID. Providing this would allow me to locate your specific training run and diagnose the disconnection issue more accurately.

https://hub.ultralytics.com/models/dgVKP5ncHhxfgoIsbM3N

**Comment by glenn-jocher** [comment]
@kuldeepaher01 thank you for providing the model ID. I'll now review the logs and details of your training session on our server in order to gain more insights into the network disconnection issue you're experiencing. In the meantime, you may want to ensure that your server's network connection is stable, as intermittent connectivity could potentially cause such issues. I'm going to work on this and will get back to you as soon as possible. Your patience is appreciated!

**Comment by kalenmike** [comment]
@kuldeepaher01 We managed to track this bug down to a printing error. Uploads where successful but we were leaving some bytes off of the response which were causing the client to assume a failure. This should now be resolved.
