### ISSUE TITLE
Request for hiding other features while detecting objects

### ISSUE THREAD

**Issue by labelllll** [ultralytics/hub#345]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

(I posted an issue few days ago but it seems there is an error that makes it kept unseen when I logged out. I don't know why, so I just made another id and copied the previous one here, just in case. Sorry if you have seen this one before.)

Hello, thank you for making the application. I am using it very well, but there is one little thing that I want to suggest; it would be really helpful if there is some kind of feature that I can hide menu/models/time/fps while detecting objects. They cover the detection result and take up quite a bit of space. Hope I can use the full screen, if it's possible.

Maybe letting the user remove the heart from default models(yolov8) and also delete other downloaded models would partially solve this issue, since the list of those models occupy a line on the screen even when I'm not using them. 

![257502474-e2e0336a-0e73-45fd-946f-c552b9a8496f](https://github.com/ultralytics/hub/assets/141245889/b05ca698-12ef-41ac-b106-933f662df2f4)

**Comment by kalenmike** [comment]
@labelllll Thanks for the feature request. I have added this to our feature list for investigation where it will be discussed and either approved or cancelled.

https://github.com/orgs/ultralytics/projects/10?pane=issue&itemId=34952185
