### ISSUE TITLE
The server encountered a temporary error

### ISSUE THREAD

**Issue by ukrenzz** [ultralytics/hub#347]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin, API Key

### Bug

First, I running hub.login() on Google Colab. API key was copied from hub, but get a error message **The server encountered a temporary error and could not complete your request.**. From this message, system need me to retry on 30 seconds, but nothing happen and get same error.

![image](https://github.com/ultralytics/hub/assets/27771217/269ed63d-84a6-4919-ac63-9ef1328a7c63)

### Environment

- Computer: MSI GF63 Thin
- OS: Windows 11
- Browser: Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)
- Google Colab Hardware: T4
- Google Colab GPU RAM: 15GB
- Google Colab System RAM: 12.7GB

### Minimal Reproducible Example

1. Login to Hub
2. Click Models
3. Select Model
4. Copy Colab code to Google Colab
5. Install  Ultralytics module
6. Import YOLO, checks, hub from ultralytics
7. Running `hub.login('API-KEY')`

### Additional

-

**Comment by kuldeepaher01** [comment]
> ### Search before asking
> * [x]  I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.
> 
> ### HUB Component
> Signin, API Key
> 
> ### Bug
> First, I running hub.login() on Google Colab. API key was copied from hub, but get a error message **The server encountered a temporary error and could not complete your request.**. From this message, system need me to retry on 30 seconds, but nothing happen and get same error.
> 
> ![image](https://user-images.githubusercontent.com/27771217/258069964-269ed63d-84a6-4919-ac63-9ef1328a7c63.png)
> 
> ### Environment
> * Computer: MSI GF63 Thin
> * OS: Windows 11
> * Browser: Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)
> * Google Colab Hardware: T4
> * Google Colab GPU RAM: 15GB
> * Google Colab System RAM: 12.7GB
> 
> ### Minimal Reproducible Example
> 1. Login to Hub
> 2. Click Models
> 3. Select Model
> 4. Copy Colab code to Google Colab
> 5. Install  Ultralytics module
> 6. Import YOLO, checks, hub from ultralytics
> 7. Running `hub.login('API-KEY')`
> 
> ### Additional

Facing same issue

**Comment by kuldeepaher01** [comment]
I am also facing same issue.

**Comment by Errozo** [comment]
I am also facing the same issue. Does anyone have a fix?

**Comment by glenn-jocher** [comment]
@kuldeepaher01 thank you for reaching out and sorry for the inconvenience you're experiencing. This seems like an issue with server connectivity and could likely be a temporary problem. Here are a few suggestions:

1. Retrying after a while: As the error message suggests, there might be a temporary issue with the server. Please try running the code again after a few minutes.

2. API Key: Please ensure that the API key you're using is valid and has the necessary permissions.

3. Internet Connection: Please make sure you are connected to a stable internet connection.

If the issue persists, please be patient as this could take some time to resolve. Our team is alert and working diligently to fix this. I'll keep you posted with updates. Thanks for your understanding and cooperation.

**Comment by kalenmike** [comment]
@ukrenzz @kuldeepaher01 @Errozo This should be resolved now, let us know if you are continuing to get errors.
