### ISSUE TITLE
Unable to reach server

### ISSUE THREAD

**Issue by Errozo** [ultralytics/hub#348]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

I cannot upload datasets without the system telling me "Failed Unable to Reach Server". Is the server down or what is the problem?

Thanks.

**Comment by kalenmike** [comment]
@Errozo Thanks for raising this bug. Our server has gone down, we are working on a quick resolution to this.

**Comment by Errozo** [comment]
@kalenmike Thanks for the quick response. Can you update me when the server is available again?

**Comment by kalenmike** [comment]
@Errozo Will do.

**Comment by kalenmike** [comment]
@Errozo We are back online now. You should be able to continue. Thank you for your patience.
