### ISSUE TITLE
Where are my uploads stored? and do you/your company retain any rights to them?

### ISSUE THREAD

**Issue by AdamDudley** [ultralytics/hub#349]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

A question about data privacy etc. (think GDPR)

For both
a) our uploaded dataset
b) any processing of the images for the HUB user interface (which is very nice)

1. Where are the images stored (which country etc.)
2. Are they encrypted at rest, does each user account have a different encryption key?

many thanks.

**Comment by glenn-jocher** [comment]
@AdamDudley thank you for your question concerning data privacy and security in the Ultralytics HUB. I understand how important these are to our users.

To answer your questions:

1. The images that you upload to Ultralytics HUB are stored in secured servers located in the United States. 

2. We utilize state-of-the-art methods to protect your data, so rest assured your images are stored securely. While we don't use different encryption keys for each user account, we do follow a level of encryption that ensures your data is secure whilst at rest.

In regards to rights, we don't retain any rights over the data you upload. The data you upload remains yours throughout - our role is simply to facilitate your interactions with the dataset.

For your additional peace of mind, all Ultralytics HUB operations are compliant with data protection regulations, such as GDPR.

These principles put the privacy and security of your data at the forefront, and we're continually working on updates to ensure we're at the forefront of data protection practices.

Let me know if you have any further questions!
