### ISSUE TITLE
Use exported .onnx model on QGIS "Deepness" plugin

### ISSUE THREAD

**Issue by fredrikbacke92** [ultralytics/hub#350]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

When running the plugin with exported model it generates a massive amount of 'channels' (polygon layers) causing QGIS to crash, due to running out of memory. I've tried a included .onnx model which only generate 1 channel which is the class 'car' and that works without problems. I've uploaded to models to netron.app, hopefully that helps.

**Exported ultralytics model .onnx** ([Full graph](https://i.ibb.co/SmXmYv6/full-graph.png))
![model properties](https://github.com/ultralytics/hub/assets/141426274/30355857-e6a1-4f40-9641-963eb24305e3)

**Included model in plugin .onnx** ([Full graph](https://i.ibb.co/ZgKZz81/car-aerial-detection-yolo7-ITCVD-deepness-onnx.png))
![model2 properties](https://github.com/ultralytics/hub/assets/141426274/a2517c23-fd0e-4951-9d32-f09c4e468be5)

Cheers!

**Comment by glenn-jocher** [comment]
@fredrikbacke92 hello, and thank you for bringing this to our attention!

From what you've described, it appears you're experiencing an issue with the exported ONNX model when using it with the QGIS "Deepness" plugin. The problem arises when the generated polygon layers or 'channels' become too numerous, leading to a memory overflow and consequently making QGIS crash.

In comparing the .onnx models, it sounds like the key difference is the number of classes they are trained to recognize. The model included in the plugin, which is working as expected, is trained to detect only a single class - 'car'. This means it exclusively creates polygon layers for this one class, hence only one channel is generated. 

On the other hand, when exporting models with the Ultralytics HUB, they will by default be trained to detect numerous classes based on the COCO dataset. This expanded class detection is likely leading to the creation of many polygon layers, or 'channels', thereby exceeding the memory on QGIS and causing it to crash.

To resolve this, one possible solution would be to re-train your model to detect only the specific classes you are interested in. This would reduce the number of channels, and we expect it would prevent the memory overload for QGIS. You could perform your training with a dataset that contains only your desired classes to ensure the model will only generate the corresponding channels.

I hope this helps guide you in investigating and addressing this issue. If you have any further queries or need further clarification, please do not hesitate to reach out! We're here to help, and appreciate you being part of the Ultralytics and YOLO community.

**Comment by fredrikbacke92** [comment]
Thanks you for the answer!

I should mention i use roboflow for annotation then use the API to train model on ultralytics. So far i've tried instance segmentation and object detection project (you choose before annotating), so i've tried 2 datasets. Both of these i've only annotated one class, "tree". I guess i could try a single-object classification project.

I tried training a new model without COCO pretraining. Used the object detection dataset and YOLOv8m. The only difference when trying this in QGIS was that it didn't visually generate layers in the layers tab. But it still crashes and you can see all channels still remain in the plugin options.

**Comment by fredrikbacke92** [comment]
**Solved!**

There was some compatible issue that was solved by the creator of deepness. See link.

https://github.com/PUTvision/qgis-plugin-deepness/discussions/101#discussioncomment-6662235

This workflow now works if you install fixed version of deepness provided in the linked thread.
