### ISSUE TITLE
YOLOv5u models cannot train directly from architecture

### ISSUE THREAD

**Issue by ankur-paan** [ultralytics/hub#351]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/*******API***Redacted**for**Privacy 🚀
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-2-9d498827fd9a> in <cell line: 3>()
      1 hub.login('ade***redacted***for***Privacy***')
      2 
----> 3 model = YOLO('https://hub.ultralytics.com/models/5MUhOs7Tt1GxpAQ9HpLJ')
      4 model.train()

4 frames
/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py in __init__(self, model, task)
     90             model, suffix = Path(model).with_suffix('.pt'), '.pt'  # add suffix, i.e. yolov8n -> yolov8n.pt
     91         if suffix in ('.yaml', '.yml'):
---> 92             self._new(model, task)
     93         else:
     94             self._load(model, task)

/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py in _new(self, cfg, task, model, verbose)
    116             verbose (bool): display model info on load
    117         """
--> 118         cfg_dict = yaml_model_load(cfg)
    119         self.cfg = cfg
    120         self.task = task or guess_model_task(cfg_dict)

/usr/local/lib/python3.10/dist-packages/ultralytics/nn/tasks.py in yaml_model_load(path)
    735 
    736     unified_path = re.sub(r'(\d+)([nslmx])(.+)?$', r'\1\3', str(path))  # i.e. yolov8x.yaml -> yolov8.yaml
--> 737     yaml_file = check_yaml(unified_path, hard=False) or check_yaml(path)
    738     d = yaml_load(yaml_file)  # model dict
    739     d['scale'] = guess_model_scale(path)

/usr/local/lib/python3.10/dist-packages/ultralytics/utils/checks.py in check_yaml(file, suffix, hard)
    373 def check_yaml(file, suffix=('.yaml', '.yml'), hard=True):
    374     """Search/download YAML file (if necessary) and return path, checking suffix."""
--> 375     return check_file(file, suffix, hard=hard)
    376 
    377 

/usr/local/lib/python3.10/dist-packages/ultralytics/utils/checks.py in check_file(file, suffix, download, hard)
    365         files = glob.glob(str(ROOT / 'cfg' / '**' / file), recursive=True)  # find file
    366         if not files and hard:
--> 367             raise FileNotFoundError(f"'{file}' does not exist")
    368         elif len(files) > 1 and hard:
    369             raise FileNotFoundError(f"Multiple files match '{file}', specify exact path: {files}")

FileNotFoundError: 'yolov5nu.yaml' does not exist

### Environment

Ultralytics YOLOv8.0.148 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 24.9/78.2 GB disk)
on google collab

### Minimal Reproducible Example

1. login to hub
2. select a dataset
3. when choosing a pretrained model, select advance and toggle off use pretrained model
4. train using google collab or any other way

**Comment by kalenmike** [comment]
@ankur-paan Thank you for raising this bug. We have confirmed this when training from the architecture directly with the YOLOv5u models. We are looking into this and hope to release a fix soon.
