### ISSUE TITLE
How to use the output of a model converted to CoreML?

### ISSUE THREAD

**Issue by Joao-Neves** [ultralytics/hub#352]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello, I've trained a YOLOv8x model in the Hub and then converted it to CoreML.

When adding the CoreML model to Xcode it tells me that the output is a `var_1365` that is a `MultiArray : Float32 1 × 5 × 8400 array`.
I was expecting a list of boxes or something similar.

How do I use the `var_1365`? Do I need to convert it to something else?

Thank you for your help 🙇.

**Comment by glenn-jocher** [comment]
@Joao-Neves if you are using CoreML exports you probably want to set NMS=True, which will process all detections and only return actual objects seen. Then you can use Xcode to preview inference results etc.

<img width="1064" alt="Screenshot 2023-08-08 at 15 34 00" src="https://github.com/ultralytics/hub/assets/26833433/ff02ccf3-6198-4be6-8709-d03c5b549f95">

**Comment by Joao-Neves** [comment]
@glenn-jocher thank you so much ❤️! That was it! I can get data I can work with now 😁!
