### ISSUE TITLE
Google colab has gone through all the eras and in the end gives an error.

### ISSUE THREAD

**Issue by SiriusMklain** [ultralytics/hub#359]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Training

### Bug

How to fix it? 
FileNotFoundError: 
Dataset '/content/datasets/new_project/new_project/config.yaml' images not found ⚠️, missing path '/content/datasets/project2/valid/images'
Note dataset download directory is '/content/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml'

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    125                     self.args.data = self.data['yaml_file']  # for validating 'yolo train data=url.zip' usage
    126         except Exception as e:
--> 127             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    128 
    129         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset '/content/datasets/new_project/new_project/config.yaml' error ❌ 
Dataset '/content/datasets/new_project/new_project/config.yaml' images not found ⚠️, missing path '/content/datasets/project2/valid/images'
Note dataset download directory is '/content/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml 

### Environment

google colab 

### Minimal Reproducible Example

Opened hub.ultralytics.com
Opened models
clicked on the model where there was a disconnect
copied the code
opened google colab link
pasted the code
learning lasted 100 epochs
and there was an error 

### Additional

Resumed work after a while in google colab
Training reached 100 out of 100 epochs but now this error. And I don't know how to fix it! After all, in the dataset on hub.ultralytics.com I have both pictures and a yaml file. what to do?

**Comment by kalenmike** [comment]
@SiriusMklain Thanks for raising this. I will take a look and see if what is going on here. How many times have you resumed? Also can you share the model id here?

`https://hub.ultralytics.com/models/MODEL_ID`
