### ISSUE TITLE
Dataset not Processing

### ISSUE THREAD

**Issue by tehreemkamal111** [ultralytics/hub#36]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

i want to train my dataset why is my dataset is processing take time too much

**Comment by tehreemkamal111** [comment]
I uploaded dataset and it is still processing

**Comment by glenn-jocher** [comment]
@tehreemkamal111 processing times correlate with dataset size, so the larger the dataset the longer it will take to process on upload. A very large dataset like COCO might take up to an hour.

**Comment by tehreemkamal111** [comment]
But it is small data set with 50 images only

**Comment by glenn-jocher** [comment]
@tehreemkamal111 that is a small dataset. Please make sure you are following the formatting directions exactly, and retry again a little later. If you still have problems please let us know and if you could provide your dataset that might help identify issues with it.

**Comment by kalenmike** [comment]
@tehreemkamal111 Processing can take some time, as we are not just processing the dataset you uploaded but also augmenting images for preview, etc. We have timeout sets which would catch any issues with datasets not completing the processing. We try to avoid processing on the client side to preserve your resources. If your dataset is showing as failed please let us know and we can investigate further.

**Comment by tehreemkamal111** [comment]
What is the formate?

**Comment by kalenmike** [comment]
@tehreemkamal111 The Ultralytics HUB now supports the standard YOLOv5 format. You can see how to create your dataset here https://github.com/ultralytics/hub/ and you can also import a dataset downloaded from Roboflow.
