### ISSUE TITLE
Export issue of custom trained model in coreml format in Ultralytics HUB

### ISSUE THREAD

**Issue by 00jackng00** [ultralytics/hub#360]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I trained a new model with my custom dataset and try to export it to coreml format in the deploy tab. However, it just keep loading and other formats also met the same issue. How could I solve it?
<img width="948" alt="Screenshot 2023-08-18 at 10 25 41 PM" src="https://github.com/ultralytics/hub/assets/142605997/8cfdbbe1-bf40-4eb1-aa65-9522c2abacc8">

### Additional

-Ultralytics HUB Version
v0.1.18-beta.31
-Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
-Operating System
MacIntel
-Browser Window Size
1245 x 1127
-Server Timestamp
1692368800

**Comment by kalenmike** [comment]
@00jackng00 Thanks for raising this. I have verified that our exports are working correctly, this may be related directly to your model. Could you please share your model id which you can find in the url:

https://hub.ultralytics.com/models/`MODEL_ID`?tab=deploy

**Comment by 00jackng00** [comment]
The related url is: https://hub.ultralytics.com/models/ydwuc6c3urSic74mhBvJ?tab=deploy
Thank you.

**Comment by UltralyticsAssistant** [comment]
@00jackng00 thank you for providing the model ID. We will be able to further look into this situation with this information.

On occasion, the process encounters issues if the model's architecture or parameters are incompatible with the targeted export format, but we'll need to investigate this specific case.

Our team will look into this problem with the model conversion to CoreML and we'll get back to you as soon as we have more insight or if we need additional information. We appreciate your patience in this matter.

**Comment by kalenmike** [comment]
@00jackng00 I was able to successfully export your model to coreml. I have since deleted the export. It looks like your model might have been too large for our previous export code, but we have made updates. If you would please try again and let me know how it goes.

**Comment by 00jackng00** [comment]
@kalenmike I was able to export the model in coreml format. Thanks for you help!

**Comment by UltralyticsAssistant** [comment]
@00jackng00 That's great to hear! I'm glad to know the issue is resolved and you can export your model in the CoreML format now. Should you encounter any other problems or have any more questions in the future, feel free to reach out. We're here to help! Thanks for using Ultralytics HUB, happy coding!
