### ISSUE TITLE
How to only have one object be tracked

### ISSUE THREAD

**Issue by oswinkil** [ultralytics/hub#361]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi, I'm trying to only track the object called "golf club-head" but I can't find any documentation on how to specifically track a class using names and not just an id.

**Comment by kalenmike** [comment]
Hi, @oswinkil!

Thank you so much for contacting Ultralytics. We're always eager to support passionate learners and enthusiasts in our community.

We have a vibrant community that's always ready to assist:

GitHub Community Support: You can post your questions or issues on our repositories. Our community and team members regularly monitor and assist there. Visit [Ultralytics GitHub](https://github.com/ultralytics).

Discord Channel: Engage with other users and some of our team members in real-time. You'll find it to be a treasure trove of knowledge and experience. Join us at [Ultralytics Discord](https://ultralytics.com/discord).

Many questions have already been addressed in these forums, and you might discover useful insights and solutions from previous discussions.

We value your interest and look forward to engaging with you in our online communities.
