### ISSUE TITLE
Project_yolo

### ISSUE THREAD

**Issue by murillowilmar1** [ultralytics/hub#364]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Project

### Use case

Academic

**Comment by UltralyticsAssistant** [comment]
@murillowilmar1 hi there! Thanks for your interest in the Ultralytics HUB for your academic project. I noticed that you didn't provide a specific question or issue. Could you please provide a bit more detail on what you're looking to accomplish or any challenges you're currently facing? Whether you're having trouble uploading a dataset, training a model, or just want some general guidance, we're here to help. The more specific you can be, the more useful help we can provide! Looking forward to hearing more about your project.
