### ISSUE TITLE
Project 

### ISSUE THREAD

**Issue by murillowilmar1** [ultralytics/hub#365]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Project

### Use case

Academic

**Comment by UltralyticsAssistant** [comment]
@murillowilmar1 i'd be happy to assist you, but it seems your message was cut short. Could you please provide more detailed information about your project and your specific question or concern? That will help me guide you through the Ultralytics HUB capabilities most pertinently. If your question pertains to the usage of a specific feature, elaborating on your use case scenario would be very beneficial. Looking forward to hearing from you!
