### ISSUE TITLE
colab notebook training

### ISSUE THREAD

**Issue by omumbare7** [ultralytics/hub#369]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

does the colab notebook training (through ultralytics hub) keep working even if i shutdown my PC?

**Comment by kalenmike** [comment]
@omumbare7 This will depend on your Colab plan. Google Colab may shutdown if not in use. The free Colab plan will timeout if there is no interaction within x minutes.

**Comment by omumbare7** [comment]
i just found out and i absolutely love the fact that ultralytics hub lets you have checkpoints on epochs, so that even if you are disconnected you can start training again from the last checkpoint, this feature is an absolute time and resource saver

**Comment by UltralyticsAssistant** [comment]
@omumbare7 hello, I'm glad to hear you are finding the checkpointing feature useful! It is indeed a valuable feature the team at Ultralytics has developed, making sure your training process is as resilient as possible. Your encouraging words mean a lot to us, and we are happy to know that the features are making a difference. Please remember that while we continue to develop and refine Ultralytics HUB, the credit also goes to the vibrant YOLO and Ultralytics communities that always provide constructive feedback. Don't hesitate to share any other thoughts you have or problems you encounter. Thank you!
