### ISSUE TITLE
Timeout No response from servers

### ISSUE THREAD

**Issue by PHIKHONAMTHEMBU** [ultralytics/hub#370]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I am uploading a dataset to Ultralytics HUB, and for several attempts now, I am getting Timeouts - No response from the servers.

### Minimal Reproducible Example

1. Login
2. Click Datasets
3. Upload dataset

**Comment by kalenmike** [comment]
@PHIKHONAMTHEMBU Thanks for raising this bug. We recently made some changes to our dataset upload code. Its possible that your upload job is not being assigned enough memory. How large is the dataset you are trying to upload?

**Comment by PHIKHONAMTHEMBU** [comment]
Thank you, my dataset is 8.1GB.

**Comment by kalenmike** [comment]
Ok I will look into this for you now.

**Comment by kalenmike** [comment]
@PHIKHONAMTHEMBU I identified an issue with our memory allocation this has now been resolved. Any pending datasets you had should now complete successfully.

We will deploy some changes to the HUB in the next hour that will allow you to retry processing for any timeouts you may have had today.
