### ISSUE TITLE
Dataset upload error

### ISSUE THREAD

**Issue by rumjie** [ultralytics/hub#371]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

<img width="410" alt="image" src="https://github.com/ultralytics/hub/assets/103101268/90c93ef2-43f7-468c-a53a-989104b84573">
Dataset upload is keep making error with dataset images cannot be located, but I made all path and locations same as guide. 

<img width="254" alt="image" src="https://github.com/ultralytics/hub/assets/103101268/6f7ecbf7-624e-4d8c-a9f7-e49ece3385e8">

Is this caused by image format - png or something else?

**Comment by kalenmike** [comment]
@rumjie Thanks for raising this bug. We have recently made some improvements to our dataset processing and its possible that a bug was introduced into the validation. I will take a look into our logs and see if I can figure out what is going wrong here. For the moment can you share the contents of your YAML file to confirm that the paths are correct?

**Comment by rumjie** [comment]
@kalenmike Thank you for super quick response. 
Here I paste my yaml file.     
<img width="853" alt="image" src="https://github.com/ultralytics/hub/assets/103101268/e85f724d-f901-4177-9745-1ca78e4e0b07">

**Comment by kalenmike** [comment]
@rumjie Thank you. It looks good. If you hover on the text 'The dataset images cannot be created' what is the tooltip that you see?

**Comment by rumjie** [comment]
@kalenmike Sadly that's the weird point, nothing popped up. When I met another error before, there was some messages that I can recognize which fix but this time I cannot.

**Comment by UltralyticsAssistant** [comment]
@rumjie I understand the confusion, normally a tooltip does show up with more details. It could be a UI bug or some backend issue. I'm forwarding this to our engineering team right away to investigate the problem. While they're looking it over, can you confirm that your image files are accessible and in correct format? Also, please make sure there's no problem with the permissions of the files or the directories they reside in. These are some common reasons why the dataset images might not be located.

We'll try to resolve this issue as quickly as we can for you. Thank you for your patience and understanding.

**Comment by kalenmike** [comment]
@rumjie I found an issue in the validation when the dataset was zipped with the `__MACOSX` folder at root. This has been addressed and new datasets will now work. I will get the server to reprocess datasets that failed recently because of this error.

**Comment by rumjie** [comment]
@kalenmike Many thanks for quick answer and fix 👍

**Comment by UltralyticsAssistant** [comment]
@rumjie You're welcome! I'm glad we were able to address this promptly. If you encounter any further issues, please don't hesitate to report them. We appreciate your patience and support in helping us improve the Ultralytics HUB. Happy coding!
