### ISSUE TITLE
upload model directly to a device

### ISSUE THREAD

**Issue by jasonoglio** [ultralytics/hub#375]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Can i upload a model directly to a device that i have trained on my computer?

**Comment by kalenmike** [comment]
@jasonoglio Thanks for asking the question. We do not currently support uploading models into Ultralytics HUB that were trained without a HUB connection.

**Comment by lonnylundsten** [comment]
You can export your .pt model from ultralytics to .coreml format and, assuming you're using iOS, you can load your model into the Vision Detector app on your iPhone/pad/MacOS and use your device camera for testing realtime detection. https://apps.apple.com/us/app/vision-detector/id6443729650

**Comment by UltralyticsAssistant** [comment]
@lonnylundsten sure, that's correct. Once you have a model trained using Ultralytics, you can export it to Core ML format using the export functionality on Ultralytics HUB. Then, you can use this Core ML model effectively with many iOS apps which allows for importing custom Core ML models, such as Vision Detector app you mentioned. This app uses the device camera for real-time object detection. This way, you can directly utilize your trained models on your device.

**Comment by kalenmike** [comment]
@lonnylundsten We also have a companion app for [Ultralytics HUB.](https://apps.apple.com/us/app/ultralytics-hub/id1583935240)
