### ISSUE TITLE
Trained model in Colab disconnected in the hub

### ISSUE THREAD

**Issue by PHIKHONAMTHEMBU** [ultralytics/hub#378]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

Ultralytics HUB Version
v0.1.22
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
2400 x 1174
Server Timestamp
1693738544

It seems the model's metadata is not sent to the hub, trained model from google colab, however metadata not sent back to the hub

### Minimal Reproducible Example

1. upload dataset
2. clicks train model
3. copy google colab integration data (API Key, ...)
4. run in google colad
5. model is running but no update in hub

**Comment by kalenmike** [comment]
@PHIKHONAMTHEMBU Thank you for raising the bug. Can you share your model if so that I can look into this?

**Comment by PHIKHONAMTHEMBU** [comment]
@kalenmike , you may close this incident, thanks
