### ISSUE TITLE
counter 

### ISSUE THREAD

**Issue by aditcodiant** [ultralytics/hub#382]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

object counter based on the calsses

**Comment by UltralyticsAssistant** [comment]
@aditcodiant hi there, 

Thanks for your feature request regarding object counting based on classes. Unfortunately, as of our current version, the Ultralytics HUB does not natively support this function. 

However, you can achieve it by post-processing the HUB's output. In brief, the HUB produces the detection results for each image, and these results include class labels for detected objects. You can create a custom script to cross-reference these labels with your class of interest and keep count.

Remember that the detection outputs a list of detections for each image, where each detection is a tuple of (box coordinates, class confidence, class label). You can iterate over these results, and for each detection, examine the class label. If it matches your class of interest, increment your counter.

Keep watching for updates as we continually strive to improve and expand the functionalities based on the user requests like yours.

Thanks again for your interest in Ultralytics HUB! Please feel free to contribute to the discussions and the repository itself.

Best regards,
Ultralytics Assistant
