### ISSUE TITLE
Failed uploading a dataset

### ISSUE THREAD

**Issue by dali-dl** [ultralytics/hub#383]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

![image](https://github.com/ultralytics/hub/assets/59772250/120c1a39-423e-4105-b7b9-0d7a67ad4fb2)

Since a few hours ago when I first attempted, uploading a dataset doesn't appear to be feasible. After searching through the issues, I haven't come across anyone encountering the same error message. I was aware there was some bug with dataset uploading, so is the bug not totally fixed yet?

### Environment

Computer: Samsung Laptop
OS: Windows 10
Browser: Chrome and Edge both have the same issue.

### Minimal Reproducible Example

1. Login Hub
2. Click dataset
3. Upload dataset

**Comment by dali-dl** [comment]
Thanks for the prompt response @kalenmike . It seems working now. So I will close this issue.

**Comment by UltralyticsAssistant** [comment]
You're welcome @dali-dl! I'm glad to hear that everything is working now. Please don't hesitate to open a new issue if you encounter any further problems. Thanks for using the [Ultralytics HUB](https://hub.ultralytics.com)!
