### ISSUE TITLE
Model Size

### ISSUE THREAD

**Issue by eggmakers** [ultralytics/hub#388]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How could I find my model size before o after training, like this ?pls help
<img width="191" alt="image" src="https://github.com/ultralytics/hub/assets/39152460/0b3ee429-4209-4e72-a4f6-9511257f4d5c">

**Comment by UltralyticsAssistant** [comment]
@eggmakers sure, I'd be happy to help clarify this for you. You can generally determine the size of your model both before and after training by checking the memory space that your model takes up on disk. When you save your model using the PyTorch "torch.save()" method, it creates a file. You can check the size of this file to get an idea of your model's size.

However, please note that this size might not be exact. The PyTorch save method includes additional information, like the model's weights and the state of the optimizer. Therefore, the file size might be larger than the actual model size.

The image you are showing seems to be the output of a model summary function which can provide computational aspects of the model like number of parameters, type of layers, etc. In PyTorch, the `torchsummary` package provides a similar kind of model summary which can help you infer the number of parameters before and after training.

Do remember that the number of parameters of a model don't generally change before and after training. The learning process updates the values of these parameters, but does not add or remove any.

I hope this clarifies your query. If not, feel free to ask further questions.

**Comment by kalenmike** [comment]
@eggmakers In Ultralytics HUB you can see your model size on the deploy tab for each of your exported formats:

![image](https://github.com/ultralytics/hub/assets/25989362/6feac990-fe42-479f-93e0-64da654b8ad8)
