### ISSUE TITLE
Is the HUB supporting cls ，pose， and seg traing？

### ISSUE THREAD

**Issue by ghgggg** [ultralytics/hub#396]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

as mentioned in the title, I 'm using hub to train some detection model,and I also want to train some other algs, such as classification,pose and segmetation. But I find  in HUB no cls ,pose and seg pretrained model which can be selected.  
![image](https://github.com/ultralytics/hub/assets/17875613/00f6833a-27a2-45e4-a4a1-1734053a653b)

I want to know if or not  cls pose ,seg supported in hub now?

**Comment by UltralyticsAssistant** [comment]
@ghgggg thank you for reaching out with your question! 

As of now, Ultralytics HUB primarily focuses on object detection training, particularly with the YOLO family of models. This includes YOLOv5 and YOLOv8 models. We're specialized in object detection and have made strides to develop a systematic yet versatile model training, evaluation, and deployment system for YOLO.

While there's currently no direct support for classification(cls), pose estimation(pose), and segmentation(seg) tasks, we're always open to community feedback. It helps us understand the needs of users like you and plan our future enhancements accordingly.

I will be sure to forward your request to our development team. It's the valued input and active engagement from our community that helps drive the evolution of the HUB. Please stay tuned for updates as we're continually improving and expanding!

Once again, thank you for your feedback and for supporting Ultralytics HUB! If you have any more questions or need further clarification, feel free to ask.

**Comment by kalenmike** [comment]
@ghgggg Thanks for asking the question. Yes, Ultralytics HUB  supports multiple tasks. The models tasks is determined by the dataset that you have selected.

When you update a dataset that supports another task, through the manual upload or Roboflow integration your model will train for that task.

![image](https://github.com/ultralytics/hub/assets/25989362/260ada52-cbc6-420f-ac46-5364a236d636)
