### ISSUE TITLE
Provided Colab for training errors out

### ISSUE THREAD

**Issue by ldorigo** [ultralytics/hub#397]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

When I train on colab, the first cell gives the following error: 

![Screenshot_20230913_212953](https://github.com/ultralytics/hub/assets/8631181/e0753755-9e28-4a42-b561-177fa2e4b1dc)

### Environment

Colab as linked from the hub

**Comment by miba-joshkehl** [comment]
I am having the exact same issue from both Colab and my local machine.

**Comment by kalenmike** [comment]
@ldorigo @miba-joshkehl Thanks for raising this. We have a bug in our latest release we just yanked it, you should be good to go. You will need to install the old package or refresh your colab.

`%pip install ultralytics=8.0.176`
