### ISSUE TITLE
Bounding boxes stays on screen after detection until next object appears on the screen

### ISSUE THREAD

**Issue by nuhmanpk** [ultralytics/hub#399]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

When i fo inference on mobile (Android 13) Nothing phone 2, the boxes stays on screen even after i move the camera away from the object .

### Environment

Nothing phone 2 Android 13

**Comment by sergiossm** [comment]
@nuhmanpk thanks for reporting! We're aware of the issue and will solve it ASAP.

**Comment by kalenmike** [comment]
We are going to manage this issue [here](https://github.com/ultralytics/hub/issues/421) going forward.
