### ISSUE TITLE
How Do I import my already Trained model in Ultralytics Hub?

### ISSUE THREAD

**Issue by GitProgrammerGuy32** [ultralytics/hub#401]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hey @glenn-jocher how do I upload my pretrained model in the ultralytics hub , I have already trained the YOLOV8 model with datasets on my Google collab with my annotations and stuff, exported it in ` .pt` format as well,tested but how do I upload them in the Utralytics hub with classnames so as to use them in the ultralytics realtime detection application?

Thanks in Advance!
Best Regards
Shaurya Grover

**Comment by lonnylundsten** [comment]
You can export your .pt model from ultralytics to .coreml format and, assuming you're using iOS, you can load your model into the Vision Detector app on your iPhone/pad/MacOS and use your device camera for testing realtime detection. https://apps.apple.com/us/app/vision-detector/id6443729650

**Comment by UltralyticsAssistant** [comment]
@lonnylundsten sure, here's how you can accomplish it. Once you have your Ultralytics-based model trained and exported as a .pt file, you'll need to convert it into the .coreml format. This format is compatible with the Apple ecosystem, so you can use it for real-time object detection on your iOS devices.

After you've converted your file into the .coreml format, you can load this model into the Vision Detector application. This application allows you to utilize the camera on your device (such as an iPhone, iPad, or MacOS device) to perform real-time object detection. 

Remember to also import your class labels into the Vision Detector app, so it correctly identifies the objects detected by your model. This way, your pretrained YOLOv8 model can be used for real-time detection on your device. 

I hope this helps! Let me know if you have any other questions.
