### ISSUE TITLE
Samsung Galaxy S21 Ultra 5G crash

### ISSUE THREAD

**Issue by jquaglia-uss** [ultralytics/hub#402]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

![image](https://github.com/ultralytics/hub/assets/114497590/2e9318af-3c02-4ca5-a894-c38999fd6ff3)

### Environment

Android 
Samsung GS21 Ultra 5G
Software Version: G998USQU*EWH6

### Minimal Reproducible Example

Open App on device
Click around to various sections
Observe app crash

**Comment by UltralyticsAssistant** [comment]
@jquaglia-uss hello! Thank you for reporting the issue with the HUB app on your Samsung Galaxy S21 Ultra 5G. I'm sorry to hear that you're experiencing crashes. 

To address this, could you please ensure that your device's software is up to date with the latest version provided by Samsung? Additionally, clearing the app's cache often resolves such issues. If the problem persists, you could try reinstalling the app to see if this improves stability.

In case these steps do not resolve the issue, it would be very helpful if you could provide more specific details regarding the crash. Information such as the sections of the app you clicked on before the crash and the actions you performed could help us identify the cause more effectively.

Lastly, if you have the ability to capture any error messages or logs produced during the crash, that would greatly assist our investigation into the matter.

Please follow up with any additional information you can provide, and we'll do our best to address the problem.  Also, consider checking the Ultralytics HUB documentation for further assistance on troubleshooting common issues.
