### ISSUE TITLE
Who to display images, bounding boxes, etc. on screen with YOLOv8

### ISSUE THREAD

**Issue by rspandolfi** [ultralytics/hub#404]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

With YOLOv5, the YOLO argument "view-img" displays images, bounding boxes, etc. on the screen. This is not a valid YOLO argument with YOLOv8. What approach can be used in YOLOv8 to display images, bounding boxes, etc. on the screen?

**Comment by UltralyticsAssistant** [comment]
@rspandolfi in YOLOv8, the functionality to display images, bounding boxes, and other elements directly on the screen is not available as a command-line argument, unlike in YOLOv5. However, you can take advantage of the Python tools available in the Ultralytics/YOLOv8 ecosystem to achieve similar results. 

After running your model, you will get your outputs usually saved in the 'runs' directory, from where you can access the prediction data including the bounding boxes, labels, and scores. Once you have this output data, you can use popular libraries like OpenCV or Matplotlib to display the images with bounding boxes or any other overlays.

Remember to maintain a copy of your original image to easily overlay these elements. For OpenCV, the cv2.rectangle and cv2.putText functions would be useful for overlaying bounding boxes and labels. With Matplotlib, you can use patches.Rectangle to draw bounding boxes.

We welcome more suggestions from the community in the discussions panel too! The strength of YOLO is built upon the efforts of its users and developers.

**Comment by rspandolfi** [comment]
I forget to include the --show=true argument
With that argument, YOLOv8 displayed the images, bounding boxes, and other elements directly on the screen.

**Comment by UltralyticsAssistant** [comment]
@rspandolfi glad that you found the solution! Yes, including the `--show=true` argument in the command when running YOLOv8 will indeed allow you to have images, bounding boxes, and other elements displayed directly on the screen. It's a handy feature when you want to have a quick visual confirmation of your detection results.

Thanks for bringing it to notice and acknowledging. The goal of Ultralytics and the YOLO community is to collaboratively build tools with ease-of-use and functionality. If you have more questions about YOLOv8 usage, feel free to ask them here or in the discussions section, we are here to help. Remember, your questions and experiences can also help others in their journey with YOLO.
