### ISSUE TITLE
The ultralytics docs website cannot be opened

### ISSUE THREAD

**Issue by ckpjasher** [ultralytics/hub#407]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

The ultralytics docs website cannot be opened
I want to check out the https://docs.ultralytics.com/usage/python/ website, but can not access the show has reset the connection

**Comment by kalenmike** [comment]
@ckpjasher Thanks for asking this. We don't have any issues at the moment and the site is loading correctly. Please look into your connection or reset your cache.
