### ISSUE TITLE
How to extract result in YOLO v8x

### ISSUE THREAD

**Issue by pt2241701** [ultralytics/hub#409]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How to extract result when code run, i want append the object detected to my array, example: 1 tv 2 keyboard 3 cup, a.append(tv) a.append(keyboard) a.append(cup) , a.append(....)

**Comment by kalenmike** [comment]
@pt2241701 Thanks for asking the questions, you will be able to get support you need from our [discord community](https://ultralytics.com/discord).
