### ISSUE TITLE
Classifier export to coreML fails

### ISSUE THREAD

**Issue by Banhalmi** [ultralytics/hub#410]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

I trained a classification model using HUB, it wnet down normally.
After, I tried several times to export the model to CoreML, but it fails.
The export fails too, when I try it to IOS.

I changed the input size, 640 is too big, I changed to 224x224 before train the Yolov8m-cls network, other parameters were the defaults.

### Environment

Yolo HUB, training was done on my comuter, not with colab.

### Minimal Reproducible Example

Log in.
Project: LP classification.
Model: yolov8m
Deploy.
Export - CoreML

**Comment by kalenmike** [comment]
@Banhalmi Thanks for raising this. We are still working on improving the task implementation in HUB, its possible there is an issue here. We will add it to our list to be addressed.

**Comment by kalenmike** [comment]
This has been confirmed resolved.
