### ISSUE TITLE
Two errors in the "See Example Dataset" section  

### ISSUE THREAD

**Issue by greg87vel** [ultralytics/hub#413]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

![ultralytics errors](https://github.com/ultralytics/hub/assets/116429722/37c5e77e-56dc-4128-b0bc-e03d346a4849)
The two errors are:
- in purple: the .zip file, the root folder in the .zip file and the .yaml file must have the same name. ('detect-example.zip' is a wrong name, the right name for the .zip file is 'detect.zip')
- in red: the directory of the val images is not 'images/train' but 'images/val'

**Comment by UltralyticsAssistant** [comment]
@greg87vel hi there, we appreciate you taking the time to provide feedback. I apologize for the errors you've observed in the "See Example Dataset" section! 

You're correct about both points:

1. The .zip file, the root folder inside the .zip file, and the .yaml file should indeed have the same name. The suggested 'detect.zip' is correct.

2. The directory for the validation images is definitely not 'images/train'. It should be 'images/val' as you've noted.

Thanks for catching these mistakes and bringing it to our attention. It's an oversight on our part and we'll work on updating the documentation to reflect the correct information promptly. Please accept our apologies for any confusion caused.

Our thanks again for your vigilance. It's contributions like yours that help us continually improve and keep our documentation accurate.

**Comment by kalenmike** [comment]
@greg87vel Thanks for pointing this out. We will get this updated. We have made some improvements so the YAML no longer needs to be named the same as the zip file.

**Comment by greg87vel** [comment]
Thank you!

Il Gio 28 Set 2023, 10:08 Kalen Michael ***@***.***> ha
scritto:

**Comment by UltralyticsAssistant** [comment]
@greg87vel hello,

We want to acknowledge and thank you for bringing these errors to our attention. We're now in the process of making the necessary corrections to ensure our documentation is accurate. 

One important update we made is that we no longer require the YAML file to carry the same name as the zip file. This change is part of our continuous effort to improve the user experience.

We appreciate your contribution to the Ultralytics community and your help in making our platform better!

**Comment by kalenmike** [comment]
This will is fixed for the next release.
