### ISSUE TITLE
Where is Ultralytics Road Map?

### ISSUE THREAD

**Issue by jquaglia-uss** [ultralytics/hub#416]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Just wondering if the road map is anywhere handy?

And if Anomaly Detection is on anyone @ Ultralytics radar?

Could yolov8 be ported to do some some pseudo anomaly detection?  

i.e. Where there is only presence of the NORMAL condition

**Comment by UltralyticsAssistant** [comment]
@jquaglia-uss hello,

Thank you for your interest in Ultralytics. Currently, we do not have a singular, publicly viewable roadmap. Features and advancements are often driven by ongoing projects, collaborations, and the needs of the broader community.

With regards to Anomaly Detection, it isn't a primary focus at the moment. That being said, it's a fascinating area that has the potential for interesting applications with regard to object detection models like YOLOv8. 

Your suggestion about adapting YOLOv8 for anomaly detection by identifying departures from "NORMAL" conditions is certainly an intriguing possibility in future development.

At Ultralytics, we are always open to new ideas and suggestions from the community. You're welcome to contribute or provide further insights on your perspective. Every contribution helps us to build a more robust system. 

Best Regards,
Ultralytics Team

**Comment by kalenmike** [comment]
@jquaglia-uss You can find our planned roadmaps within our projects:

https://github.com/orgs/ultralytics/projects

I will get back to you on the other questions.

**Comment by kalenmike** [comment]
@jquaglia-uss I have not been able to get any answers to the questions you raised regarding YOLOv8. You might be better placed asking this on the ultralytics/ultralytics repo.
