### ISSUE TITLE
Error using API

### ISSUE THREAD

**Issue by simasvelez** [ultralytics/hub#418]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have trained a model and I am trying to access it via API (desktop and also collab).
I keep getting the error
MaxRetryError: HTTPSConnectionPool(host='api.ultralytics.com', port=443): Max retries exceeded with url: /v1/predict/JdDiwatWl7QAD52yI9cR (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:2426)')))
I'm running the example that is provided with the model

Is this something on my end?
Thanks

**Comment by UltralyticsAssistant** [comment]
@simasvelez hello,

It's unfortunate that you're encountering this error. The error message you're seeing, `MaxRetryError: HTTPSConnectionPool`, is typically related to network issues. Occasionally, this kind of problem may occur if your network is blocking the connection to our servers or if there is a network instability issue.

It’s always a good idea to check your internet connection first in such situations. If you're on a company network, there could be firewall settings that are blocking your requests. If possible, you could try using a different network, or discussing the issue with your network administrator. 

The issue could also relate to your Python environment. Sometimes, Python environments can have issues with SSL certificates depending on how they were installed. If the situation continues, you may want to consider reinstalling Python or creating a new virtual environment to eliminate any issues in your Python installation and dependencies.

I hope this helps guide you in identifying the issue! Let us know if you continue to experience this problem after trying out these recommendations, providing additional details would also be helpful in further troubleshooting.

Thanks for your understanding and patience!

**Comment by simasvelez** [comment]
Sorted with urllib3

**Comment by UltralyticsAssistant** [comment]
@simasvelez, I'm glad to hear that you have resolved your issue by using urllib3. It's often beneficial to explore different Python libraries when encountering such problems, as different libraries can handle network protocols in distinct ways.

Thank you for taking the time to let us know your solution. This will likely assist others who might encounter similar situations in the future. If you have any more issues or questions about Ultralytics HUB, don't hesitate to raise them. We're here to help! The continual improvements of our platform are heavily inspired by constructive feedback and inquiries from users like you.

Keep exploring the HUB, and happy coding!
