### ISSUE TITLE
Pytorch Lite 

### ISSUE THREAD

**Issue by IyazGreat** [ultralytics/hub#419]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Hi, it's great to have a pytorch lite export futures.

**Comment by UltralyticsAssistant** [comment]
@IyazGreat hello,

Thank you for your positive feedback and suggestion for a feature to support PyTorch Lite in Ultralytics HUB!

Currently, PyTorch Lite is not directly supported in the Ultralytics HUB. However, we understand the benefits and importance of having this feature, as PyTorch Lite offers efficient inference on edge and mobile devices, and we always aim to be up to date with features that can enhance the utility of our platform.

We have added your request to our internal tracking system and will discuss it as a possible new feature in future updates.

We appreciate your suggestion and are always thrilled to hear feature requests that can make our platform even better.

Stay tuned for any updates based on your suggestion, and feel free to continue exploring the current offerings of Ultralytics HUB.

Thanks!
