### ISSUE TITLE
when i run yolov8 with opencv it prints every thing in the terminal

### ISSUE THREAD

**Issue by omumbare7** [ultralytics/hub#422]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

when i run inference using frames from open cv, which i later want to process more on using the coordinates recieved, i get a lot of stuff printed out on the terminal like, "0: 640x640 (no detections), 45.9ms
Speed: 4.0ms preprocess, 45.9ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 640)" which i dont want, how can i deal with it ?

### Additional

i want to use the calculate the centroids and then plot it to servos this the code so far

from ultralytics import YOLO
import cv2
import math
import numpy as np

# start webcam
cap = cv2.VideoCapture(0)

input_size = (640, 640)

# model
model = YOLO("weedLAU.pt")

# object classes
classNames = ['weed']

def track(x1,y1,x2,y2, height, width):
    
    fx= int((x1+x2)/2)  #for servo coords
    fy= int((y1+y2)/2)
    servoX = np.interp(fx, [0, width], [0, 180])
    servoY = np.interp(fy, [0, height], [0, 180])
    #if abs(servoX - servoPos[0]) > 5:
        #servoPos[0] = servoX
    #if abs(servoY - servoPos[1]) > 5:
        #servoPos[1] = servoY
    if servoX < 0:
        servoX = 0
    elif servoX > 180:
        servoX = 180
    if servoY < 0:
        servoY = 0
    elif servoY > 180:
        servoY = 180
    #servoPos[0] = servoX
    #servoPos[1] = servoY
    print(fx, fy)
    
    

    
while True:
    success, frame = cap.read()
    inp_frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)#opencv defaul channel is bgr
    inp_frame = cv2.resize(inp_frame, input_size)
    img = inp_frame
    kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
    sharpened = cv2.filter2D(img, -1, kernel)
    kernel2 = np.ones((1, 1), np.uint8)
    dilated_img = cv2.dilate(sharpened, kernel2, iterations=1)
    sharp_frame = cv2.erode(dilated_img, kernel2, iterations=1)
    final_frame = cv2.cvtColor(sharp_frame, cv2.COLOR_BGR2RGB)
    
    results = model(final_frame, stream= True)

    # coordinates
    for r in results:
        boxes = r.boxes

        for box in boxes:
            # bounding box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)  # convert to int values

            # confidence
            confidence = math.ceil((box.conf[0] * 100)) / 100
            
            # Only print data if confidence is greater than or equal to 0.5
            if confidence >= 0.75:
                print("Confidence --->", confidence)

                # class name
                cls = int(box.cls[0])
                print("Class name -->", classNames[cls])

                # object details
                org = [x1, y1]
                font = cv2.FONT_HERSHEY_SIMPLEX
                fontScale = 1
                color = (255, 0, 0)
                thickness = 2

                cv2.putText(img, classNames[cls], org, font, fontScale, color, thickness)
                height, width, channels = final_frame.shape
                track(x1, y1, x2, y2, height, width)
                
            # Draw bounding box for all objects regardless of confidence
            cv2.rectangle(img, (x1, y1), (x2, y2), (255, 0, 255), 3)

    cv2.imshow('Webcam', img)
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

**Comment by UltralyticsAssistant** [comment]
@omumbare7 your question pertains to suppressing the console statements produced during the inference process with YOLOv8 model. These print statements are actually coming from the Ultralytics YOLOv8 implementation itself. They provide important insights into the model's performance including processing and inference times. 

However, to silence these print statements, you would want to modify your local version of the YOLO code. Specifically, look for the part of the code where these stats are being printed, and you can comment it out. In YOLOv8 the output is controlled by the Logger class which can be found in the 'utils/logs.py' file, this is where you should check.

Remember, any modifications you make should comply with the AGPL-3.0 license under which this repository is protected. Always bear in mind that altering the print statements might make future troubleshooting more challenging as you won't be seeing the live stats during model inference.

**Comment by kalenmike** [comment]
@omumbare7 YOLOv8 should be using logging for its output now. To silence the output you can set the logging output to critical.

```python
import logging
logging.basicConfig(level=logging.CRITICAL)
```
If you still have issues it could be because the logger is somehow overwriting the default value. In that case you can force all loggers to update:

```python
for name in logging.root.manager.loggerDict:
    t_logger = logging.getLogger(name)
    t_logger.setLevel(logging.CRITICAL)
```

**Comment by omumbare7** [comment]
yep this solved my issue thank you very much @kalenmike

**Comment by UltralyticsAssistant** [comment]
@omumbare7 that's great news! I'm glad the solution worked for you. Remember, if you have any more issues or questions in the future, feel free to ask. Thanks for being a part of the Ultralytics and YOLO community!
