### ISSUE TITLE
i have disabled the console logging, but this prints, i dont want anyting to be printed 

### ISSUE THREAD

**Issue by omumbare7** [ultralytics/hub#433]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question
is there any built in functionality to put a number on the bounding box and keep the same number until it is told to release the number?

**Comment by kalenmike** [comment]
@omumbare7 It looks like you are printing that in your script? Share your script here and we can try to help.

**Comment by omumbare7** [comment]
> @omumbare7 It looks like you are printing that in your script? Share your script here and we can try to help.

oh my bad, yes you are right about printing confidence and class names, also is there any built in functionality to put a number on the bounding box and keep the same number until it is told to release the number?

**Comment by kalenmike** [comment]
@omumbare7 It sounds like you are trying to implement tracking. You can read more on that here:

https://docs.ultralytics.com/modes/track/?h=tracking

**Comment by omumbare7** [comment]
> @omumbare7 It sounds like you are trying to implement tracking. You can read more on that here:
> 
> https://docs.ultralytics.com/modes/track/?h=tracking

i have tried this bytetracker and it works as expected, but i havent figured out a way to extract ids and put them on my opencv window i want to display on (i dont want to use show = True) ( i want to access IDs and use them further in my other parts of the code) i am attaching the code below



from ultralytics import YOLO
import cv2
import math
import numpy as np


print("please provide the name of .pt file you want to use")
a=input(str()) #you can provide file name here if you have multime choices for .pt files you can choose one here
# model
model = YOLO(a + ".pt")
# start webcam
cap = cv2.VideoCapture(0)

input_size = (640, 640)

# object classes
classNames = model.names

def track(x1,y1,x2,y2, height, width, frame):
    
    fx= int((x1+x2)/2)  #for servo coords
    fy= int((y1+y2)/2)
    servoX = np.interp(fx, [0, width], [0, 180])
    servoY = np.interp(fy, [0, height], [0, 180])
    #if abs(servoX - servoPos[0]) > 5:
        #servoPos[0] = servoX
    #if abs(servoY - servoPos[1]) > 5:
        #servoPos[1] = servoY
    if servoX < 0:
        servoX = 0
    elif servoX > 180:
        servoX = 180
    if servoY < 0:
        servoY = 0
    elif servoY > 180:
        servoY = 180
    #servoPos[0] = servoX
    #servoPos[1] = servoY
    print(fx, fy)
    cv2.line(frame, (int(frame.shape[1] / 2), int(frame.shape[0] / 2)),(fx, fy), (0, 255, 0), 2)
    


    
while True:
    success, frame = cap.read()
    results = model.track(frame, stream = True, verbose = False, tracker = "bytetrack.yaml", persist=True)
    
    # coordinates
    for r in results:
        boxes = r.boxes

        for box in boxes:
            # bounding box
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)  # convert to int values
            track_ids = results[0].boxes.id.int().cpu().tolist()
            # confidence
            confidence = math.ceil((box.conf[0] * 100)) / 100
            
            # Only print data if confidence is greater than or equal to 0.5
            if confidence >= 0.5:

                # class name
                cls = int(box.cls[0])

                # object details
                org = [x1, y1]
                font = cv2.FONT_HERSHEY_SIMPLEX
                fontScale = 1
                color = (0, 255, 0)
                thickness = 1
                
                #cv2.putText(frame, classNames[cls], org, font, fontScale, color, thickness)
                cv2.putText(frame, str(confidence), (x2, y1), font, fontScale, color, thickness)
                cv2.putText(frame, str(track_ids), org, font, fontScale, color, thickness)
                height, width, channels = frame.shape
                track(x1, y1, x2, y2, height, width, frame)
                
            # Draw bounding box for all objects regardless of confidence
            cv2.rectangle(frame, (x1, y1), (x2, y2), (255, 0, 255), 3)

    cv2.imshow('Webcam', frame)
    
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

**Comment by UltralyticsAssistant** [comment]
@omumbare7 it sounds like you've made good progress with your implementation. To access the tracked IDs of the detections, you can use the `.id` attribute of each detected bounding box object (`box`) in your results. Here's the general idea:

```
for r in results:
    boxes = r.boxes
    for box in boxes:
        track_id = box.id.int()
        # Now you can use track_id in your logic
```

Remember you'll need the ByteTrack model loaded and running for the `.id` attribute to hold the correct IDs. The ByteTrack model provides these IDs for each object across frames. 

Keep in mind that the ID will change every time it recognizes a new object or when the same object reappears after a period of not being detected. They are not intended to be persistent identifiers for distinct objects but rather identifiers for tracking within a specific session.

Also note that if the tracker is unable to detect an object for a certain number of frames (which can happen due to occlusion, for example), it may deallocate the ID assigned to that object. When the object reappears, it would then be assigned a new ID. This is part of the tracker's design to minimize the impact of false-positive detections and to provide better performance in real-time tracking.

Make sure to incorporate this understanding into your planning when designing your system to work with multiple detectors.

**Comment by omumbare7** [comment]
> @omumbare7 it sounds like you've made good progress with your implementation. To access the tracked IDs of the detections, you can use the `.id` attribute of each detected bounding box object (`box`) in your results. Here's the general idea:
> 
> ```
> for r in results:
>     boxes = r.boxes
>     for box in boxes:
>         track_id = box.id.int()
>         # Now you can use track_id in your logic
> ```
> 
> Remember you'll need the ByteTrack model loaded and running for the `.id` attribute to hold the correct IDs. The ByteTrack model provides these IDs for each object across frames.
> 
> Keep in mind that the ID will change every time it recognizes a new object or when the same object reappears after a period of not being detected. They are not intended to be persistent identifiers for distinct objects but rather identifiers for tracking within a specific session.
> 
> Also note that if the tracker is unable to detect an object for a certain number of frames (which can happen due to occlusion, for example), it may deallocate the ID assigned to that object. When the object reappears, it would then be assigned a new ID. This is part of the tracker's design to minimize the impact of false-positive detections and to provide better performance in real-time tracking.
> 
> Make sure to incorporate this understanding into your planning when designing your system to work with multiple detectors.

this will give out an error when there is no boxes, hence need to use it as 

if box.id is not None:
                track_id = box.id.int()
this works but gives out values in tensors

**Comment by UltralyticsAssistant** [comment]
@omumbare7 I'm glad to hear that you're making progress. You're correct that in absence of bounding boxes, trying to access the `id` property could result in an error. Including a conditional check utilizing `if box.id is not None:` can help to handle these scenarios without an error. 

Regarding the `id` values being output as tensors: yes, that's expected as Ultralytics stores these IDs and other object properties in tensor format for efficiency during computations. However, you can always convert the PyTorch tensor to a standard Python data type using the `.item()` function when you need to use it in other parts of your code, as tensors might not be as straightforward to interact with. So `track_id = box.id.int().item()` should give you an integer ID, which may be more helpful for your use case. 

Remember that working with ByteTrack model and interacting with IDs might have nuanced behaviors. For example, the allocated IDs could change dynamically when a new object is detected or when an existing object reappears after not being detected for some frames. Similarly, the tracker may deallocate an ID if the respective object is not detected for several frames. So, please do consider these points during your system's design phase.

**Comment by kalenmike** [comment]
@omumbare7 For help in implementing solutions like this you may be better served in our discord community

https://ultralytics.com/discord
