### ISSUE TITLE
Can researchers use models trained on datasets published on the ultralytics hub in their papers?

### ISSUE THREAD

**Issue by yukkin1021** [ultralytics/hub#435]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi.

I'm a university student.

I would like to use the models trained in the Ultralytics Hub in my paper.

Of course, we will not use the data for any purpose other than research purposes.

In the VisDrone-Dataset（https://github.com/VisDrone/VisDrone-Dataset）, you can find the following information.

"Note that the bounding box annotations of test-dev are avalialbe. Researchers can use test-dev to publish papers. testset-challenge is used for VisDrone2020 Challenge and the annotations is unavailable."

Does this mean that the datasets published on the Ultralytics HUB are test-dev??

Also, what should I write in the references?

**Comment by UltralyticsAssistant** [comment]
@yukkin1021 hello,

As the maintainer of the Ultralytics HUB, I'm happy to hear about your interest in using the models trained on our platform for your research!

Regarding the usage of models trained on datasets, the usage and licensing typically depend on the provisions of the individual datasets. Some datasets may freely allow usage in academic contexts, while others may have more restricted terms. In the case of the VisDrone dataset, they provide specific guidance on the usage of their data.

As for whether the datasets published on Ultralytics HUB are 'test-dev', the classification of datasets (train, validation, test-dev etc.) depends on the guidelines provided by the dataset's creator. The Ultralytics HUB doesn't specifically designate datasets as 'test-dev' or any other particular category.

Lastly, in terms of references, it's standard in academic research to cite the authors and source of the model you're using, as well as the dataset from which the model was trained. For usage of Ultralytics HUB, we suggest referring to the original paper or source for the specific model you used.

Remember, always check the specifics given by the dataset creator or model developer for the most accurate guidance on usage and citation.

I hope this answers your queries. Good luck with your research!

**Comment by UltralyticsAssistant** [comment]
Hello @github-actions[bot],

Yes, researchers can use models trained on datasets available on the Ultralytics HUB for their academic research papers. Generally speaking, we encourage the application of the models and datasets we host for research purposes, assuming the licensing of the individual datasets permits this.

For referencing, you should cite the dataset and the model according to the citation guidelines provided by their respective authors or organizations—usually found with the dataset or model documentation. For any models trained using Ultralytics HUB tools or systems, a citation to the Ultralytics HUB or the relevant publications or repositories should be included in your paper.

Make sure to closely follow the specific requirements for the datasets you're using. Publications and repositories often provide explicit instructions on how to cite their resources.

Should you need additional guidance, please consult our HUB Docs for more detailed information on terms of data usage and reference formatting. 

Happy researching!
