### ISSUE TITLE
How can I retrain my model with the updated dataset?

### ISSUE THREAD

**Issue by esquinasamira** [ultralytics/hub#439]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I just updated my dataset on roboflow and wanted to retrain my model on hub.
The model was already trained before in the hub project.
Is there a way to run the training in the project again?

**Comment by UltralyticsAssistant** [comment]
@esquinasamira yes, the Ultralytics HUB allows you to retrain your models easily. To do this, simply follow these steps:

1. Upload your updated dataset onto the HUB.
2. Navigate to the specific project where your model is saved.
3. You will find the previous training run associated with the model. Click on it.
4. On the top right corner of the respective run page, there's a button labeled 'Retrain'.
5. Clicking on 'Retrain' will initiate a new training run with the same configurations but with your updated dataset.

Remember, to use the updated dataset, you need to select it while initiating the retraining process. The HUB will automatically detect changes in your dataset and apply them to your new training run.

Feel free to reach out if you have any additional questions or concerns!

**Comment by esquinasamira** [comment]
@UltralyticsAssistant  I tried to find the button, but I couldn't find it.
My dataset came from roboflow. Is it related to this problem?

**Comment by UltralyticsAssistant** [comment]
@esquinasamira hello, I apologize if you're finding it difficult to locate the 'Retrain' button. Let me try and guide you again.

From the Ultralytics HUB main dashboard, click on the specific project where your model is hosted. Inside the project, you should see a list of your models trained in previous 'runs'. If you click on one of these runs, it should take you to a detailed view of that particular run. In the top-right corner of this page, there should be a 'Retrain' button. 

Regarding your updated dataset from Roboflow, the key is to make sure that the updated dataset has been uploaded properly to the HUB. Once the updated dataset is correctly uploaded, you should be able to select it during the retraining process.

Remember, the 'Retrain' action will use the same training configuration as the original run, but with the new dataset you selected. If you've done this correctly, the system should automatically detect changes in your dataset and use it for the new training run.

If you're still having trouble, please let us know, and we will do our best to assist you further.

**Comment by esquinasamira** [comment]
@UltralyticsAssistant @AyushExel can you add a screen picture here? or Should I buy a premium plan to retrain my model?

**Comment by UltralyticsAssistant** [comment]
@esquinasamira, I'm sorry for any confusion caused, but I, as a text-based AI, lack the capability to share screen pictures. 

To clarify, you don't necessarily need a premium plan to retrain your model in Ultralytics HUB. The ability to retrain a model is available for both free and premium users. 

Here's the step-by-step guide to help you locate the 'Retrain' button:

1. From the main dashboard, click the 'Projects' option.
2. Select the particular project that houses your model.
3. Inside the project, you will see a list of 'Runs’. These are your previous training runs.
4. Select the specific run which you want to retrain. 
5. Inside the run details, you should see a 'Retrain' button on the top right of the screen.

By clicking 'Retrain', your model will start a new training run with the same setup as the original but using the updated dataset you provide. As for your updated Roboflow dataset, it needs to be correctly uploaded to the HUB before retraining. 

If you're still having difficulties, we're here to help. Don't hesitate to ask your questions.

**Comment by kalenmike** [comment]
@esquinasamira It sounds like you would like to use your original model as a base model for retraining. We do not currently support this on HUB but it is a feature that is scheduled for development.
