### ISSUE TITLE
Ultralytics app not working 

### ISSUE THREAD

**Issue by Busterfake** [ultralytics/hub#440]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

Hello, i have trained on the hub a model with yolov8 that i wanted to try on the Ultralytics app. However the app seems to not work at all and i habe the message 'An error occurred' on most pages.
![bug_ultralytics](https://github.com/ultralytics/hub/assets/36502499/947978f8-8d33-4f61-b7dc-b879fc5806a2)

### Environment

- Iphone 15 Pro Max
- Lastest IOS version 

### Minimal Reproducible Example

Login the the hub app 
Go to Project
Click on any project 
An error occurred

### Additional

I'm looking to implement my yolov8 trained model into my own app but i can't find any implementation example (IOS & Android). I've already discussed with you about the licensing solution and i'm still interested into having an easy solution to implement my yolov8 models into my app. However, it would be better if i can first try these models into the hub app.

**Comment by sergiossm** [comment]
@Busterfake thanks for reporting! We'll look into it and get back to you.

**Comment by krilezr** [comment]
Same issue I have on the iPhone 13 and latest iOS version. Is there any news on that matter?

**Comment by sergiossm** [comment]
Hey @krilezr @krilezr we're looking into it!

**Comment by kalenmike** [comment]
@Busterfake @krilezr Are you still experiencing this issue with the latest version of the App? If so could you provide us with some way to identify your accounts? This could be the email you used to signup or the id of a custom model, dataset, or project.

**Comment by krilezr** [comment]
Hello Ultralytics team,

I tried with new models and now seems working smooth for iOS.
If any issues occur I will report to you immediately.

Well done and have a good day.

B.r.

**Comment by kalenmike** [comment]
@krilezr Thanks for the quick response and we are glad to hear that everything is now working for you.

**Comment by Busterfake** [comment]
@kalenmike I reinstalled the app and know it seems to work smooth !
Have a nice day :)

**Comment by kalenmike** [comment]
@Busterfake Great to hear! Thank you for the update!
