### ISSUE TITLE
Argoverse Dataset yaml file missing error

### ISSUE THREAD

**Issue by SY227** [ultralytics/hub#446]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

![image](https://github.com/ultralytics/hub/assets/38198978/06dd17c3-2dea-412b-983b-f8365f725499)

**Comment by UltralyticsAssistant** [comment]
@SY227 thank you for bringing this to our attention. It appears that the Argoverse Dataset yaml file is missing which is causing the error. 

To resolve this, you need to create a corresponding yaml file that describes the structure of the Argoverse Dataset properly. This yaml file should be placed in the same directory as your dataset. It must contain essential information such as the path details, classes, and any transformation or augmentation details, based on the format accepted by the HUB.

Please remember that each dataset can have a unique structure and therefore, different datasets might require slightly different yaml configurations. 

If you are still having trouble creating the yaml file or the error persists, please don't hesitate to get back to us, we're happy to help.

**Comment by SY227** [comment]
Thank you for the quick response. As Argoverse Dataset is one of the default dataset in the Ultralytics, can you the Ultralytics team add the missing yaml file?

**Comment by UltralyticsAssistant** [comment]
@SY227, thank you for your suggestion. As you mentioned, the Argoverse Dataset is indeed part of the default datasets provided by Ultralytics. Currently, our team is always working on expanding and refining the dataset support. 

Your request has been noted, and we will consider integrating this missing yaml file into a future update. However, creating a yaml file that works best with your specific use case can often be a specific task. Therefore, we also encourage our users to create their own yaml files to cater for more customized processing during the interim.

As always, don't hesitate to follow up if you encounter any further issues or have additional questions. We appreciate your understanding and patience.

**Comment by SY227** [comment]
Can you give me some guidance on how to create a yaml file that works best with specific use case? Or let me know when the yaml file will be ready in the dataset? Thanks. I appreciate all your help.

**Comment by UltralyticsAssistant** [comment]
@SY227 hello,

Creating a yaml file tailored to your specific use case involves providing the necessary details regarding your dataset. Here are basic steps you can follow:

1. **Name your yaml file**: It should be with the name of your dataset for easier identification.

2. **Specify path details**: You need to indicate the paths to your dataset. This typically includes path to your training, validation, and/or test data, depending on how you've divided your dataset.

3. **List your classes**: These are the labels in your dataset. They should be listed in the same order as they appear in your dataset records.

4. **Mention transformations and augmentations** (if any): Depending upon your work, you may want to specify particular transformations or augmentations in the yaml file. This is optional and case-specific.

Please remember that the structure of yaml can vary based on the dataset specifics.

As for the addition of the Argoverse yaml file in the dataset, we don't have a concrete timeline yet. However, your demand has been noted, and the team is working on it. We always aim to improve our tools based on user requests and continue to refine the dataset support.

We hope that this provides a bit more clarity, and thank you for your patience and understanding.

**Comment by glenn-jocher** [comment]
@SY227 you can download Argoverse manually here:
https://drive.google.com/file/d/1st9qW3BeIwQsnR0t8mRpvbsSWIo16ACi/view?usp=drive_link

**Comment by SY227** [comment]
Thank you @glenn-jocher. I will try that :)

**Comment by UltralyticsAssistant** [comment]
@SY227 You're welcome! I'm glad I could assist you. If you have more questions or encounter any issues while trying it out, please don't hesitate to raise them. Remember, we're here to help. Good luck with your work on the Argoverse Dataset!
