### ISSUE TITLE
HUB- local agent: CUDA not detected

### ISSUE THREAD

**Issue by barney2074** [ultralytics/hub#45]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello,

When using the HUB local agent (on Windows)- how can I get it to utilise the graphics card ?
I get an error 'CUDA not detected' message
![image](https://user-images.githubusercontent.com/25944617/172393219-05b7eec6-90b6-47eb-894b-2963b3078874.png)

- I have tried COLAB (I have a Pro subscription)- but as is my usual experience with COLAB- it gets 90% finished, then disconnects, and won't let me back on with a GPU- very annoying....!
- I do also have a Linux/RTX3060 machine which I can try, when it has finished on another job

thank you

Andrew

**Comment by glenn-jocher** [comment]
@barney2074 your pytorch installation is not recognizing any CUDA devices. See https://pytorch.org/get-started/locally/ to get started.

You can test correct Pytorch-GPU installation with `import torch; print(torch.cuda.is_available())`

**Comment by barney2074** [comment]
thanks @glenn-jocher 

I played around with it for ages- different graphics driver & CUDA versions- but couldn't get Pytorch to recognise it

In the end, I gave up on the Windows machine, and used the Linux one instead
The model training and deployment to an IOS device worked perfectly

thanks,


Andrew

**Comment by glenn-jocher** [comment]
@barney2074 @kalenmike thanks for the info! From your screenshots it does seem like it's a PyTorch install issue.

In our investigations we also identified a new failure mode with AutoBatch on consumer GPUs, but this appears unrelated to your original issue. In any case we should be pushing an AutoBatch update soon which will resolve that.

**Comment by barney2074** [comment]
thanks @glenn-jocher 

I was wondering if Docker would be an easier option for the local HUB agent ?- but suppose not everyone has Docker plus you need NVIDIA Docker as well

**Comment by kalenmike** [comment]
@barney2074 That's a good suggestion and something I think we will look into implementing. We want to make using local agents as easy as possible.

**Comment by glenn-jocher** [comment]
@barney2074 yes this isn't a bad idea to offer this as an additional local option. Then rather than need to debug local python environments the main requirement would be to have Docker installed correctly as well as all NVIDIA/CUDA drivers.
