### ISSUE TITLE
Can't Export YOLOv8 Model to TensorFlow Lite

### ISSUE THREAD

**Issue by brianajiks123** [ultralytics/hub#452]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have already YOLOv8 model, but I can't export them to TFLite with INT8 Quantization. What do I have to do?

**Comment by UltralyticsAssistant** [comment]
@brianajiks123 thank you for reaching out to Ultralytics with your question. I understand you are trying to export your YOLOv8 model to TensorFlow Lite with INT8 Quantization.

The Ultralytics HUB currently supports TensorFlow Lite export for YOLOv5 models. However, for YOLOv8 models the TensorFlow Lite export functionality is, as of yet, not supported.

Our engineers continuously work on enhancing the functionality of the Ultralytics HUB. Therefore, this feature might be available in future. 

We recommend keeping an eye on the Ultralytics HUB's updates for the latest features and enhancements.

Thank you for your patience and your ongoing support of Ultralytics. Let us know if you need any further assistance!

**Comment by brianajiks123** [comment]
I have already YOLOv5 model, but it's same, can't export them to TFLite
with INT8 QUANTIZATION. Do you can help me?

My work email: ***@***.***

Now, I have 2 model, but the model can't export to TFLite with INT8
QUANTIZATION.

**Comment by UltralyticsAssistant** [comment]
@brianajiks123, I understand that you're having issues exporting both YOLOv5 and YOLOv8 models to TensorFlow Lite with INT8 Quantization. 

As I mentioned before, Ultralytics HUB currently doesn't support INT8 Quantization for exporting models to TensorFlow Lite. This applies to both YOLOv5 and YOLOv8 models. Our engineering team continuously works to expand and improve features, and INT8 Quantization support may be implemented in the future.

Meanwhile, you can continue exporting your models to TensorFlow Lite, albeit without INT8 Quantization. If you're interested in enhanced model performance, there are other techniques you might explore such as pruning or optimizing your model architecture.

If there are other questions or if you're experiencing different issues, please don't hesitate to inform us. We're here to assist you in your journey with Ultralytics. Thanks for your understanding and support!
