### ISSUE TITLE
Custom Trained model stops training at 100th epoch

### ISSUE THREAD

**Issue by vrushank41** [ultralytics/hub#460]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

My model is paused at the 99th epoch and crashes everytime while optimising the weights.
What could be done to resolve the issue?

![image](https://github.com/ultralytics/hub/assets/93258530/d71c3a8e-a6c4-4f11-b443-29024466096e)

### Environment

Ultralytics HUB Version
v0.1.28
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Operating System
Win32
Browser Window Size
1488 x 716
Server Timestamp
1699430339

**Comment by kalenmike** [comment]
@vrushank41 It looks like there was issues with the resume function. We are currently looking into this. You can follow the progress here:

https://github.com/ultralytics/hub/issues/461

In the meantime we will look into applying a fix to the model in your screenshot.
