### ISSUE TITLE
Server no response with large dataset

### ISSUE THREAD

**Issue by FlySka** [ultralytics/hub#469]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

When I try to upload a large dataset (~6GB, 82885 images) when optimizing it gives the error:

Time Out: No response from the server

![image](https://github.com/ultralytics/hub/assets/53591591/bcde61f3-6241-4818-9066-2f95efb91645)

What can I do to upload this dataset to HUB?

### Environment

- Levono Legion 5i Pro - i9-3600HX, 16RAM, SSD 512GB, Nvidia Geforce RTX 4060
-  Windows 11
- Edge Versión 119.0.2151.58 (Compilación oficial) (64 bits)

**Comment by kalenmike** [comment]
@FlySka Your dataset is uploading, we have logs of an internal error on generating the previews and the stat file. We will look into this further and see if we can figure out what is going wrong.

**Comment by kalenmike** [comment]
@FlySka After review it seems we had a temporary outage. It looks like your latest attempt completed successfully can you please confirm?
