### ISSUE TITLE
Custom agent training args

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/hub#479]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Include "expert" controls for 'bring your own agent' option. Allows for ability to make more fine-tuned adjustments for hardware (assumes user knows optimal settings to use on their equipment). Either reveal additional controls in HUB GUI or allow for arguments passed via `train` method override initial settings.

Assume default HUB settings + bring your own device, then code run is:

```py
from ultralytics import YOLO, checks, hub
checks()

hub.login('key')

YOLO('modelURL')
results = model.train(freeze=6, batch=12, half=True) # allow these to override HUB defaults if/when running on own hardware
```

### Use case

If not all made available in HUB GUI, best arguments to include (and why)

- `half` :: use `FP16` instead of default `FP32`, reduces GPU memory usage (minor penalty on performance)
- `freeze` :: freezing layers reduces GPU memory usage if all layers of model don't need to be trained (transfer learning)
- `amp` :: depending on the device, it may need to be disabled (GTX-16 series GPUs have an issue with using AMP)

**Comment by kalenmike** [comment]
@Burhan-Q We aim to keep the HUB interface simple and for that reason restricted some options. We will add in these three and perhaps a text based override. Coming soon we have the option to create a model from the CLI which will give you access to all the training arguments.
