### ISSUE TITLE
Sign on

### ISSUE THREAD

**Issue by Hypermechanic** [ultralytics/hub#48]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I would like biometrics enable to sign in. Thank you.
I use an IPad Pro, Linux Ubuntu, kali, window all.
But I am sick and I am just going to suffer a long incurable tortures life. So the less I have to navigate to get to my distractions from my continuous walk hell of nonstop total body pain the better. Yours suffering and really grumpy.

### Additional

Apple facial, android finger print and the recent build has facial recognition.

**Comment by stefani-kovachevska** [comment]
Thank you for reaching out @Hypermechanic. I can see how having to go through multiple steps to log in can be a real pain. 

At the moment we are focused on building better training capabilities as we believe this will bring the most value to our users. 
We strive to provide the best user experience possible and we appreciate your feedback. We'll have more time to look into this further in some of the next releases. 

In the meantime, you can still log in with your Apple, Google, and GitHub accounts. 

Best, 
Stefani

**Comment by glenn-jocher** [comment]
@stefani-kovachevska you should have Triage access now as part of the Internal team. Let me know if you have any issues closing this issue.
