### ISSUE TITLE
Using private Trained Model on Android Mobile

### ISSUE THREAD

**Issue by Shyamcme** [ultralytics/hub#489]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I want to test my private model using my own android mobile. I have clicked on the export button, but in mobile it displays as 0% only. Anything i am missing out ?

**Comment by kalenmike** [comment]
@Shyamcme It sounds like you have encountered a bug. Can you provide me the model id that you see in the URL on web? I will then see if I can see what has gone wrong.

**Comment by Shyamcme** [comment]
<img width="953" alt="Screenshot 2023-12-12 223456" src="https://github.com/ultralytics/hub/assets/144660698/63c0aad6-1cd9-4250-975a-0b968b515e93">

![WhatsApp Image 2023-12-12 at 22 35 20](https://github.com/ultralytics/hub/assets/144660698/bc3aba76-087b-42d5-ad57-59fa8d668013)

![WhatsApp Image 2023-12-12 at 22 35 19 (2)](https://github.com/ultralytics/hub/assets/144660698/51e5aa1d-6b39-4c46-8c70-7c532e07cb9e)

![WhatsApp Image 2023-12-12 at 22 35 19 (1)](https://github.com/ultralytics/hub/assets/144660698/56f836fd-1865-4ad1-baef-0efffd4e070a)

![WhatsApp Image 2023-12-12 at 22 35 19](https://github.com/ultralytics/hub/assets/144660698/a76f2e65-baa9-449e-a50c-9939cc18ae53)

**Comment by UltralyticsAssistant** [comment]
Thank you for providing the screenshots and additional information, @Shyamcme! It's quite helpful. From what you've described, it indeed seems like the download is not proceeding as expected on your mobile device.

To assist you better with this, could you please provide the specific model ID or the URL (not the image or link) from the web where you're trying to export the model? This ID is typically found in your web browser's address bar when you view your model on the Ultralytics HUB.

With that information, I can look into the issue more deeply and aim to provide a resolution. In the meantime, you might want to check your mobile network connection, ensure that no VPN or firewall is blocking the download, and that there's sufficient storage space on your device.

If these basic checks don't resolve the problem, please provide the model ID, and I'll take the next steps to troubleshoot the issue for you. Thanks for your patience! 😊

**Comment by Shyamcme** [comment]
The URL link for the model is https://hub.ultralytics.com/models/O9DgTPFMceDLuddRBovm

Hope this will help

Regards

**Comment by UltralyticsAssistant** [comment]
Thank you for providing the model ID, @Shyamcme. I'll investigate this issue with the given model (O9DgTPFMceDLuddRBovm) and see what might be causing the download interruption on your mobile device.

It's also useful to know that you see the export as completed for different formats, but are missing the "Ultralytics Android" option on the HUB web version. I'll look into the discrepancy between the web and mobile app interfaces regarding export options as well.

Your diligence in providing these details is much appreciated! I'll work on resolving this as soon as possible so you can proceed with using your trained model on your Android device. Please bear with us while we troubleshoot. 🛠️

In the meantime, if you have any more information that might assist us in this process, feel free to add it. Your cooperation is invaluable. 🌟

**Comment by Shyamcme** [comment]
Kalen... Great to see you in the livestream held tonight on YOLOV8.1  and thanks for the solution to my bug ... Cheers

**Comment by kalenmike** [comment]
@Shyamcme Thanks for joining the livestream. In HUB Web you can see the app export in the preview tab:

https://hub.ultralytics.com/models/O9DgTPFMceDLuddRBovm?tab=preview

It looks like your model has been exported but is failing to download to the app. We are busy testing a new release of the app that should be released soon, it makes some changes to the android export. Once it is released you should be able to export again and download the model.

We hope to have this new version out tomorrow.

**Comment by RGBreinin** [comment]
I am having a similar issue with model : 1omqas0480ijGUwyoYzx
I was able to export it to both android and IOS apps, however upon using the Android app, the model fails to download at all; and simply loops with "downloading the model".

Using the IOS app, it downloaded successfully, but the preview does not identify anything (the preview within hub does however work as expected)

**Comment by UltralyticsAssistant** [comment]
@RGBreinin i'm sorry to hear you're experiencing issues with your model (1omqas0480ijGUwyoYzx) on the Android app. It seems like there might be a problem with the download process within the app itself. As mentioned earlier, we are aware of some issues and are working on an update that should address these problems.

For the iOS app, if the model has downloaded but isn't identifying objects as expected, it could be related to the model's performance on the device or a compatibility issue. It's good to hear that the preview within the HUB works, which suggests that the model itself is functional.

Please keep an eye out for the upcoming app release, which should improve the export and download functionality. Once the new version is available, please try exporting and downloading your model again.

If you continue to face issues after the update, don't hesitate to reach out, and we'll be happy to assist further. Thank you for your patience and understanding. 🙏

**Comment by sergiossm** [comment]
Hey @RGBreinin is this still happening in the latest Android version of the app (0.9.24)?
