### ISSUE TITLE
Can't access a data when using Ultralytic and Roboflow 

### ISSUE THREAD

**Issue by nagorntow** [ultralytics/hub#492]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I upload a dataset on roboflow then using integration feature to access data on ultralytic but Colab can't download a dataset
![Screenshot 2566-12-11 at 23 34 33](https://github.com/ultralytics/hub/assets/24240177/7dbf7a01-e346-4fd8-8cbc-e32afb94c67d)
![Screenshot 2566-12-11 at 23 38 06](https://github.com/ultralytics/hub/assets/24240177/572c5db0-ad8b-4ed3-8c96-7776fac06a1b)

**Comment by kalenmike** [comment]
@nagorntow Thanks for raising this. It seems like the Roboflow export did not complete for your dataset. This may be due to a delay in the process and it could start working after a a few minutes. Can you try again after 10 minutes and let us know if you are still seeing the same error message?

**Comment by nagorntow** [comment]
Yes, I seeing the same message error.

**Comment by UltralyticsAssistant** [comment]
@nagorntow i'm sorry to hear that the issue persists. Since this involves an integration feature with Roboflow, it may be due to a temporary issue with their service, an incorrect URL, or an access permission problem. Please ensure that:

1. Your Roboflow account has the correct permissions for exporting datasets.
2. You're using the correct and complete export URL from Roboflow.
3. There are no outages or issues on Roboflow's side that might affect dataset export functionality.

If after checking these points the problem remains, I would recommend reaching out to Roboflow support to ensure there isn't an issue on their end that's preventing the export. 

For detailed instructions on how to integrate with Roboflow, please refer to our Ultralytics HUB Docs. If you keep experiencing difficulties, feel free to provide more details, and we will do our best to assist you further! 🙌

**Comment by wizkitglobal-create** [comment]
Hi, I'm facing the same issue. Can't go around it in anyway! 

Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/v9VD3nAIkSxMUzjIS1IC 🚀
Ultralytics YOLOv8.1.0 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8x.pt, data=https://storage.googleapis.com/ultralytics-hub.appspot.com/ROBOFLOW_INTEGRATION, epochs=100, time=None, patience=100, batch=-1, imgsz=640, save=True, save_period=-1, cache=ram, device=0, workers=8, project=None, name=train9, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train9
Found https://storage.googleapis.com/ultralytics-hub.appspot.com/ROBOFLOW_INTEGRATION locally at ROBOFLOW_INTEGRATION
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    132             elif self.args.data.split(".")[-1] in ("yaml", "yml") or self.args.task in ("detect", "segment", "pose"):
--> 133                 self.data = check_det_dataset(self.args.data)
    134                 if "yaml_file" in self.data:

4 frames
AssertionError: Attempting to load non-YAML file ROBOFLOW_INTEGRATION with yaml_load()

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    135                     self.args.data = self.data["yaml_file"]  # for validating 'yolo train data=url.zip' usage
    136         except Exception as e:
--> 137             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    138 
    139         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'https://storage.googleapis.com/ultralytics-hub.appspot.com/ROBOFLOW_INTEGRATION' error ❌ Attempting to load non-YAML file ROBOFLOW_INTEGRATION with yaml_load()

**Comment by kalenmike** [comment]
@wizkitglobal-create This means that you Roboflow dataset has not been exported into the YOLO format. This should happen automatically when you create a model. There is sometimes a delay in the update, we will look into this and see if there is a bug on the HUB or Roboflow side.
