### ISSUE TITLE
When will the pose feature be available on iOS Ultralytics App?

### ISSUE THREAD

**Issue by naruto553** [ultralytics/hub#499]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is there any planned date to release pose feature on iOS Ultralytics App? 

![Coming_soon](https://github.com/ultralytics/hub/assets/135929161/22aaa19d-8c6e-44b7-916c-327f34afdd6d)

**Comment by UltralyticsAssistant** [comment]
@naruto553 hello! Thanks for reaching out with your question about the pose feature for the iOS Ultralytics App. We're constantly working on improving our app and adding new features. However, we don't have a specific release date for the pose feature at this time. Keep an eye on the updates—we’ll make sure to announce new features as they become available! Also, don't hesitate to check our documentation for any news and updates about upcoming features. Your patience and support for the Ultralytics community are greatly appreciated! 😊

**Comment by naruto553** [comment]
@UltralyticsAssistant Thank you for your reply! Looking forward to seeing your release soon!!

**Comment by UltralyticsAssistant** [comment]
You're welcome, @naruto553! We're thrilled to hear about your enthusiasm. Thanks for your support, and we're just as excited to bring new features to you. Stay tuned! 😄🚀
