### ISSUE TITLE
Account recovery

### ISSUE THREAD

**Issue by Muhammad-Asad-Ferozi** [ultralytics/hub#506]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

I think i accendently deleted my account, i done my uni project on it. i access the my account on my friends mobile phone, i think that instead of sign out my account from his device he deleted it, Kindly can u recover my account, there is evaluation of my project on monday 25 dec 2023.
i will be a great favour.

### Environment

Ultralytics HUB Version
v0.1.31
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
1600 x 739
Server Timestamp
1703404425

### Minimal Reproducible Example

email 
maferozi373@gmail.com

i singed in directly with google account.

### Additional

please do recovery

**Comment by kalenmike** [comment]
@Muhammad-Asad-Ferozi Your account has been restored.

**Comment by Muhammad-Asad-Ferozi** [comment]
thanks

**Comment by UltralyticsAssistant** [comment]
@Muhammad-Asad-Ferozi you're welcome! If you need further assistance or have any more questions, feel free to reach out. Good luck with the evaluation of your project! 😊
