### ISSUE TITLE
Custom model for testing

### ISSUE THREAD

**Issue by Satyajit1993** [ultralytics/hub#509]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I trained my model already. Can I upload the weight (best. pt) file and the class (class. yaml) file to the hub to do only testing tasks with different versions of YOLO?

**Comment by UltralyticsAssistant** [comment]
@Satyajit1993 hello there! 😊

Certainly, after training your model, you can upload your custom weights (best.pt) and class (class.yaml) file to the Ultralytics HUB to run tests using different versions of YOLO. The HUB is designed to make it straightforward to apply your models to various tasks.

Just make sure that your files adhere to the HUB's requirements for uploads. You can find the specific instructions and guidelines on how to do this in the Ultralytics HUB Docs.

Good luck with your testing, and if you have any more questions or need further assistance, don't hesitate to ask! Happy testing! 🚀
