### ISSUE TITLE
Mixing a datasets and classes

### ISSUE THREAD

**Issue by swhgithubcom** [ultralytics/hub#510]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Building a model using a few selected datasets would be a very good feature.
For example, when we start creating a model, we have the opportunity to choose "**Argoverse**", "**coco2017**" and "**custom**" datasets and then train model. 
Mixing classes from datasets would be even better.

### Use case

Will help everyone achieve results much faster and more flexibly.

**Comment by kalenmike** [comment]
@swhgithubcom Thanks for sending this. This has been a feature we have had on our minds for some time and we are very interested in implementing this. Hopefully it is something we can tackle soon.

**Comment by swhgithubcom** [comment]
We follow all your developments with excitement and impatience.
Thank you to your entire team,
I wish you a happy new year and wish you health, happiness and success.

**Comment by UltralyticsAssistant** [comment]
@swhgithubcom your support and enthusiasm for our efforts are truly appreciated! 🌟 It's the involvement of community members like yourself that motivates us. Wishing you, too, a year filled with health, happiness, and success. Happy New Year! 🎉🎊
