### ISSUE TITLE
Can HUB be Configured  on IOS to ONLY Display the Label and Probability (no buttons, no FPS, no time in ms)?

### ISSUE THREAD

**Issue by dbl001** [ultralytics/hub#514]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I want to use YOLO Hub with IOS Accessibility Screen-to-Text.  I’d like to reduce what’s being displayed to only the detected object and probability.

### Additional

This is for a sight-less person.

**Comment by UltralyticsAssistant** [comment]
@dbl001 hello! Thank you for reaching out with your question. 🌟

Yes, the Ultralytics HUB can be configured to simplify the display output to show only the label and probability. You can adjust the settings in the app to disable any additional overlays such as buttons, FPS, and time in ms, to cater to the needs of a sight-less person using iOS Accessibility features.

For detailed instructions on how to adjust these settings, please refer to the Ultralytics HUB documentation. If you require further assistance or have any more questions, feel free to ask. We're here to help!

Best wishes on your project, and it's wonderful to hear that our technology is being used to assist those with visual impairments. 😊

**Comment by dbl001** [comment]
I don’t see any ’setting’s options in the IOS app.  Did I miss something? Or, do I have to build a custom IOS app with ONLY the Ultralytics HUB features I need displayed?

**Comment by UltralyticsAssistant** [comment]
Apologies for any confusion, @dbl001. If there are no direct settings options available within the iOS app to customize the display, it would indeed require building a custom iOS app with the specific features you need displayed.

The Ultralytics HUB is designed to be flexible, and the source code can be modified to suit such specific use cases. You would need to adjust the code responsible for the UI elements to ensure that only the label and probability are displayed during detections.

If you're comfortable with iOS app development, you can clone the repository and make the necessary adjustments. If you need further guidance on which parts of the code to modify, please refer to the documentation or ask specific questions in the repository's issues section, and we'll do our best to assist you.

Thank you for your understanding, and we appreciate your efforts to make the app more accessible! 😊
