### ISSUE TITLE
Training in progress. Checkpoint saved for epoch Bug

### ISSUE THREAD

**Issue by swhgithubcom** [ultralytics/hub#517]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

![first_2](https://github.com/ultralytics/hub/assets/114502060/f9866246-2fe7-4525-97ba-974be3513452)
![first_1](https://github.com/ultralytics/hub/assets/114502060/f795c72b-373f-4496-91b0-6c3ad1b4e16d)

Greetings to everyone,
I started the new "Train" on my local computer and it's still running,
Even though I have Epoch 93, the graph shows only 1% completion. 
When a new epoch is completed, it displays the correct numbers for a few seconds and returns to its previous state.

**Comment by UltralyticsAssistant** [comment]
@swhgithubcom hello! Thank you for reporting this issue with the training progress visualization. It seems like there might be a bug with the updating mechanism of the progress graph. The temporary correct display after each epoch suggests that the data is being recorded correctly, but the persistent display is not reflecting these updates as it should.

Could you please check the console logs for any errors or warnings that occur when the graph reverts to the incorrect state? Also, ensure that your local setup meets all the necessary requirements and that there are no interruptions in the training process that might affect the graph's state.

If the issue persists, you can document it with the exact steps you followed, any relevant configurations, and the observed behavior, then submit it as a new issue on the HUB repo. Our team will look into it and work on a fix. In the meantime, you can track your progress through the epoch numbers and other metrics that are correctly displayed.

For further guidance, please refer to the Ultralytics HUB Docs. Your contributions to improving the HUB are greatly appreciated! 🌟

**Comment by kalenmike** [comment]
@swhgithubcom Thanks for raising this, can you share the Environment Details that are present on the support page?

**Comment by UltralyticsAssistant** [comment]
Hello @swhgithubcom, I'm sorry to hear about the trouble you've encountered. It sounds like there may be an issue with the storage not updating correctly after you've deleted a training session. This could be a caching issue or a delay in the system's synchronization of storage status.

For now, please ensure that all associated data from the previous training session is indeed deleted and that there are no hidden files consuming the storage. If the problem persists and your storage still shows as overutilized, you might want to report this as a new issue with detailed steps of what you did and the unexpected behavior you're observing.

We appreciate your patience and cooperation as we work to resolve these issues. Your efforts help us improve the HUB for everyone. 🛠️ If you need further assistance, don't hesitate to reach out.
