### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by volome** [ultralytics/hub#524]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

If I train a model and need to convert it to say TFlite and use it on my embedded hardware that has no internet connection and just my own app. Can I do that and is that an extra cost.

### Additional

This is not very clear in your movie, you always refer using our app.

**Comment by UltralyticsAssistant** [comment]
@volome hello!

Thank you for reaching out with your question. Yes, you can train a model and convert it to TFLite for use on your embedded hardware without an internet connection. There is no extra cost associated with converting your model to TFLite and deploying it on your hardware for offline use. The AGPL-3.0 license allows for such use cases, provided you comply with the terms of the license.

For detailed guidance on the conversion process, please refer to the Ultralytics HUB Docs. If you have any further questions or need assistance, feel free to ask. We're here to help!

**Comment by volome** [comment]
Thank you for your response!

Super very helpful

**Comment by UltralyticsAssistant** [comment]
You're very welcome, @volome! I'm glad I could assist you. 😊 If you have any more questions in the future or need further support, don't hesitate to reach out. Good luck with your project, and have a great time working with your model on your embedded hardware!
