### ISSUE TITLE
No puedo acceder a mis modelos desde la App Android

### ISSUE THREAD

**Issue by saulacunha** [ultralytics/hub#535]
### Search before asking

- [ ] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Export

### Bug

No puedo acceder a mis modelos desde la app de android, no me lista los modelos, tampoco me lista mis datasets. 
 
![image](https://github.com/ultralytics/hub/assets/18223198/46308039-9c8d-4361-940c-a0e1fe6212e7)
Intento descargar el modelo pero genera errores.
<img width="1213" alt="image" src="https://github.com/ultralytics/hub/assets/18223198/562218c0-b49c-4fb7-bb53-d3c333c561d7">

**Comment by saulacunha** [comment]
He encontrado un problema similar, cierro el issues.

**Comment by UltralyticsAssistant** [comment]
@saulacunha ¡Genial que hayas encontrado una solución! Si tienes más preguntas o necesitas ayuda adicional, no dudes en abrir un nuevo issue. Estamos aquí para ayudarte. ¡Feliz codificación! 😊👍

**Comment by saulacunha** [comment]
No he encontrado una solución, he escrito debajo de la persona que lo ha reportado anteriormente para no duplicarlo, he hecho han sugerido pero aún así persiste el problema.

**Comment by UltralyticsAssistant** [comment]
Lamento escuchar que el problema persiste, @saulacunha. Para poder ayudarte mejor, te recomendaría que sigas estos pasos:

1. Asegúrate de que tu aplicación Android esté actualizada a la última versión.
2. Verifica que estás iniciando sesión con las credenciales correctas y que tienes acceso a internet estable.
3. Intenta cerrar sesión en la aplicación y vuelve a iniciarla.

Si después de seguir estos pasos el problema continúa, por favor, abre un nuevo issue con todos los detalles, incluyendo los pasos que has seguido y cualquier mensaje de error que la aplicación te muestre. Esto nos ayudará a diagnosticar y resolver el problema más eficientemente.

Gracias por tu paciencia y por formar parte de la comunidad de Ultralytics. 🌟
