### ISSUE TITLE
This account is currently being deleted"

### ISSUE THREAD

**Issue by Alexeykutyrev** [ultralytics/hub#538]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! An error occurs when logging into my google account: This account is currently being deleted. Please restore my account: alexeykutyrev@gmail.com

**Comment by kalenmike** [comment]
@Alexeykutyrev Your account has been restored.
