### ISSUE TITLE
This account is currently being deleted

### ISSUE THREAD

**Issue by Alexeykutyrev** [ultralytics/hub#539]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Hello! An error occurs when logging into my google account: This account is currently being deleted. Please restore my account: alexeykutyrev@gmail.com

**Comment by pderrenger** [comment]
Hello! Thanks for reaching out. I’m sorry to hear you’re experiencing this issue. 🙁

For privacy and security reasons, we can't handle account restoration requests directly through GitHub issues. Could I please direct you to visit our official support channel? You'll find the contact form in our documentation here: https://docs.ultralytics.com/hub. They'll be able to look into your account details securely and provide the appropriate assistance.

Thank you for your understanding, and we hope to get this resolved for you soon!
