### ISSUE TITLE
Linear Regression Head

### ISSUE THREAD

**Issue by clindhorst2** [ultralytics/hub#54]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Easy to make linear regression head and object detection head. A way to find an object in a picture and give you a linear regression model about the characteristics of that model. 

### Use case

If you want to find a rose and how many days until it is fully bloomed would be a great example.

**Comment by glenn-jocher** [comment]
@clindhorst2 thanks for the feature request. Architecture updates for additional regression outputs (in addition to the existing 4 box regression outputs) are very easy to create of course. The difficulty is in balancing additional losses and measuring metrics in addition to standardizing dataset formats for custom outputs.

**Comment by clindhorst2** [comment]
@glenn-jocher thanks for responding do you have any documentation on how to do that on YOLO v5? I am not an AI scientist I just learned this terminology from reading posts about creating a CNN with linear regression. I'm not asking you to do it for me I just have no idea where to start in YOLO v5.  The reason I chose YOLO v5 was that in a video you had you said that Ultralytics is making machine learning capabilities for everyone.

**Comment by glenn-jocher** [comment]
@clindhorst2 yes we are trying! It's a big task though, and we have to start somewhere, so we are starting with Detection, then moving to Classification and next Segmentation. These two will be ready in second half of this year, and additional tasks like regression later on. It's super helpful to hear community feedback though on what users want so I will keep this in mind when planning our roadmap!

<img width="1070" alt="Screen Shot 2022-07-08 at 9 51 54 PM" src="https://user-images.githubusercontent.com/26833433/178061134-07e3c9f5-4b31-4b4e-9aaa-cba9be125479.png">

**Comment by clindhorst2** [comment]
@glenn-jocher in the not-to-distant future will you be able to perform linear regression during Instance Segmentation?

**Comment by glenn-jocher** [comment]
@clindhorst2 well linear regression just means that you are fitting a continuous value rather than a discrete value (i.e. classification).

**Comment by clindhorst2** [comment]
@glenn-jocher Yes, I am aware of that. Did I use terminology that was incorrect? I think you are misunderstanding what I am trying to do.  I am trying to find fruit on a table (object detection) and be able to predict the sweetness on a scale of 1-10 (linear regression) from the image.
