### ISSUE TITLE
Apple M3 Support

### ISSUE THREAD

**Issue by ice6** [ultralytics/hub#541]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I am using a M3 Macbook to do the training.

It seems that when I run the train code copy from `Ultralytics HUB`, it can not run with GPU option selected, if I select CPU then the train runs in a terrible slow manner :)

I think it just use `cpu`, not the `mps`.

**Comment by UltralyticsAssistant** [comment]
@ice6 hello! Thank you for reaching out with your inquiry about Apple M3 support. 🍏

As of my last update, the Ultralytics HUB is designed to work with a variety of hardware configurations, but specific support for Apple's M3 chips and the Metal Performance Shaders (MPS) may not be fully integrated or optimized yet.

Training on the CPU, as you've noticed, can indeed be significantly slower compared to using a GPU or MPS acceleration. We understand the importance of efficient training and are continually working to improve compatibility and performance across different platforms.

For the most up-to-date information on hardware support and to get the best possible performance tips for your current setup, I recommend checking out the Ultralytics HUB Docs. There, you'll find guidance on setting up your environment and optimizing your training process.

If you have any further questions or if there's anything else we can assist you with, please let us know. Your feedback is valuable as we strive to enhance the HUB for all users. Happy training! 😊

**Comment by RaulArtigues** [comment]
Hello,

I have the same problem. I want to do a Yolo V8 training using the Ultralytics library and it gives me an MPS incompatibility on my MacBook Pro M3. It should be noted that I want to use the computer's GPU and NOT THE CPU. How can I solve it?

Thank you so much

**Comment by UltralyticsAssistant** [comment]
@RaulArtigues hello!

I'm sorry to hear you're encountering MPS incompatibility issues on your MacBook Pro M3. As of now, our team is continuously working on enhancing support for various hardware, including the latest Apple chips.

For YOLOv8 training using the Ultralytics library to utilize the GPU on M3 MacBooks, verifying that your environment is set up correctly for MPS is a great first step. Apple's recent hardware requires specific configurations, and our documentation is a fantastic resource for ensuring you have all necessary dependencies and settings.

However, if direct support seems limited, one workaround is to use Docker or another virtualization tool that provides better control over hardware access. This approach can sometimes offer a more standardized environment, enabling better compatibility with certain libraries and tools.

We're committed to improving the user experience and compatibility. Keep an eye on our updates for any enhancements related to Apple's MPS. If there’s anything more we can assist you with or any further feedback you have, please feel free to share. Thanks for your patience and support!

**Comment by sergiuwaxmann** [comment]
Hello! First of all, sorry for the late reply.

@ice6 
We recently added the MPS option in [Ultralytics HUB](https://hub.ultralytics.com).
This option is available in the Advanced Model Configuration (see image below).
![hub_model_device_mps](https://github.com/ultralytics/hub/assets/47978446/9a6899fa-e030-4d20-8982-a2fc051fedfb)

@RaulArtigues 
Please check the [ultralytics](https://github.com/ultralytics/ultralytics) available [Train Settings](https://docs.ultralytics.com/modes/train/#train-settings).
You can use `device="mps"`.
