### ISSUE TITLE
Cannot see model on android app

### ISSUE THREAD

**Issue by Fabrizio1990** [ultralytics/hub#544]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

Hi,
I am trying to use my fine tuned model, i want to test it with android app but each time i click Ultralytics hub android button it load for quite time and then fail.  inference on preview tab on website is working correctly so i don't understand why it cannot be show in the app.
thank's in advance and greetings for the great job you are doing.
Base model: **YOLOv8m**

### Environment

Env details:
Ultralytics HUB Version
v0.1.33
Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Operating System
MacIntel
Browser Window Size
1920 x 881
Server Timestamp
1705667515

### Minimal Reproducible Example

-fine tune a model
-on preview page click to "Ultralytics hub android" button under "Real-Time Preview" section

**Comment by Fabrizio1990** [comment]
clicking on export button "Ultralytics HUB iOS" seems had do something, i can see the package size.. but cannot test because i don't have ios

**Comment by Fabrizio1990** [comment]
cannot see model also on ios. also if it is correctly exported
![WhatsApp Image 2024-01-19 at 14 07 25](https://github.com/ultralytics/hub/assets/17012826/cbdcd2be-d711-4481-baa9-1766d6dbc04b)
![WhatsApp Image 2024-01-19 at 14 07 26 (1)](https://github.com/ultralytics/hub/assets/17012826/b43c7445-d200-4af2-931b-d3f76b53fe65)
![WhatsApp Image 2024-01-19 at 14 07 26](https://github.com/ultralytics/hub/assets/17012826/fad4e65b-abe4-4a59-90eb-e8554dec793e)

**Comment by UltralyticsAssistant** [comment]
@Fabrizio1990 hello! Thank you for reaching out and for your kind words. 🌟

I'm sorry to hear you're experiencing issues with viewing your model on the Android and iOS apps. It seems like there might be a problem with the app integration or the export process. Here's what you can try:

1. Ensure that you have the latest version of the Ultralytics HUB app installed on your device.
2. Check if there are any updates or maintenance notices for the HUB that could affect the app functionality.
3. Verify that your exported model is compatible with the app. Some models may have specific requirements or limitations.
4. If the issue persists, consider submitting a detailed bug report through the HUB's issue tracker, including any error messages or logs that could help diagnose the problem.

For further guidance, you can refer to the Ultralytics HUB Docs, which may have additional troubleshooting steps or information on app compatibility and export procedures.

We appreciate your patience and are here to help you get back on track with your model testing! 🛠️
