### ISSUE TITLE
error ❌ Attempting to load non-YAML file ROBOFLOW_INTEGRATION with yaml_load()

### ISSUE THREAD

**Issue by cooperkenda** [ultralytics/hub#547]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Ultralytics HUB: New authentication successful ✅
Ultralytics HUB: View model at https://hub.ultralytics.com/models/SJENqBNf9LQlvWhrXD8Q 🚀
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/yolov8n.pt to 'yolov8n.pt'...
100%|██████████| 6.23M/6.23M [00:00<00:00, 93.5MB/s]
Ultralytics YOLOv8.1.5 🚀 Python-3.10.12 torch-2.1.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
engine/trainer: task=detect, mode=train, model=yolov8n.pt, data=https://storage.googleapis.com/ultralytics-hub.appspot.com/ROBOFLOW_INTEGRATION, epochs=100, time=None, patience=100, batch=-1, imgsz=640, save=True, save_period=-1, cache=ram, device=0, workers=8, project=None, name=train, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=True, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs/detect/train
Downloading https://storage.googleapis.com/ultralytics-hub.appspot.com/ROBOFLOW_INTEGRATION to 'ROBOFLOW_INTEGRATION'...
⚠️ Download failure, retrying 1/3 https://storage.googleapis.com/ultralytics-hub.appspot.com/ROBOFLOW_INTEGRATION?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=firebase-adminsdk-jsjt9%40ultralytics-hub.iam.gserviceaccount.com%2F20240125%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20240125T192124Z&X-Goog-Expires=900&X-Goog-SignedHeaders=host&X-Goog-Signature=577b2cda04d6d79650a273d729f1e3ecb9e3ef6bc1fccb3cb7f86119ca0e0acee3d1785e799ec12b38fd9f8837726bc6f4ca5061dc89094844dc69fcc44611270c343faf1fbc8d5ba30629adb3a15c40745c5d7b5560661a8a2fd42aaf2fa8026e0109d0ac43290abd52165372decdb810ce7a73da3e13a714d892e39e148cb1bc76f618cd8f158eb64f32b3cbc493cb075f6339abcd1a58b9f062f2778236bacb8f9b4288116229815b22b33765b89e68786f582f5a54ad06883f35e2d003188dd1ea12f1535b958ea19a3792ffdf6365b64a79586e6093ad776c49d9773af0c5f0c049702c8d97ca6e97653d1b255182a4a4c463ecacbf33525fb89522e45d...
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    132             elif self.args.data.split(".")[-1] in ("yaml", "yml") or self.args.task in ("detect", "segment", "pose"):
--> 133                 self.data = check_det_dataset(self.args.data)
    134                 if "yaml_file" in self.data:

4 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py](https://localhost:8080/#) in check_det_dataset(dataset, autodownload)
    276     # Read YAML
--> 277     data = yaml_load(file, append_filename=True)  # dictionary
    278 

[/usr/local/lib/python3.10/dist-packages/ultralytics/utils/__init__.py](https://localhost:8080/#) in yaml_load(file, append_filename)
    356     """
--> 357     assert Path(file).suffix in (".yaml", ".yml"), f"Attempting to load non-YAML file {file} with yaml_load()"
    358     with open(file, errors="ignore", encoding="utf-8") as f:

AssertionError: Attempting to load non-YAML file ROBOFLOW_INTEGRATION with yaml_load()

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
[<ipython-input-3-f14229fab7d8>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 model = YOLO('https://hub.ultralytics.com/models/SJENqBNf9LQlvWhrXD8Q')
----> 4 results = model.train()

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in train(self, trainer, **kwargs)
    370             args["resume"] = self.ckpt_path
    371 
--> 372         self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
    373         if not args.get("resume"):  # manually set model only if not resuming
    374             self.trainer.model = self.trainer.get_model(weights=self.model if self.ckpt else None, cfg=self.model.yaml)

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in __init__(self, cfg, overrides, _callbacks)
    135                     self.args.data = self.data["yaml_file"]  # for validating 'yolo train data=url.zip' usage
    136         except Exception as e:
--> 137             raise RuntimeError(emojis(f"Dataset '{clean_url(self.args.data)}' error ❌ {e}")) from e
    138 
    139         self.trainset, self.testset = self.get_dataset(self.data)

RuntimeError: Dataset 'https://storage.googleapis.com/ultralytics-hub.appspot.com/ROBOFLOW_INTEGRATION' error ❌ Attempting to load non-YAML file ROBOFLOW_INTEGRATION with yaml_load()

### Environment

Google Colab

**Comment by UltralyticsAssistant** [comment]
@cooperkenda hello! It looks like there's an issue with the dataset path or format you're trying to use. The error message indicates that the trainer is expecting a YAML file for the dataset configuration, but it received a path or file name that doesn't end with `.yaml` or `.yml`.

Please ensure that the dataset path you provide points to a valid YAML file that contains the dataset configuration. If you're trying to use a dataset from Roboflow, make sure you've correctly downloaded and referenced the YAML file that describes your dataset.

For more detailed instructions on how to set up your dataset correctly, please refer to the Ultralytics HUB Docs. If you continue to face issues, feel free to provide more details about the steps you've taken, and we'll be happy to help you troubleshoot further. 😊
