### ISSUE TITLE
Dataset Processing failed

### ISSUE THREAD

**Issue by UnkoC0wbOy** [ultralytics/hub#55]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

I am working on a new dataset and tried to upload it to the HUB. The dataset seemed to upload just fine and quickly reached the processing stage. Shortly after beginning the processing stage the progress bar turned red and failed with the text "processing error" appearing below. I'm trying to determine if there is something wrong with my dataset(very possible as I'm new to this) or if the processing error is on the HUB's end. Any guidance would be greatly appreciated! I have attached the screenshot as well as my zipped dataset file below. 
![Image 7-8-22 at 9 51 PM](https://user-images.githubusercontent.com/89663444/178090899-a1fef18b-aec0-4d96-9e08-9162a09ed5cc.jpg)
[07.zip](https://github.com/ultralytics/hub/files/9075846/07.zip)
.

### Environment

-Computer: Mac Mini Late 2014. Processor: 2.6 GHz Dual-Core Intel Core i5. Memory: 8GB 1600 MHz DDR3. MacOS: Big Sur. Graphics: Intel Iris 1536 MB

### Minimal Reproducible Example

Uploaded new dataset, let it reach 100%, Processing begins and shortly fails.

### Additional

Keep up the AWESOME work and tools! This technology is helping so many people with various tasks and makes machine learning to the average Joe.

**Comment by barney2074** [comment]
the problem is likely with your YAML file- post that & a snapshot of your data structure

**Comment by kalenmike** [comment]
@UnkoC0wbOy Thanks for taking the time to submit your question. I have reviewed your dataset and I can see that your labels are not in the correct format.

Your labels are formatted:
`159 132 259 132 259 211 159 211 Mule-Deer 0`

The YOLOv5 format for labels is:
`class x_center y_center width height`
* The label file should contain only numbers, the class is the index of your classes array. In your case with only one class the index would be 0.

To be able to upload your custom dataset you will need to change the labels. You can get a more detailed description of how to correctly [format your dataset here ](https://github.com/ultralytics/hub#1-create-a-dataset).
