### ISSUE TITLE
Increase Rate Limit Quota (HTTPError: 429 /v1/predict/<model-id>)

### ISSUE THREAD

**Issue by kamangir** [ultralytics/hub#557]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

I have a PRO account and I have called the API on a yolov8x model `~25,000` times in the past 2.5 months. Recently (in the past two weeks), I have been receiving,

> HTTPError: 429 Client Error: Too Many Requests for url: https://api.ultralytics.com/v1/predict/1xKPEuwRoyDdwL6uamBI

when I call any of the models. example: https://github.com/kamangir/Vancouver-Watching/blob/main/notebooks/ultralytics_original.ipynb

have I hit the limit? how can I increase my quota? 😊

### Environment

`Python 3.9.18`, on [aws batch](https://aws.amazon.com/batch/).

example: https://github.com/kamangir/Vancouver-Watching/blob/main/notebooks/ultralytics_api.ipynb

### Minimal Reproducible Example

try this: https://hub.ultralytics.com/models/R6nMlK6kQjSsQ76MPqQM?tab=deploy

### Additional

<img width="1003" alt="image" src="https://github.com/ultralytics/hub/assets/1007567/8d17128e-38b8-4460-b097-f81288784b49">

**Comment by UltralyticsAssistant** [comment]
@kamangir hello! Thank you for reaching out and for your support as a PRO account user. 😊

The HTTP 429 error indicates that you've exceeded the rate limits for the API. Even with a PRO account, there are still some limitations in place to ensure fair usage and system stability.

To address this issue, you can consider the following steps:
1. Review your current usage patterns and try to distribute your API calls more evenly over time.
2. Implement a backoff strategy in your code to handle 429 errors by waiting for a certain period before retrying the request.
3. If you believe your use case requires a higher quota, you can reach out to the Ultralytics support team to discuss potential account upgrades or custom solutions.

For more detailed information on rate limits and handling best practices, please refer to the Ultralytics HUB Docs.

We appreciate your understanding and are here to help ensure you have the best experience with our services. If you have further questions or need assistance, don't hesitate to ask. Happy coding! 🚀

**Comment by kalenmike** [comment]
@kamangir We do not have any interface at the moment for you to see your current usage in the HUB. We have a plan to implement this. You are able to see your limits in the response header from a request:

> x-ratelimit-limit: Your limit for the active window
> x-ratelimit-remaining: Your remaining requests for the active window
> x-ratelimit-reset: The expiry timestamp for the active window.

The default HUB Pro limits are:
2/second, 1000/hour, 10000/month

It is possible to request an increase, this is currently a manual process. Are you interested in scheduling a call to discuss this further?

**Comment by kamangir** [comment]
@kalenmike 😄 thank you very much for your reply. I need to find another solution. 

here is the longer story: [what I am building](https://github.com/kamangir/Vancouver-Watching) needs `~100k` API calls per month = 10X the current limit -> `$200` / month, doesn't fit in the budget.

I'll try to [deploy the model on sagemaker](https://github.com/aws-samples/host-yolov8-on-sagemaker-endpoint/tree/main), and likely find out that it is going to cost me 10X more, and will be back. 🤣 

for now, closing this task - thank you! ❤️

**Comment by kalenmike** [comment]
@kamangir Thanks for the clarrification. To be clear we do not charge $20 per 10k requests. That is just the fee for the Pro plan, if you are interested in increasing your rate limit we would have a meeting to discuss your requirements and come to an agreement on the price for a custom solution. 

If you only wanted to increase the inference rate limit from 10k to 100k per month the price would definitely be lower than $200 per month.

As you included your model id in your original comment I should be able to find your HUB email. I will send you an email to clarify and we can go from there.
