### ISSUE TITLE
Minor GUI comments on HUB

### ISSUE THREAD

**Issue by barney2074** [ultralytics/hub#56]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Minor comments on HUB GUI (not really a bug)

1. 'Sign Up' button should possibly say 'Sign In' i.e. if you've already got an account
![image](https://user-images.githubusercontent.com/25944617/178098766-8388dba7-0109-4214-802f-9bc51068ef65.png)

2. In the models page- the 'Device' and 'Cache' items don't seem to be correct- I'm certain I used GPU and RAM cache (with a local agent). Without an overload of info, it might be useful to display which method was used (COLAB. local agent etc & how long training took) I haven't used WandB with the agent- but perhaps a link to this ?![image](https://user-images.githubusercontent.com/25944617/178098807-601eb195-8685-499e-b81d-1a6758aedec6.png)

Andrew

**Comment by kalenmike** [comment]
@barney2074 Thanks for the feedback. I will raise this with the rest of the team and we will see what we can do to improve these elements.
