### ISSUE TITLE
Model doesn't dowload in the androind app

### ISSUE THREAD

**Issue by vonzo** [ultralytics/hub#562]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

I trained a model using the sample database of the Simpsons. 
It works quite well when I test it on the desktop version of chrome.
However, in the Ultralitycs app for Android, after logging I can see that the model is available. Still, when I hit the "download" button it doesn't download, even after seeing the "Download the model" message.

![WhatsApp Image 2024-02-06 at 9 57 43 AM](https://github.com/ultralytics/hub/assets/34040775/984fbe7f-ab86-48d7-bb74-e075a7fddd3f)

### Environment

Pixel 6 phone
Android 14

**Comment by UltralyticsAssistant** [comment]
@vonzo hello! Thank you for reporting the issue with downloading the model in the Android app. It's great to hear that your model is working well on the desktop version.

To address the problem with the Android app, could you please try the following steps:
1. Ensure that your Android device has a stable internet connection.
2. Check if there's enough storage space on your device to accommodate the model.
3. Try clearing the app's cache and data from your device's settings and attempt to download the model again.
4. Restart the app and, if necessary, your device, and then try downloading once more.

If the issue persists after these steps, it would be helpful to know if any error messages are displayed or if the download progress bar appears and gets stuck. Please provide this additional information in a follow-up issue report.

For further troubleshooting steps and guidance, you can refer to the Ultralytics HUB Docs. If you continue to experience difficulties, don't hesitate to reach out again. We're here to help! 😊

**Comment by sergiossm** [comment]
Hey @vonzo which version of the Android app are you running? Latest version now is 0.9.24
