### ISSUE TITLE
Images quality on Ultralytics HUB

### ISSUE THREAD

**Issue by davidemerolla** [ultralytics/hub#563]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello. I'm using Ultralytics HUB to train a YOLOv8 for traffic sign detection; when I upload my dataset on the platform, i can notice a reduction in images quality. Does it have an impact on my model's accuracy later on?
Thanks

**Comment by kalenmike** [comment]
@davidemerolla Thanks for asking the question. The images you see in HUB are preview images compressed and reduced to a maximum of 1920x1080. The images that are uploaded still exist in there raw form and the raw images are what we use for training.

In summary, your model trains on the same images that you uploaded only the preview images are compressed.

I hope this answers your question.
