### ISSUE TITLE
Using the app

### ISSUE THREAD

**Issue by feitgemel** [ultralytics/hub#564]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi,
Can you send me a link for a tutorial how can use your app to detect my custom model ?
a link to a documentation or the a  video ?

Thanks 
Eran

**Comment by UltralyticsAssistant** [comment]
@feitgemel hi Eran,

Thank you for reaching out! You can find comprehensive documentation on how to use the Ultralytics HUB for custom models at our official documentation page. Please visit the Ultralytics HUB Docs and look for the section on using custom models. This should provide you with all the necessary steps and guidance.

If you have any further questions after consulting the documentation, feel free to ask here. We're here to help!

**Comment by sergiossm** [comment]
Hey @feitgemel hope [this](https://www.youtube.com/watch?v=lveF9iCMIzc) video helps you. Feel free to to ask if you have any questions after watching it
