### ISSUE TITLE
How to Format Dataset for HUB

### ISSUE THREAD

**Issue by earriagadadiaz** [ultralytics/hub#566]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

hello, I am having trouble uploading my data set
it doesn't recognize the format and it is identically the same as coco8's example.

![Screenshot_1](https://github.com/ultralytics/hub/assets/2879783/a0cecae0-3b6a-4077-aed5-29cda5548585)

### Environment

windows 10
chrome

### Minimal Reproducible Example

![Screenshot_2](https://github.com/ultralytics/hub/assets/2879783/3412b162-25e8-464b-ad88-4df735d1bc92)

**Comment by UltralyticsAssistant** [comment]
@earriagadadiaz hello! Thank you for reaching out with your issue regarding dataset upload.

It seems like there might be a discrepancy between your dataset format and the expected format. To ensure compatibility, please double-check the following:

1. Verify that your dataset structure strictly follows the COCO format guidelines.
2. Ensure that all necessary JSON keys are present and correctly named.
3. Confirm that your image files and annotations are correctly linked in your JSON file.

If after these checks you're still facing issues, it might be helpful to validate your dataset with a COCO dataset validator to catch any potential formatting errors.

For more detailed instructions on preparing and uploading datasets, you can refer to our documentation at the Ultralytics HUB Docs.

If the problem persists, please provide us with the error message you're receiving, and we'll be happy to assist you further. 😊

**Comment by kalenmike** [comment]
@earriagadadiaz Can you share the contents of your `dataset.yaml`, its likely that the paths are not configured correctly there.
