### ISSUE TITLE
Cant Find Model Advanced Options for Training

### ISSUE THREAD

**Issue by ghofranebetta** [ultralytics/hub#567]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I wanted to ask a question about Ultralytics Hub, I wanted to train a model for object recognition, but I can't select the parameters (Batch,Epoch,...), advanced options are not visible for me, why?

**Comment by kalenmike** [comment]
@ghofranebetta We recently moved the advanced options into the second step of the model creation. Can you see them there?

![image](https://github.com/ultralytics/hub/assets/25989362/a822c322-9303-44de-9dfa-7a5a6aa253bb)

**Comment by ghofranebetta** [comment]
![bild](https://github.com/ultralytics/hub/assets/159462212/b7dbd05f-1c3f-4040-98d1-88b48f2eb764)
unfortunately it does not come up when I press there

**Comment by UltralyticsAssistant** [comment]
@ghofranebetta i'm sorry to hear you're experiencing issues with accessing the advanced options. It sounds like there might be a UI glitch or a step that's being overlooked. Here's what you can do:

1. Ensure that you are logged in and have the necessary permissions to access advanced training options.
2. Try refreshing the page or restarting your browser to see if this resolves the issue.
3. Clear your browser cache, as sometimes outdated cache data can cause display issues.
4. If the problem persists, please take a screenshot of what you're seeing and open an issue on the HUB repository detailing the steps you've taken and the problem you're encountering.

Our team will be happy to help you troubleshoot this further. Meanwhile, you can also refer to the Ultralytics HUB Docs for more information on the training process.

**Comment by Burhan-Q** [comment]
@ghofranebetta notice in this screenshot that it shows as `▲ Advanced Model Configuration` instead of `▼ Advanced Model Configuration`
![image](https://github.com/ultralytics/hub/assets/62214284/ef3d1ada-ef4b-4496-b5f4-b4b427b7c49c)

Your screenshot shows the icon as ▼ meaning that the option has not been expanded / opened
