### ISSUE TITLE
Can someone help restore my ultralytics beta account email?

### ISSUE THREAD

**Issue by brandonng126** [ultralytics/hub#568]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I accidentally deleted my account associated with the email bng@scu.edu. I saw that someone restored someone else's account who was in a similar position as me. Could you restore my account associated with that email? Thank you!

**Comment by sergiuwaxmann** [comment]
@brandonng126 Your account has been restored. Sorry for the late reply.
