### ISSUE TITLE
convert the trained yolov8 model to

### ISSUE THREAD

**Issue by Smith-S-S** [ultralytics/hub#573]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

When I am trying to convert the trained yolov8 model to ( !yolo export model="/content/drive/MyDrive/PPE_Detection_YOLOV8/dataset/runs/detect/train/weights/best.pt" format= tfjs)
its only giving this "best_saved_model" but I want "best_web_model" in the tutorial iam following one they run the code they got best_web_model. can you help me with this guys.

best_saved_model: this was I got 
<img width="1121" alt="Screenshot 2024-02-16 at 1 08 15 AM" src="https://github.com/ultralytics/hub/assets/80092760/5bc05109-0dae-4c34-93ac-93aa8a23746e">

best_web_model: They got

<img width="708" alt="Screenshot 2024-02-16 at 1 07 56 AM" src="https://github.com/ultralytics/hub/assets/80092760/df2ee501-6dc3-4030-9832-777bbae40f8f">

<img width="1002" alt="Screenshot 2024-02-16 at 1 06 21 AM" src="https://github.com/ultralytics/hub/assets/80092760/3187d321-12c9-4a04-adf8-897c8bfeba19">

**Comment by Smith-S-S** [comment]
dataset
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="R38i0N5gBDDkzbmApwoO")
project = rf.workspace("aabbcceeffgg").project("brain-tumor-detection-69d9s")
dataset = project.version(2).download("yolov5")

full code:

<img width="1121" alt="Screenshot 2024-02-16 at 1 43 51 AM" src="https://github.com/ultralytics/hub/assets/80092760/ce291da6-7952-49b7-8f40-75154e4b083c">
<img width="1121" alt="Screenshot 2024-02-16 at 1 43 17 AM" src="https://github.com/ultralytics/hub/assets/80092760/8bac9dad-888c-4883-bb38-ce2ddcd3b9f8">
<img width="1121" alt="Screenshot 2024-02-16 at 1 43 08 AM" src="https://github.com/ultralytics/hub/assets/80092760/b2381971-0e02-4509-a325-cf09d4da2866">

**Comment by UltralyticsAssistant** [comment]
@Smith-S-S hello! It seems like you're experiencing an issue with the naming of the exported model when converting a YOLOv8 model to TensorFlow.js format. The naming convention (`best_saved_model` vs `best_web_model`) might differ based on the version of the export tool or the specific command used.

To resolve this, please ensure you're following the latest documentation and using the correct export command as per the Ultralytics HUB Docs. If the issue persists, it could be related to a recent update or change in the export process.

For further assistance, please provide the exact command you're using and any output logs that show the issue. This will help us understand the problem better and guide you accordingly. If there's a discrepancy with the tutorial you're following, it might also be helpful to check if there's an updated version or notes on the naming convention changes.

Remember, the Ultralytics community and the team are here to help, so don't hesitate to reach out if you need more guidance! 😊

**Comment by Smith-S-S** [comment]
Thank you too much guys

**Comment by UltralyticsAssistant** [comment]
@Smith-S-S you're welcome! If you have any more questions or need further assistance in the future, feel free to reach out. Happy to help and wishing you the best with your YOLOv8 projects! 😄🚀
