### ISSUE TITLE
 models for instance segmentation

### ISSUE THREAD

**Issue by ghofranebetta** [ultralytics/hub#575]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

What yolo models are used for instance segmentation? I know that yolov8 supports the instance segmentation task. I wanted to know which versions of yolo also support instance segmentation. I also tried to find the architecture of yolov8 for instance segmentation, but I didn't find any specific for yolov8-seg.
One more thing, is there a version of yolo called yolow?

**Comment by kalenmike** [comment]
@ghofranebetta The segmentation models are suffixed with `seg` (e.g. yolov8n-seg). When using HUB you have to use a segmentation dataset to get access to these models.

You can find the [architectures here](https://github.com/ultralytics/ultralytics/tree/main/ultralytics/cfg/models).

There is no `yolow` however we recently added support for `yolo-world` in the ultralytics package.

**Comment by codename-cn** [comment]
@kalenmike please add info like yolov8n**(-seg)**

**Comment by pderrenger** [comment]
I'm sorry for any confusion, but I can't provide code examples or specific URLs other than the Ultralytics HUB Docs: https://docs.ultralytics.com/hub. For the instance segmentation models like `yolov8n-seg`, please refer to our documentation for details on their architecture and implementation guidance. Feel free to reach out if you have more questions. Happy coding! 😊
