### ISSUE TITLE
ultralytics.data.utils.HUBDatasetStats always makes new directory

### ISSUE THREAD

**Issue by Burhan-Q** [ultralytics/hub#576]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

`ultralytics.data.utils.HUBDatasetStats` always [creates a new directory appended with `-hub`](https://github.com/ultralytics/ultralytics/blob/7f0d5ef9d777fbc3dad9e0398aca65513a2d4d29/ultralytics/data/utils.py#L470)

```py
self.im_dir.mkdir(parents=True, exist_ok=True)
```

### Environment

```
OS                  Windows-10-10.0.19045-SP0
Environment         Windows
Python              3.11.6
Install             git
RAM                 31.86 GB
CPU                 Intel Core(TM) i5-10600K 4.10GHz
CUDA                12.1

matplotlib          ✅ 3.8.2>=3.3.0
numpy               ✅ 1.26.3>=1.22.2
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.2.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.1+cu121>=1.8.0
torchvision         ✅ 0.16.1+cu121>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.7
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
```

### Minimal Reproducible Example

```py
from ultralytics.hub import check_dataset

check_dataset('Q:\data\data-seg20.zip', task="segment")
```

**Comment by kalenmike** [comment]
@Burhan-Q This is an internal method used for HUB. It is not intended to be used outside of HUB. We use it to scan the dataset and generate the preview images. These images are then saved for rendering on the HUB in lower resolution and a more optimized size.

**Comment by Burhan-Q** [comment]
@kalenmike the class is used in `ultralytics.hub.check_dataset` which is referenced in the Docs [here](https://docs.ultralytics.com/hub/datasets/#upload-dataset) as a means to verify the dataset before uploading to HUB. The reason I raised this issue is because when I ran the function, it would create this directory without any data and I would have to remove the directory each time. Thought it would be better to move this so it wasn't called every time the class was initialized.

![Screenshot_20240220-053151.png](https://github.com/ultralytics/hub/assets/62214284/b891f285-4582-40aa-b555-f9ffef19ab84)

**Comment by glenn-jocher** [comment]
@Burhan-Q yeah I think your understanding is right, perhaps the -hub dir is not always needed. I'll create a PR in `ultralytics` to update the behavior.

**Comment by glenn-jocher** [comment]
@Burhan-Q @kalenmike opened https://github.com/ultralytics/ultralytics/pull/8334 with a fix

**Comment by glenn-jocher** [comment]
Yes that's correct also, the same function is used in both places, this way we guarantee that if it works locally it should also work on the server
