### ISSUE TITLE
Does my dataset become public when I upload it?

### ISSUE THREAD

**Issue by saran-invitrace** [ultralytics/hub#578]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Does my dataset become public when I upload it?

**Comment by kalenmike** [comment]
@saran-invitrace Thank you for the question. Currently HUB datasets default to Private. We are looking at limiting the amount of private datasets that are available on the Free plan however currently there is no limit in place other than the total data storage allowed.
