### ISSUE TITLE
Problems with the configuration of my .yaml file

### ISSUE THREAD

**Issue by Geointeligente** [ultralytics/hub#579]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Good morning. To start, thank you for having this space. Since I am new to this topic of loading data sets. I have the necessary information to upload my data set, but I am failing to configure my custom.yaml. Can you guide me on how to write this configuration, knowing that I have a data folder, within data are other folders images and labeling, but when loading the system tells me that the uploaded yaml is not correct. With Gratitude Omar

![yaml_custom](https://github.com/ultralytics/hub/assets/119644776/33f0fc40-c0cc-4e95-b889-a78988ea2061)

### Additional

![images_and_labels](https://github.com/ultralytics/hub/assets/119644776/ec917772-3ace-4610-8fc0-bf1f1ff8e423)
Please be very detailed in the explanation because I am not very knowledgeable in the matter, but I do understand the concept, but it is difficult for me to do what was mentioned above. My email is geomensurainnteligente@gmail.com

**Comment by Geointeligente** [comment]
Thanks for your help @kalenmike. I have pasted the custom.yaml, and it tells me that it is fine. I am trying to create a dataset of house roofs, in which there is only one category, but I don't know what could be wrong, if I have my images with their respective labels.
![yaml Lint](https://github.com/ultralytics/hub/assets/119644776/654bc4e5-2ef7-4103-ae87-e9b72014dc39)
[custom.zip](https://github.com/ultralytics/hub/files/14470870/custom.zip)

**Comment by kalenmike** [comment]
@kalenmike While your YAML is valid syntax, it is not correct for YOLO. Your names key is creating a dictionary that contains an array. 

You can see an [example dataset here](https://github.com/ultralytics/hub/blob/main/example_datasets/coco8/coco8.yaml).

What you need to do is remove the array inside names, it should look like this:

```yaml
names:
    0: techo
```
