### ISSUE TITLE
Mobile app sign in freezes 

### ISSUE THREAD

**Issue by elikling** [ultralytics/hub#58]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

Tried to create a user thought the app (eli_kling@hotmail.com). No error messages just did not progress. Managed to use the Google button to sign in with my g-account. 

### Environment

Android on Samsung s21+

### Minimal Reproducible Example

Install the app
Select create account

**Comment by sergiossm** [comment]
@elikling Thank you for reporting the issue. It's solved now.

**Comment by glenn-jocher** [comment]
@elikling also please let us know if you run into any other issues with the HUB app or website, or if any features come to mind you'd like to see added to the product :)
