### ISSUE TITLE
pay via wire transfer

### ISSUE THREAD

**Issue by lfleon9b** [ultralytics/hub#581]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello !, I am asking if it's possible to pay via wire transfer for an annual subscription, I am part of a public institution in Chile and its administration policy  allows only this kind of payment method, thanks in advance,  Lorenzo Leon

**Comment by lfleon9b** [comment]
Re: Inquiry About Payment via Wire Transfer for Annual Subscription

Dear Ultralytics Team,
Thank you for your prompt and comprehensive response regarding my inquiry into arranging a wire transfer for our annual subscription. It is comforting to know that although standard payment methods are preferred, you are willing to explore alternative solutions to meet specific institutional requirements.
Per your guidance, I will review the contact information in the Ultralytics HUB Documentation to begin the payment process under our institution's policies. Additionally, I would like to seek clarification on the appropriate channel for further inquiries. Specifically, is the commentary box on your website, located at https://docs.ultralytics.com/es/hub/cloud-training/#payments-and-billing-options, the preferred method for submitting such questions? Or would you recommend a more direct form of communication for addressing specific concerns or requests?
Your assistance and flexibility in accommodating our needs are greatly appreciated. I look forward to continuing the subscription and building a productive partnership.
Warmest regards,
Lorenzo

**Comment by UltralyticsAssistant** [comment]
@lfleon9b hello Lorenzo,

I'm glad to hear that you found our response helpful. For further inquiries regarding payment processes, especially those that require specific attention like wire transfers, a more direct form of communication would be preferable. This allows us to provide you with personalized assistance and ensures that your questions and concerns are addressed promptly and accurately.

Please use the direct contact method outlined in the Ultralytics HUB Documentation to reach out to our team. We will then provide you with the necessary details and support to facilitate the wire transfer for your annual subscription.

Thank you for your kind words and for taking the steps to establish a productive partnership with us. We are here to assist you and look forward to a successful collaboration.

Warm
