### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by luisjun1203** [ultralytics/hub#582]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

"I'm a Korean student studying artificial intelligence these days, and while studying YOLO, I've come up with a model I want to create but I'm struggling with implementation. I would appreciate it if you could help me. What I want to do now is extract only the characteristics of the video data when I input video data using YOLO , but I don't know how to do it."

### Additional

Thank you

**Comment by UltralyticsAssistant** [comment]
@luisjun1203 hello! It's great to hear about your interest in artificial intelligence and YOLO. If you're looking to extract features from video data using YOLO, you would typically run the YOLO model on each frame of the video to get the desired outputs, which could include object bounding boxes, class labels, and confidence scores.

To achieve this, you would:
1. Split your video into individual frames.
2. Run the YOLO model on each frame to detect objects.
3. Collect the output data (features) such as the coordinates of bounding boxes, class IDs, and confidence levels.
4. Optionally, you can aggregate or further process these features depending on your specific requirements.

Remember to check the Ultralytics HUB Docs for guidance on using the model and for any specific commands or configurations that might be helpful for your project.

Keep exploring and best of luck with your model! If you have more specific questions as you progress, feel free to reach out. 😊👍
