### ISSUE TITLE
Is there a maximum size for a dataset or a timeout period for uploading one?

### ISSUE THREAD

**Issue by kev0051** [ultralytics/hub#584]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

<img width="642" alt="Screenshot 2024-02-22 at 12 09 50 PM" src="https://github.com/ultralytics/hub/assets/126007369/52032d7b-55ce-4c14-acc1-7328802539ad">

I'm getting this error when trying to upload my dataset. I saw someone had a similar issue but never got a solid answer, so I'm wondering the exact specifics for this problem.

1) What is the maximum size for a dataset that I can upload, if any?
2) What is the period of time I have to upload my dataset before the timeout that may lead to the above error?

Is there a way to rectify this issue? For example, can I upload the dataset in chunks and combine them later? If so, how? I understand that there is an AI that's trying to help users with these issues but its responses haven't been too useful from what I have read so far.

Thanks.

**Comment by kalenmike** [comment]
@kev0051 From the looks of the screenshot the upload is not the problem rather the processing. Something is going wrong when we attempt to validate and process the dataset.

**Comment by kev0051** [comment]
> @kev0051 Our job queue was a little backed up, this has been resolved and all pending work has been processed. Would you please confirm that your dataset is now ready?

Sorry for the late response, looks like everything works now! Thanks!

**Comment by kalenmike** [comment]
Glad to hear it!
