### ISSUE TITLE
Object Counter

### ISSUE THREAD

**Issue by adamekcerv** [ultralytics/hub#59]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Hi,
I would like to use Ultralytics app as real time traffic counter. - I would like to count how many different objects (cars, bicycles, pedestrians,...) cross the street. 

### Use case

This feature should be potentionally use for urban development and smart cities. I would like to measure where is efficient to built a bicycle lanes, other infrastructure etc. - based on the counter.

**Comment by glenn-jocher** [comment]
@adamekcerv 👋 Hello! Thanks for asking about object **tracking** in computer vision. YOLOv5 🚀 is an object **detector** that detect, localizes and classifies objects in a single image. It does not connect objects across multiple images, for this you need a tracking solution. A few possible tracking solutions are:

- [Extended Kalman Filter (EKF)](https://en.wikipedia.org/wiki/Kalman_filter)
- [Kanade-Lukas-Tomasi (KLT) Feature Tracker](https://en.wikipedia.org/wiki/Kanade%E2%80%93Lucas%E2%80%93Tomasi_feature_tracker): 
- [YOLOv5 DeepSort Tracker](https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch) 
- [Apple iOS VNTrackObjectRequest](https://developer.apple.com/documentation/vision/tracking_multiple_objects_or_rectangles_in_video)

Good luck 🍀 and let us know if you have any other questions!
