### ISSUE TITLE
Payment for services in Ultralytics HUB

### ISSUE THREAD

**Issue by lfleon9b** [ultralytics/hub#590]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Dear Ultralytics Hub Team,
I hope this message finds you well. Following our previous discussions regarding subscription options for Instituto de Investigaciones Agropecuarias (INIA)- Chile, I would like to take the next steps to secure an annual subscription through a wire transfer. Given our institution's preference for wire transfers in compliance with our payment policies, I kindly request your assistance with the following:
* 		An Official Invoice for the annual subscription service of Ultralytics HUB Pro. Please ensure it includes:
    * The name and address of the Institute de Investigaciones Agropecuarias.
    * A detailed breakdown of the subscription period and the services included.
    * The invoice will be for two users and one year.
* 		A Quotation for Computing Credits (If available) for model training on the Ultralytics cloud. This should detail:
    * The cost per unit of computing credit.
    * Any packages or discounts are available for bulk purchases.
    * The validity period of the purchased credits.
    * We need to contract 200 US dollars per account for this initial phase.
* 		Bank Account Details for the wire transfer, including:
    * Beneficiary name.
    * Bank name and address.
    * Account number and routing information, such as SWIFT code or IBAN.
* 		Confirmation of the Total Payment Amount for both the subscription and the computing credits, inclusive of any applicable taxes or additional fees.
Please let me know if additional forms or specific information are required from our side to streamline this process. We aim to ensure a seamless and compliant transaction, aligning with our institutional policies and your requirements.
Thank you for your understanding and support. I look forward to your prompt response and to fostering a continued partnership.
Warm regards,
Lorenzo Leon G. Researcher, Agr. Eng. Mg.Sc. Institute de investigaciones Agropecuarias, Chile lleon@inia.cl (mailto:lleon@inia.cl) +56-995566139

If this is not the place, to address this email, or contact, could you please send me a proper (direct) contact to ask this payment issue ?. thanks in advance , L.

**Comment by kalenmike** [comment]
@lfleon9b Thank you. I will reach out to you via email and we can continue the conversation there.
