### ISSUE TITLE
Trained models doesn't appear on mobile app for android

### ISSUE THREAD

**Issue by leiut0queen** [ultralytics/hub#592]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have problem when testing in ultralytics app for android, the trained models doesn't appear, and it keeps loading when I open it on private. I try to change the settings to public but it still doesn't work.
![423422731_808219791143592_1695932116569142040_n (1)](https://github.com/ultralytics/hub/assets/161662972/bb01ca44-6713-4346-846e-259c95ca5bd5)

**Comment by UltralyticsAssistant** [comment]
@leiut0queen hello! 👋

I'm sorry to hear you're experiencing issues with your trained models not appearing in the Ultralytics app for Android. Let's try to troubleshoot this together.

First, ensure that your models are indeed set to public, as private models won't be visible in the app. Next, please check if your app is updated to the latest version, as compatibility issues might cause such problems.

If the issue persists, try clearing the app's cache or reinstalling the app to see if that resolves the problem. Sometimes, a fresh start can help eliminate any glitches.

For more detailed guidance, our documentation at https://docs.ultralytics.com/hub might offer additional insights or steps to follow.

If none of these steps work, please provide us with more details about the issue, such as any error messages you're receiving or steps you've already tried. This will help us assist you more effectively.

Thank you for reaching out, and we appreciate your patience as we work to resolve this issue! 🚀

**Comment by kalenmike** [comment]
@leiut0queen Thanks for raising this, to help troubleshoot and resolve this can you share the version of the app you are using and the device? You can see it on the very bottom of the account screen or by opening the app page in your app store.
