### ISSUE TITLE
Accessing checkpoints once google collab got disconnected in between training

### ISSUE THREAD

**Issue by vipin-prabhakaran** [ultralytics/hub#593]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

i was training for a dataset for around 13000 images ,but google collab got disconnected in the middle of the training  , the bellow is the check point url https://hub.ultralytics.com/models/fjTOVdZKmQMsYBEqakVV . i was trying to access the best.pt in weights section as it got almost completed with 63 epocs .
as the training is not over i was not able to access the weights folder and best.pt ,can anyone help me in how to access the completed checkpoints to take out the best.pt

**Comment by kalenmike** [comment]
@vipin-prabhakaran If your Colab instance got disconnected and you do not have it connected with a permanent storage solution its probable that the environment got reset. I checked HUB and the model did not upload any checkpoints so you are not able to resume.

Your best hope is checking the /content directory in Colab and seeing if the weights are still there.

**Comment by vipin-prabhakaran** [comment]
Hi @kalenmike  thank you so much for your response , If your Colab instance got disconnected and you do not have it connected with a permanent storage solution its probable that the environment got reset. I checked HUB and the model did not upload any checkpoints so you are not able to resume.as i am new to the system can u please throw some light on how to connect colab to a permenant storage ,thanks in advance

**Comment by kalenmike** [comment]
@vipin-prabhakaran This is not something that we handle directly and we suggest that you use our Pro plan with our Cloud Training feature.

If you prefer to continue with Colab you can find many guides online that show how to configure a connection to your storage. You will need to ensure that the path is correctly defined in yolo settings. You can read the docs to see how to configure your settings:

https://docs.ultralytics.com/quickstart/?h=settings#modifying-settings

Here are a few I just sourced now:

https://towardsdatascience.com/different-ways-to-connect-google-drive-to-a-google-colab-notebook-pt-1-de03433d2f7a
https://stackoverflow.com/questions/64808087/how-do-i-save-files-from-google-colab-to-google-drive
https://www.youtube.com/watch?v=6UnCrulz-fE

**Comment by vipin-prabhakaran** [comment]
hi @kalenmike  thank you so much for your quick responses ,can you pls mention where i need to check in my account  to make sure that my ultralytics hub training is properly connected with cloudpro url /or any kind of permanant storage

**Comment by kalenmike** [comment]
@vipin-prabhakaran You can follow this document for getting started with Cloud Training and upgrading to HUB Pro:

https://docs.ultralytics.com/hub/cloud-training/

**Comment by vipin-prabhakaran** [comment]
@kalenmike  I have completed my training using ultralytics HUB web portal with out using scripts and its showing 100% completion and still after training its saying it got disconnected ,and resume from epic 72 as the total number of epocs is 75 ,but its not clickable also ,can you pls help me on this as its very urgent for me and I am going clueless on what's happening
