### ISSUE TITLE
COCO128 Is not working in Cloud Training

### ISSUE THREAD

**Issue by vipin-prabhakaran** [ultralytics/hub#596]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Training, Export

### Bug

I have an account at HUB ,today for an urgent training requirement I changed to PRO for training using 20 $ and again for training another 20$ as top up,but my training keeps on disconnecting and model will not be available for export ,the same is happening in so many of my friends account  also, 
<img width="1122" alt="Screenshot 2024-03-03 at 8 49 06 PM" src="https://github.com/ultralytics/hub/assets/161804976/111539aa-0d09-43ef-96e2-b2aec43dbfdd">

As we have an urgent requirement and any delay will affect our business plans, request team to please give us a solution asap ,pls let us know if any more info is required on the subject .I have just selected one of the coco18 data set available and tried to run with only 1 cycle to just to check whether it can be exported .

**Comment by UltralyticsAssistant** [comment]
@vipin-prabhakaran hello! 👋

Thank you for reaching out and detailing the issue you're experiencing with training disconnections on the HUB. We understand how crucial timely training is, especially when urgent requirements are at stake. I'm here to help!

Firstly, it's important to ensure that your internet connection is stable during the training process, as intermittent connectivity could lead to the issues you're facing. Additionally, please verify that your account has sufficient credits for the training session you're initiating. Running out of credits mid-training could also result in disconnections.

If the problem persists despite a stable connection and sufficient credits, it might be related to a temporary issue on our end. In such cases, we recommend trying the following steps:
1. Log out and then log back into your HUB account.
2. Attempt to start the training session again after a short wait.
3. Ensure that the dataset and model configurations do not contain any errors that might interrupt the training process.

We're committed to resolving your issue as quickly as possible. If these steps do not resolve the problem, please provide us with any error messages or additional details about when the disconnection occurs. This information will be crucial for our team to diagnose and address the issue effectively.

For more detailed guidance on troubleshooting and other features, you can always refer to our documentation at https://docs.ultralytics.com/hub.

We appreciate your patience and understanding as we work to resolve this for you and your team. 🚀

**Comment by kalenmike** [comment]
@vipin-prabhakaran We have identified a configuration issue with the public coco128 dataset, we have taken it offline until it can be resolved. Are you having issues with any other datasets?

**Comment by vipin-prabhakaran** [comment]
@kalenmike  thanks  for your prompt response and actions,no issues found with my custom data set ,if possible i request your comment on one thing  as i am  pro user if i got disconnected during training is there any way i can take out the model created till that cycle or do i need to enable any settings to access it ,thanks in advance

**Comment by vipin-prabhakaran** [comment]
@kalenmike  ok thanks for the clarification, looking forward for this feature as it will be a great help for people who is running larger no of cycles for training during interruptions due to various reasons

**Comment by kalenmike** [comment]
@vipin-prabhakaran You do currently have access to resume in epoch training with all agents.

**Comment by vipin-prabhakaran** [comment]
@kalenmike thanks for your response, will check this and respond , had one more issuehttps://hub.ultralytics.com/models/4iiEIb7peyXxmzwkUbVN?tab=deploy , when I am trying to export the model in tflite with advanced settings open for both FP 16 and int8 its giving me an error like an unknown error occurred, can you pls help me on this as its a public model available 
<img width="1037" alt="Screenshot 2024-03-05 at 11 01 52 AM" src="https://github.com/ultralytics/hub/assets/161804976/3c74363b-7ba1-4c18-a3be-955f26a1a68d">

**Comment by kalenmike** [comment]
@vipin-prabhakaran The reason you are unable to export the model is that it does not belong to you. This option should not be available on the frontend, and is being rejected by the server. Only users that have write access to a model are able to export it into different formats.

You will be able to complete an export with this configuration if you train a custom model or by using the ultralytics package directly.

**Comment by vipin-prabhakaran** [comment]
hi @kalenmike  ,Thanks a lot for all your helps which is giving a great amount of trust and confidence on training on UltralyticsHUB.I just want to know I had an 8n model which is trained with my own custom data set ,now I want to fine tune my model with an updated data set ,is there any way for this in HUB portal

**Comment by vipin-prabhakaran** [comment]
I am using preview feature to test my model ,and everything is working fine ,but when I am using Tensorflow lite model with fp16& int8 optimisations ,its not giving that much accuracy as much as I am getting with the same model on my preview tab 

@sergiuwaxmann  can u pls find out to figure out the root cause to get in to the bottom of the issue

**Comment by sergiuwaxmann** [comment]
@vipin-prabhakaran Unfortunately, I won't be able to help you with this but someone from the ML team might be able to help you.

Please open a new issue as the question is not related to the original question. Thank you!
