### ISSUE TITLE
Training Models to Show More Information

### ISSUE THREAD

**Issue by kalenmike** [ultralytics/hub#6]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

When a model is in training it would be helpful to see how many epochs are completed versus the total. It would also be awesome to see an estimated time to completion and perhaps a total train time to date. It would be great to preview the model as it is in the last uploaded epoch.

- See current epoch
- See estimated training completion time
- Preview models currently in training

**Comment by glenn-jocher** [comment]
@kalenmike should we update the stale patience to 90 days? I've seen 90 days used in other repos occasionally.

We can make changes easily here:
https://github.com/ultralytics/hub/blob/6f75dcc28e8d5b82902767664cae2cc1e5703f01/.github/workflows/stale.yml#L34-L38
