### ISSUE TITLE
Can't get step 2 on Colab to work. Needs more than API key? 

### ISSUE THREAD

**Issue by Russ76** [ultralytics/hub#60]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training, API Key

### Bug

Must the model name also be included in step 2 in the Google Colab? With API key inserted, it produces error, saying "Name is not defined."

### Environment

Computer: PC, i7 with 16 Gig RAM, SSD
Ubuntu 20.04
Firefox browser, updated.

### Minimal Reproducible Example

Started new model, selected format, selected dataset, went to Colab to train.

### Additional

Ultralytics HUB Version
v0.1.14-beta.12
Client User Agent
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
Operating System
Linux x86_64
Browser Window Size
1271 x 968
Server Timestamp
1658112208

**Comment by glenn-jocher** [comment]
@Russ76 you need to copy the entire string from here. It's the API Key concatenated with your Model ID.

<img width="1285" alt="Screen Shot 2022-07-18 at 8 04 29 AM" src="https://user-images.githubusercontent.com/26833433/179453220-0982795e-f976-4b55-b07a-e13685681cd6.png">

**Comment by Russ76** [comment]
There seems to be no way to go back to that screen. I had to create a new model. But now this one is training! Seems to me that I did the very same thing last night, but that time it wouldn't work. My next model I'll upload my own data! Thanks

**Comment by Russ76** [comment]
Thanks, guys!

**Comment by UltralyticsAssistant** [comment]
@Russ76 you're welcome! If you have any more questions in the future or need further assistance, feel free to reach out. Happy training with your models, and best of luck with your projects! Remember, the credit goes to the entire YOLO community and the Ultralytics team for making this possible. Have a great day!
