### ISSUE TITLE
Checkpoint

### ISSUE THREAD

**Issue by slaymurs** [ultralytics/hub#600]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello, help me please. For the 3rd time in a row I’ve been trying to train a model via https://colab.research.google.com/github/ultralytics/hub/blob/main/hub.ipynb It takes a long time to train 20 hours, this is normal. After an interruption, checkpoints do not work. It's just that learning starts from the very beginning. What to do? What should I do? Previously, everything worked fine and saved the checkpoint, but now it doesn’t. Please check, correct, and let me know. It's very urgent. I'm really looking forward to it.

### Additional

Здравствуйте, помогите мне пожалуйста. Уже 3-й раз подряд пробую обучить модель через https://colab.research.google.com/github/ultralytics/hub/blob/main/hub.ipynb Обучается долго 20 часов, это нормально. После прерывания не срабатывают чекпоинт. Просто обучение начинается с самого начала. Что делать? Как быть? Раньше все нормально работало, и сохраняло чекпоинт, а сейчас нет. Проверьте пожалуйста, исправьте, и мне сообщите. Очень срочно нужно. Очень жду.

**Comment by slaymurs** [comment]
![Screenshot_3](https://github.com/ultralytics/hub/assets/141275789/c1b65b6d-4f47-4b92-afb1-078bd9b585ee)

**Comment by slaymurs** [comment]
![Screenshot_2](https://github.com/ultralytics/hub/assets/141275789/05c063de-3776-4d32-afbf-1f263980fdf5)

I tried to have it learn on my PC, but there are only errors :-( Please help me.

Пробовал чтоб обучалось на моем пк Но там одни ошибки :-( Помогите пожалуйста мне.

**Comment by UltralyticsAssistant** [comment]
@slaymurs hello! I'm sorry to hear you're experiencing issues with training checkpoints and errors on your PC. Let's tackle these one at a time:

1. **Checkpoints not working in Colab**: It's crucial to ensure that your training session in Colab is not interrupted, as Colab sessions can reset if left idle or run for too long. To manage checkpoints effectively, make sure you're saving them to a persistent location like Google Drive. This way, even if the session resets, you can resume training from the last saved checkpoint. Please refer to the Ultralytics HUB Docs for guidance on setting up checkpoint saving and resuming training.

2. **Errors on PC**: Training on your PC requires a proper environment setup. Common issues include incorrect installation of dependencies or incompatible hardware. Ensure that your system meets the requirements for CUDA (if using GPU acceleration), and that all dependencies are correctly installed. Without specific error messages, it's challenging to provide a precise solution, but reviewing the installation and setup instructions in the Ultralytics HUB Docs can help identify and resolve common issues.

Remember, the Ultralytics team and the YOLO community are here to support you. If you continue to face issues, please provide detailed error messages or descriptions of the problems you're encountering for more targeted assistance. 🚀

**Comment by slaymurs** [comment]
Все получилось все работает, можно закрывать, всем спасибо :+1:

**Comment by pderrenger** [comment]
That's great news, @slaymurs! 😊 I'm delighted to hear everything is working for you now. If you have any more questions or run into issues in the future, don't hesitate to reach out. Happy coding, and best of luck with your projects! Closing this issue now.
