### ISSUE TITLE
Feature: Add Support for Choosing GPU Index

### ISSUE THREAD

**Issue by Pedro-Leitek** [ultralytics/hub#601]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi,

I tried to train a model using the hub feature on a multi-gpu machine. This machine was rented remotely using vast.ai. When I ran the python line "results = model.train", on the middle of the script, it got stuck. Here is a similar issue https://github.com/ultralytics/ultralytics/issues/5337
On my case I got stuck on "AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed" (the script stopped)

Noting that when I chose a single gpu in the hub, the issue didn't happen. In google colab everything works fine, by following the same steps (installation).

Do you know why this could be happening?

**Comment by kalenmike** [comment]
@Pedro-Leitek We would need more information to be helpful here. The model id that is giving you problems if trained from HUB or the full command if you are using the ultralytics package directly.

**Comment by Pedro-Leitek** [comment]
> @Pedro-Leitek We would need more information to be helpful here. The model id that is giving you problems if trained from HUB or the full command if you are using the ultralytics package directly.

@kalenmike ok, the model is yolov5m6u, the command I'm using is the following:

```
from ultralytics import YOLO, checks, hub
checks()

hub.login('cb41d55ce5b6e026202e4cb2e8879bf609113fce75')

model = YOLO('https://hub.ultralytics.com/models/lvOqRZ7rWGdek3K5Mdwk')
results = model.train()
```

**Comment by kalenmike** [comment]
@Pedro-Leitek The model you have set here is a single GPU model?

**Comment by Pedro-Leitek** [comment]
@kalenmike yes it was, here is the code for multi-gpu

```
from ultralytics import YOLO, checks, hub
checks()

hub.login('')

model = YOLO('https://hub.ultralytics.com/models/lvOqRZ7rWGdek3K5Mdwk')
results = model.train()
```

**Comment by kalenmike** [comment]
@Pedro-Leitek Do you have logs for the server you were training on? One issue could be that you are assigned GPU's that are at a different index. You are currently requesting GPU 0 and 1, perhaps they are already busy or they are not available?

Also ensure that you have access to the GPU from where you are running the code.

**Comment by Pedro-Leitek** [comment]
@kalenmike I read somewhere that it may work if I request GPU 0, 2 or 1,3. For some reason it worked with another user. I didn't notice if the gpus were consecutive. But, lets just say I rent a machine that the gpus are not consecutive, lets say 0,2, how can I force the hub to set devices 0, 2 (or any other sequence)?

**Comment by kalenmike** [comment]
@Pedro-Leitek Currently the device id's cannot be set on HUB for multi GPU training. We are planning to release more advanced configuration soon. The solution at the moment is to train the model from your server and connect it to HUB by logging in first, this will mean that your model will not have a connection to the dataset.

If you want to go this route here is an example, you will need to have your dataset available on the server and pass all the arguments to model.train.

```python
from ultralytics import YOLO, checks, hub
checks()

hub.login(API_KEY)

model = YOLO('yolov8n.pt')
results = model.train(TRAIN_ARGS)
```

**Comment by kalenmike** [comment]
@sergiuwaxmann This is something we need to ensure is possible with the new advanced options. I have seen this problem regularly in the wild. Currently we assign the GPU index incrementally from 0. HUB users need the option to overwrite this with an array of custom indexes.

**Comment by sergiuwaxmann** [comment]
@Pedro-Leitek Hello!
First of all, my apologies for the delayed response.
I'm pleased to inform you that we introduced a new "Custom" option in the Advanced Model Configuration approximately two weeks ago. This enhancement allows users to utilize all supported [training settings](https://docs.ultralytics.com/modes/train/#train-settings). It also includes the capability to specify custom indexes (see image attached below).
![device](https://github.com/ultralytics/hub/assets/47978446/72869490-06c8-4abb-b1e9-79208d2f4528)
