### ISSUE TITLE
Resume training not available for cloud trained model/

### ISSUE THREAD

**Issue by rolurq** [ultralytics/hub#604]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Training

### Bug

I have a model that trained for 257 epochs of 300. The training was using the cloud agent but at some point i stopped training and now I can't resume.

![image](https://github.com/ultralytics/hub/assets/13684824/6af58873-205e-4ed0-8c39-8e81cd8bd92a)

I have no access to the checkpoint or to resume training in any way, which is really frustrating since it has already taken 27 hours of training.

### Environment

Ultralytics HUB Version
v0.1.36
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
2560 x 1305
Server Timestamp
1709905304

### Minimal Reproducible Example

1. Login to Ultralytics HUB
2. Access interrupted training model
3. Try to resume

### Additional

Bug report from #602

**Comment by kalenmike** [comment]
@rolurq I can take a look into this for you, what is the model id? YOu can find it in the URL.

**Comment by kalenmike** [comment]
@rolurq We are able to replicate this bug in the UI and are pushing a fix now.

**Comment by kalenmike** [comment]
@rolurq The fix is now live, you may need to refresh your page and/or cache to see it reflected.

**Comment by rolurq** [comment]
Awesome! It's working now. Thanks a lot.

**Comment by UltralyticsAssistant** [comment]
You're welcome, @rolurq! 😊 If you have any more questions or run into any issues, feel free to reach out. Happy training!
