### ISSUE TITLE
Trained model Preview Error : An error has occurred, pls try again later

### ISSUE THREAD

**Issue by chunyu-visiiontif** [ultralytics/hub#609]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

When I tried to preview the trained model and uploaded the image. I got An error has occurred, pls try again later.
For the inspect -> Console I got 

Access to XMLHttpRequest at 'https://api.ultralytics.com/v1/predict/MYQpsaF9kjOSevprJRt9' from origin 'https://hub.ultralytics.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
api.ultralytics.com/v1/predict/MYQpsaF9kjOSevprJRt9:1 
 
![ultralytics-Preview_Error](https://github.com/ultralytics/hub/assets/93896506/a1fab9a6-6f76-4782-8cb8-8e4196f002e2)
Failed to load resource: net::ERR_FAILED

### Environment

Windows 10 
Chrome is up to date
Version 122.0.6261.112 (Official Build) (64-bit)

### Minimal Reproducible Example

logon to the hub.
select a model
click preview
upload an image
https://hub.ultralytics.com/models/MYQpsaF9kjOSevprJRt9?tab=preview

**Comment by UltralyticsAssistant** [comment]
@chunyu-visiiontif hello! Thank you for bringing this issue to our attention. It seems like you're encountering a CORS (Cross-Origin Resource Sharing) policy error when trying to preview your trained model on the Ultralytics HUB. This is typically related to how web browsers enforce security measures to prevent potentially malicious websites from accessing resources and data from another domain without permission.

Here are a few steps you can take to troubleshoot and potentially resolve this issue:

1. **Clear Browser Cache and Cookies**: Sometimes, outdated cache or cookies can cause unexpected behavior. Try clearing your browser's cache and cookies and then attempt to preview the model again.

2. **Try a Different Browser**: To rule out browser-specific issues, try accessing the HUB using a different web browser.

3. **Check Network Configuration**: If you're on a corporate or school network, there might be network-level security policies in place that could block certain requests. If possible, try accessing the HUB from a different network environment.

4. **Disable Browser Extensions**: Sometimes, browser extensions can interfere with web requests. Try disabling any extensions, especially those related to security or ad-blocking, and see if that resolves the issue.

If after trying these steps you're still facing the problem, please provide us with any additional details or changes in the error message. This will help us further diagnose and address the issue more effectively.

For more detailed guidance on using the Ultralytics HUB, you can refer to our documentation at https://docs.ultralytics.com/hub.

We appreciate your patience and are here to help you get back to your work as smoothly as possible! 😊

**Comment by sergiuwaxmann** [comment]
Hi @chunyu-visiiontif!
Thank you for bringing this issue to our attention.
We were able to replicate this issue and are working on a fix now.

**Comment by sergiuwaxmann** [comment]
@chunyu-visiiontif @dougkote
A fix has been deployed. Apologies for any inconvenience caused.
