### ISSUE TITLE
Dataset upload yaml file missing

### ISSUE THREAD

**Issue by Latzi** [ultralytics/hub#61]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I am new to the Ultralytics HUB. I thought I give it a try and I uploaded a custom dataset after creating a project etc. The upload finished (big dataset around 14 GB), then I had the "processing " phase for a few minutes then it failed saying that it didn't find the yaml file for my dataset. That's is right because I didn't upload. My dataset comes in the format required by the colab example. I didn't know up front that the yaml has to be included and now that I know that I have no idea where to add it? 

Can you please clarify at what stage or where to upload the yaml file. I'll try again once that is clear because the upload take quite a while like 2h .Apart from that this looks awesome I can hardly wait to see if I can train a model.

**Comment by Latzi** [comment]
Oh that answers my question. I should have read that before even attempting to train the 1st model. I'll have another go with it. Thanks and please disregard my question :-)

**Comment by UltralyticsAssistant** [comment]
@Latzi hello!

No worries at all! We're delighted to hear that you're giving Ultralytics HUB a try with your custom dataset. I'm glad to hear that you found the information you needed. Should you have any more questions or run into any other issues in the future, don't hesitate to reach out. We're here to help ensure you have a smooth experience training your models with us. Best of luck with your training, and we hope Ultralytics HUB meets your expectations and helps you achieve great results!

Warm
