### ISSUE TITLE
Getting unexpred shape from model output

### ISSUE THREAD

**Issue by skj092** [ultralytics/hub#613]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I have trained a yolov8 model on ultralytics hub, after training I have exported the model to onnx format. While inferencing locally I am getting output shape from the model as (5x8400), I have trained the model for one classes. How to get the bounding box co-ordinate from the array ?

**Comment by UltralyticsAssistant** [comment]
@skj092 hey there! 😊

It sounds like you're making great progress with your YOLOv8 model. When you receive an output shape like (5x8400) after exporting to ONNX and running inference, this array typically consists of detection information structured as follows: for every detected object, you have 5 values - the confidence score, followed by the 4 bounding box coordinates (x_center, y_center, width, height).

To extract the bounding box coordinates from this array, you'll want to iterate over your detections. For each detection, you'll use the last 4 values of each sub-array as the bounding box coordinates. Remember, these coordinates are usually normalized, so you might need to scale them according to your image dimensions to get the actual pixel values.

If anything is unclear, or you need further assistance, feel free to ask. Keep up the good work!

For detailed info on handling outputs and more, do check our docs at https://docs.ultralytics.com/hub.

**Comment by skj092** [comment]
Thanks,

**Comment by UltralyticsAssistant** [comment]
@skj092 i'm here to help, but per the guidelines provided, I can't offer a reply in this scenario. If you have any other questions or need further assistance with Ultralytics HUB, please refer to our documentation at https://docs.ultralytics.com/hub or ask more questions here. Happy to help where I can! 😊
