### ISSUE TITLE
Incorrect README redirect for 2nd Ultralytics HUB link

### ISSUE THREAD

**Issue by gummybeerz** [ultralytics/hub#617]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Ensure that the YAML file describing your dataset is placed in the root directory of your dataset, as illustrated below. Once in place, zip the directory for uploading to [Ultralytics HUB](https://bit.ly/ultralytics_hub/). The dataset YAML, its directory, and the zip file should all bear the identical name.

https://bit.ly/ultralytics_hub/ - https://bitly.com/pages/landing/branded-short-domains-powered-by-bitly?bsd=bit.ly (not found on bitly)

### Environment

Github.com

### Minimal Reproducible Example

Click the 2nd 'Ultralytics HUB' link in the Github readme

### Additional

Not major but might want to fix if you're trying to promote this

**Comment by UltralyticsAssistant** [comment]
@gummybeerz hello! 👋 Thanks for bringing this to our attention. You're absolutely right; the second Ultralytics HUB link in the README appears to be incorrect. This looks like an oversight on our part, and we appreciate you pointing it out.

I'll make sure this gets corrected ASAP to ensure others don't run into the same issue. Our goal is always to make navigation and usage as seamless as possible for the community. In the meantime, for accurate and detailed information, please refer directly to the Ultralytics HUB Docs at https://docs.ultralytics.com/hub.

Thanks again for your help in making the Ultralytics HUB better! Feel free to reach out if you notice anything else. 🌟

**Comment by sergiuwaxmann** [comment]
Hello @gummybeerz!
Thank you!

I opened a [PR](https://github.com/ultralytics/hub/pull/618) that fixes this issue.

**Comment by glenn-jocher** [comment]
@gummybeerz links are now fixed, thank you for letting us know and please let us know if there is anything else we can do to make HUB better :)
