### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by harshithabannu** [ultralytics/hub#619]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

waiting for connection and not connecting in 2nd step of training

### Minimal Reproducible Example

waiting for connection and not connecting in 2nd step of training

**Comment by sergiuwaxmann** [comment]
Hello @harshithabannu!
Can you provide a little more information so we can reproduce this issue? Maybe you can share the agent you are using to train your model or the logs?
