### ISSUE TITLE
Choosing Yolov8 OBB model when selecting model to train with

### ISSUE THREAD

**Issue by Drake-Sunryder** [ultralytics/hub#621]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Apologies if I somehow missed where this is explained or addressed somewhere, but I couldn't find anything. I see that when you upload your own dataset to the Hub, you have the option of choosing to specify that it's an OBB dataset.

My understanding, based on the explanations that I've seen on training OBB models is that they require specific models such as YOLOv8n-obb or YOLOv8x-obb. However, in the second step of training a model when you pick from a list of models, such OBB models are nowhere to be found. Is this intentional or am I missing something and/or misunderstanding something?
![image](https://github.com/ultralytics/hub/assets/112013734/27725728-489b-4cf0-aa27-ffef1f0b90bb)

How exactly to I train a dataset with a YOLOv8 OBB model in the Ultralytics Hub?

**Comment by sergiuwaxmann** [comment]
Hello @Drake-Sunryder!

In order to have access to OBB architectures, you need to select an OBB dataset in the first step.
![SCR-20240326-001](https://github.com/ultralytics/hub/assets/47978446/6dc20a6f-9cc0-48cb-94f3-079ad78ef304)

You can make sure you selected an OBB dataset by training a model directly from the dataset page of your OBB dataset.
![SCR-20240326-002](https://github.com/ultralytics/hub/assets/47978446/c585ed57-c7b9-4d89-8de0-35d1b3a1d7c5)

You can try this using our [Ultralytics DOTA8 Dataset](https://github.com/ultralytics/hub/blob/main/example_datasets/dota8.zip) - read more about uploading a dataset [here](https://docs.ultralytics.com/hub/datasets/#upload-dataset).

**Comment by Drake-Sunryder** [comment]
> Hello @Drake-Sunryder!
> 
> In order to have access to OBB architectures, you need to select an OBB dataset in the first step. ![SCR-20240326-001](https://private-user-images.githubusercontent.com/47978446/317010328-6dc20a6f-9cc0-48cb-94f3-079ad78ef304.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODE0MzIsIm5iZiI6MTcxMTQ4MTEzMiwicGF0aCI6Ii80Nzk3ODQ0Ni8zMTcwMTAzMjgtNmRjMjBhNmYtOWNjMC00OGNiLTk0ZjMtMDc5YWQ3OGVmMzA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE5MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhN2U5Y2QxMTIwNDAxZGJiODIxNjhiYThkYzliZDQ5YmFhNGQwMmE3YjZmMzk0MTEzMDY5ZmE0NjAwM2JiYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ve7_MXBv-cN9dzWoDqFEzO-KZKaXaupY3nkkngJ5pug)
> 
> You can make sure you selected an OBB dataset by training a model directly from the dataset page of your OBB dataset. ![SCR-20240326-002](https://private-user-images.githubusercontent.com/47978446/317010058-c585ed57-c7b9-4d89-8de0-35d1b3a1d7c5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODE0MzIsIm5iZiI6MTcxMTQ4MTEzMiwicGF0aCI6Ii80Nzk3ODQ0Ni8zMTcwMTAwNTgtYzU4NWVkNTctYzdiOS00ZDg5LThkZTAtMzVkMWIzYTFkN2M1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNlQxOTI1MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmU0M2QxZjBkOGQ4YTM3OGRjMTkzZGI5MDU2ZWE3M2IzNDJkZTIxMjUxNGFhNmM5N2VjZWQwMGE5ZDUyZmRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LMCX40N4P0nFiSj1w0yegEWPtlbX3EyNtZjQgywAj5c)
> 
> You can try this using our [Ultralytics DOTA8 Dataset](https://github.com/ultralytics/hub/blob/main/example_datasets/dota8.zip) - read more about uploading a dataset [here](https://docs.ultralytics.com/hub/datasets/#upload-dataset).

Yup, after double-checking the dataset I uploaded, I didn't upload it as an OBB dataset correctly. This one's on me! Thanks for the help, though!

**Comment by sergiuwaxmann** [comment]
@Drake-Sunryder No worries!
