### ISSUE TITLE
How to display the key point coordinates of yolov8 detection target

### ISSUE THREAD

**Issue by yueguang01** [ultralytics/hub#623]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How to display the key point coordinates of yolov8 detection target

**Comment by UltralyticsAssistant** [comment]
@yueguang01 hi there! 🎉

To display key point coordinates of a detection target with YOLOv8, after processing your image or video with the model, you can access the key point information directly from the detection results. The results object contains detected classes, bounding boxes, and key points when applicable. For each detection, key points are stored as part of the object attributes, typically in an array or similar structure, where each key point is represented by its (x, y) coordinates.

Please refer to the "Handling Results" section in the Ultralytics HUB Docs for a detailed explanation on accessing and manipulating these detection results. Keep in mind that the exact method might vary slightly based on how you're implementing the YOLOv8 model (e.g., Python script, Jupyter notebook).

Happy detecting! 😊
