### ISSUE TITLE
My cell phone app doesn't work

### ISSUE THREAD

**Issue by Djalma10** [ultralytics/hub#628]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

My cell phone app doesn't work

**Comment by UltralyticsAssistant** [comment]
@Djalma10 hi there! 😊

Sorry to hear you're having trouble with the cell phone app. To better assist you, could you provide more details? Specifically:

1. The type of phone and operating system you're using.
2. The exact nature of the issue - does the app not open, crash, or behave unexpectedly in some way?
3. Any error messages you see when the issue occurs.

Knowing these will greatly help us in diagnosing and addressing your concern. For more general troubleshooting tips, you might find our documentation at https://docs.ultralytics.com/hub helpful. 

Looking forward to helping you get back on track!

**Comment by oliverlibaw** [comment]
@Djalma10 I'm also having an issue with the Hub app. I can use the "Predict" button on the bottom left corner of the app to the default YOLOv8s and YOLOv8n models and do real-time prediction on my iOS device. 

But I can't get any models to load using the "Projects" button next to the "Predict" button. The app just spins indefinitely. 
![IMG_DA3F55667AD0-1](https://github.com/ultralytics/hub/assets/92615450/b961b16f-75dc-4af6-b0a2-0f958806d155)

I'm using version 0.923 of the app on an iPhone 15 with iOS 17.4.1

**Comment by Djalma10** [comment]
I'm having the same problem as above. On iPhone 15.

**Comment by Djalma10** [comment]
My projects don't load and don't work on my cell phone.
![WhatsApp Image 2024-04-04 at 1 34 32 PM (1)](https://github.com/ultralytics/hub/assets/32706453/d32a232a-99f2-46e7-953e-5dfa8d14120f)
![WhatsApp Image 2024-04-04 at 1 34 32 PM](https://github.com/ultralytics/hub/assets/32706453/00131e83-ae6a-40d4-855a-bc2e2ee558f3)

**Comment by UltralyticsAssistant** [comment]
@Djalma10, thanks for reaching out and providing the visuals! 📸

This issue with projects not loading seems to be affecting users on newer iPhone models. Here are a few things to try that might help resolve the issue:

1. Ensure your app is updated to the latest version available in the App Store.
2. Close and reopen the app to clear any temporary glitches.
3. Check your internet connection to make sure it's stable.
4. Restart your phone to refresh its system fully.

If the problem persists after these steps, it could be a bug we need to investigate further. Could you let us know the app version you're currently using and confirm your iOS version? This information will help us pinpoint the issue more accurately.

Your experience is very important to us, and we appreciate your patience as we work through this! 🛠

**Comment by Djalma10** [comment]
I performed the actions above and the error persists.
App version 923
iPhone 15 pro max ios version 17.4.1

**Comment by UltralyticsAssistant** [comment]
Thanks for trying those steps and for the additional details, @Djalma10! 🌟

It seems we might be encountering a specific bug with app version 923 on iPhone 15 Pro Max running iOS 17.4.1. I'll report this to our team so we can dive deeper into resolving it. 

In the meantime, keep your app and iOS up to date, as we frequently release fixes and improvements. Your feedback is crucial in helping us improve, so thank you for your patience and assistance! 🛠️

**Comment by hncvj** [comment]
I'm having the same issue on my android device. Please sort this out asap.

**Comment by pderrenger** [comment]
Hi there! Sorry for the inconvenience. 🙁

We're on it. Could you please provide the Android version and the app version you're using? This information will help us identify and resolve the issue more quickly. Thank you for your patience!

**Comment by PHIKHONAMTHEMBU** [comment]
Was this ever resolved ?

I've got same issue, with on Android and IOS

**Comment by pderrenger** [comment]
Hi @PHIKHONAMTHEMBU,

Thanks for reaching out! 😊

We understand how frustrating this can be. To help us investigate and resolve this issue effectively, could you please provide a minimal reproducible example? This will allow us to replicate the problem on our end. You can find guidance on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example). 

Additionally, please ensure you are using the latest versions of `torch`, `ultralytics`, and `hub-sdk`. If not, kindly update these packages and see if the issue persists.

Your cooperation is greatly appreciated, and we're here to help you get this sorted out as quickly as possible! 🚀
