### ISSUE TITLE
Home -> Teams add email address with ".cloud" extension not working

### ISSUE THREAD

**Issue by togro** [ultralytics/hub#629]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Settings

### Bug

Hi,

I want to change my email address but domain **.cloud** is not recognized .

I put screenshot below from :

Home -> Teams -> Pavimento 

When I put mtoro@movilgate.cloud  the web form response with : **"Please enter a valid email address"** 

### Additional

<img width="645" alt="image" src="https://github.com/ultralytics/hub/assets/7252575/217464a1-4592-4da0-9311-ec8ccf07ab2f">

**Comment by sergiuwaxmann** [comment]
Hi @togro! Thank you for bringing this to our attention.
We recently released a new version that allows users to use emails that use the `.cloud` domain. Your patience and understanding are greatly appreciated.

PS Keep in mind that each unique member counts as one seat, regardless of how many teams they are in, and you will be charged $20 per month for each seat, or $200 per year if you choose the annual plan.
![team_seats_note](https://github.com/ultralytics/hub/assets/47978446/773c8ae5-7268-4533-ba47-ba5ffcdc1748)
