### ISSUE TITLE
Quality of images cropped from a video with YOLO

### ISSUE THREAD

**Issue by davidemerolla** [ultralytics/hub#632]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! I'm cropping images of object detected with YOLOv8 from a video? My video is 4K, but it seems that the quality of the images i have in output after cropping is low. How can I solve this problem?
![91](https://github.com/ultralytics/hub/assets/159159660/3981f467-907f-4c3c-b56d-7bf04b27f424)

### Additional

I'll need to classify these road signs into damaged/not damaged to later train a CNN

**Comment by pderrenger** [comment]
Hello! 😊 It sounds like you're working on an interesting project with YOLOv8 and facing a challenge with the quality of the cropped images. When extracting objects from a 4K video, maintaining high image quality is crucial, especially for detailed analysis like assessing damage.

If you're experiencing lower quality in the output images than expected, the issue might be tied to the resize or compression settings used during the cropping process. YOLO itself doesn't degrade the quality of your images, but how you handle the images post-detection can impact their quality.

A few things to consider:
- Ensure you are not resizing the cropped images unintentionally. Keeping the original size of the detected objects can help preserve the quality.
- Check the format in which you're saving the cropped images. Lossless formats like PNG might serve your needs better than lossy formats like JPEG, which can degrade quality.
- If you're using any additional processing or saving steps after cropping, verify that these steps are configured to maintain high fidelity of the image data.

For detailed steps on how to adjust these settings, depending on your specific processing pipeline, you might want to refer to our documentation at https://docs.ultralytics.com/hub. While I've refrained from providing direct code examples, following these general guidelines should help you maintain high quality in your cropped images. Remember, keeping a close eye on each step of your image processing pipeline is key to preserving the quality of your outputs.

Best of luck with your road sign classification project! 🚀
