### ISSUE TITLE
The Model update are not fetching on App

### ISSUE THREAD

**Issue by dharun9** [ultralytics/hub#636]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models, Projects, Training

### Bug

It's not fetching the information from web to app

**Comment by dharun9** [comment]
![IMG_20240411_234922](https://github.com/ultralytics/hub/assets/98309416/7d0c1c78-9b85-421b-87e8-d55c6a8fa29b)
![Screenshot_2024-04-11-23-48-22-62_86fb2c7910b23de5075bffb6e3566782](https://github.com/ultralytics/hub/assets/98309416/ab330146-2c64-4777-835e-0553f46bd9c9)
![Screenshot_2024-04-11-23-48-18-35_86fb2c7910b23de5075bffb6e3566782](https://github.com/ultralytics/hub/assets/98309416/f57f9501-17cb-4367-88eb-db895df0fefd)


As you can see in this picture the information is not fetching to my app, the model name is displayed but there is no trained model inside the folder ,In Web all the information are displayed correctly and I've same account for both the web and Android login

**Comment by pderrenger** [comment]
Hello! 👋 Thank you for sharing those screenshots and details. It appears there's a sync issue between the web platform and the app regarding model updates. A few things to check that might resolve the problem:

1. Ensure you're using the latest version of the app. Sometimes, these issues are resolved in updates.
2. Try logging out and then logging back into the app. This can sometimes force a refresh of the data.
3. Check your internet connection stability on your device. A poor connection might hinder the syncing process.
4. Clear the app's cache. Sometimes, old data stored in the cache can cause syncing problems.

If these steps do not solve the issue, could you report this directly through the app's feedback or support section? Please include the details you've provided here, specifically mentioning that the problem persists despite following standard troubleshooting steps.

Your participation helps improve the experience for everyone! Thanks for reaching out. 🌟
