### ISSUE TITLE
Segment Dataset from Roboflow not loading

### ISSUE THREAD

**Issue by seniorb** [ultralytics/hub#637]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

After selecting a dataset in the Hub from Roboflow, it doesn't load even after waiting over a minute.
It could be a coincidence, but it seems to only be affecting segment projects. The dataset did load last time I tried a couple of days ago.

<img width="751" alt="Screenshot 2024-04-12 103543" src="https://github.com/ultralytics/hub/assets/29486767/3e5b730d-ced1-430f-9dd2-72794394a74a">

### Environment

Ultralytics HUB Version
v0.1.39
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Operating System
Win32
Browser Window Size
1266 x 764
Server Timestamp
1712914626

### Minimal Reproducible Example

Login to Hub. Click Datasets. Click on Segment Dataset that is from Roboflow

### Additional

Things I've tried:
Logging out and back in again. 
Waiting half an hour
Refreshing the page and trying again

My temporary solution was to manually export from Roboflow and import which works

**Comment by sergiuwaxmann** [comment]
Hello @seniorb!
I just tried viewing Roboflow segment datasets in Ultralytics HUB and it works fine on my end. Maybe you can try removing the Roboflow Workspace from Settings or the Roboflow Universe dataset and import it again?

**Comment by seniorb** [comment]
I tried that just now and it didn't work unfortunately. I ended up just importing it manually

**Comment by pderrenger** [comment]
I'm sorry to hear that the issue persists, @seniorb! It's great that you found a workaround by manually importing the dataset. Meanwhile, we'll continue to investigate this problem to ensure smoother integration with Roboflow datasets in the future. If you encounter any more issues or have further questions, feel free to reach out. Your patience and contributions to improving the Ultralytics HUB are greatly appreciated! 🌟
