### ISSUE TITLE
上传数据集时，中文数据集乱码

### ISSUE THREAD

**Issue by linkuiyuan** [ultralytics/hub#639]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

上传数据集时，中文数据集乱码。解压含有中文的数据集时会有乱码。

**Comment by pderrenger** [comment]
非常感谢你的报告！遇到中文数据集乱码问题，可以尝试在上传前确保你的文件采用UTF-8编码，这通常有助于解决乱码问题。如果问题依旧，请通过我们的HUB文档页面（https://docs.ultralytics.com/hub）提供更多环境细节，以便我们更好地协助你。再次感谢你对Ultralytics社区的支持！🙌

**Comment by sergiuwaxmann** [comment]
@linkuiyuan Closing this issue as it is duplicated by #640.
