### ISSUE TITLE
How should I format my custom dataset?

### ISSUE THREAD

**Issue by Ibrahim-Ahrash** [ultralytics/hub#64]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Every time I upload my dataset i get an error says Zip Formatted Incorrectly
I tried to modify my zip file and the same I even tried to download some random dataset from roboflow and upload it and still same problem 

### Environment

Browser Chorme last version  windows 10

### Minimal Reproducible Example

Zip Formatted Incorrectly

**Comment by kalenmike** [comment]
@Ibrahim-Ahrash We have an example [dataset here](https://github.com/ultralytics/hub/blob/master/coco6.zip). If you download that you will be able to see how your dataset needs to be formatted. In the example you give above it sounds like either your zip does not contain a folder or the folder it contains is not the same name as the zip file. You can also check out the [README.md](https://github.com/ultralytics/hub) for help on formatting your dataset correctly.

I hope that the this will help you in getting your custom datasets uploaded, please let me know if you have nay more issues.

**Comment by Ibrahim-Ahrash** [comment]
> @Ibrahim-Ahrash We have an example [dataset here](https://github.com/ultralytics/hub/blob/master/coco6.zip). If you download that you will be able to see how your dataset needs to be formatted. In the example you give above it sounds like either your zip does not contain a folder or the folder it contains is not the same name as the zip file. You can also check out the [README.md](https://github.com/ultralytics/hub) for help on formatting your dataset correctly.
> 
> I hope that the this will help you in getting your custom datasets uploaded, please let me know if you have nay more issues.

Hello
Yes as you said my zip didn't contain folder holding the data instead all it was directly a train and valid folders. I moved all inside a folder and zipped the folder .
Thank you for the reply

**Comment by UltralyticsAssistant** [comment]
Hello @Ibrahim-Ahrash,

I'm glad to hear that the issue with your dataset has been resolved! Remember, the folder structure is crucial for the HUB to recognize and process your dataset correctly. If you have any more questions or encounter further issues, don't hesitate to reach out. Happy training! 🚀
