### ISSUE TITLE
how to continue my interupted work

### ISSUE THREAD

**Issue by Zero-start0** [ultralytics/hub#641]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

My work in ultralytics hub will be interupted after all epoch trained.  How to continue my work from the interupted point

**Comment by sergiuwaxmann** [comment]
Hi @Zero-start0!
When training a model using Ultralytics HUB, we try to save a checkpoint every 15 minutes. If a checkpoint is saved, you can resume training - the resume option is shown on the model page automatically.

**Comment by Zero-start0** [comment]
> Hi @Zero-start0! When training a model using Ultralytics HUB, we try to save a checkpoint every 15 minutes. If a checkpoint is saved, you can resume training - the resume option is shown on the model page automatically.

However, I see the checkpoint has been upload to hub, I can't find the resume option

**Comment by Zero-start0** [comment]
> Hi @Zero-start0! When training a model using Ultralytics HUB, we try to save a checkpoint every 15 minutes. If a checkpoint is saved, you can resume training - the resume option is shown on the model page automatically.

Could you show a detail instruction? This question drive me mad

**Comment by sergiuwaxmann** [comment]
@Zero-start0 If your model is disconnected and a checkpoint is saved, the message on the model page should be "Resume training from epoch X". What do you see on the model page?

**Comment by Zero-start0** [comment]
![image](https://github.com/ultralytics/hub/assets/63403003/032d9080-321a-4b46-a58c-4ebb8368505e)
![image](https://github.com/ultralytics/hub/assets/63403003/a45c3ef9-265f-41a2-b7b7-9c45285a4273)

**Comment by Zero-start0** [comment]
> @Zero-start0 If your model is disconnected and a checkpoint is saved, the message on the model page should be "Resume training from epoch X". What do you see on the model page?

What should I do now

**Comment by Zero-start0** [comment]
![image](https://github.com/ultralytics/hub/assets/63403003/a139b9c3-c4fb-40dc-a183-ef774c83b411)


> @Zero-start0 If your model is disconnected and a checkpoint is saved, the message on the model page should be "Resume training from epoch X". What do you see on the model page?

I can see the checkpoint, but I don't have the option

**Comment by sergiuwaxmann** [comment]
@Zero-start0 Based on the Ultralytics HUB screenshots you shared, there is no checkpoint saved in the Ultralytics HUB. I have attached an image of a model that has a checkpoint saved in the Ultralytics HUB.
![resume](https://github.com/ultralytics/hub/assets/47978446/3f228be7-52d2-4519-b28b-93c626e938b9)

Looking at the `ultralytics` logs you shared, I can see that a checkpoint began uploading - perhaps the process did not succeed or something went wrong. Our team will investigate if there is an issue on our end related to the upload, and I will keep you updated.

**Comment by Zero-start0** [comment]
> @Zero-start0 Based on the Ultralytics HUB screenshots you shared, there is no checkpoint saved in the Ultralytics HUB. I have attached an image of a model that has a checkpoint saved in the Ultralytics HUB. ![resume](https://private-user-images.githubusercontent.com/47978446/322568389-3f228be7-52d2-4519-b28b-93c626e938b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyMDE5MTcsIm5iZiI6MTcxMzIwMTYxNywicGF0aCI6Ii80Nzk3ODQ0Ni8zMjI1NjgzODktM2YyMjhiZTctNTJkMi00NTE5LWIyOGItOTNjNjI2ZTkzOGI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDE3MjAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYmJiYTIxODYwYTc1YTkxOTZhMjg1ZjhhMWYxZDQyYmU3M2M0YWQ5YTE1NzU5OGI0NmQ1NDgzY2M0NTI0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z2nrzMiRBZk5l9OfIAB7Mvi1rHgyyS3ptKnlMTeb-b8)
> 
> Looking at the logs you shared, I can see that a checkpoint began uploading - perhaps the process did not succeed or something went wrong. Our team will investigate if there is an issue on our end related to the upload, and I will keep you updated.`ultralytics`

So how can I continue my work. Any method can I use to continue

**Comment by Zero-start0** [comment]
Now I can only to use this method to train my model

from ultralytics import YOLO

# Load a model
model = YOLO('../ultralytics/runs/detect/train/weights/last.pt')  # load a partially trained model

# Resume training
results = model.train(resume=True)

**Comment by Zero-start0** [comment]
I have experienced this situation so many time. If there is any solution please contact me.

**Comment by Zero-start0** [comment]
What's more, how can I upload my trained model to the hub?

**Comment by sergiuwaxmann** [comment]
> Now I can only to use this method to train my model
> 
> from ultralytics import YOLO
> # Load a model
> 
> model = YOLO('../ultralytics/runs/detect/train/weights/last.pt') # load a partially trained model
> # Resume training
> 
> results = model.train(resume=True)

@Zero-start0 Yes, this is a valid temporary solution.
As mentioned above, I will keep you updated. Thank you for understanding!

**Comment by LightDex9** [comment]
Hello, I have the same problem, the training stops after 33 epochs and i can't resume it

**Comment by pderrenger** [comment]
Hello! 😊 If your training in Colab stops and you're unable to resume it directly, make sure you're saving checkpoints at regular intervals during training. After a stoppage, you can resume training from the last saved checkpoint by specifying its path when initializing your training command. Please make sure your code for resuming training on Colab includes the path to the checkpoint. Remember, consistent checkpoints are key for smoothly resuming training, especially in environments like Colab that have time limits on sessions.

**Comment by LightDex9** [comment]
> Hello! 😊 If your training in Colab stops and you're unable to resume it directly, make sure you're saving checkpoints at regular intervals during training. After a stoppage, you can resume training from the last saved checkpoint by specifying its path when initializing your training command. Please make sure your code for resuming training on Colab includes the path to the checkpoint. Remember, consistent checkpoints are key for smoothly resuming training, especially in environments like Colab that have time limits on sessions.

Thanks for the reply, how can i see the path where the last checkpoint is saved on Colab? During training it says "Uploading Checkpoints https://hub.ultralytics.com/models/..." every 3 epochs, but I can't see saved checkpoints on Ultralytics Hub

**Comment by Zero-start0** [comment]
> > Hello! 😊 If your training in Colab stops and you're unable to resume it directly, make sure you're saving checkpoints at regular intervals during training. After a stoppage, you can resume training from the last saved checkpoint by specifying its path when initializing your training command. Please make sure your code for resuming training on Colab includes the path to the checkpoint. Remember, consistent checkpoints are key for smoothly resuming training, especially in environments like Colab that have time limits on sessions.
> 
> Thanks for the reply, how can i see the path where the last checkpoint is saved on Colab? During training it says "Uploading Checkpoints https://hub.ultralytics.com/models/..." every 3 epochs, but I can't see saved checkpoints on Ultralytics Hub

Yeah, I have the same question. Although the Uploading Checkpoint was shown in the notebook but I can't find any checkpoint in the Ultralytics Hub

**Comment by pderrenger** [comment]
Hello! 😊 If the checkpoints appear to be uploading but aren't visible in your Ultralytics Hub account, there might be a syncing issue. Checkpoints automatically saved during training should ideally be accessible through your Hub account. If they're not there:

1. Double-check that you're logged into the correct Ultralytics Hub account.
2. Ensure there's no issue with the network connection in your Colab session that might be hindering the upload process.

If the checkpoints are still missing after these checks, it’s possible there was an issue during the upload. For now, try manually saving your models in Colab and uploading them directly to the Hub through the web interface. Keep an eye out for any updates as our team looks into smoothing out this process.

For uploading trained models to the hub directly, you can visit our documentation at https://docs.ultralytics.com/hub for step-by-step guidance! 🌟

**Comment by sergiuwaxmann** [comment]
> Thanks for the reply, how can i see the path where the last checkpoint is saved on Colab? During training it says "Uploading Checkpoints https://hub.ultralytics.com/models/..." every 3 epochs, but I can't see saved checkpoints on Ultralytics Hub.
> 
> Edit: Now I've seen that on Colab it says "WARNING ⚠️ using HUB training arguments, ignoring local training arguments." and the argument "save_period" is equal to -1 in the HUB training
> 
> ![Screenshot 2024-04-16 071439](https://private-user-images.githubusercontent.com/167091626/322709391-f8698dcb-17c9-4ec6-b83f-1b3ddbc06985.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNTIxMDUsIm5iZiI6MTcxMzI1MTgwNSwicGF0aCI6Ii8xNjcwOTE2MjYvMzIyNzA5MzkxLWY4Njk4ZGNiLTE3YzktNGVjNi1iODNmLTFiM2RkYmMwNjk4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQwNzE2NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDZlMzQ3ZjBkYmUwMDQ0ZDRhZDkwNThhNDQ4MTZlNjAxNzVlZTllNDc1OTRmMzVkMjQ5Yzc3MDRjNjE3Mjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HzU_5WkePvVgHtsFQ0Jolp6N1ZgDQmj5snhcttHkISM)

Hello @LightDex9!
Indeed, the local training arguments are ignored when training a model from Ultralytics HUB.

The log you see (`Ultralytics HUB: Uploading checkpoint...`) is shown when the upload starts but it doesn't check if the upload was successful and it doesn't retry if the job is interrupted.

Our team will investigate if there is an issue on our end related to the upload, and I will keep you updated.

**Comment by sergiuwaxmann** [comment]
@Zero-start0 @LightDex9 

I wanted to update you on the recent release from `ultralytics`, version `8.2.0`, which addresses the issue you encountered. The checkpoints are now being uploaded correctly.

For verification, I conducted a test in my local virtual environment. I modified the `"ckpt"` value from `900.0` to `1.0` in the `ultralytics/hub/session.py` file and initiated training using my local agent. The results confirmed that the fix is effective.

Please feel free to reach out if you encounter any further issues.
