### ISSUE TITLE
Upload dataset fail

### ISSUE THREAD

**Issue by togro** [ultralytics/hub#642]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

I'm trying to upload dataset zip of 638.9 MB , buy fail .

I can't see why, may be de names of files ? 

eg: "PV-Baches-Abiertos-0f6caec54dbcbdf16fa06bbbe1abc5007040fd9f9d19d2d99ee8af1a093b8386-2024-03-22-12_02_38-Wondershare-Filmora"

![image](https://github.com/ultralytics/hub/assets/7252575/c3cfca93-bd64-4d34-9491-33832fefc145)

**Comment by togro** [comment]
I try with small set like , like this doc : https://docs.ultralytics.com/hub/datasets/

But fail too ... 

[detect.zip](https://github.com/ultralytics/hub/files/14984648/detect.zip)

**Comment by togro** [comment]
Was the yaml ...

I fixed and wodks

**Comment by pderrenger** [comment]
Great to hear you've resolved the issue by fixing the YAML! If you have any more questions or run into further issues, feel free to reach out. Happy detecting! 😊
