### ISSUE TITLE
Zip Formatted Incorrectly

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/hub#65]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Hello there, Glenn. I tried to upload data on hub but it is giving me a "zip formatted incorrectly" error, even though i have compressed it in the same format as you have shown in coco6. The dataset is prepared using roboflow and it is in the format that yolov5 accepts but i am unable to proceed ahead due to this error.

### Environment

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/97718899/181104431-f334df95-3e9a-47dc-999d-392c52cc719b.png">

**Comment by kalenmike** [comment]
@rexayyy The formatting is still very strict at the moment, we are working to try and make it less so. If you are seeing that error it is likely that either your dataset zip does not contain a folder but rather the files themselves or the name of the zip does not match the name of the folder inside the zip. Can you verify those to things and let me know if it solves your error?

**Comment by barney2074** [comment]
it also took me a few tries to get it right
A screenshot like this of your zip file would help
![](https://user-images.githubusercontent.com/26833433/141502652-e4b0477c-6c2a-41b3-b21a-b3d1444cdda7.png)

**Comment by rexayyy** [comment]
![Screen Shot 2022-07-27 at 2 26 29 PM](https://user-images.githubusercontent.com/97718899/181212913-d1582c36-e3c9-4544-b040-e888a1b9f44f.png)
![Screen Shot 2022-07-27 at 2 25 52 PM](https://user-images.githubusercontent.com/97718899/181213916-53edd471-e7b2-40ee-b40e-2066af8fb276.png)

**Comment by barney2074** [comment]
Mike will be able to say for sure- I don't know if it is case sensitive- but your folder (& presumably zip file) is called 'Data', whereas your yaml is 'data'

**Comment by rexayyy** [comment]
i will give that a try and get  back to you

**Comment by rexayyy** [comment]
I got this now, even though all the files are in the right folders as i have shown you in the previous ss
![Screen Shot 2022-07-27 at 3 14 44 PM](https://user-images.githubusercontent.com/97718899/181223080-bf94dae6-adc9-4d5d-9c2e-e40e1fa8f07b.png)

**Comment by barney2074** [comment]
looks like the yaml has capital D data

**Comment by rexayyy** [comment]
![Screen Shot 2022-07-27 at 3 17 41 PM](https://user-images.githubusercontent.com/97718899/181223634-5136d1cd-88bd-46ef-ac2e-50df915b45f5.png)

**Comment by barney2074** [comment]
I mean the text for the paths inside the yaml file

**Comment by rexayyy** [comment]
would you please show me by opening and screen shoting your .yaml file

**Comment by rexayyy** [comment]
![Screen Shot 2022-07-27 at 3 23 23 PM](https://user-images.githubusercontent.com/97718899/181224735-9497e1da-9f56-4301-b2b3-c41724be3753.png)

**Comment by rexayyy** [comment]
i got the mistake, i am trying with fixing it

**Comment by rexayyy** [comment]
it is still not working for me

**Comment by barney2074** [comment]
(disregard my previous comment about the path in the yaml- I was incorrect in thinking it contains the parent 'Data' folder)

Your yaml has '../train/images' whereas the example has 'images/train' and this corresponds with your file structure
I'd take the example yaml and just update your classes

![image](https://user-images.githubusercontent.com/25944617/181235997-20d97c7f-ae36-4301-b8e9-2c44bc6065d2.png)

**Comment by rexayyy** [comment]
yes Barney, thank you so much for helping. I figured it out after hit and trial and got it right

**Comment by Alhashim2** [comment]
@rexayyy  can you please help how you got it to work. I am facing the same issue 

@barney2074  kindly help if you spot anything wrong 
here are my files structure.

![Screen Shot 2022-07-31 at 6 59 55 PM](https://user-images.githubusercontent.com/94074621/182034984-a71be1c7-cae4-4ca3-af3e-5de4a25966d8.png)
![Screen Shot 2022-07-31 at 6 58 56 PM](https://user-images.githubusercontent.com/94074621/182034993-275bc02e-657d-4876-a7bc-ba49be3c3a45.png)

**Comment by glenn-jocher** [comment]
@Alhashim2 your YAML is not formatted correctly, i.e. you don't have correct spacing. You can open your YAML in any editor and it will automatically indicate errors, i.e. if I remove the spacing from a field in PyCharm:

<img width="700" alt="Screen Shot 2022-07-31 at 6 11 41 PM" src="https://user-images.githubusercontent.com/26833433/182035428-bf1df3a4-66e3-4dca-aaaf-b5e282b650d2.png">

**Comment by Alhashim2** [comment]
@glenn-jocher  Thanks for the reply, I have added the space and below is a snapshot of it. 

but when space is added, i get another error the uploader is telling me Invalid dataset (see snapshot)

![Screen Shot 2022-07-31 at 8 25 55 PM](https://user-images.githubu
![Screen Shot 2022-07-31 at 8 24 31 PM](https://user-images.githubusercontent.com/94074621/182038304-0a194084-1619-401a-8a52-e3a7b0da2551.png)
sercontent.com/94074621/182038292-2c5d03bf-d41d-4962-bea8-c61b752d402f.png)

**Comment by kalenmike** [comment]
@Alhashim2 Are you 100% sure you are zipping the folder containing the content and not just zipping the content?

**Comment by Alhashim2** [comment]
@kalenmike Much appreciated that worked I was zipping the content without the outer folder.

**Comment by rexayyy** [comment]
dataset is uploaded successfully but i get the dataset error while running the train. Any idea??
