### ISSUE TITLE
Is it possible to export training results?

### ISSUE THREAD

**Issue by henningheyen** [ultralytics/hub#651]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hey, 

I trained a custom model using the Ultalytics Hub. Now I would like to export the training results (charts, weights, etc). Similar to "runs/detect/train/" when training locally. 

Is there such an export feature?

### Environment Details

- Ultralytics HUB Version: v0.1.40
- Client User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2.1 Safari/605.1.15
- Operating System: MacIntel
- Browser Window Size: 1920 x 1000
- Server Timestamp: 1713615377

**Comment by pderrenger** [comment]
@henningheyen hey there! 😊

Absolutely, you can export your training results from the Ultralytics Hub. Once your model training is complete, you'll find options to download the trained weights, charts detailing the training progress, and other relevant results. Look for a "Download" or "Export" button or section in the interface associated with your completed training session.

If you're having trouble finding this or need more detailed steps, I strongly recommend reviewing the Ultralytics HUB Docs for guidance on managing and exporting your training results.

Thank you for exploring the Ultralytics HUB, and happy modeling!

**Comment by yogendrasinghx** [comment]
Yes, we support exporting training results like charts and weights from the Ultralytics Hub using our HUB SDK. You can easily accomplish this with the following Python code snippet:

```python
from hub_sdk import HUBClient

# Initialize the HUBClient with your API key
credentials = {"api_key": "<API-KEY>"}
client = HUBClient(credentials)
print("Authenticated:", client.authenticated)

# Access your trained model by its ID
model = client.model("<MODEL-ID>")

# Retrieve metrics from the model
metrics = model.get_metrics()
print("Metrics Data:", metrics)

# Get a URL to download the best model weights
weight_url = model.get_weights_url("best")
print("Weight URL link:", weight_url)
```

Make sure to replace `<API-KEY>` and `<MODEL-ID>` with your actual API key and model ID. This script will authenticate you, fetch the training metrics, and provide a direct link to download the best weights.

For more details and additional functionalities, refer to the [Ultralytics HUB SDK documentation](https://docs.ultralytics.com/hub/sdk/).
