### ISSUE TITLE
Subscription not canceled

### ISSUE THREAD

**Issue by pablofntdz** [ultralytics/hub#655]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I  made the decision to delete my account associated with Ultralytics Hub one moth ago. However, I realized that I had an active subscription tied to this account.
I've noticed that I've been charged for this month's subscription, but my account has been deleted, so I can't access it. I'd appreciate your assistance in resolving this issue as soon as possible. Thank you
Data account:
email: [huuj65@gmail.com]
user: Pablo Font

**Comment by sergiuwaxmann** [comment]
Hello @pablofntdz!

We sincerely apologize for the inconvenience caused. Maybe there was an oversight in our system which allowed the subscription charges to continue after your account was deleted. Thank you for bringing this to our attention.

We have issued a refund for this month's charge and have taken steps to ensure that there will be no further charges in the future. You should see the refund on your card within 5-10 business days.

**Comment by WidiaPrasetia** [comment]
@sergiuwaxmann sorry sir, i will ask a question for you
If I cancel my plans, can I get a refund?
thankyou, best regards
