### ISSUE TITLE
Yolo9 ClassNames

### ISSUE THREAD

**Issue by makbarin** [ultralytics/hub#656]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Where can I find classnames for Yolo9 .pt model? I am looking for "deer" ClassID name. 
Thank you,

**Comment by pderrenger** [comment]
Hello! 😊 For the YOLOv9 model, you can find the class names, including the one for "deer", directly in the model's `.pt` file or in the `data.yaml` file associated with the dataset you used for training. If you're using one of our pre-trained models, the class names will align with the COCO dataset classes. For specific guidance on accessing these details, please refer to our documentation at https://docs.ultralytics.com/hub. If "deer" is part of the dataset classes, it should be listed there. Happy coding!
