### ISSUE TITLE
UBM_Tesis

### ISSUE THREAD

**Issue by marcelocl1363** [ultralytics/hub#659]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Algo en proceso

### Use case

Medicina

### Additional

Por ahora nada

**Comment by pderrenger** [comment]
@marcelocl1363 hola UBM_Tesis! 👋

Parece que estás trabajando en algo relacionado con Medicina y tienes algo "en proceso". Nos encantaría ayudarte mejor. ¿Podrías dar más detalles sobre lo que necesitas o sobre el tipo de característica que te gustaría ver en el Ultralytics HUB? Entender específicamente tu caso de uso nos ayudará a brindarte el apoyo más adecuado.

Mientras tanto, te recomiendo visitar nuestra documentación en https://docs.ultralytics.com/hub para más información que podría ser de ayuda.

¡Esperamos tu respuesta! 😊

**Comment by sergiuwaxmann** [comment]
Closing this issue as duplicate. Will continue the discussion on the #668 issue.

**Comment by marcelocl1363** [comment]
Hi Paula, I am working on my thesis about detecting some organs on UBM
images. These are ultrasound images.

I had a great advance using Roboflow and Ultralyctis.

I will try to finish on August. By the way I prefer do not mentioned until
the presentation. Thanks a lot.

Regards,

Marcelo Letamendía.
Scientific Data.
Electrical Enginner.
Med & Tech s.a.
Argentina

**Comment by marcelocl1363** [comment]
Muchas gracias Paula, seguramente me surgirán dudas, se las haré saber.

Mis más cordiales saludos.

Marcelo.

**Comment by pderrenger** [comment]
@marcelocl1363 ¡Claro, Marcelo! ✨ No dudes en hacernos llegar tus dudas cuando surjan. Estamos aquí para ayudarte a que tu proyecto sea un éxito. 

¡Te deseo lo mejor con tu tesis y espero escuchar sobre tu avance!

Saludos cordiales,

Paula
