### ISSUE TITLE
Storage does not reduce after deleting dataset

### ISSUE THREAD

**Issue by Denizzje** [ultralytics/hub#66]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Hello all,

I have invited myself to the beta after finding the Hub by sheer coincidence and I can say this has some true potential!

When I just started out, I made things easy for myself by inmediately starting with a full size, unresized dataset, and misunderstanding the preparing dataset page. I thus did quite some retries with various datasets. I always deleted those, but now my storage does seem to be full.

![image](https://user-images.githubusercontent.com/25279882/181907779-35eda2f4-5b58-4a39-920d-9e8a132a40ec.png)

While this is the current sizes of my own uploaded datasets:

![image](https://user-images.githubusercontent.com/25279882/181907807-df10d7c9-e033-4863-a419-e44a31bb1daa.png)

It does prevent me from uploading any new datasets at the moment with the message "storage is full". So either the files arent truely deleted, or the storage counter isnt deducting it properly.

### Environment

Ultralytics HUB Version
v0.1.15-beta.1
Client User Agent
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Operating System
Win32
Browser Window Size
2560 x 1355
Server Timestamp
1659178770

### Minimal Reproducible Example

1. Login  to hub
2. Upload massive dataset and prepare the data incorrectly
3. Wait for it to fail
4. Delete dataset

### Additional

I think I encountered another  bug with big datasets (after I manage to do them correctly now), it shows processing has failed while it is actually still processing... it was just magically ready the next day after being failed.

**Comment by glenn-jocher** [comment]
@Denizzje thanks for the bug report! We have a known issue at the moment with immediate deletion of items, currently they are redirected to a 30 day trashcan that you can't see. We are working on a trash can tool where you'll be able to empty your trashcan and regain all your storage. This should be out soon. 

In the meantime @kalenmike can empty your trashcan if you provide your login email.

**Comment by kalenmike** [comment]
@Denizzje We will have the trash can live this week which will give you the option to permanently delete your files. As @glenn-jocher  mentioned I can empty your files for you, but I will need your account email. You can send it to me at kalen.michael@ultralytics.com 

Thanks for pointing out the issue in your additional section as well. We have a fallback for timeout errors that is being triggered if the processing takes too long, we will look into fixing this.

**Comment by Denizzje** [comment]
Thanks for the replies @glenn-jocher and @kalenmike , I sent an email to Kalen. It is good to know however that soon I shall be able to clean up after myself ;).

**Comment by kalenmike** [comment]
@Denizzje Your account is now reset. Please let me know if you have any issues.
