### ISSUE TITLE
ThesisUBM

### ISSUE THREAD

**Issue by marcelocl1363** [ultralytics/hub#668]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Esperando una autorizacion

### Use case

UMB ultrasound

**Comment by pderrenger** [comment]
Hello, ThesisUBM! 🌟 It seems like you're awaiting an authorization for a specific use case related to UMB ultrasound. To offer you more targeted assistance, could you please provide a bit more detail on the type of authorization you're referring to? Are you looking for access permissions, API keys, or something else? This will help us direct you appropriately or offer the right guidance. For immediate general information, don't forget to check our Docs at https://docs.ultralytics.com/hub. Looking forward to hearing more from you!

**Comment by marcelocl1363** [comment]
Hello Paula, I sent e-mail few minutes ago.

I want to view the inference image on my Jupyter Notebook.

Thanks a lot. Regards,

Marcelo Letamendía.
