### ISSUE TITLE
Can I resume training that reported a timeout?

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/hub#67]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

<img width="1188" alt="Annotation 2022-08-02 153700" src="https://user-images.githubusercontent.com/97718899/182355195-92d11f90-8393-4f0e-8389-d188900b3ead.png">
 is there anyway i can resume the training from where it has failed, as the error message is time-out. The linked colab is unable to run the code.
<img width="1304" alt="Annotation 2022-08-02 153851" src="https://user-images.githubusercontent.com/97718899/182355511-52c4daaa-7529-40b6-b129-5c9437ec3d4d.png">

**Comment by kalenmike** [comment]
@rexayyy Unfortunately we do not currently offer any resume capabilities. The work is currently being done on YOLOv5 and once it is finished we will add resume capabilities into the Ultralytics HUB.

**Comment by rexayyy** [comment]
Is there any way to avoid this kind of failures?

**Comment by kalenmike** [comment]
@rexayyy The Colab instance does not stay active if you do not interact with it. You can train using your own agent, by selecting 'Bring your own agent' and following the setup guide to start training on your own or cloud hardware.

**Comment by glenn-jocher** [comment]
@rexayyy thanks for the question! 

@kalenmike I see this could be pretty useful for Colab users. I'll prioritize the --resume single-file packaging feature we discussed.

**Comment by kalenmike** [comment]
The work is coming along and we are expecting the have this feature live in the next 3 days.

**Comment by rexayyy** [comment]
Brilliant! I am very excited to try this. Thank you so much

**Comment by kalenmike** [comment]
@rexayyy We are excited to comment that we have now deployed the training resume feature. This will only apply to models that started training from 05 August 2022 16:00 GMT as additional data has to be embedded in the weights. 

To resume training a model simply pass the same API key and the Ultralytics pip package will resume from the last saved checkpoint.

It would be great to hear your feedback on this feature and let us know if there is anything else we should consider to improve your workflow.

**Comment by Denizzje** [comment]
Hey Kalen,

As I was testing this very useful feature by both timing out on a Colab background execution and training on a normal VM (with just temporary storage) and stopping the training, I came to the grave realisation that I didnt save the API keys. Put them in a notepad and then forgot to save it :). 

It would be nice if the training key is displayed or requestable somewhere.

**Comment by glenn-jocher** [comment]
@Denizzje thanks for the feedback! This is a very good point.

@kalenmike we probably want to show the API-model key during training, and then we can remove it once training completes successfully.

**Comment by kalenmike** [comment]
@Denizzje Yes we are busy working to show the API key in the model page. For the moment you can get them your self as they are a combination of your API key on your settings page and your model id in the URL joined with an underscore.

https://hub.ultralytics.com/settings/api-keys = YYYYYYYYYYY

https://hub.ultralytics.com/models/XXXXXXXXXXXXX

Model API key = YYYYYYYYYYY_XXXXXXXXXXX

**Comment by kalenmike** [comment]
API keys for training models can now be requested on the model page while the model is still in training.

**Comment by Denizzje** [comment]
@glenn-jocher @kalenmike I confirm that this feature works brilliantly, after having succesfully failed my training runs on purpose. Both the Colab ""Pro +"" background execution training , and the more difficult one, a Lambda labs RTX A6000 VM which I abruptly stopped training for and connected it to a completely different enviornment (Paperspace Gradient free GPU) worked like a charm to resume.

Perhaps "plugging into" a completly different enviornment has some unintended side effects to model training / results but this is potentially such a great feature especially for those with a limited training budget.

**Comment by kalenmike** [comment]
@Denizzje Thanks for the feedback and great to hear its working for you! We were also pretty excited about this feature!

**Comment by glenn-jocher** [comment]
@Denizzje awesome! That's super cool that you resumed from a completely different environment!!
