### ISSUE TITLE
Ultra2Seg

### ISSUE THREAD

**Issue by marcelocl1363** [ultralytics/hub#672]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Segmentacion

### Use case

Viendo si puedo segmentar

**Comment by pderrenger** [comment]
Hi! Thanks for reaching out. 🌟 It seems like you're interested in segmentation capabilities with Ultralytics. While our primary focus has been on object detection with YOLO models, segmentation is a bit out of our current scope. However, I'd recommend checking our Docs at https://docs.ultralytics.com/hub for updates and more info on what's available and upcoming features. Your interest helps guide what we might consider adding in the future, so we truly appreciate your input! Keep the ideas coming. 🚀
