### ISSUE TITLE
Using Ultralytics SAHI Tiled Inference in Ultralytics Hub

### ISSUE THREAD

**Issue by Sabeeh-H** [ultralytics/hub#673]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I would like to use SAHI in order to process large images with smaller objects in Ultralytics Hub. However, I could not find any place to use it prior to deployment, is there any way I can call the function in Hub, or do I have to use a virtual machine for it instead?

**Comment by pderrenger** [comment]
Hello! 😊 We're glad you're interested in using SAHI for tiled inference with large images in Ultralytics HUB. Currently, the HUB doesn't directly support the SAHI utility within its user interface or API for preprocessing large images before deployment.

For now, you'd need to process your images using SAHI locally or in a virtual machine environment before uploading the processed images or deploying models in the HUB. This step involves using SAHI to slice your large images into smaller, manageable tiles, perform inference on each tile, and then merge the results.

For detailed instructions on how to use SAHI with YOLO models, including slicing and merging strategies, please refer to the official SAHI documentation and examples. Remember, after processing your images with SAHI, you can easily upload and manage your models or inference results directly in the Ultralytics HUB.

If you have further questions or need assistance with other features in the HUB, feel free to reach out. Happy detecting!
