### ISSUE TITLE
@sergiuwaxmann @glenn-jocher   could you please explain why your system is deducting 2 bills for single model training ??

### ISSUE THREAD

**Issue by kumarneeraj2005** [ultralytics/hub#675]
@sergiuwaxmann @glenn-jocher   could you please explain why your system is deducting 2 bills for single model training ??
<img width="1291" alt="image" src="https://github.com/ultralytics/hub/assets/8565041/62408651-0a23-4e02-a977-22cbd037aa40">

_Originally posted by @kumarneeraj2005 in https://github.com/ultralytics/hub/issues/665#issuecomment-2094700089_

**Comment by sergiuwaxmann** [comment]
@kumarneeraj2005 I replied [here](https://github.com/ultralytics/hub/issues/665#issuecomment-2094790876). I will investigate this issue and update you as soon as possible. Thank you for your patience!

**Comment by sergiuwaxmann** [comment]
@kumarneeraj2005 I just checked our logs and it looks like the first Cloud Training session crashed after ~16 hours and you resumed training (started a new Cloud Training session) ~3 hours later that finished successfully (~39 hours). The account balance wasn't deducted concurrently or wrongfully.
As suspected, this is a UI issue that our team will handle in the next release. Thank you for bringing this to our attention.
