### ISSUE TITLE
How to train my images using the android mobile version of YOLOV8 model

### ISSUE THREAD

**Issue by abddawn174** [ultralytics/hub#678]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Training using mobile app

### Use case

I want to train my dataset using the mobile app

**Comment by sergiuwaxmann** [comment]
@abddawn174 Hello!
You can train your dataset using [Ultralytics HUB Web](https://hub.ultralytics.com) and after training, load the trained model in the [Ultralytics HUB App](https://www.ultralytics.com/app-install).
You can read more about using Ultralytics HUB on [our docs](https://docs.ultralytics.com/hub).
