### ISSUE TITLE
Train two models using Ultralytics cloud in Pro mode

### ISSUE THREAD

**Issue by vintagefilmography** [ultralytics/hub#679]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I would like to combine two data sets and train them using my pro account in the hub cloud. For example I want to detect store aisle  using the SKU-110K dataset but that one will not detect  people or obstacles  in the aisle so I want to add the COCO2017 to it and train it using the cloud because my PC is slow.

**Comment by pderrenger** [comment]
@vintagefilmography hello! Training a combined dataset using your Pro account on Ultralytics Cloud is a great way to leverage the power of both the SKU-110K and COCO2017 datasets. To get started, you'll first need to merge these datasets. Ensure that both datasets are formatted consistently (e.g., annotations and labels) before merging them into a single dataset.

Once your dataset is ready, upload it to the HUB and then start your training process using the cloud environment. You can monitor the training progress directly from your dashboard and even tweak the settings as needed for optimal results.

For detailed steps on dataset preparation, uploading, and training, please refer to the Ultralytics HUB Docs. If you need further assistance, feel free to reach out on the community discussions!

Happy training! 😊

**Comment by vintagefilmography** [comment]
Thank you Paul,
That is good news that it can be done and does not seem to be too difficult.
Regards,
Statn

**Comment by pderrenger** [comment]
Hello Statn,

You're welcome! I'm glad to hear you found the information helpful and manageable. If you have any more questions or need further assistance as you get started with your training, don't hesitate to reach out. Good luck with your project! 🚀
