### ISSUE TITLE
Is it possilbe to upload custom models? If not could this be added?

### ISSUE THREAD

**Issue by mrKallah** [ultralytics/hub#68]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is it possilbe to upload custom models? If not could this be added?

**Comment by kalenmike** [comment]
@mrKallah Thanks for the question. We are not currently considering custom models to be uploaded. This is mainly because custom models would be very limited at the moment as we they would not contain any of the other information we show (metrics, dataset, etc).

This is related to #46 and #43
