### ISSUE TITLE
YAML file creation 

### ISSUE THREAD

**Issue by abddawn174** [ultralytics/hub#680]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I need a guide on composing YAML file compatible with the Ultralytics hub training web.

### Additional

I want to compose the YAML code for my custom dataset

**Comment by pderrenger** [comment]
@abddawn174 hello!

Great to hear you're setting up your YAML for a custom dataset! For a compatible YAML file in the Ultralytics HUB, you will structure it to mainly include the paths to your train and validation data sets, class names, and the number of classes.

The general format looks like this:
- **path**: top-level config pointing to the dataset root
- **train**: subpath to training images
- **val**: subpath to validation images
- **nc**: number of classes
- **names**: list of class names

To tailor it to your needs, specify paths and classes directly corresponding to your dataset structure. For a comprehensive explanation and other configuration details, please visit the Ultralytics HUB Documentation at https://docs.ultralytics.com/hub.📘

Best of luck with your project! If you have any more questions, feel free to ask. 😊

**Comment by sergiuwaxmann** [comment]
Hello @abddawn174!

Here are some links that will help you format your dataset YAML:
- [Detect](https://docs.ultralytics.com/datasets/detect/#ultralytics-yolo-format)
- [Segment](https://docs.ultralytics.com/datasets/segment/#dataset-yaml-format)
- [Pose](https://docs.ultralytics.com/datasets/pose/#dataset-yaml-format)
