### ISSUE TITLE
Not able to export the model for Android or iOS and also not able to test by uploading any image or capture with camera

### ISSUE THREAD

**Issue by prathamgyanani** [ultralytics/hub#686]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Not able to export the model for Android or iOS and also not able to test by uploading any image or capture with camera

**Comment by pderrenger** [comment]
@prathamgyanani hello! Thanks for reaching out. I'm sorry to hear that you're experiencing issues with exporting your model for Android/iOS and testing it with images or camera captures.

To resolve the export problem, ensure that you are following the correct steps outlined in our documentation for exporting models. Each platform (Android/iOS) may have specific requirements or settings that need to be adjusted.

For testing images or using the camera, please double-check that you have the necessary permissions enabled on your device if you're testing directly from a mobile device. Additionally, verify that the app or testing environment is correctly set up to handle file uploads and camera inputs.

If these tips don't resolve the issues, could you please provide more details about the errors you are encountering or any specific steps you've followed? This will help us identify the issue more effectively. We're here to help! 😊

**Comment by prathamgyanani** [comment]
![image](https://github.com/ultralytics/hub/assets/97597687/a5f67515-ec2b-4dfc-a392-f4bf8cdc7288)
![image](https://github.com/ultralytics/hub/assets/97597687/998fe3a3-4e4e-4ccd-ae87-ecf39e7dfc15)


I am not able to export anything from the hub platform after 10+ trials

**Comment by sergiuwaxmann** [comment]
@prathamgyanani We just tested exports and everything seems to be working fine.
Can you please share your model ID so we can investigate this further?

CC @yogendrasinghx

**Comment by prathamgyanani** [comment]
https://hub.ultralytics.com/models/fI4aYOq3oIWBLDXAeHxQ
this is the model id of my model

**Comment by sergiuwaxmann** [comment]
@prathamgyanani Thank you!
I can confirm the inference issue. Our team will investigate it and fix it in the next release. I will keep you updated.

**Comment by sergiuwaxmann** [comment]
@prathamgyanani Can you check if you still have this issue?

Inference on my `YOLOv8n` model trained on the [CarParts dataset](https://hub.ultralytics.com/datasets/0ypXu21SQni55IfGErsC):
![hub_686_voc](https://github.com/ultralytics/hub/assets/47978446/88a17e86-3648-462f-9df0-92a9d5e4e664)

**Comment by prathamgyanani** [comment]
No, I am not. same issue and i have trained another models also facing the
same issue

**Comment by prathamgyanani** [comment]
Ok, let me know.

**Comment by sergiuwaxmann** [comment]
@prathamgyanani Sure. Thank you for your patience!

**Comment by sergiuwaxmann** [comment]
@prathamgyanani 
New release 🚀 Inference and exports should work fine now.

**Comment by prathamgyanani** [comment]
It works! on Deployment and by giving image or using camera also works but
now export for android and IOS is showing unavailable[image: image.png]

**Comment by sergiuwaxmann** [comment]
@prathamgyanani The Ultralytics HUB App exports are working, but only for detect models, as the Ultralytics HUB App supports only detect models. I guess you are looking at a classify/obb/segment/pose model, correct?

Since the Ultralytics HUB App currently supports only detect models, if we left the exports enabled for the other tasks, you would just use unnecessary space from your storage.
