### ISSUE TITLE
Nguyen9789

### ISSUE THREAD

**Issue by nguyen9789** [ultralytics/hub#689]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Tesst luan van thac si

**Comment by pderrenger** [comment]
Hello @nguyen9789,

Thanks for reaching out! It seems like your message might be incomplete. Could you please provide more details about the feature request or the issue you're encountering? This will help us assist you better! 😊

Looking forward to your response!
