### ISSUE TITLE
Camera not working

### ISSUE THREAD

**Issue by SwirX** [ultralytics/hub#69]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

when I just downloaded the app it was working fine but after I logged in with github and returned to the main page the screen was black then I closed and re opened the app but I had the same problem I went and declined the camera permission then re-allowed the app but it still not working

### Environment

- Mobile: Redmi Note 9s
- CPU:Snapdragon 720G Octa-core Max2.32GHz
- Android 11

### Minimal Reproducible Example

logged in with github and returned to the main page the screen was black

**Comment by glenn-jocher** [comment]
@SwirX hi thanks for the bug report! You should accept the camera permissions the first time you open the app after install. If you declined the permissions then the app will not be able to use your camera and the screen will be black. In this case please uninstall and reinstall to accept the permissions. 

If the issue persists after following the above steps please let us know, thank you!
