### ISSUE TITLE
Yolov8 segmentation model preview

### ISSUE THREAD

**Issue by StudentMihaZorman** [ultralytics/hub#691]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

Hello, when I train the Yolov8 segmentation model, it completes successfully. However, I always get an error when testing the model: "An error has occurred. Please try again later."

![Screenshot from 2024-05-21 09-22-31](https://github.com/ultralytics/hub/assets/114138037/e588585b-d105-432b-9373-cbd314842fa2)

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman Hello!
Can you share the model ID (model page URL) so I can investigate this further?

**Comment by StudentMihaZorman** [comment]
https://api.ultralytics.com/v1/predict/WjqdRQUdXL74S30JtM1Z

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman Thank you!
I will keep you updated.

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman Can you maybe share an image that has this issue? Or does this issue occur for any image?

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman The current inference is in a shared environment and it might fail **sometimes for large models** when the usage is high. Our team is working on developing a dedicated inference solution to fix this scenario.
Do you always have this issue for the same image?

**Comment by StudentMihaZorman** [comment]
Hi,

I have thease error on any image.


Thease is a dataset which i used for training model: https://hub.ultralytics.com/datasets/URbF3dtnQ69ldn2ZxuFX
________________________________

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman Do you mind sharing your dataset `.zip` with me so I can run some tests on my end? I can't directly access a user's datasets.

**Comment by StudentMihaZorman** [comment]
[https://res-h3.public.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]detect_seg_2_21_5_2024.zip<https://unilj-my.sharepoint.com/:u:/g/personal/mz0989_student_uni-lj_si/EZmNdMav8LdLtZONeI4_coQBi_1hlAG2Il3U1EsWFbA5pw>
________________________________
Od: Sergiu Waxmann ***@***.***>
Poslano: torek, 21. maj 2024 19:05
Za: ultralytics/hub ***@***.***>
Kp: ZORMAN, miha ***@***.***>; Mention ***@***.***>
Zadeva: Re: [ultralytics/hub] Yolov8 segmentation model preview (Issue #691)


@StudentMihaZorman<https://github.com/StudentMihaZorman> Do you mind sharing your dataset .zip with me so I can run some tests on my end? I can't directly access a user's datasets.

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman Thank you! I will keep you updated.
![github_issue_691](https://github.com/ultralytics/hub/assets/47978446/86026ea7-9cfb-49c5-90b3-d9f956fc6403)

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman I just trained a `YOLOv8x-SEG` for 100 epochs on [your dataset](https://unilj-my.sharepoint.com/:u:/g/personal/mz0989_student_uni-lj_si/EZmNdMav8LdLtZONeI4_coQBi_1hlAG2Il3U1EsWFbA5pw) using [Ultralytics Cloud](https://docs.ultralytics.com/hub/cloud-training) and everything works fine for me:
![github_issue_691](https://github.com/ultralytics/hub/assets/47978446/7cd77a7b-f86b-4da6-aa26-b1017887528f)

Maybe it was a temporary issue (because of the shared environment)?

I made the model's privacy **unlisted** so you can view it - [read more about sharing a model](https://docs.ultralytics.com/hub/models#share-model).
Here is a link to the model: https://hub.ultralytics.com/models/hwCgGlgWsPhwFTL4HzCz.
![github_issue_691_unlisted](https://github.com/ultralytics/hub/assets/47978446/21a62d2c-c9da-4177-bf10-4029adebb53c)

**Comment by StudentMihaZorman** [comment]
thank you very much
________________________________
Od: Sergiu Waxmann ***@***.***>
Poslano: torek, 21. maj 2024 19:45
Za: ultralytics/hub ***@***.***>
Kp: ZORMAN, miha ***@***.***>; Mention ***@***.***>
Zadeva: Re: [ultralytics/hub] Yolov8 segmentation model preview (Issue #691)


@StudentMihaZorman<https://github.com/StudentMihaZorman> I just trained a YOLOv8x-SEG for 100 epochs on your dataset<https://unilj-my.sharepoint.com/:u:/g/personal/mz0989_student_uni-lj_si/EZmNdMav8LdLtZONeI4_coQBi_1hlAG2Il3U1EsWFbA5pw> using Ultralytics Cloud<https://docs.ultralytics.com/hub/cloud-training> and everything works fine for me:
github_issue_691.png (view on web)<https://github.com/ultralytics/hub/assets/47978446/7cd77a7b-f86b-4da6-aa26-b1017887528f>

Maybe it was a temporary issue (because of the shared environment)?

I made the model's privacy unlisted so you can view it - read more about sharing a model<https://docs.ultralytics.com/hub/models#share-model>.
Here is a link to the model: https://hub.ultralytics.com/models/hwCgGlgWsPhwFTL4HzCz.
github_issue_691_unlisted.jpeg (view on web)<https://github.com/ultralytics/hub/assets/47978446/21a62d2c-c9da-4177-bf10-4029adebb53c>

**Comment by sergiuwaxmann** [comment]
@StudentMihaZorman You're welcome! Don't hesitate to reach out if you have more questions!

**Comment by suren1986** [comment]
> @StudentMihaZorman I just trained a `YOLOv8x-SEG` for 100 epochs on [your dataset](https://unilj-my.sharepoint.com/:u:/g/personal/mz0989_student_uni-lj_si/EZmNdMav8LdLtZONeI4_coQBi_1hlAG2Il3U1EsWFbA5pw) using [Ultralytics Cloud](https://docs.ultralytics.com/hub/cloud-training) and everything works fine for me: ![github_issue_691](https://private-user-images.githubusercontent.com/47978446/332524860-7cd77a7b-f86b-4da6-aa26-b1017887528f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDc1OTIsIm5iZiI6MTcxNjM0NzI5MiwicGF0aCI6Ii80Nzk3ODQ0Ni8zMzI1MjQ4NjAtN2NkNzdhN2ItZjg2Yi00ZGE2LWFhMjYtYjEwMTc4ODc1MjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDAzMDgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4NTViMTYyYzE2MmE2Nzk0ZDliNDRiNmJkMjE5ZTkzMzkxYmFkYmRlYzIzNTFlYTM4ZmY5MmJhZTliN2I1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iuUFep4BgD5XE4IsHfuP0a7Tr7dNY-6OyyK1RyiFkdc)
> 
> Maybe it was a temporary issue (because of the shared environment)? When you are uploading an image, maybe make it smaller so that the server can process it faster?
> 
> I made the model's privacy **unlisted** so you can view it - [read more about sharing a model](https://docs.ultralytics.com/hub/models#share-model). Here is a link to the model: https://hub.ultralytics.com/models/hwCgGlgWsPhwFTL4HzCz. ![github_issue_691_unlisted](https://private-user-images.githubusercontent.com/47978446/332525748-21a62d2c-c9da-4177-bf10-4029adebb53c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNDc1OTIsIm5iZiI6MTcxNjM0NzI5MiwicGF0aCI6Ii80Nzk3ODQ0Ni8zMzI1MjU3NDgtMjFhNjJkMmMtYzlkYS00MTc3LWJmMTAtNDAyOWFkZWJiNTNjLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwMzA4MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODI4YTE1ODEwZTY3M2IyNGFlNzVlZWU3OGRjYWRkOWQwYTU2MTIxYzc2NjI5NzdjMTY4YTBkMTU5MjEwZmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7Kq3ooFdRNJCcfi9nXncr0Ipf-jVvWj-AqsN5EgZTRY)

I`m from #682 , I`m also meeting this problem.
I trained a model today, when I previewed this model, the error "An error has occurred. Please try again later." happend.
While I trained a model month ago, I works fine.

My dataset: https://hub.ultralytics.com/datasets/RCo82CmjIiW6LdiCf4c7
The model I trained today: https://hub.ultralytics.com/models/1JRAn4RtCD7XygyPLAmI
The model I trained one month ago: https://hub.ultralytics.com/models/yWb4FSzpQ9wBXqf5WzCX
Instead of using Ultralytics Cloud, I use Google Colab to train my model.

The error screen shot.
<img width="1286" alt="图片" src="https://github.com/ultralytics/hub/assets/1575035/66e330a0-8591-4251-87c2-c183a75f6a04">
