### ISSUE TITLE
Model Uploading

### ISSUE THREAD

**Issue by rag0nn** [ultralytics/hub#692]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I am trying to upload my custom yolo model to hub but Model upload button does not appear. 
I heard the button from this issue talk: https://github.com/ultralytics/ultralytics/issues/12845#issuecomment-2122970927 
I've tried use different browser such as Brave, Edge, Chrome but result is same.

**Comment by sergiuwaxmann** [comment]
@rag0nn Hi there!

There is no **Upload Model** yet - we are planning on adding such button in the future.

At the moment, [Ultralytics HUB](https://hub.ultralytics.com) allows you to create models and train them using the UI as described in the [documentation](https://docs.ultralytics.com/hub/models#train-model).

Alternatively, you can [create the model using Ultralytics HUB SDK](https://docs.ultralytics.com/hub/sdk/model#create-a-new-model-with-custom-configuration) and [upload the metrics using Ultralytics HUB SDK](https://docs.ultralytics.com/hub/sdk/model#upload-and-visualize-training-metrics). Keep in mind that this is a new feature that we are still working on.

**Comment by rag0nn** [comment]
Thanks for help!

**Comment by sergiuwaxmann** [comment]
@rag0nn Don't hesitate to reach out if you have more questions!
