### ISSUE TITLE
Dataset upload

### ISSUE THREAD

**Issue by caarmeecoorbii** [ultralytics/hub#693]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Hello, I tried to upload my 8.9 GB dataset to Ultralytics HUB, it uploaded to 100% but at the end, I got the error that I leave below. Is it a server issue? Yesterday, I was able to upload my dataset perfectly.
![image](https://github.com/ultralytics/hub/assets/92037229/fd6809f2-15cc-4bba-a947-d0ee6f5684f5)

### Environment

- Computer: HP
- Browser: Google Chrome

**Comment by sergiuwaxmann** [comment]
@caarmeecoorbii Hi there!

The server looks fine - no issues and also no changes made (to the server) in the last week.

Did you upload the same dataset yesterday? If yes, why are you uploading the same dataset again?
Maybe you had an issue with the internet during the upload?
Did you follow [our instructions](https://docs.ultralytics.com/hub/datasets#upload-dataset)? To make sure you upload succeeds, it is recommended to **always** [validate your dataset](https://docs.ultralytics.com/reference/hub/__init__#ultralytics.hub.check_dataset) before the upload:
```python
from ultralytics.hub import check_dataset

check_dataset("path/to/dataset.zip", task="detect")
```

**Comment by caarmeecoorbii** [comment]
![image](https://github.com/ultralytics/hub/assets/92037229/772209fa-db39-4718-b9ce-64beeb4301ab)
I did it and it's all okey.

**Comment by sergiuwaxmann** [comment]
@caarmeecoorbii Great! I think you faced an internet connection issue.
