### ISSUE TITLE
Private Project not loading on Android Mobile Phone

### ISSUE THREAD

**Issue by PHIKHONAMTHEMBU** [ultralytics/hub#694]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

Hi, for some odd reason,

My private Project does not load onto my android nor IOS Mobile devices, please assist.

### Additional

Hi, for some odd reason,

My private Project does not load onto my android nor IOS Mobile devices, please assist.

**Comment by pderrenger** [comment]
Hello! Thanks for reaching out. It sounds frustrating to deal with loading issues on mobile devices. To help you better, could you please provide a bit more information:

1. Are there any specific error messages you receive when trying to load the project?
2. What version of the HUB app are you using on your Android and iOS devices?
3. Could you try clearing the app cache or reinstalling the app to see if that resolves the issue?

These details will help us pinpoint the problem more effectively. Looking forward to your response! 😊

**Comment by PHIKHONAMTHEMBU** [comment]
Hi, 

Please see attached images. If I look at the private models section, total model size is 0B, which could explain why when I try to 
![Uploading Screenshot_20240529_040028.jpg…]()
load any models it gives a splash screen.

**Comment by PHIKHONAMTHEMBU** [comment]
![Screenshot_20240529_040016](https://github.com/ultralytics/hub/assets/16671146/b09dc201-64bb-488d-8d8f-27777c970f6d)
![Screenshot_20240529_035926](https://github.com/ultralytics/hub/assets/16671146/60919ff0-0be5-4350-9824-e300cf2c19fa)

**Comment by PHIKHONAMTHEMBU** [comment]
![Screenshot_20240529_040028](https://github.com/ultralytics/hub/assets/16671146/c65d8ffc-9575-456a-a171-644ddfed80b0)

**Comment by pderrenger** [comment]
Thank you for providing the screenshots. It appears there might be an issue with how the model data is being handled or displayed in your private projects section. The "0B" size indicates that the models might not be properly synced or uploaded.

Could you please try the following steps:
1. Ensure that you are connected to a stable internet connection.
2. Log out and then log back into your account on the HUB app.
3. Check if the model sizes are correctly displayed after re-login.

If the issue persists, it might be helpful to check the model files on the server or source where they were uploaded to ensure they are intact and correctly sized. Let us know how it goes!

**Comment by PHIKHONAMTHEMBU** [comment]
Hi, 

No solution still, I still get "0B" size, can you share any doc links on how the sync actually works. after removing all my dataset,  my private project now shows Models : 0 
![WhatsApp Image 2024-06-03 at 16 53 30_2beaa1e2](https://github.com/ultralytics/hub/assets/16671146/20b514c2-9d16-4194-bdac-2c69dc780d38)

**Comment by PHIKHONAMTHEMBU** [comment]
here is a model ID you can use to check where the problem might be, 
https://hub.ultralytics.com/models/JqSaJuKI0cW1jjYBnbhF

**Comment by sergiuwaxmann** [comment]
@PHIKHONAMTHEMBU I apologize for the inconvenience.
Our team will investigate this issue further and try to fix it as soon as possible. Thank you for your patience!

**Comment by PHIKHONAMTHEMBU** [comment]
thank you, 

for you info, on IOS, i do get an error **Datasetfailure.unexpected()**

![Screenshot 2024-06-03 172157](https://github.com/ultralytics/hub/assets/16671146/a7d504c1-f12d-4e90-8122-2445dfda0217)

**Comment by PHIKHONAMTHEMBU** [comment]
Hi, 

did you manage to fix the bug?

**Comment by pderrenger** [comment]
@PHIKHONAMTHEMBU hi,

We are still working on resolving the issue. I'll keep you updated as soon as we have a fix or further information. Thank you for your patience! 😊

**Comment by PHIKHONAMTHEMBU** [comment]
Hi, it's been 3 weeks now, still no solution ?

**Comment by pderrenger** [comment]
Hi @PHIKHONAMTHEMBU,

Thank you for your patience. I understand how frustrating this can be. To ensure we can effectively address the issue, could you please provide a minimal reproducible example? This will help us replicate the problem on our end and expedite the troubleshooting process. You can find guidance on creating a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please make sure you are using the latest versions of `torch`, `ultralytics`, and `hub-sdk`. Sometimes, updating these packages can resolve unexpected issues. If you haven't already, please update and try again.

Your cooperation is greatly appreciated, and we are committed to resolving this as quickly as possible. Thank you for your understanding! 😊

**Comment by PHIKHONAMTHEMBU** [comment]
Why don't you read history comments with all the snapshots? Your latest comment was that the latest release of the mobile Ultrlytics Hub app does not work for some users.

Have you managed to trace why that is the case? Can you resolve urgently I've been patient for a reasonable time now.

**Comment by PHIKHONAMTHEMBU** [comment]
Am I the only user who's experiencing this?

**Comment by pderrenger** [comment]
Hi @PHIKHONAMTHEMBU,

Thank you for your patience and for providing additional details. I understand how important this is for you, and I apologize for the inconvenience.

To address your question, you are not alone in experiencing this issue. We have identified that some users are facing similar problems with the latest release of the Ultralytics Hub mobile app. Our team is actively working on a fix.

In the meantime, could you please ensure that you are using the latest versions of `torch`, `ultralytics`, and `hub-sdk`? Sometimes, updating these packages can resolve unexpected issues. If you haven't already, please update and try again.

Additionally, if you could provide a minimal reproducible example, it would greatly help us in diagnosing and resolving the issue more efficiently. You can find guidance on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

We appreciate your patience and understanding as we work to resolve this. Your feedback is invaluable, and we are committed to getting this fixed as soon as possible. 😊

Thank you for your cooperation!

**Comment by PHIKHONAMTHEMBU** [comment]
@pderrenger @sergiuwaxmann any update on this ?
