### ISSUE TITLE
How to download my dataset?

### ISSUE THREAD

**Issue by choibyeongyeong** [ultralytics/hub#696]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Dear Ultralytics Support Team,

I hope this message finds you well.

I am writing to inquire about the process of downloading my dataset from the Ultralytics Hub. I have previously uploaded a dataset for training purposes, but I am unable to locate a direct download button on the platform.

Could you please provide me with instructions or a link to download my dataset? Below are the details of my dataset:

Thank you very much for your assistance. I look forward to your response.

**Comment by sergiuwaxmann** [comment]
@choibyeongyeong Hello!
Unfortunately, at the moment, there is no **Download** button in the UI but you can [download the dataset using the Ultralytics HUB SDK](https://docs.ultralytics.com/hub/sdk/dataset#get-url-from-storage).

**Comment by UltralyticsAssistant** [comment]
@choibyeongyeong great news! The dataset download button has been implemented in HUB by @sergiuwaxmann and is now live :)

![image](https://github.com/user-attachments/assets/71919636-9e62-4c2f-96a6-5ce54271c27e)

For more details see https://docs.ultralytics.com/hub/datasets
