### ISSUE TITLE
Train and predict multiple classes detecting for single object  YOLO8

### ISSUE THREAD

**Issue by SutirthaChakraborty** [ultralytics/hub#704]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How can we train a model to detect multiple class of a single object.
For example :
an image of bee, it should be able to detect bee and 'insect'
an image of rat, it should be able to detect 'rat' and 'rodent'

### Additional

Right now, it's detecting either of any labels and then toggling between two classes.

**Comment by pderrenger** [comment]
Hello!

Thank you for reaching out with your question. To train a model on YOLO8 that can detect multiple classes for a single object, you'll need to adjust your dataset annotations to reflect these hierarchical class relationships. Each image should have annotations for both the specific class (e.g., 'bee') and its broader category (e.g., 'insect'). 

Here’s a brief guide on how to proceed:

1. **Annotation Format**: Ensure your annotation files list multiple classes for the objects that belong to more than one class. For example, an image with a bee might have annotations for both 'bee' and 'insect'.

2. **Modify Dataset Loading**: When loading your dataset in the training script, make sure the loader is configured to handle multiple labels per object.

3. **Model Configuration**: In your model configuration file, define all the classes (specific and general) that you want the model to learn.

4. **Training**: Train your model with these annotations. The model should learn to recognize objects in both their specific and general classes.

5. **Evaluation**: During inference, the model should predict multiple classes for a single object as per the training.

If toggling between two classes still occurs, it might be helpful to look into the confidence thresholds and non-maximum suppression settings to ensure that the model can confidently predict multiple classes for the same object.

Let me know if you need further assistance or specific guidance on any of the steps!
