### ISSUE TITLE
Inquiry About Live Video Feed Deployment on Ultralytics Hub

### ISSUE THREAD

**Issue by Hariii17** [ultralytics/hub#706]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Dear Ultralytics Support Team,

I hope this message finds you well.
I have been working on an object detection project using a CCTV camera, but my local system struggles with CPU utilization, often reaching 100% and causing the process to terminate. To address this, I have transitioned to using Ultralytics Hub for training my model.

My query is regarding the deployment phase: Is it possible to deploy the trained object detection model on a live video feed directly within Ultralytics Hub? Given that my local system lacks the necessary GPU compute capabilities, I am looking for a solution that leverages the computational resources available on Ultralytics Hub.

Your guidance on this matter would be highly appreciated.

**Comment by pderrenger** [comment]
@Hariii17 hello,

Thank you for reaching out and detailing your situation. I'm glad to hear that you've chosen Ultralytics HUB for training your model!

Regarding your query on deploying the trained model for live video feed analysis directly within Ultralytics HUB: Currently, HUB primarily supports training and model management, and does not directly host live video feed processing. However, you can export your trained model to various formats suitable for deployment on different platforms that support live video processing.

For real-time video processing, you might consider deploying your model on a cloud service with GPU support, or on local servers equipped with the necessary hardware. Our [Inference API](https://docs.ultralytics.com/hub/) could also be a viable option, depending on your specific requirements and setup.

If you need further assistance or have more questions, please feel free to ask!

**Comment by Hariii17** [comment]
Suppose if this project is assigned for your team will  you be able to do it. Can we discuss about this?

**Comment by pderrenger** [comment]
@Hariii17 hello,

Thank you for considering our team for your project! We're always ready to discuss potential collaborations and how we can assist you. Please let us know a convenient time for you, or you can directly share more details about your project requirements here.

Looking forward to our discussion! 😊

**Comment by Hariii17** [comment]
Yeah thats good if you are up for collaboration can you please provide your contact number and your free time ?

**Comment by pderrenger** [comment]
Hello @Hariii17,

Thank you for your interest in collaborating! For privacy and security reasons, we handle all professional communications through official channels. Could you please reach out to us via our support email provided on the Ultralytics HUB website? From there, we can schedule a time to discuss your project in detail.

Looking forward to hearing from you soon!

**Comment by Hariii17** [comment]
Okay can you mention your support email id.

**Comment by sergiuwaxmann** [comment]
@Hariii17 Hi!

You you can use this form:
https://www.ultralytics.com/contact

**Comment by Hariii17** [comment]
Done

**Comment by pderrenger** [comment]
Hello @Hariii17,

Great! If you need any further assistance, feel free to reach out. Happy to help! 😊
