### ISSUE TITLE
on upload : No response from the server.

### ISSUE THREAD

**Issue by togro** [ultralytics/hub#709]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

Hi

We are uploading dataset but receive : No response from the server on dataset "RDD2022-01"

Best Regards

### Additional

![image](https://github.com/ultralytics/hub/assets/7252575/1df49221-4d98-4c1a-9518-09e2a8f19701)

**Comment by pderrenger** [comment]
Hello,

Thank you for reaching out and providing detailed information about the issue you're encountering.

It seems like there might be a connectivity or timeout issue during the dataset upload process. Here are a few steps you can try to resolve the problem:

1. **Check Network Connection:** Ensure that your internet connection is stable during the upload process.
2. **Retry the Upload:** Sometimes, simply retrying the upload can resolve transient issues.
3. **Check Server Status:** Verify if there are any known issues or maintenance activities on the Ultralytics HUB that might be affecting server responses.
4. **Review Dataset Size and Format:** Ensure that the dataset size and format comply with the HUB's requirements.

If the issue persists, could you please provide more details about the dataset size and the exact steps you are following? This information will help us diagnose the problem more effectively.

**Comment by togro** [comment]
I'm trying again but  is not working First time works , but fail on final part:Msg:  Timeout : No response from the server.8 classes 34761 images 7.2 GBSecond time :Msg: Failed Upload Incomplete.7.2 GB is too big ?Best regardsOn jun. 1 2024, at 10:04 pm, Paula Derrenger ***@***.***> wrote:Hello,Thank you for reaching out and providing detailed information about the issue you're encountering.It seems like there might be a connectivity or timeout issue during the dataset upload process. Here are a few steps you can try to resolve the problem:Check Network Connection: Ensure that your internet connection is stable during the upload process.Retry the Upload: Sometimes, simply retrying the upload can resolve transient issues.Check Server Status: Verify if there are any known issues or maintenance activities on the Ultralytics HUB that might be affecting server responses.Review Dataset Size and Format: Ensure that the dataset size and format comply with the HUB's requirements.If the issue persists, could you please provide more details about the dataset size and the exact steps you are following? This information will help us diagnose the problem more effectively.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by pderrenger** [comment]
Hello,

Thank you for the update and for trying the suggested steps. It seems the issue might be related to the size of the dataset, as larger uploads can sometimes lead to timeouts or incomplete transfers.

Here are a couple of additional suggestions:
- **Split the Dataset:** If possible, try splitting the dataset into smaller parts and upload them separately. This can help avoid timeouts due to large file sizes.
- **Use a Stable and Fast Internet Connection:** Ensure the upload is done using a connection that can handle large data transfers reliably.

If these steps do not resolve the issue, it might be helpful to look into any specific server-side limitations or configurations that could be affecting the upload process for large datasets.

**Comment by togro** [comment]
HiLet's say I divide the 7.2 GB into two.I don't see how I can add the extra 3.6 GB from the second load to the same data set in another load. It doesn't make sense to me to split it, I don't see a way to add it to the dataset I uploaded.Maybe when you say split it it means in another sense?Kind regards
        
        
          On jun. 2 2024, at 1:19 am, Paula Derrenger ***@***.***> wrote:
          
        
        
          
Hello,
Thank you for the update and for trying the suggested steps. It seems the issue might be related to the size of the dataset, as larger uploads can sometimes lead to timeouts or incomplete transfers.
Here are a couple of additional suggestions:

Split the Dataset: If possible, try splitting the dataset into smaller parts and upload them separately. This can help avoid timeouts due to large file sizes.
Use a Stable and Fast Internet Connection: Ensure the upload is done using a connection that can handle large data transfers reliably.

If these steps do not resolve the issue, it might be helpful to look into any specific server-side limitations or configurations that could be affecting the upload process for large datasets.

**Comment by pderrenger** [comment]
@togro hello,

Thank you for your response and for clarifying your concerns about splitting the dataset.

When suggesting splitting the dataset, the idea was indeed to upload smaller, manageable parts separately. However, I understand your concern about maintaining dataset integrity and continuity.

To address this, you can upload the parts as separate datasets initially. Once all parts are uploaded successfully, you can then merge these parts into a single dataset within the HUB. This approach allows you to bypass the upload size limitations while ensuring all your data remains part of one cohesive dataset.

If you need further assistance on how to merge datasets within the HUB or any other queries, please feel free to ask.

Kind

**Comment by togro** [comment]
Ok, can you tell me how to merge datasets on hub ?I read doc : https://docs.ultralytics.com/hub/datasets/#delete-datasetBut merge option is not mentionatedBest RegardsOn jun. 2 2024, at 8:18 am, Paula Derrenger ***@***.***> ***@***.*** hello,Thank you for your response and for clarifying your concerns about splitting the dataset.When suggesting splitting the dataset, the idea was indeed to upload smaller, manageable parts separately. However, I understand your concern about maintaining dataset integrity and continuity.To address this, you can upload the parts as separate datasets initially. Once all parts are uploaded successfully, you can then merge these parts into a single dataset within the HUB. This approach allows you to bypass the upload size limitations while ensuring all your data remains part of one cohesive dataset.If you need further assistance on how to merge datasets within the HUB or any other queries, please feel free to ask.Kind—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by pderrenger** [comment]
Hello,

Apologies for any confusion. Currently, the Ultralytics HUB does not support direct merging of datasets through the user interface. My previous message was incorrect in suggesting that functionality. 

To manage multiple parts of a dataset as one, you would typically need to handle them as separate datasets within the HUB. If you require them to be treated as a single dataset for training or analysis, you might consider combining them locally on your machine before uploading.

Thank you for your understanding, and please let us know if there's anything else we can help with!

**Comment by sergiuwaxmann** [comment]
@togro I just checked and everything is working correctly.

Can you please retry the upload and ensure that your internet connection is stable during the upload process?
