### ISSUE TITLE
Is it possible to use the checkpoints that the platform makes if the model is overtrained?

### ISSUE THREAD

**Issue by togro** [ultralytics/hub#711]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

When I have an overtrained model and I want to use a previous training period that was recorded at some checkpoint... is it possible?

Or do we have to train the model again and configure the epochs again?

Best regards

**Comment by pderrenger** [comment]
@togro hello!

Yes, you can definitely use the checkpoints saved during training if you find that your model has overtrained. These checkpoints allow you to revert to a previous state of the model that might have had better generalization performance. There's no need to retrain the model from scratch unless you want to change your training configuration significantly.

Simply load the desired checkpoint and continue your evaluation or further training from there. This feature is designed to save time and resources, making your model development process more efficient.

**Comment by togro** [comment]
But Hub support this ? 

I see checkpoints saved on training on web  , but using service from hub we can't access to checkpoints ... no ?

**Comment by sergiuwaxmann** [comment]
@togro Unfortunately, at the moment, you can't access the checkpoints using Ultralytics HUB.

**Comment by togro** [comment]
I imagined

Thank you

**Comment by sergiuwaxmann** [comment]
@togro No worries!
