### ISSUE TITLE
A.S.D.O. Proyect

### ISSUE THREAD

**Issue by TomasAlvarez45** [ultralytics/hub#712]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Dear UltralyticsHub,

My name is Tomás Álvarez and I am addressing you on behalf of a school project that we are developing at the Manuel Belgrano technical school. Our goal is to improve the way waste is separated in recycling centers and replace unhealthy jobs by using advanced technologies.

We are working with an artificial intelligence designed from scratch, based on the YOLOv8x model. However, we face an important limitation: we do not have the necessary infrastructure to properly train this model, nor the resources to acquire it.

For this reason, we would like to request your sponsorship so that we can train our model on your service. We believe that your support would be essential to the success of our project and to advance our mission of improving recycling processes and working conditions in this sector.

I am happy to provide you with any additional information you need about the project and our educational institution.

We thank you in advance for your attention and consideration.

Sincerely,

Tomas Alvarez
tomas311005@gmail.com
E.T. N11 D.E. 6 "Manuel Belgrano"

**Comment by pderrenger** [comment]
Hello Tomás,

Thank you for reaching out and sharing the details of your commendable project at the Manuel Belgrano technical school. It's inspiring to see you leveraging AI for such a significant environmental and social impact.

Regarding your request for sponsorship to train your model using our services, we typically review these requests on a case-by-case basis. Could you please provide a detailed proposal including the scope of the project, expected outcomes, and any specific requirements you have? This will help us better understand how we might support your initiative.

Please send your proposal to our dedicated support channel, and we will ensure it reaches the right team for consideration.

We look forward to hearing more about your project and exploring how we can assist you in making a positive change.

**Comment by TomasAlvarez45** [comment]
Hello Paula,
I want to express my gratitude for considering our proposal and taking the time to evaluate it. We are honored to share the details of our project, which seeks to address a major problem in local recycling centers in Argentina.
In our country, the separation of waste in recycling centers is carried out mainly by human labor. This process, in addition to being inefficient, entails significant risks to the health of workers. For this reason, we have undertaken extensive research into the current system and its challenges, and have explored alternatives to replacing labor with automated systems.
Our approach has been to develop a system called "A.S.D.O." (Automatic Differentiation and Organization System), which consists of a series of mechanical separation and organization processes. This system ensures that waste is efficiently sorted and arrives in an orderly manner to a central artificial intelligence, which uses the YOLOv8x model to classify objects and send signals to mechanical actuators for separation.
Despite the limited resources we have, we have managed to expand our training data set from 20,000 to 120,000 images, many of which were classified manually. We recognize that our team and infrastructure are modest, but we are committed to our cause and dedicated to continuous improvement.
However, we faced a significant obstacle: the lack of computing power to effectively train our model. For this reason, we are looking for collaborations that allow us to use additional computational resources. If we could use your services to train our model, it would be a considerable help in achieving our goals.
Furthermore, in the event that we manage to attract the interest of investors for the development of the project, we would be happy to collaborate with you to improve our design. At that time, we would be able to adequately compensate any services provided to us.
I thank you again for your consideration and hope that our project piques your interest. I remain at your disposal to discuss any additional aspects or answer questions that may arise.
Sincerely,
Tomas Alvarez
tomas311005@gmail.com
E.T. N11 D.E. 6 "Manuel Belgrano"

**Comment by pderrenger** [comment]
Hello Tomas,

Thank you for providing such a detailed overview of your A.S.D.O. project. It's impressive to see the progress you've made, especially in expanding your training dataset under constrained resources. Your initiative to integrate AI for enhancing recycling processes while ensuring worker safety is truly commendable.

We understand the challenge of limited computing power and are keen to explore how we can assist your project further. Could you please send a formal proposal outlining your specific resource needs, expected timelines, and any potential collaborative opportunities post-investment? This will help us evaluate the feasibility of support more effectively.

Looking forward to your proposal and hoping to contribute to your innovative efforts.

**Comment by TomasAlvarez45** [comment]
Hello Paula,
Thank you for your encouraging message and for recognizing the effort and progress of our A.S.D.O project. at the Manuel Belgrano Technical School. We are pleased to know that our initiative to integrate AI to improve recycling processes and ensure worker safety has been well received.

Specific Resource Needs: To successfully train the artificial intelligence model we need to be able to use your UltralyticsHub cloud model training service. Our goal is to give you a training of 300 epochs (if more could be done, it would be very useful to us and likewise if it is a lot, we can reduce it to what you can offer us). In itself, the main thing would be that, but if it is within the possibilities, it would be of great help to us to be able to work on the roboflow platform with data sets larger than the limit of 10,000 images that it has by default. Below I detail the needs in the form of a list:

- Permission to train a YOLOv8x model in the cloud.
- Possibility of working with larger data sets on the roboflow platform.

Expected Schedules: We foresee the following schedule for our project, conditional on obtaining the necessary resources:

- Initial Configuration and Data Preparation: 1 day
- Model Training and Optimization: 1-2 weeks
- System Integration and Testing: 1 week

 Project Scope: The A.S.D.O. It will be presented at the “Science and Arts Fair” in Argentina where we will seek to attract the attention of possible public sector investors for the project. And as I mentioned in the previous message, if we obtain this financing we would be delighted to be able to work with you for the development and advancement of the project, but now being able to pay for all the required services. Among possible future collaborations are:


- Joint development to refine and improve our AI model.
- Long-term partnerships to expand the reach and impact of our project.
- Proposals to encourage the use of artificial intelligence in educational institutions.
- Potential shared research and development initiatives.

We are convinced that your support will be essential for the success of our project and to promote innovation in the field of recycling. We attached the detailed proposal document.
[Informe Técnico ASDO .pdf](https://github.com/user-attachments/files/15597847/Informe.Tecnico.ASDO.pdf)

We are aware of the value of the services requested and they would be of great help to develop our project. We thank you again for your interest and are excited about the possibility of collaborating with you.
Sincerely,

Tomás Álvarez
tomas311005@gmail.com
Escuela Técnica Manuel Belgrano

**Comment by pderrenger** [comment]
Hello Tomás,

Thank you for the detailed outline of your resource needs and project timeline. It's clear that you've thought thoroughly about the scope and execution of the A.S.D.O. project.

We appreciate the structured approach to your request, and I'll forward this to our team to review the feasibility of supporting your training needs on the UltralyticsHub cloud and potentially on the Roboflow platform for handling larger datasets.

Your project's potential for societal impact is exciting, and we are looking forward to exploring ways we can collaborate, especially in fostering AI integration in educational and environmental sectors.

We'll review the attached detailed proposal and get back to you with our feedback and possible next steps soon.

**Comment by TomasAlvarez45** [comment]
Hello Paula,
I hope you're well.
I wanted to follow up on our proposal for the A.S.D.O project. at the Manuel Belgrano Technical School. In your last message you mentioned that the team would review our proposal and give us feedback and possible next steps.
We understand that these evaluations may take time and we appreciate your consideration. We would like to know if there has been any progress or if there is additional information we can provide to facilitate the review.
We are very excited about the possibility of collaborating and greatly appreciate the time and effort you are dedicating to evaluating our project.
Stay tuned to reply.
Greetings,
Tomas Alvarez
tomas311005@gmail.com
Manuel Belgrano Technical School

**Comment by pderrenger** [comment]
Hello Tomás,

Thank you for your patience and for following up on your proposal for the A.S.D.O. project. We appreciate your enthusiasm and the detailed information you have provided so far.

Our team is currently reviewing your proposal and assessing how we can best support your initiative. These evaluations do take some time, as we want to ensure we can provide the most effective assistance possible.

In the meantime, if you have any additional updates or further details about your project, please feel free to share them. This could include any recent progress, specific technical requirements, or any other information that might help us better understand your needs.

We are excited about the potential collaboration and will get back to you with feedback and possible next steps as soon as we can.

Thank you again for your patience and dedication to this important project.

**Comment by TomasAlvarez45** [comment]
Hello Paula,
I hope you are well. I wanted to share with you that we already have our new A.S.D.O project website. online: https://www.proyectoasdo.com. We'd love for you to take a look. Also tell you that there is the first advertising spot that seeks to encourage recycling and publicize the project.
Also, this Monday, July 1st is our first presentation at the science fair. If you are interested in knowing more, it is possible that a lot of material is uploaded on the social networks of the government of the Autonomous City of Buenos Aires, which we can gladly share with you.
By the way, I wanted to ask if there has been any progress with our proposal and if it is still standing.
Thank you very much for your time. Greetings!
Tomas Alvarez
tomas311005@gmail.com
Manuel Belgrano Technical School

**Comment by pderrenger** [comment]
Hello Tomás,

Thank you for sharing the exciting news about your new A.S.D.O. project website! It's fantastic to see your dedication and progress. I'll definitely take a look at https://www.proyectoasdo.com and check out the advertising spot promoting recycling and your project.

Regarding your upcoming presentation at the science fair on Monday, July 1st, I wish you the best of luck! It sounds like a great opportunity to showcase your hard work. Please feel free to share any material or updates from the event through the appropriate channels.

As for your proposal, our team is still in the process of reviewing it. These evaluations can take some time, but we appreciate your patience and enthusiasm. We will get back to you with feedback and possible next steps as soon as we can.

Thank you again for your dedication to this important project and for keeping us updated. If you have any further questions or updates, please don't hesitate to share them here.

Best regards and good luck with your presentation!

Paula
