### ISSUE TITLE
Project is disconnected

### ISSUE THREAD

**Issue by spartajet** [ultralytics/hub#713]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

My project is disconnected and cannot get cloud trainning result .
Model - 5 June 2024 18:48

**Comment by pderrenger** [comment]
Hello,

Thank you for reporting this issue with your project disconnection. To assist you better, could you please provide a bit more detail about the steps leading up to the disconnection? Additionally, any error messages or logs that were generated during the disconnection would be very helpful.

We'll work to resolve this as quickly as possible once we have a bit more information.

**Comment by spartajet** [comment]
thanks，however, I just config the classify task in your HUB website and pay, Then I cannot get the train result. as shown in pic
<img width="1324" alt="Snipaste_2024-06-06_15-08-01" src="https://github.com/ultralytics/hub/assets/8477178/5b806be4-878a-44a3-802f-c3e6752674e2">

**Comment by sergiuwaxmann** [comment]
@spartajet Can you share the model ID so I can investigate this further?

The issue might be GPU availability as I just tested and everything works fine.
Read more about Cloud Training: https://docs.ultralytics.com/hub/cloud-training

**Comment by spartajet** [comment]
I think "JADqyjS8ocsOQsULppOS" is my model id from share dialog webpage. thank you!

**Comment by sergiuwaxmann** [comment]
@spartajet Perfect, thank you! I will keep you updated.

**Comment by emilio-balda** [comment]
Hi @pderrenger 👋 I have the same issue

When training a model. It trains normally. I reach to the point of "Optimizing Weights" but then it gets stuck in that state for around 5 minutes. After that I get the following screen saying the model is "Disconnected".
![image](https://github.com/ultralytics/hub/assets/89062539/de1d1efb-ef1d-4dcf-8999-74d3c6f8db18)

It lets me retry training from the last checkpoint, but the same issue happens again. 
You can see here that I tried a couple of times.
![image](https://github.com/ultralytics/hub/assets/89062539/9e7c555f-a140-4f1f-8522-93409adcd73a)

This is how it looks in the Models Panel 
![image](https://github.com/ultralytics/hub/assets/89062539/3f6056b4-41e8-4e2a-b593-8ea76617608d)

I had a similar issue earlier today when uploading datasets. The dataset was not huge (2GB). I got an "Unknown Error". This happened to me twice with slightly different versions of my dataset. On the third try, I was able to upload it. 

PS: Things were working fine for me 2 days ago. Maybe something changed yesterday or today.

**Comment by spartajet** [comment]
@emilio-balda my dataset is just 54M, and I cannot get error message ...

**Comment by sergiuwaxmann** [comment]
@emilio-balda Hello!
Can you please share your model ID so I can investigate this further?

**Comment by emilio-balda** [comment]
@sergiuwaxmann Hi! I saw above that the issue might be GPU availability so I tried resuming training in the middle of the night and that worked 🚀

![image](https://github.com/ultralytics/hub/assets/89062539/48f01bc6-dd7f-439d-b53b-3f7ee3fc7e68)

In case you want to take look, here is my model ID: `aASmZT80nXYK3VTG9rIw`

**Comment by sergiuwaxmann** [comment]
@emilio-balda Thank you! Yes, I will look into this but I am glad it worked in the end.

**Comment by jankalthoefer** [comment]
Hey @sergiuwaxmann 
I am having the same issue over and over again. 
Sometimes it works when I retry, the last couple of tries it didn't unfortunately.

Is there anything to keep in mind?

Here are two projects that failed before:
nBWRPqNKwzLUPmDwfESX
Uqlbyy57FiLg394OlkXU

**Comment by sergiuwaxmann** [comment]
@jankalthoefer Hello!
I believe the issue might be related to GPU availability. During the 15-minute timeout, we attempt to spin up the dedicated instance for Cloud Training, but it might fail due to GPU availability. This issue has been logged, and we are working on improving the error handling.

**Comment by jankalthoefer** [comment]
Got it! 
Let me know if you have any updates.
For now I am moving to Colab then.

**Comment by sergiuwaxmann** [comment]
@jankalthoefer Sure thing! Apologies for the inconvenience.
