### ISSUE TITLE
Ultralytics HUB API Issue

### ISSUE THREAD

**Issue by locastro10** [ultralytics/hub#715]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Inference

### Bug

After I trained my model, I ran the python code you provided in the deploy section and the code is working as expected: 

Python Code; 
import json
import requests

# Run inference on an image
url = "https://api.ultralytics.com/v1/predict/oVq1wky72fW1uHWobShy"
headers = {"x-api-key": "f2a84f7891f2204ddbf3a9a7d5aeed2fc19a03bf49"}
data = {"size": 640, "confidence": 0.25, "iou": 0.45}
with open("RoblesSitePlan1.png", "rb") as f:
	response = requests.post(url, headers=headers, data=data, files={"image": f})

# Check for successful response
response.raise_for_status()

# Print inference results
print(json.dumps(response.json(), indent=2))

However, if I try to call the inference API in my angular application I get a 500 error: 

URL that is failing: https://api.ultralytics.com/v1/predict/oVq1wky72fW1uHWobShy
Failed to load resource: the server responded with a status of 500 ()Understand this error
core.mjs:11752 ERROR HttpErrorResponseerror: message: "Unhandled server error."success: false[[Prototype]]: Objectheaders: HttpHeaders {normalizedNames: Map(0), lazyUpdate: null, lazyInit: ƒ}lazyInit: () => {…}lazyUpdate: nullnormalizedNames: Map(0) {size: 0}[[Prototype]]: Objectmessage: "Http failure response for https://api.ultralytics.com/v1/predict/oVq1wky72fW1uHWobShy: 500 OK"name: "HttpErrorResponse"ok: falsestatus: 500statusText: "OK"url: "https://api.ultralytics.com/v1/predict/oVq1wky72fW1uHWobShy"[[Prototype]]: HttpResponseBase

This the code I'm trying to use in my angular application: 

        imageUrl: string = "assets/RoblesSitePlan1.png"; 
        inferenceResults: any; 

        const url = "https://api.ultralytics.com/v1/predict/oVq1wky72fW1uHWobShy";
        const headers = { 'x-api-key': 'f2a84f7891f2204ddbf3a9a7d5aeed2fc19a03bf49' }; 
        const data = { size: 640, confidence: 0.25, iou: 0.45 };
    
        const formData = new FormData();
        formData.append('size', data.size.toString());
        formData.append('confidence', data.confidence.toString());
        formData.append('iou', data.iou.toString());
        formData.append('image', this.imageUrl);
    
        this.http.post(url, formData, { headers: headers, reportProgress: true, observe: 'response' })
          .subscribe(response => {
            if (response.status === 200) {
              this.inferenceResults = response.body;
              console.log("Inference Results:", this.inferenceResults);
            } else {
              console.error("Ultralytics API Error:", response.statusText);
            }
          });
<img width="1512" alt="Screenshot 2024-06-08 at 12 27 04 PM" src="https://github.com/ultralytics/hub/assets/129409042/ab05d7bd-f1f1-4823-878a-623c0bddc049">

Any help you could provide would be appreciated.

Thank you
Luis Castro

### Environment

Ultralytics HUB Version
v0.1.44
Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Safari/605.1.15
Operating System
MacIntel
Browser Window Size
1445 x 758
Server Timestamp
1717869950

### Minimal Reproducible Example

N/A

### Additional

N/A

**Comment by sergiuwaxmann** [comment]
@locastro10 Hello!

I just checked our system and everything works fine.

From the code snippet you shared, here are a few things I noticed just by reading it:
1. You are sending a string (`imageUrl`) instead of the image file.
2. You are sending `size`, `confidence` and `iou` as strings.

Unfortunately, I can't help you with your Angular project, but I suggest trying to create a Canvas element for your image and sending the [data as a URL](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).

You can read more about our [Inference API in our documentation](https://docs.ultralytics.com/hub/inference-api).
