### ISSUE TITLE
This account is currently being deleted.

### ISSUE THREAD

**Issue by kehuanjack** [ultralytics/hub#719]
Hello! I accidentally deleted my account. Can you help me restore my account? My account is 1506289682@qq.com

**Comment by sergiuwaxmann** [comment]
@kehuanjack Done! 🚀 Your account is active again.

**Comment by kehuanjack** [comment]
> @kehuanjack Done! 🚀 Your account is active again.

thanks

**Comment by pderrenger** [comment]
Hello @kehuanjack,

You're welcome! 😊 If you encounter any further issues or have any questions, feel free to reach out. We're here to help!
