### ISSUE TITLE
det

### ISSUE THREAD

**Issue by Hamzaboughfir123** [ultralytics/hub#722]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Would like to know how can i upload my model trained outside ultralytics hub

**Comment by sergiuwaxmann** [comment]
@Hamzaboughfir123 Hello!

At the moment, there is no visual way to do this. I suggest training your model using [Ultralytics HUB](https://hub.ultralytics.com).

However, you could use [Ultralytics HUB SDK](https://docs.ultralytics.com/hub/sdk) to [Upload and Visualize Training Metrics](https://docs.ultralytics.com/hub/sdk/model#upload-and-visualize-training-metrics). Furthermore, you can use [Ultralytics HUB SDK](https://docs.ultralytics.com/hub/sdk) to export training results (such as metrics and weights) - [read more](https://github.com/ultralytics/hub/issues/651#issuecomment-2071523602).
