### ISSUE TITLE
Merging datasets

### ISSUE THREAD

**Issue by MMarvasti** [ultralytics/hub#733]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi,
Is it possible to merge a custom dataset with your official datasets (or two of your official datasets) on Ultralytics HUB?

**Comment by sergiuwaxmann** [comment]
@MMarvasti Hello!
Unfortunately, at the moment, this is not possible using [Ultralytics HUB](https://hub.ultralytics.com) but you could do this locally and upload the merged dataset to [Ultralytics HUB](https://hub.ultralytics.com).

**Comment by MMarvasti** [comment]
Thanks for your reply, @sergiuwaxmann

Could you please confirm if there is an image limit when using Ultralytics Hub?

**Comment by sergiuwaxmann** [comment]
@MMarvasti The limit is your account's storage (20GB FREE and 200GB PRO).
