### ISSUE TITLE
Stitched image detection

### ISSUE THREAD

**Issue by ZBC0de** [ultralytics/hub#738]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hey there, I am looking to detect features on a single image that contains 6 images that are stitched together horizontally. The width of the base images will be over 10000px and the height will be set at 1224. How can I train on an image of this size? As I need to maintain the aspect ratio when training.

### Additional

N/a

**Comment by pderrenger** [comment]
@ZBC0de hello,

Thank you for reaching out with your question about detecting features on a stitched image. To assist you effectively, could you please provide a minimum reproducible code example? This will help us understand your setup and reproduce the issue on our end. You can find guidelines on how to create a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example). It's crucial for us to replicate the problem to investigate and provide a solution.

Additionally, please ensure that you are using the latest versions of `torch`, `ultralytics`, and `hub-sdk`. If you haven't updated recently, please upgrade your packages and try again to see if the issue persists.

Regarding your specific question about training on large images while maintaining the aspect ratio, here are a few suggestions:

1. **Image Resizing**: You can resize your images to a manageable size while maintaining the aspect ratio. For example, you can use the `cv2.resize` function in OpenCV to resize your images before feeding them into the model.

    ```python
    import cv2

    image = cv2.imread('path_to_your_image.jpg')
    resized_image = cv2.resize(image, (desired_width, desired_height))
    ```

2. **Image Patching**: Another approach is to divide your large image into smaller patches and train the model on these patches. This way, you can handle high-resolution images without running into memory issues.

    ```python
    def split_image(image, patch_size):
        patches = []
        for y in range(0, image.shape[0], patch_size[1]):
            for x in range(0, image.shape[1], patch_size[0]):
                patch = image[y:y + patch_size[1], x:x + patch_size[0]]
                patches.append(patch)
        return patches

    patches = split_image(image, (desired_width, desired_height))
    ```

3. **Custom DataLoader**: You can create a custom DataLoader that handles large images by either resizing or patching them on-the-fly during training.

If you provide more details or a code example, we can offer more specific guidance. Thank you for your cooperation, and we look forward to helping you resolve this issue!

**Comment by ZBC0de** [comment]
It's not so much an issue as it is a quest about how to go about it. I currently have 6x 8MP images that I am horizontally stitching together. I want to use your API to do detections on the stitched image. When training on an image this large through the ultralytics hub, will the aspect ratio always remain the same?

**Comment by pderrenger** [comment]
Hello @ZBC0de,

Thank you for your question and for providing context about your project! It's great to hear that you're exploring the use of our API for detecting features on stitched images.

To address your query about maintaining the aspect ratio when training on large images through the Ultralytics HUB, here are a few key points:

1. **Aspect Ratio Maintenance**: When you upload and train images using the Ultralytics HUB, the aspect ratio of your images is typically preserved. However, it's important to ensure that your images are within a manageable size for the model to handle efficiently. Extremely large images can pose challenges in terms of memory and processing power.

2. **Image Resizing**: If your stitched image is exceptionally large (e.g., over 10000px in width), you might consider resizing it while maintaining the aspect ratio. This can be done using image processing libraries like OpenCV. Here's a quick example:

    ```python
    import cv2

    image = cv2.imread('path_to_your_image.jpg')
    resized_image = cv2.resize(image, (desired_width, desired_height))
    ```

3. **Image Patching**: Another effective approach is to divide your large stitched image into smaller patches. This allows you to process high-resolution images without running into memory issues. You can then train the model on these patches and aggregate the results. Here's a sample function to split an image into patches:

    ```python
    def split_image(image, patch_size):
        patches = []
        for y in range(0, image.shape[0], patch_size[1]):
            for x in range(0, image.shape[1], patch_size[0]):
                patch = image[y:y + patch_size[1], x:x + patch_size[0]]
                patches.append(patch)
        return patches

    patches = split_image(image, (desired_width, desired_height))
    ```

4. **Custom DataLoader**: You can also create a custom DataLoader that handles large images by resizing or patching them on-the-fly during training.

If you encounter any specific issues or have further questions, please provide a minimum reproducible code example. This will help us understand your setup better and offer more precise guidance. You can find guidelines on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest versions of `torch`, `ultralytics`, and `hub-sdk`. If you haven't updated recently, please upgrade your packages and try again to see if the issue persists.

We appreciate your engagement with the YOLO community and the Ultralytics team. We're here to help you succeed with your project!
