### ISSUE TITLE
how to upload my own model through .ONNX or .PT file

### ISSUE THREAD

**Issue by anseryuer** [ultralytics/hub#74]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I wonder if I can import my own model trained based on YOLOv5s through uploading the .onnx file or .pt file and see how it performs.

If the function is not availble yet, I wonder if you can add it to the website? Thanks a lot for your work!

**Comment by glenn-jocher** [comment]
@anseryuer thanks for the feedback! Model upload is not available, but you can train a model with HUB and then preview and export to any destination including ONNX.
