### ISSUE TITLE
Model Cant be load and stuck at optimize

### ISSUE THREAD

**Issue by ImannKamal** [ultralytics/hub#742]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

Model Cant be load and stuck at optimize, I try to wait for the first time it stuck at optimize and the system ask me to train it again at epoch 99 but when I train it again it still have the warning unable to load to best model.
![model](https://github.com/ultralytics/hub/assets/81039876/85b07419-c47e-4868-a826-4b489419c999)

**Comment by ImannKamal** [comment]
![fail](https://github.com/ultralytics/hub/assets/81039876/1db30551-f76d-4a53-9e40-3a3832d6a66a)
this is the third time i try to training the model and it still stuck and cant deploy the model

**Comment by pderrenger** [comment]
@ImannKamal hi there,

Thank you for reaching out and providing the details of your issue. I understand how frustrating it can be when things don't work as expected. Let's work together to resolve this.

Firstly, could you please ensure that you are using the latest version of the Ultralytics HUB and related packages? Sometimes, updates include important bug fixes and improvements that might resolve your issue.

Additionally, to better assist you, it would be very helpful if you could provide a minimal reproducible example of your code. This will allow us to understand the context and specifics of your setup. You can find guidance on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, here are a few steps you can try:
1. **Clear Cache**: Sometimes, clearing the cache can resolve issues related to model loading and optimization.
2. **Check Logs**: Review the logs for any specific error messages that might give more insight into why the model is getting stuck.
3. **Resource Availability**: Ensure that your system has sufficient resources (CPU, GPU, memory) available for the training process.

If the issue persists after trying these steps, please share the logs and any additional details that might help us diagnose the problem further.

Thank you for your patience and cooperation. We're here to help you get your model up and running smoothly!

**Comment by sergiuwaxmann** [comment]
@ImannKamal Hello!
Can you share the model ID with me so I can investigate this further?

**Comment by ImannKamal** [comment]
> Member
https://hub.ultralytics.com/models/T16PM3Aeq2HdX8C10t0u
For your reference, Im training the model using google colab. So, i think all the package is up to date because the hub auto update right?

**Comment by sergiuwaxmann** [comment]
@ImannKamal I just checked and it looks like [Ultralytics HUB](https://hub.ultralytics.com) didn't receive the final weights, reason why it shows "Disconnected" - most likely because of the internet connection. It looks like the last checkpoint is for epoch 99 (which is the final epoch).
Maybe you can try resuming the training? However, I am not sure if `ultralytics` will simply optimize the weights or try to resume which might not be possible as you are resuming the training from the final epoch.
I logged this bug and our team will work on fixing it as fast as possible.
Thank you for understanding!
