### ISSUE TITLE
How to get the app on huawei phones？

### ISSUE THREAD

**Issue by HLX-GitHub** [ultralytics/hub#745]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I want to get the app on huawei phones However the google play can't be installed on huawei phones.

**Comment by sergiuwaxmann** [comment]
@HLX-GitHub Hello!
Unfortunately, the Ultralytics YOLO mobile application is available only on the [App Store](https://apps.apple.com/us/app/ultralytics-yolo/id1452689527).
