### ISSUE TITLE
Problem in epoch 99

### ISSUE THREAD

**Issue by raoufstx** [ultralytics/hub#747]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

Hello,
I have a problem with the site. I ran a training of a YOLOv8 n model on 100 epochs. When I put the resume to continue the training on Google Colab, it remains stuck at 99 epochs and the training never ends even if it is indicated that the training ended on colab, so I can not deploy the model in question. I've tried several times to restart the training but the problem remains.
![image](https://github.com/ultralytics/hub/assets/109248476/304a13a6-9e5f-4c1d-b4ab-6a32f1096201)

### Environment

- Browser : Version 126.0.6478.127 (Build officiel) (64 bits).

**Comment by pderrenger** [comment]
@raoufstx hello,

Thank you for reaching out and providing details about the issue you're encountering with your YOLOv8 model training on Google Colab. To better assist you, it would be very helpful if you could provide a minimal reproducible example of your code. This will allow us to diagnose the problem more effectively. You can find guidance on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

In the meantime, please ensure that you are using the latest versions of all relevant packages, including the Ultralytics library. Sometimes, issues like this can be resolved by updating to the most recent versions.

If the problem persists after updating and providing a reproducible example, we will be more than happy to assist you further.

Thank you for your cooperation and patience! 😊

**Comment by sergiuwaxmann** [comment]
@raoufstx Hello!
Can you please share your model ID with me so I can investigate this further?

**Comment by raoufstx** [comment]
Hello!!
Yes sure.
https://hub.ultralytics.com/models/Iz4ReYF1SfLT9Hp6Dwl4

**Comment by pderrenger** [comment]
Hello @raoufstx,

Thank you for providing the model ID. This will help us investigate the issue more thoroughly.

To proceed, please ensure that you are using the latest versions of all relevant packages, including the Ultralytics library. Sometimes, issues like this can be resolved by updating to the most recent versions.

Additionally, if you could provide a minimal reproducible example of your code, it would greatly assist us in diagnosing the problem. You can find guidance on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

We appreciate your patience and cooperation. If the issue persists after these steps, we will continue to assist you in resolving it.

Thank you! 😊
