### ISSUE TITLE
INT 8 quantization is not implemented when selected to export TensorFlow Lite

### ISSUE THREAD

**Issue by franciscocostela** [ultralytics/hub#748]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

I trained an Object Detection Model using both YoloV5n and YoloV8n. In the Deploy tab, I selected TensorFlow Lite - advanced and selected 'Int 8 Quantization'. Then I clicked Export and downloaded the model when the button Download became available.
![Screenshot 2024-06-06 at 9 25 05 AM](https://github.com/ultralytics/hub/assets/68574696/9c8839e2-095f-4130-801f-9cc30ee78910)
 However, when I inspect the file, it looks like the quantization is never applied. This happens for both YoloV5n and YoloV8n
![image](https://github.com/ultralytics/hub/assets/68574696/aa52f73a-698b-4445-b0c4-859bf7cd5c34)
Is there anything that I am not doing correctly or is this really a bug?

**Comment by pderrenger** [comment]
@franciscocostela hello,

Thank you for bringing this to our attention and for providing detailed information about your issue. To better assist you, could you please provide a minimal reproducible example? This will help us understand the context and reproduce the issue on our end. You can find guidelines on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of the Ultralytics packages, as updates often include bug fixes and improvements that might resolve your issue.

Once we have this information, we can investigate further and provide more specific guidance. Thank you for your cooperation!

**Comment by sergiuwaxmann** [comment]
@franciscocostela Hello!
Can you check if the exported model size is 4x smaller than the fp32 one?

**Comment by franciscocostela** [comment]
Hi Sergiu,

Yes - It is about 4x smaller. These are the sizes of the files:
Original FP32 - 11.6MB
Fp16 - 5.8MB
Int8 - 3.0MB

I am trying to run the TFLite file through a conversion pipeline to deploy it into a camera but it fails with an error message about the file not being quantized. When I inspect it with Netron, I see that the quantization bias is FLOAT32. INT8 is used in some of the convolution layers but not all of them (see screenshot). This seems to trigger the error message using the conversion pipeline.

**Comment by pderrenger** [comment]
@franciscocostela hi Sergiu,

Thank you for the detailed information and for verifying the file sizes. It does seem like the INT8 quantization is partially applied, which might be causing the issue in your conversion pipeline.

To further investigate and resolve this, could you please provide a minimal reproducible example of your workflow? This will help us understand the exact steps and configurations you are using. You can find guidelines on how to create a minimal reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure you are using the latest versions of the Ultralytics packages and TensorFlow Lite tools, as updates often include important bug fixes and improvements.

Thank you for your cooperation, and we look forward to assisting you further!

**Comment by sergiuwaxmann** [comment]
@franciscocostela Based on the file size, the quantization is applied.
