### ISSUE TITLE
 Ultralytics IOS app doesn't work

### ISSUE THREAD

**Issue by Geniuspond** [ultralytics/hub#749]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets, Models, Projects

### Bug

I am a member of Ultralytics Pro and I trained my own model using the Ultralytics system. I have an iPhone XS Max. I installed the Ultralytics Hub IOS application and logged into the system. However, I can see the model I trained in the predict section of the application, but when I open the model, I do not see the results for this model. I think it shows results related to YOLOv8. Additionally, I see the model I trained in a private section of the project part of the application. When I try to open it, the system constantly appears to be loading and does not work. When I open the datasets tab, "datasetfailure" appears and I cannot see the dataset. I can access all these models via computer. I think your app is not working. Could there be a problem with the application?

**Comment by sergiuwaxmann** [comment]
@Geniuspond Please accept our apologies for the inconvenience. 

We are facing some issues with our Ultralytics HUB mobile application and our team is working of fixing them.

Thank you for understanding!

**Comment by yogendrasinghx** [comment]
@Geniuspond Thank you for reaching out and for detailing the issues you’re experiencing. We apologize for the inconvenience. I’m pleased to inform you that our latest app update, version `0.9.26,` includes fixes for several model and dataset loading issues.

Please update to version` 0.9.26`. If you continue to experience issues with your model results or loading datasets, try signing out, then uninstalling and reinstalling the app to ensure a fresh setup. We appreciate your patience and your valuable feedback—thank you for helping us improve the app experience. Let us know if there's anything more we can assist with!
