### ISSUE TITLE
How to deploy my own custom model in android devices

### ISSUE THREAD

**Issue by Joe-KI333** [ultralytics/hub#75]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Add the Train model in detect section.

**Comment by kalenmike** [comment]
@Joe-KI333 Thank you for reaching out. I am not quite sure I understand what you are suggesting, do you mind elaborating?

**Comment by Joe-KI333** [comment]
> elaborating

Actually I trained my own custom dateset  in yolov5n model from ultralytics hub. Can I use that model to deploy it on android devices.

**Comment by barney2074** [comment]
You'll obviously need the Ultralytics app
<img width="1249" alt="Screen Shot 2022-08-10 at 9 40 02 pm" src="https://user-images.githubusercontent.com/25944617/183897730-875fe512-104d-42ac-8590-4d486d5daca9.png">

**Comment by kalenmike** [comment]
@Joe-KI333 Thanks for elaborating. You can preview your custom model using the Ultralytics App as mentioned by @barney2074. You can get the app here:
[https://play.google.com/store/apps/details?id=com.ultralytics.ultralytics_app](https://play.google.com/store/apps/details?id=com.ultralytics.ultralytics_app)

You can also export to TensorFlow Lite  if you have already built your own android application.

I hope that answers your question?

**Comment by kalenmike** [comment]
@Joe-KI333 Thanks for the response. We found an issue with the exports on our end. You should now be able to try again it should work for you.

Please let me know if you still have issues.

**Comment by Joe-KI333** [comment]
> @Joe-KI333 Thanks for the response. We found an issue with the exports on our end. You should now be able to try again it should work for you.
> 
> Please let me know if you still have issues.

Thank you sir now I'm able to download those model but while running it on android it is not detecting object or drawing box, I should retrain my model my issues almost solved.🙏👼

**Comment by kalenmike** [comment]
@Joe-KI333 Does your model detect correctly when using the web preview?

**Comment by Joe-KI333** [comment]
> @Joe-KI333 Does your model detect correctly when using the web preview?

Yes sir it is fine in web preview.
 My phone is redmi 6 it have 4gb  ram 
![image](https://user-images.githubusercontent.com/85284912/184209401-ca46e3d9-005a-481e-ae0e-98126d77df31.png)

**Comment by Joe-KI333** [comment]
> @Joe-KI333 Does your model detect correctly when using the web preview?

yes this is the results from phone even change the the threshold
![WhatsApp Image 2022-08-14 at 1 35 04 AM](https://user-images.githubusercontent.com/85284912/184535478-37dc1927-3a65-43dd-8e0f-d5276b65faa4.jpeg)

**Comment by kalenmike** [comment]
@Joe-KI333 Thanks for the feedback. We will take a look at the Android app and see why it is not playing well with your device.

**Comment by Joe-KI333** [comment]
> @Joe-KI333 Thanks for the feedback. We will take a look at the Android app and see why it is not playing well with your device.

Thank you Sir All the best to Ultralytics team. Looking forward for a good result👼

**Comment by UltralyticsAssistant** [comment]
@Joe-KI333 Your patience and understanding are much appreciated! Rest assured, the team is working on it. If you have any more questions or need further assistance in the future, don't hesitate to reach out. Best of luck with your projects, and thank you for being part of the YOLO community! 🌟

**Comment by Joe-KI333** [comment]
> @Joe-KI333 Your patience and understanding are much appreciated! Rest assured, the team is working on it. If you have any more questions or need further assistance in the future, don't hesitate to reach out. Best of luck with your projects, and thank you for being part of the YOLO community! 🌟

Thank you

**Comment by UltralyticsAssistant** [comment]
@Joe-KI333 you're welcome! If you need any more help, just let us know. Happy to assist! 😊🚀
