### ISSUE TITLE
No replication in mobile app

### ISSUE THREAD

**Issue by ghost** [ultralytics/hub#756]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

I created a project in web and it's doesn't replicate in mobile app ,I trained model with custom data set.

### Environment

Dell Inspiron 14 5140

**Comment by sergiuwaxmann** [comment]
@Charan2128 Unfortunately, we have some issues with the mobile application. Try to uninstall the application and re-install it again.

**Comment by WARHE8D** [comment]
+1

**Comment by WARHE8D** [comment]
Hello I'm facing this issue,
I have created a project and trained my model in it. The folder was updated in my android app but I couldn't use the model.

The model is working pretty good on pc but...

![Screenshot_20240720-032844.png](https://github.com/user-attachments/assets/4c405902-a295-4d66-b1f3-3fbfe00af772)

![Screenshot_20240720-032941.png](https://github.com/user-attachments/assets/032aac03-f9e8-48d8-8046-1c644c72a2a4)

As you can I have selected my model but it's not using my model.

![Screenshot_20240720-033014.png](https://github.com/user-attachments/assets/643b0c7d-c661-4eb1-b4f4-3de465138df7)

**Comment by pderrenger** [comment]
Hi @WARHE8D,

Thank you for reaching out and providing detailed information about the issue you're experiencing. It sounds like there might be a synchronization issue between the web and mobile app.

To help us diagnose and resolve this issue, could you please try the following steps:

1. **Ensure Latest Versions**: Make sure you are using the latest versions of both the Ultralytics HUB web and mobile applications. Sometimes, updates include important bug fixes and improvements.

2. **Re-login**: Try logging out and back into your account on the mobile app. This can sometimes resolve synchronization issues.

3. **Check Internet Connection**: Ensure that your mobile device has a stable internet connection, as poor connectivity might hinder proper synchronization.

4. **Clear Cache**: On your mobile device, go to the app settings and clear the cache. This can help resolve any temporary issues.

If the issue persists after trying these steps, please let us know. Additionally, any error messages or logs you can provide would be very helpful for further troubleshooting.

Thank you for your patience and cooperation. We appreciate your support and are here to help you get this resolved as quickly as possible. 😊

**Comment by WARHE8D** [comment]
Hello,
Thank you for a prompt response.
Yes I did try everything.
I have reinstalled the app from my mobile and just now I did clear my cache. No luck.

**Comment by pderrenger** [comment]
Hi @WARHE8D,

Thank you for trying those steps and for your prompt response. I'm sorry to hear that the issue persists despite your efforts.

Given that you've already reinstalled the app and cleared the cache, let's try a few more troubleshooting steps:

1. **Verify Model Status**: Ensure that the model training has been fully completed and the model is properly saved and accessible on the web platform. Sometimes, incomplete training or saving issues can cause synchronization problems.

2. **Check Model Permissions**: Make sure that the model and project permissions are correctly set to allow access from the mobile app. Occasionally, permission settings can restrict access.

3. **Sync Manually**: On the mobile app, try to manually refresh or sync the project list. This can sometimes force the app to update its data.

4. **Error Logs**: If possible, check if there are any error messages or logs on the mobile app that might give us more insight into what’s going wrong. Screenshots or descriptions of any errors would be very helpful.

If none of these steps resolve the issue, it might be a bug that needs further investigation. In that case, could you please provide the following additional information:
- The version of the mobile app you are using.
- The operating system version of your mobile device.
- Any specific error messages or behavior you observe when trying to use the model.

We appreciate your patience and cooperation as we work to resolve this issue. Your feedback is invaluable to us, and we are committed to ensuring you have a smooth experience with Ultralytics HUB.

Thank you! 😊

**Comment by WARHE8D** [comment]
Hello @pderrenger ,
sorry for the late reply.
Here's the update:
1) the model is completely trained
2) the permission is **private** but I am logged in with the same account on my mobile as well.
3) did try refreshing but it remains unchanged
4) app version: 0.9.24, andriod version: 14

**Comment by yogendrasinghx** [comment]
@WARHE8D  Thank you for letting us know about the issues with syncing and viewing your project on the mobile app. We’ve recently released an update, version `0.9.26`, which addresses several syncing and model loading issues on mobile devices.

Please update to version `0.9.26`. If the issue continues, try signing out, then uninstalling and reinstalling the app for a clean setup. We appreciate your patience and feedback, as it helps us improve. Let us know if you encounter any further issues—thank you!
