### ISSUE TITLE
Is it possible to add my own 10 classes to an existing dataset?

### ISSUE THREAD

**Issue by proDev-Theron** [ultralytics/hub#76]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I want to train a model that can detect what plant it is based on an image of a leaf. 
I don't want the model to process it if the image is not a leaf in the first place.
I'm thinking of adding my 10 classes to the COCO128 dataset so if the Inference Result is 'none' then it can start detecting what species of plant the leaf is.
What I'm thinking of right now seems like a very bad idea. Maybe I want your answer to be more about changing my approach.

**Comment by glenn-jocher** [comment]
@proDev-Theron I don't understand your question. To determine if the image has a leaf you'll need a model to run. If you're going to run a model just run the model with the 10 classes you'd like to detect. Simple.

**Comment by barney2074** [comment]
@proDev-Theron
do you mean a second stage classifier ?
i.e the 1st one might detect plants. The 2nd one detects species of plants

**Comment by proDev-Theron** [comment]
> @proDev-Theron do you mean a second stage classifier ? i.e the 1st one might detect plants. The 2nd one detects species of plants

Maybe. It's my first time hearing about second-stage classifiers. What kind of output will I have with a second-stage classifier? A single .pt file? How do I connect that to a custom website?

**Comment by kalenmike** [comment]
@proDev-Theron It seems like your solution may be overly complicated. If you train your model on your 10 classes of leaves you can then run inference on an image, if a leaf is detected and matches on of your classes it will show up in the results. If there are no leaves detected then the inference results will be empty.

Using a pretrained YOLOv5 model gives you all of the benefits of a model trained on COCO2017, but its classes will not show up in your inference results if you do not include then in your class list.

**Comment by proDev-Theron** [comment]
You mean I could use the pretrained model and get inference results just by
adding them to my classes in the yaml file? That's awesome!
How can I use the model in my web app?

**Comment by kalenmike** [comment]
@proDev-Theron You would still have to retrain the pretrained model on your custom dataset. 

We do not currently offer any frameworks to help get your web app setup but we are busy working on an inference API which would allow your web app to connect to the API and fetch inference results. We also offer Tensorflow JS as an export option which you would then have to implement  in your web app yourself.

Check out this link for more on Tensorflow JS
[https://www.tensorflow.org/js](https://www.tensorflow.org/js)
