### ISSUE TITLE
Team invitation never arrives

### ISSUE THREAD

**Issue by rolurq** [ultralytics/hub#763]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Settings

### Bug

I created a team and sent an invite using an email address, but the invite never arrives. I have tried with a couple different emails and is the same result.

### Environment

Ultralytics HUB Version
v0.1.45
Client User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.5 Safari/605.1.15
Operating System
MacIntel
Browser Window Size
1470 x 866
Server Timestamp
1720457011

### Minimal Reproducible Example

1. Go to settings -> Teams
2. Access an already existing team
3. Click on Invite Member
4. Fill the email address and click and click Invite

The email never arrives and the invitation is forever in pending state.

**Comment by sergiuwaxmann** [comment]
@rolurq Hello!

As this is a new feature, we're still in the process of developing and refining it to ensure it meets your needs. At the moment, the person you invited will see an in-app notification as described in [our documentation](https://docs.ultralytics.com/hub/teams#join-team) - apologies for the confusion.

Here are some relevant pages:
https://docs.ultralytics.com/hub/teams#invite-member
https://docs.ultralytics.com/hub/teams#seats (important)
https://docs.ultralytics.com/hub/teams#join-team
