### ISSUE TITLE
Training with HUB crashed

### ISSUE THREAD

**Issue by pavelboyko** [ultralytics/hub#769]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

This training run https://hub.ultralytics.com/models/pv4h5kBINzUQVO5s8ee3?tab=train completed all epochs but got stuck in this state and never finished.

<img width="1440" alt="Screenshot 2024-07-17 at 12 33 28" src="https://github.com/user-attachments/assets/4e428411-dda6-4e61-b839-debbe811a84f">

### Environment

Web

### Minimal Reproducible Example

Login to the HUB, upload the small dataset, start training, and observe the bug.

**Comment by pavelboyko** [comment]
The second attempt crashed in the same way https://hub.ultralytics.com/models/V5Y3L3AuODQs1H9uROs8?tab=train

**Comment by sergiuwaxmann** [comment]
@pavelboyko Hello!

Apologies for the inconvenience.

I did a test on my end and everything seems to work correctly - I will investigate this further.

Do you have the option to resume the training that crashed?

**Comment by pavelboyko** [comment]
Hi Sergiu,

Thanks for your prompt response. No, I don't have the option to resume training, only "Start training." See the screenshot:

<img width="1438" alt="Screenshot 2024-07-17 at 13 09 19" src="https://github.com/user-attachments/assets/4e74ac3c-0bdb-4ee3-8f04-23beb598f89b">

This is what I see on the models list screen:

<img width="1227" alt="Screenshot 2024-07-17 at 13 09 02" src="https://github.com/user-attachments/assets/486701fd-446f-4ac3-97ca-22cadfe8a51a">

The training crashed during or after the "Optimizing model" stage if it helps.

**Comment by pavelboyko** [comment]
You're right; these training runs are shorter than 15 minutes. 

I retried with the same result. When all the epochs are done, it goes from this:

<img width="1440" alt="Screenshot 2024-07-17 at 13 22 21" src="https://github.com/user-attachments/assets/63a2129b-43bf-4ffb-8aad-63db9cbe8c85">

to this:

<img width="1440" alt="Screenshot 2024-07-17 at 13 24 04" src="https://github.com/user-attachments/assets/7410e78f-2924-47b4-b112-b2058ed8cf03">

**Comment by sergiuwaxmann** [comment]
@pavelboyko I still can't reproduce it on my end but let me restart our backend. I will update you soon.

**Comment by pavelboyko** [comment]
@sergiuwaxmann I ran the same training loop with Google Colab backend and also got a crash after training with the following stack:

```
100 epochs completed in 0.165 hours.
Optimizer stripped from runs/detect/train/weights/last.pt, 6.2MB
Optimizer stripped from runs/detect/train/weights/best.pt, 6.2MB

Validating runs/detect/train/weights/best.pt...
Ultralytics YOLOv8.2.58 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Model summary (fused): 168 layers, 3,007,013 parameters, 0 gradients, 8.1 GFLOPs
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-3-75755c0f186c>](https://localhost:8080/#) in <cell line: 4>()
      2 
      3 model = YOLO('https://hub.ultralytics.com/models/wUSd0KvmyWU5LBVNfP9F')
----> 4 results = model.train()

6 frames
[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py](https://localhost:8080/#) in train(self, trainer, **kwargs)
    650 
    651         self.trainer.hub_session = self.session  # attach optional HUB session
--> 652         self.trainer.train()
    653         # Update model and cfg after training
    654         if RANK in {-1, 0}:

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in train(self)
    202 
    203         else:
--> 204             self._do_train(world_size)
    205 
    206     def _setup_scheduler(self):

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in _do_train(self, world_size)
    467                 f"{(time.time() - self.train_time_start) / 3600:.3f} hours."
    468             )
--> 469             self.final_eval()
    470             if self.args.plots:
    471                 self.plot_metrics()

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py](https://localhost:8080/#) in final_eval(self)
    645                     LOGGER.info(f"\nValidating {f}...")
    646                     self.validator.args.plots = self.args.plots
--> 647                     self.metrics = self.validator(model=f)
    648                     self.metrics.pop("fitness", None)
    649                     self.run_callbacks("on_fit_epoch_end")

[/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py](https://localhost:8080/#) in decorate_context(*args, **kwargs)
    113     def decorate_context(*args, **kwargs):
    114         with ctx_factory():
--> 115             return func(*args, **kwargs)
    116 
    117     return decorate_context

[/usr/local/lib/python3.10/dist-packages/ultralytics/engine/validator.py](https://localhost:8080/#) in __call__(self, trainer, model)
    141 
    142             if str(self.args.data).split(".")[-1] in {"yaml", "yml"}:
--> 143                 self.data = check_det_dataset(self.args.data)
    144             elif self.args.task == "classify":
    145                 self.data = check_cls_dataset(self.args.data, split=self.args.split)

[/usr/local/lib/python3.10/dist-packages/ultralytics/data/utils.py](https://localhost:8080/#) in check_det_dataset(dataset, autodownload)
    327             else:
    328                 m += f"\nNote dataset download directory is '{DATASETS_DIR}'. You can update this in '{SETTINGS_YAML}'"
--> 329                 raise FileNotFoundError(m)
    330             t = time.time()
    331             r = None  # success

FileNotFoundError: 
Dataset '/content/datasets/project-1-at-2024-07-17-08-22-d92461f2_ultralytics/data.yaml' images not found ⚠️, missing path '/content/datasets/images/val'
Note dataset download directory is '/content/datasets'. You can update this in '/root/.config/Ultralytics/settings.yaml'
```

I guess this is the same crash that also happens in your training backend. Can you please explain it? 

I do have images/val folder in my custom dataset:

<img width="318" alt="Screenshot 2024-07-17 at 15 37 07" src="https://github.com/user-attachments/assets/b03eb247-a43f-4f4e-886f-3cae76bbb687">

Also, the training loop successfully prints validation metrics after every epoch, so it looks like it can find validation images & labels.

Just in case, this is how my data.yaml file looks like:

```
names:
[REDACTED]
path: .
train: images/train
val: images/val
```

**Comment by pavelboyko** [comment]
I re-uploaded the dataset without this line in the `data.yaml` file:

```
path: .
```

And now the training has successfully finished. 

I'm closing the issue. In the ideal world, I would fix the validation step behavior and also improve logging and dataset format documentation, but this is up to you to decide.

**Comment by sergiuwaxmann** [comment]
@pavelboyko Nice catch! I am glad it worked in the end and I added to our backlog the enhancement you mentioned.
Also, we just restarted our backend.
