### ISSUE TITLE
How to logging results of hub ultralytics training process in Google Drive ?

### ISSUE THREAD

**Issue by adindravickarega** [ultralytics/hub#77]
Hello...

This is my first time using Ultralytics Hub for training my model.

In Google Colab with cloned yolov5 official repository, i am used to run this code for training my model in order to log my training process results in my Google Drive folder :

!python train.py --img 640 --batch 8 --epochs 200 --data /content/drive/MyDrive/dataset/data.yaml --weights yolov5s.pt --cache --project /content/drive/MyDrive/ --name yolov5s_train_dataset

In case of training model with Ultralytics Hub, to train the model, we run this code 

ultralytics.start('API KEY')  # train 

And logging results are automatically saved in yolov5/runs/train/exp

So, how can i modify the Colab so that the training logging results can be saved in the Google Drive folder ?

Thank you

**Comment by barney2074** [comment]
High level logging is shown within Hub for Hub training jobs- I'd guess you can't change this
<img width="981" alt="Screen Shot 2022-07-27 at 8 53 40 am" src="https://user-images.githubusercontent.com/25944617/185387694-63936c84-b829-45b5-938f-a33c7123e99f.png">

However, normal YoloV5 will optionally log to Wandb.ai- which is very detailed- I'd recommend this

**Comment by glenn-jocher** [comment]
@barney2074 @adindravickarega yes you can just run this code in colab before starting a YOLOv5 or HUB training to also log to W&B.

```python
# Weights & Biases
%pip install -q wandb
import wandb
wandb.login()
```
