### ISSUE TITLE
Creating a small dataset

### ISSUE THREAD

**Issue by NickBarn** [ultralytics/hub#770]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi - is there a tool to create a dataset, or just to draw bounding boxes and create the labels? I have had no luck looking through the videos or issues / discussions.
Thank you!

**Comment by pderrenger** [comment]
@NickBarn hi there!

Thank you for reaching out. Creating a dataset with labeled bounding boxes is a crucial step in training your YOLO models. While Ultralytics HUB itself doesn't provide a built-in tool for drawing bounding boxes, you can use several external tools to create and label your dataset. Here are a few popular ones:

1. **LabelImg**: A graphical image annotation tool that allows you to draw bounding boxes and create labels. You can download it from [LabelImg GitHub](https://github.com/tzutalin/labelImg).

2. **Roboflow**: An online platform that offers tools for dataset creation, annotation, and augmentation. You can sign up and start using it at [Roboflow](https://roboflow.com/).

3. **CVAT (Computer Vision Annotation Tool)**: A web-based tool for annotating video and image datasets. You can find more information and get started at [CVAT](https://github.com/openvinotoolkit/cvat).

Once you have your dataset annotated, you can upload it to Ultralytics HUB and proceed with training your model. For detailed steps on how to upload your dataset and train a model, please refer to our [Ultralytics HUB Quickstart Guide](https://docs.ultralytics.com/hub/quickstart/).

If you encounter any issues or have further questions, feel free to ask. We're here to help! 😊

**Comment by NickBarn** [comment]
Muy buen y muchas gracias, Paula,
This is exactly what I needed to push me in the right direction. Used my github ID to log into Roboflow and I'm now busy grabbing images from video, ready to box and annotate.
Again, huge thank-you!
Nick

**Comment by pderrenger** [comment]
@NickBarn hi Nick,

I'm glad to hear that you're making progress with Roboflow! It's a powerful tool for creating and annotating datasets, and it should serve you well in preparing your data for training YOLO models.

Once you've completed your annotations, don't forget to export your dataset in a format compatible with Ultralytics HUB. Typically, YOLO format is a good choice. After that, you can easily upload your dataset to the HUB and start training your model.

If you need any further assistance or run into any issues, feel free to reach out here. The YOLO community and the Ultralytics team are always here to help. 😊

Happy annotating and training!

**Comment by NickBarn** [comment]
Hi Paula,

Thanks so much for your help!

Sometimes it feels as though I’m paddling in the dark across a big lake of unfamiliarity and it’s really gratifying to know there are people like you shining a light into the darkness.

Have a super weekend.



 

Nick Barnett MSc CEng MIET
Mobile:     +44 (0)7710 552994

Office:       +44 (0)2476 694496

**Comment by pderrenger** [comment]
Hi Nick,

Thank you for your kind words! It's wonderful to hear that the guidance has been helpful for you. Navigating new tools and technologies can indeed feel daunting, but you're making great strides, and that's what counts. 😊

If you have any more questions or need further assistance as you continue with your project, don't hesitate to reach out here. The community and the Ultralytics team are always ready to support you.

Wishing you a productive and enjoyable weekend!
