### ISSUE TITLE
Undelete a deleted account

### ISSUE THREAD

**Issue by sharner** [ultralytics/hub#773]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

My colleague create an account with `ezra@layerjot.com` ; he then deleted the account. How he needs the account again, but he cannot create it because it says it is being deleted.  Can you please undeleted his account or otherwise allow him to recreate his account?  Thanks.

**Comment by sergiuwaxmann** [comment]
@sharner The account was reactivated.
