### ISSUE TITLE
IOS export fails

### ISSUE THREAD

**Issue by barney2074** [ultralytics/hub#78]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Export

### Bug

Hi

I am having  problem exporting a model to IOS format
Others model exports have worked o.k- the only difference I can think of is that the training images are aerial photos with very small objects, so I trained at 1000px
![image](https://user-images.githubusercontent.com/25944617/185721807-69b4cff3-91e8-425a-a00d-e2669bcbad2f.png)

thanks

Andrew

### Environment

PC: Surface Book
OS: Windows 11
Browser: Edges

Also tried exporting on IOS app with same results

### Minimal Reproducible Example

trained model based on https://www.kaggle.com/datasets/aceofspades914/cgi-planes-in-satellite-imagery-w-bboxes
(just contains 1 class)
Inferencing within Hub works ok

**Comment by glenn-jocher** [comment]
@barney2074 thanks for the bug report! I'm able to reproduce CoreML export failures in HUB on my end. I'll add a TODO to investigate.

**Comment by glenn-jocher** [comment]
@kalenmike I'm still seeing this error on HUB CoreML and Ultralytics-iOS exports. Just tested on a newly trained ultralytics 0.0.33 model.

**Comment by barney2074** [comment]
All good, thanks Kalen

**Comment by UltralyticsAssistant** [comment]
@barney2074 you're welcome, Andrew! I'm glad to hear that the issue is resolved. If you have any more questions or encounter further issues, feel free to reach out. Happy modeling, and thank you for being a part of the YOLO community and using Ultralytics HUB. Your contributions help improve our platform for everyone.
