### ISSUE TITLE
How to download my dataset (segment)?

### ISSUE THREAD

**Issue by DGKang234** [ultralytics/hub#788]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Somehow my account is keep deleting on ultralytics which happended 5 times. Thus, I would like to download my data and use other account for the training and data management on ultralytics.

I could not find the way to download my data which uploaded on ultralytics.
Could you please let me know how to download them?

**Comment by sergiuwaxmann** [comment]
@DGKang234 At the moment, it isn't possible to download your data and re-upload it.
The account is getting deleted when the user clicks on the "Delete All Data" button and confirms the action.

**Comment by DGKang234** [comment]
@sergiuwaxmann Are you planning to have the function to download the own data?
I really have not touched anything near the "Delete All Data". I don't even know where the button is...

**Comment by sergiuwaxmann** [comment]
@DGKang234 At the moment, this feature is in the backlog. Unfortunately, we are not working on it and it isn't part of the short-term roadmap.

**Comment by UltralyticsAssistant** [comment]
@DGKang234 great news! The dataset download button has been implemented in HUB by @sergiuwaxmann and is now live :)

![image](https://github.com/user-attachments/assets/71919636-9e62-4c2f-96a6-5ce54271c27e)

For more details see https://docs.ultralytics.com/hub/datasets
