### ISSUE TITLE
Model training stuck in disconnected problem

### ISSUE THREAD

**Issue by QiConstantine** [ultralytics/hub#791]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I found my model stuck in the state of disconnected and it cannot become work again, I've got no idea how to solve it.
<img width="1255" alt="iShot_2024-08-04_14 53 52" src="https://github.com/user-attachments/assets/0bc1ffda-9103-479d-97bd-11b8779d3b66">

**Comment by pderrenger** [comment]
@QiConstantine hello,

Thank you for reaching out and providing the details of your issue. I'm sorry to hear you're experiencing difficulties with your model training.

To help resolve this, please try the following steps:

1. **Update to the Latest Version**: Ensure that you are using the latest versions of the Ultralytics HUB and YOLO packages. Sometimes, issues are resolved in newer releases. You can update your packages using:
   ```bash
   pip install --upgrade ultralytics
   ```

2. **Check Internet Connection**: The "disconnected" state might be related to network issues. Verify that your internet connection is stable.

3. **Restart the Training**: Sometimes, simply restarting the training process can resolve the issue. You can do this by stopping the current training session and starting a new one.

4. **Review Logs**: Check the logs for any error messages or warnings that might provide more insight into why the model is stuck. This can often point to specific issues that need to be addressed.

5. **Resource Availability**: Ensure that your system has sufficient resources (CPU, GPU, memory) available for training. Resource constraints can sometimes cause training processes to hang.

If the issue persists after trying these steps, please provide any additional logs or error messages you see. This will help us diagnose the problem more effectively.

Thank you for your patience and cooperation. We appreciate your contributions to the YOLO community and the Ultralytics team is here to support you!

**Comment by QiConstantine** [comment]
I rent the server on your website(https://hub.ultralytics.com) and train my model, thence I don't think I can find a log. Is it helpful if I give you my account, so you can find out what happened on the server.

**Comment by sergiuwaxmann** [comment]
@QiConstantine Can you share your model ID with me so I can investigate tis further? You can find the model ID in the URL of your model's page.

**Comment by QiConstantine** [comment]
1x4uqbE0WxqFyH720Ikj?tab=train，is this?

**Comment by sergiuwaxmann** [comment]
@QiConstantine It appears there is a bug with the timed training. While we work on fixing this issue, I have refunded the amount you used for this training so that you can start another one.

PS I suggest using Epochs training instead of Timed training.

**Comment by QiConstantine** [comment]
thanks for your help

**Comment by sergiuwaxmann** [comment]
@QiConstantine No worries! Apologies for the inconvenience.
