### ISSUE TITLE
Cannot retrieve my full storage back

### ISSUE THREAD

**Issue by PHIKHONAMTHEMBU** [ultralytics/hub#792]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

After deleting all datasets from the dataset section and also hard deleting the dataset in Trash, my storage is always around 150GB/200GB, making only 50GB available. could you advise why is this the case? 

The only datasets are those default datasets. 

![image](https://github.com/user-attachments/assets/27b2f13a-48d0-4491-9795-87b44d42c5ee)

**Comment by sergiuwaxmann** [comment]
@PHIKHONAMTHEMBU Hello!
Can you share the ID of one of your datasets/projects/models so I can identify your account?
Also, did you empty the trash? The Trash page is available in the Sidebar.

**Comment by PHIKHONAMTHEMBU** [comment]
@sergiuwaxmann , yes I did empty the trash bin. 

https://hub.ultralytics.com/projects/**cukRNmYLNGRNrGkaqAUz**

**Comment by sergiuwaxmann** [comment]
@PHIKHONAMTHEMBU Indeed, your account currently has 1 dataset, 2 projects, and 13 models. Additionally, there are 19 other datasets tracked in storage. Our team is working to resolve this issue as quickly as possible. Thank you for your understanding!

**Comment by PHIKHONAMTHEMBU** [comment]
@sergiuwaxmann , thank you.

**Comment by sergiuwaxmann** [comment]
@PHIKHONAMTHEMBU No worries! I am here to help!

**Comment by sergiuwaxmann** [comment]
@PHIKHONAMTHEMBU Is the storage issue resolved now?

**Comment by PHIKHONAMTHEMBU** [comment]
@sergiuwaxmann , yes it has, thank you very much for your assistance. Kudos to you and your team.

**Comment by sergiuwaxmann** [comment]
@PHIKHONAMTHEMBU Glad I could help!
