### ISSUE TITLE
Any dataset submitted fails

### ISSUE THREAD

**Issue by nolby003** [ultralytics/hub#793]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

I am trying to perform the detect method, I have followed the example dataset to the T and no joy, always failing, even with a set of 20 train, val and test images with accompanying labels, no joy, the interface is useless.

### Environment

Not applicable to this issue.

### Minimal Reproducible Example

Even tried your classify function, same issue, cannot get a successful init on any dataset I submit that is custom.

### Additional

Yes, if I cannot use a custom dataset on your app, I will happily make my own.

**Comment by nolby003** [comment]
Ok weird, now it works...

**Comment by pderrenger** [comment]
@nolby003 hi there,

Thank you for the update! 😊 I'm glad to hear that it's working now. Sometimes, issues can be resolved by re-uploading the dataset or making minor adjustments.

If you encounter any further problems or have any questions, please don't hesitate to reach out. We're here to help!
