### ISSUE TITLE
How does pricing work for the Cloud training?

### ISSUE THREAD

**Issue by aramirr** [ultralytics/hub#814]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

I'm intereseted in the cloud training of Ultralytics Hub. Could I get more detail on the pricing? By having a PRO account, do I have some "free" credit to train? Or I need to pay 20$ for accessing the feature + paying extra for each training?

Both options should be fine, but I want to be clear as this will be paid by my company.

Thanks!

**Comment by sergiuwaxmann** [comment]
@aramirr Hello!

The PRO Plan will give you access to the Cloud Training feature. You have to top-up your account balance which is used for during Cloud Training.

Here are some relevant docs pages:
https://docs.ultralytics.com/hub/pro
https://docs.ultralytics.com/hub/pro#account-balance
https://docs.ultralytics.com/hub/cloud-training
https://docs.ultralytics.com/hub/inference-api#dedicated-inference-api

**Comment by aramirr** [comment]
Thanks @sergiuwaxmann now it is much clearer, I couldn't find the exact info.

**Comment by sergiuwaxmann** [comment]
@aramirr Glad I could help!
