### ISSUE TITLE
Want to integrate another workspace.

### ISSUE THREAD

**Issue by Nishant2018** [ultralytics/hub#820]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I already linked my ultralytics account to roboflow, but I want to integrate Kaggle also.

**Comment by sergiuwaxmann** [comment]
@Nishant2018 Hello!
Unfortunately, we don't have an integration with Kaggle...

**Comment by Nishant2018** [comment]
> @Nishant2018 Hello! Unfortunately, we don't have an integration with Kaggle...

Thank you so much for providing me information.

**Comment by sergiuwaxmann** [comment]
@Nishant2018 No worries! Apologies for the inconvenience.
