### ISSUE TITLE
Load your models

### ISSUE THREAD

**Issue by gilligas** [ultralytics/hub#821]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I have trained some models in the past. Would be cool if you could just load you model to the app

### Use case

To show friends how your models behaves

**Comment by glenn-jocher** [comment]
@gilligas hello!

Thank you for your suggestion! 😊

You can indeed load and showcase your models using the Ultralytics HUB. Here's a quick guide on how to do it:

1. **Create a Project**: Navigate to the Projects page by clicking on the **Projects** button in the sidebar and then click on the **Create Project** button. You can name your project and add a description or image if you like.

2. **Upload Your Models**: Once your project is created, you can upload your previously trained models to this project. This will allow you to manage and showcase them effectively.

3. **Share Your Project**: To share your project with friends, navigate to the Project page, open the project actions dropdown, and click on the **Share** option. Set the general access to "Unlisted" and save. You can then share the direct link with anyone, and they will be able to view your models without needing an Ultralytics HUB account.

For more detailed instructions, you can refer to our [Ultralytics HUB Projects Documentation](https://docs.ultralytics.com/hub/projects/).

Feel free to reach out if you have any more questions or need further assistance!

**Comment by sergiuwaxmann** [comment]
@gilligas Hello!
Our team is working on releasing a new feature soon that allows users to upload models trained locally to Ultralytics HUB which can be used afterwards for analysis, inference (including the mobile application) and exports.
However, the minim model version is not determined yet.
I will keep you updated.

**Comment by john-rocky** [comment]
@gilligas 
Currently, the app has been updated to allow you to load and use custom models in hub-app. Please check it out.
https://play.google.com/store/apps/details?id=com.ultralytics.ultralytics_app

**Comment by gilligas** [comment]
Wow amazing! Super thanks!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
