### ISSUE TITLE
integrations

### ISSUE THREAD

**Issue by giantonti1801** [ultralytics/hub#825]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Is there any way to use Ultralitycs Hub only as a repository for the data set to train in Google Colab? For example, I would like to be able to indicate the address of the dataset in Ultralitycs Hub of my repository through Google Colab, where the dataset and the YAML file are located. And then I can have full control of the training in Google Colab. Just use the repository.

### Use case

I would obviously use this function, ultralitycs will have to charge me for the time of use during training. it happens that I need to train a model with yolov5s and use it as a pre-trained model but ultralitycs hub does not have this model in its system so all the training I do is not compatible for use in the custom model of yolov5 2.6. Until now I have trained with this model without problem in colab but in ultraliticx hub it does not allow it and all the yolov5 models it has are not compatible.

**Comment by glenn-jocher** [comment]
@giantonti1801 hello!

Thank you for reaching out. Currently, Ultralytics HUB is designed to provide a streamlined experience for training models directly within its platform, and it doesn't support using it solely as a dataset repository for external training environments like Google Colab.

However, you can download your datasets from Ultralytics HUB and upload them to Google Colab for training. This way, you can maintain full control over your training process in Colab.

Regarding compatibility with YOLOv5s and other versions, it's important to ensure that the model versions align with your training requirements. If you're encountering compatibility issues, you might want to check if the latest versions of YOLOv5 are being used, as updates often resolve such issues.

If you have any further questions or need assistance with a specific setup, feel free to ask. We're here to help! 😊

**Comment by sergiuwaxmann** [comment]
@giantonti1801 Ultralytics HUB doesn't support YOLOv5 for training anymore as it uses the latest YOLOv8 now.
You can use YOLOv5su instead of YOLOv5s.
