### ISSUE TITLE
restore my account

### ISSUE THREAD

**Issue by doksuri761** [ultralytics/hub#827]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! An error occurs when logging into my github account: This account is currently being deleted. Please restore my account:
factorio@naver.com

**Comment by glenn-jocher** [comment]
@doksuri761 hello! 😊

It sounds like you're experiencing an issue with your GitHub account status. Unfortunately, account restoration is something that needs to be handled directly by GitHub support. I recommend reaching out to GitHub's support team for assistance with restoring your account.

If you have any questions or need help related to Ultralytics HUB, feel free to ask here. We're happy to assist with any technical issues or questions you might have. 

Best of luck with your account restoration! 🚀

**Comment by sergiuwaxmann** [comment]
@doksuri761 Hello! Your account has been successfully restored!

**Comment by doksuri761** [comment]
It doen't works. it still alert with "This account is currently being deleted."

**Comment by pderrenger** [comment]
@doksuri761 hello! It sounds like you're experiencing an issue with your account. Please ensure you're using the latest version of the Ultralytics HUB. If the problem persists, try clearing your browser cache or using a different browser. 

If you continue to face issues, please reach out through the official support channels on the Ultralytics HUB for further assistance. Thank you for your patience! 😊
