### ISSUE TITLE
User model loading problem in android smartphone.

### ISSUE THREAD

**Issue by Passportmr** [ultralytics/hub#828]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

can't load the user's model on the android smartphone unless he exits the app and re-enters.
you should check it out on ios smartphones too.

### Environment

Android smartphone.

### Additional

1. Exporting user model : Pass
2. Downloading user model : Does not working 
Solution 
Exit from application and reopened to download user model.

**Comment by glenn-jocher** [comment]
@Passportmr hello!

Thank you for bringing this to our attention. It seems like there might be an issue with model loading on Android devices. To help us investigate further, could you please ensure that you are using the latest version of the Ultralytics Android App? Sometimes, updates can resolve unexpected behavior.

If the problem persists, try clearing the app cache or reinstalling the app to see if that helps. Additionally, testing on a different device could provide more insights.

We'll also look into the iOS version to ensure consistency across platforms. Your feedback is invaluable in helping us improve the app! 😊

If you have any more details or encounter further issues, feel free to share them here.

Thank you for your patience and support!

**Comment by yogendrasinghx** [comment]
@Passportmr Thank you for bringing this to our attention. We’ve recently released an update, version 0.9.25, which addresses issues with loading and downloading user models on Android. This should resolve the need to exit and re-enter the app to load models.

Please update to version 0.9.25. If the problem persists, try uninstalling and reinstalling the app for a fresh start. Your feedback is greatly appreciated—thank you for helping us improve!
