### ISSUE TITLE
ultralytics hub pro

### ISSUE THREAD

**Issue by wgET6e9Zykh3ez** [ultralytics/hub#837]
###  ultralytics pro

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

do i get limited on compute units? like what google does in google colab?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @wgET6e9Zykh3ez, thank you for your inquiry about the [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀!

Regarding your question about compute units, the Ultralytics HUB does offer different tiers of access, which can include limits on compute resources, similar to platforms like Google Colab. Each plan may have different resource allocations, so it's essential to check the HUB's subscription details to understand the specific limits.

For detailed information on subscription plans and their limits, please explore the [HUB Pricing Page](https://ultralytics.com/pricing) and ensure you choose the plan that suits your computational needs.

🔍 If you're encountering any issues or have more specific questions about usage:

- Consider providing detailed information about your use case or any specific limitations you've encountered. This will help us assist you more effectively.
- For any bugs, please share screenshots and step-by-step instructions to help us reproduce the issue. You can find guidance on how to create a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/).

Your question will also be reviewed by an Ultralytics engineer who will assist shortly. Thank you for your patience and for choosing Ultralytics! 😊

**Comment by sergiuwaxmann** [comment]
@wgET6e9Zykh3ez  Hello!

The PRO Plan will give you access to the Cloud Training feature. You have to top-up your account balance which is used for during Cloud Training.

Here are some relevant docs pages:
https://docs.ultralytics.com/hub/pro
https://docs.ultralytics.com/hub/pro#account-balance
https://docs.ultralytics.com/hub/cloud-training
https://docs.ultralytics.com/hub/inference-api#dedicated-inference-api
