### ISSUE TITLE
Problem to upload final result

### ISSUE THREAD

**Issue by GisAdminLKSPN** [ultralytics/hub#84]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

after succesfully training i becomes an error ( looks like is a problem with upload the final result to the hub).

ValueError                                Traceback (most recent call last)
[<ipython-input-12-09ef5983e46a>](https://localhost:8080/#) in <module>
----> 1 ultralytics.start("b77a6be53dca0ee50a7f9805f3443cfae8a4be8a7a_J9wHRe2E2Ng86tpHKLA9")

7 frames
[/usr/local/lib/python3.7/dist-packages/ultralytics/hub_logger.py](https://localhost:8080/#) in on_train_end(self, *args, **kwargs)
     56     def on_train_end(self, *args, **kwargs):
     57         # Upload final model and metrics with exponential standoff
---> 58         last, best, plots, epoch, results = args[:5]
     59         LOGGER.info(emojis(f"{PREFIX}Training completed successfully ✅"))
     60         LOGGER.info(f"{PREFIX}Uploading final {self.model_id}")

ValueError: not enough values to unpack (expected 5, got 4)

the hub says .... "training 100% complete" and the preview works ....

### Environment

- google Colab

**Comment by glenn-jocher** [comment]
@GisAdminLKSPN thanks for the bug report! This has since been fixed. I'll close this issue but please let us know if you have any other problems or feature requests.
