### ISSUE TITLE
Model 100% trained in Google Colab but Lagging in 

### ISSUE THREAD

**Issue by ShadesofPocket** [ultralytics/hub#843]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

As explained in the title, the model is 100% trained in googlecolab but Ultralytics HUB states training in progress 2% despite graphs for all Epochs being displayed
![image](https://github.com/user-attachments/assets/f344ad0f-e4f4-477b-b0f9-f3f8b75f5698)

![image](https://github.com/user-attachments/assets/6b4ef7a9-3b27-4c8e-b7b9-e5fdc9e22bac)

### Environment

GoogleColab

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ShadesofPocket, thank you for raising an issue about the [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀! We're here to help. Please check out our [HUB Docs](https://docs.ultralytics.com/hub) for more information:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Begin training and deploying YOLO models with ease.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models). Find details on training YOLOv5 and YOLOv8 models and exporting them in various formats.
- [**Integrations**](https://docs.ultralytics.com/hub/integrations). Explore integration options, including TensorFlow and OpenVINO.

If this is a 🐛 Bug Report, please provide a minimum reproducible example (MRE) along with any screenshots to help us troubleshoot the issue effectively. You can learn more about creating an MRE [here](https://docs.ultralytics.com/help/minimum_reproducible_example/).

If this is a ❓ Question, please include details about your dataset, model, and environment to help us assist you better.

An Ultralytics engineer will review your issue soon. Thanks for your patience! 😊

**Comment by sergiuwaxmann** [comment]
@ShadesofPocket It looks like your model's metrics and weights were not uploaded during training with Colab. Unfortunately, you'd have to start the training again as there isn't a way to fix this issue.

**Comment by ShadesofPocket** [comment]
@sergiuwaxmann,

Thank you for the response!
Yes I restarted the training and seemed to work second time around.

Many thanks for your help!

**Comment by sergiuwaxmann** [comment]
@ShadesofPocket No worries! Apologies for the inconvenience.
