### ISSUE TITLE
Model Results Understanding

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/hub#85]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Does this mean my model overfit?
![image](https://user-images.githubusercontent.com/97718899/186286556-873fa915-ca7c-49f3-9f5f-6b8b28526a92.png)
![image](https://user-images.githubusercontent.com/97718899/186286607-d998a596-58bb-4f35-af7e-03c624f4dd1d.png)
![image](https://user-images.githubusercontent.com/97718899/186286627-dd383308-fdfd-4ef5-af89-6eff5294da74.png)

### Additional

Please give me the insight about these curves

**Comment by glenn-jocher** [comment]
@rexayyy no, the opposite. You're model has not started overfitting and thus you have not trained long enough.
