### ISSUE TITLE
Probar mi modelo en app IOS 

### ISSUE THREAD

**Issue by Damianjam23** [ultralytics/hub#852]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Quisiera saber cómo pruebo mi proyecto ya entrenado y listo en la app, ya descargué el formato .mlmodel pero no me aparece

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Damianjam23, thank you for raising an issue about [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀! Please explore our [HUB Docs](https://docs.ultralytics.com/hub) for further assistance:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Kickstart your training and deploying journey with HUB.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app). Discover how to run models on your mobile device.
  * [**iOS**](https://docs.ultralytics.com/hub/app/ios). Learn about YOLO CoreML models on Apple's Neural Engine.

If this is a 🐛 Bug Report, please share screenshots and steps to [reproduce](https://docs.ultralytics.com/help/minimum_reproducible_example/) your issue. This helps us investigate and address it more effectively.

We appreciate your patience and effort. An Ultralytics engineer will also assist you soon! 😊

**Comment by pderrenger** [comment]
@Damianjam23 ¡Hola! 😊

Para probar tu modelo entrenado en la app de Ultralytics para iOS, sigue estos pasos:

1. **Asegúrate de estar usando la última versión de la app**: Esto es importante para garantizar que todas las funcionalidades estén disponibles y que cualquier problema previo haya sido resuelto.

2. **Sube tu modelo a Ultralytics HUB**: Si aún no lo has hecho, asegúrate de que tu modelo esté cargado en la plataforma Ultralytics HUB. Esto te permitirá acceder a él desde la app.

3. **Inicia sesión en la app**: Abre la app de Ultralytics en tu dispositivo iOS y asegúrate de haber iniciado sesión con la misma cuenta que usaste para subir tu modelo al HUB.

4. **Selecciona tu modelo**: Una vez dentro de la app, deberías ver una lista de tus modelos entrenados. Si tu modelo no aparece, verifica que esté correctamente cargado en el HUB y que la app esté sincronizada.

5. **Prueba el modelo**: Concede los permisos necesarios para que la app acceda a la cámara de tu dispositivo. Luego, selecciona tu modelo y apunta la cámara hacia los objetos que deseas detectar. La app debería mostrar las detecciones en tiempo real.

Si sigues teniendo problemas para ver tu modelo en la app, asegúrate de que el archivo .mlmodel esté correctamente exportado y compatible con Core ML. Si el problema persiste, no dudes en compartir más detalles aquí para que podamos ayudarte mejor.

¡Espero que esto te ayude a comenzar! 🚀
