### ISSUE TITLE
No aparece el proyecto creado por la web en la app

### ISSUE THREAD

**Issue by Damianjam23** [ultralytics/hub#859]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Projects

### Bug

No aparece mi proyecto creado en la web en la app. Ya tengo todo actualizado y vinculado pero aún así no aparece. Utilizo un iPhone 12. Ya seguí todas las indicaciones de su página y sigue sin solución 

### Environment

iPhone 12 y window 10

**Comment by UltralyticsAssistant** [comment]
👋 Hola @Damianjam23, gracias por informar sobre este problema en el [repositorio Hub de Ultralytics](https://github.com/ultralytics/hub) 🚀. Aquí tienes algunos recursos útiles que podrías revisar:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart): Comienza a entrenar y desplegar modelos YOLO con HUB en segundos.
- [**Proyectos: Creación y Gestión**](https://docs.ultralytics.com/hub/projects): Agrupa tus modelos en proyectos para una mejor organización.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app): Aprende sobre la aplicación Ultralytics para iOS y Android.
  * [**iOS**](https://docs.ultralytics.com/hub/app/ios): Información sobre modelos YOLO CoreML acelerados en el Neural Engine de Apple en iPhones y iPads.

Para ayudarnos a resolver este 🐛 problema, ¿podrías proporcionar un ejemplo mínimo reproducible (MRE)? Aquí hay una guía sobre cómo crear un [ejemplo reproducible](https://docs.ultralytics.com/help/minimum_reproducible_example/).

Este es un mensaje automatizado, pero pronto un ingeniero de Ultralytics te asistirá. ¡Gracias por tu paciencia! 😊

**Comment by Damianjam23** [comment]
![IMG_5168](https://github.com/user-attachments/assets/3d344421-2c82-44ae-81a9-57d119c8e5e9)
web y app 
![IMG_5169](https://github.com/user-attachments/assets/5a55f2dd-7787-4c61-89e2-aa6d0673e252)

**Comment by pderrenger** [comment]
Hola @Damianjam23,

Gracias por compartir las capturas de pantalla. Para abordar este problema, asegúrate de que tanto la aplicación como la web estén sincronizadas con la misma cuenta. Aquí hay algunos pasos que podrías seguir:

1. **Verificar Conexión**: Asegúrate de que tu dispositivo esté conectado a internet y que no haya problemas de conectividad.

2. **Cerrar Sesión y Volver a Iniciar**: Intenta cerrar sesión en la aplicación y volver a iniciarla para forzar una sincronización.

3. **Actualizar la App**: Asegúrate de que estás utilizando la última versión de la aplicación en tu iPhone. Puedes verificar actualizaciones en la App Store.

4. **Limpiar Caché**: A veces, limpiar la caché de la aplicación puede resolver problemas de sincronización.

5. **Revisar Permisos**: Asegúrate de que la aplicación tenga los permisos necesarios para acceder a internet y sincronizar datos.

Si el problema persiste después de estos pasos, por favor verifica si el problema es reproducible en la última versión de la aplicación y háznoslo saber. Estamos aquí para ayudarte. 😊

¡Gracias por tu paciencia y colaboración!

**Comment by yogendrasinghx** [comment]
@Damianjam23 Thank you for your patience and for providing details about the issue. We’ve recently released an update to the app, version` 0.9.25`, which includes a fix for project visibility in the iOS and Android Ultralytics HUB apps. This update should resolve the problem of your web-created projects not appearing on your iPhone.

Please update to version `0.9.25`. If the issue persists, try signing out, then uninstalling and reinstalling the app for a clean setup. Let us know if you encounter any further issues—we’re here to help! Thank you for your support and feedback.
