### ISSUE TITLE
Unable to save the weights after complete training

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/hub#86]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

I am getting an error that is prevent me to save the model even after its training is complete.
![image](https://user-images.githubusercontent.com/97718899/186508468-5747a1ab-93f3-4171-9568-a84ba02d8dd7.png)
![image](https://user-images.githubusercontent.com/97718899/186508512-01a97ceb-90ba-4e4e-8870-c3dc717314e0.png)

**Comment by rexayyy** [comment]
waiting for the response

**Comment by shubham190398** [comment]
Having the same issue.

**Comment by GisAdminLKSPN** [comment]
same here ....

**Comment by glenn-jocher** [comment]
@rexayyy @shubham190398 @GisAdminLKSPN thanks for the bug report! This YOLOv5 issue has been resolved now, please try training again with a fresh colab notebook or a new YOLOv5 git clone, and let us know if you run into any other problems or have any feature ideas for HUB!
