### ISSUE TITLE
When the dataset is uploaded, it doesn't read any test dataset images. It only reads the training and validation data.

### ISSUE THREAD

**Issue by shubham190398** [ultralytics/hub#87]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Datasets

### Bug

There are no test images. 
![image](https://user-images.githubusercontent.com/104817428/186579788-fbd1c4d0-0d21-4e8e-ac8d-5152769af47b.png)

### Environment

Using Ultralytics Hub on Windows 11 with Firefox.

### Minimal Reproducible Example

1. Login to Hub
2. Upload Dataset
3. Test images aren't uploaded

**Comment by rexayyy** [comment]
there is no test image in your data or the test path is not mentioned in your .yaml file. Please check the .yaml file if you have test images

**Comment by rexayyy** [comment]
your .yaml must look like this. Leave the path empty for the hub.
![Screen Shot 2022-08-25 at 10 47 06 AM](https://user-images.githubusercontent.com/97718899/186584928-0c07b32f-b5d8-4426-9289-43e907cb49d2.png)

**Comment by rexayyy** [comment]
you must have a labels folder having the labels for train, test and val with the same names

**Comment by shubham190398** [comment]
Got it. So datasets created via roboflow need an edit in their yaml files to include the test images. Thanks a lot.

**Comment by UltralyticsAssistant** [comment]
@shubham190398 hello,

You're on the right track. When using datasets in the Ultralytics HUB, the `.yaml` file plays a crucial role in defining the paths to your training, validation, and test data. If you find that the test images are not being read, it's important to ensure that the `.yaml` file is correctly set up, referencing the correct directories for each split of your dataset.

If you are using a dataset created or exported from another service, like Roboflow, you might need to adjust the `.yaml` file manually to ensure it matches the expected format. The `.yaml` configuration should indicate the correct folder paths, and as you mentioned, if you have a labels folder, the labels for training, validation, and testing should be properly organized within it, with consistent naming conventions.

I'm glad you've found the direction to check and potentially edit the `.yaml` file helpful. If you have further questions or face any other issues, feel free to reach out. Remember that you can always refer to the Ultralytics HUB Docs for detailed guidance on configuring and using your datasets.

Best regards, and happy training!
