### ISSUE TITLE
Redirect account mail 

### ISSUE THREAD

**Issue by minstai11** [ultralytics/hub#870]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

How to redirect my account to new email address?

**Comment by UltralyticsAssistant** [comment]
👋 Hello @minstai11, thank you for reaching out about your Ultralytics HUB account query 🚀! An Ultralytics engineer will assist you shortly. In the meantime, please check out our [HUB Docs](https://docs.ultralytics.com/hub) for more information:

- [**Account Management**](https://docs.ultralytics.com/hub/account). Learn how to manage your account settings, including email updates.
- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Get started quickly with training and deploying YOLO models.
- [**Datasets**](https://docs.ultralytics.com/hub/datasets). Understand how to prepare and upload datasets.
- [**Models**](https://docs.ultralytics.com/hub/models). Explore model training and exporting options.

If you are experiencing a 🐛 Bug, please provide a [minimum reproducible example](https://docs.ultralytics.com/help/minimum_reproducible_example/) to help us investigate.

For further assistance, please make sure to provide any relevant additional details to help us assist you better.

Thank you for your patience and support! 😊

**Comment by sergiuwaxmann** [comment]
@minstai11 Hello! Unfortunately, we don't have this feature but I just added it to our backlog.

**Comment by minstai11** [comment]
Could I create another account and merge them?

**Comment by sergiuwaxmann** [comment]
@minstai11 Still not a valid option... I apologize for the inconvenience.

**Comment by minstai11** [comment]
Why disapered my datasets and trained models from both accounts?

**Comment by sergiuwaxmann** [comment]
@minstai11 What do you mean?
