### ISSUE TITLE
Experiencing Server not reachable again.

### ISSUE THREAD

**Issue by PHIKHONAMTHEMBU** [ultralytics/hub#877]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

While uploading the dataset, 

I am experiencing the server not being reachable. 

there is enough storage size 
I have validated the dataset before upload. 
![image](https://github.com/user-attachments/assets/0e2f8605-a7bd-4b77-8f2d-16664a63ba5c)
![image](https://github.com/user-attachments/assets/d9416ccf-2bcf-4266-85af-32377a7cc92f)

Project ID : 7NHnJd7goVKnjXXHMryu
Dataset Name : SKU 3.4

**Comment by UltralyticsAssistant** [comment]
👋 Hello @PHIKHONAMTHEMBU, thank you for raising an issue about the [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀!

It seems you're experiencing connectivity issues with the server while uploading your dataset. To help us look into this, could you please provide a minimum reproducible example (MRE)? This would include any specific steps or configurations you used when you encountered the issue. Screenshots or error logs you've already provided are extremely helpful—thank you!

To get more insight into HUB functionality and troubleshooting, please visit our [HUB Docs](https://docs.ultralytics.com/hub):

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Start training and deploying YOLO models with HUB in seconds.
- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets). Learn how to prepare and upload your datasets to HUB in YOLO format.
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects). Group your models into projects for improved organization.
- [**Environment**](https://docs.ultralytics.com/hub/environment). Ensure your development environment is configured correctly to support HUB operations.

An Ultralytics engineer will be looking at this shortly. We appreciate your patience while we work to resolve this for you! 😊

**Comment by pderrenger** [comment]
Hello! 😊

Thank you for your detailed question. Once a dataset is uploaded to the Ultralytics HUB, it undergoes several optimization steps primarily for dataset preview purposes. These steps include:

1. **Image Resizing**: Adjusting image dimensions for efficient preview.
2. **Format Conversion**: Ensuring all images and annotations are in a consistent format.
3. **Metadata Extraction**: Gathering essential information for quick access and display.

These optimizations are indeed for preview and do not affect the dataset used for training. To potentially speed up the process, you can pre-process your dataset by ensuring consistent image sizes and formats before uploading.

If you encounter any issues, please verify that you're using the latest version of the HUB. We continuously work on improvements, and updates might resolve existing problems.

Feel free to reach out if you have more questions or need further assistance. We're here to help! 🚀

**Comment by PHIKHONAMTHEMBU** [comment]
@pderrenger , thank you for your response, 

Could you retry my dataset upload from your end ?

I see the feature for **retry** is no longer available, only **delete** now.

**Comment by pderrenger** [comment]
Hello @PHIKHONAMTHEMBU! 😊

Thank you for reaching out. Unfortunately, I'm unable to retry the dataset upload from my end. However, I recommend checking if the issue persists with the latest version of the HUB. We frequently release updates that might resolve existing issues.

If the retry option is missing, you can try re-uploading the dataset. Before doing so, ensure your dataset is pre-processed for consistency, as this can help speed up the upload and optimization process.

If you continue to experience issues, please provide any error messages or logs you encounter. This information will help us assist you more effectively.

Feel free to ask if you have more questions or need further assistance. We're here to help! 🚀
