### ISSUE TITLE
This account is currently being deleted

### ISSUE THREAD

**Issue by MazenVR** [ultralytics/hub#879]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hello! An error occurs when logging into my Google account: This account is currently being deleted. Please restore my account:
mohamed.hussein.work@gmail.com

Thanks

**Comment by UltralyticsAssistant** [comment]
👋 Hello @MazenVR, thank you for raising an issue about the [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀!

While our team investigates this, I recommend checking out the [HUB Docs](https://docs.ultralytics.com/hub) for more information:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Get started with training and deploying YOLO models quickly.
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects). Organize models effectively using projects.

Regarding your issue, please ensure you've provided all relevant details. An Ultralytics engineer will assist you soon. If this involves a 🐛 bug, providing steps to [reproduce](https://docs.ultralytics.com/help/minimum_reproducible_example/) the issue can speed up the process.

Thank you for your patience and understanding! 😊

**Comment by sergiuwaxmann** [comment]
@MazenVR Your account was restored.
