### ISSUE TITLE
Training Failed after the completion of Epochs

### ISSUE THREAD

**Issue by rexayyy** [ultralytics/hub#88]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Training

### Bug

![image](https://user-images.githubusercontent.com/97718899/186976762-dc523808-8a50-4651-a32b-ac92b4f89a0a.png)

### Minimal Reproducible Example

Ultralytics Hub
Windows
Training

**Comment by glenn-jocher** [comment]
@rexayyy thanks for the bug report! This YOLOv5 issue has been resolved now, please try training again with a fresh colab notebook or a new YOLOv5 git clone, and let us know if you run into any other problems or have any feature ideas for HUB!
