### ISSUE TITLE
weights & Biases

### ISSUE THREAD

**Issue by jchida** [ultralytics/hub#892]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

TRyng to train a model I found this warning:
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

What's this and where can I find that API Key?

**Comment by glenn-jocher** [comment]
@jchida apologies, looks like this is a new package in Google Colab. Working on a solution now.

**Comment by UltralyticsAssistant** [comment]
@jchida this should be resolved in https://github.com/ultralytics/ultralytics/pull/17023 now. If you run your same training or another one in a new Google Colab notebook everything should work correctly without any W&B prompt. 

Please let us know if this works!
