### ISSUE TITLE
Multiple GPU for Train Model

### ISSUE THREAD

**Issue by technew14** [ultralytics/hub#897]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

I want features like Multigpu access feature in Train Model.When we train new model In Ultralytics Hub.The HUB consists of many features to use like select dataset (1),model(2),train model in Google colab or other notebook.I want features in select model(2) When I want train the yolo11x model in multiple GPUs there is no option.only select the Auto,GPU,MPU,CPU.when we select the GPU it shows default choice for GPU is cuda 0.I am train the model in Kaggle Notebook because they offers free gpu like T4 GPUx2 .So I really want to use both T4 GPU training.There is no option under selecting GPU.I want When selecting GPU it shows some under option to select single GPU , multiple GPU.Multiple GPU detects all the gpus present and utilize all GPU to reduce time and increase batch size.Each GPU offers 15gb vram,totally 30gb vram approximately.Only it was the draw back .I think there is an mistake in ultralytics package.because when I install the package it only detects the single cuda 0 ,shows 15gb only vram.But I ran some detect GPU in notebook that shows 2 GPU present.nvidia-smi command also shows cuda 0,cuda 1 is present.So I want to use multiple GPU.i research parallel utilizing.In pytorch there is an DP,DDP also there.I didn't know how to use.I am new to this ML.I was basically a mechIanical engineer,not a developer or coder.

### Use case

Access multiple GPUs.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @technew14, thank you for raising this issue about [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀! It's great to see your interest in utilizing multiple GPUs for model training. An Ultralytics engineer will be with you soon to assist further.

In the meantime, please check out our [HUB Docs](https://docs.ultralytics.com/hub) which provide helpful guidance on leveraging HUB's features:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Begin training and deploying YOLO models with HUB quickly and efficiently.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models). Learn more about training your models, including how to manage hardware settings.
- [**Etc.**](https://docs.ultralytics.com/hub). Explore other documentation to make the most of your HUB experience.

For 🐛 Bug Reports, please supply screenshots and a minimum reproducible example (MRE). Our guide on [creating an MRE](https://docs.ultralytics.com/help/minimum_reproducible_example/) can assist you.

Your detailed feature suggestion for multi-GPU setup is valuable. For advanced configuration like this, make sure to document:

- Specific steps or commands you've tried to initiate multiple GPU usage.
- Outputs from commands like `nvidia-smi`.
- Environment details, including the type of notebook and packages used.

Thank you for your feedback and patience as we work towards optimizing Ultralytics HUB for multi-GPU capabilities! 🌟

**Comment by sergiuwaxmann** [comment]
@technew14 Did you see this?
https://github.com/ultralytics/hub/issues/601#issuecomment-2046943691

**Comment by technew14** [comment]
> @technew14 Did you see this? [#601 (comment)](https://github.com/ultralytics/hub/issues/601#issuecomment-2046943691)

@sergiuwaxmann Thanks for reply me.I already see that custom.But i didn't know how to change in hub.I think that was predefined value(default) for "device".The command device UI was fully surrounded by green box.It didn't highlight digit to be change.so i didnt notice that digit to be change.
