### ISSUE TITLE
The app is unable to use my camera.

### ISSUE THREAD

**Issue by shubham190398** [ultralytics/hub#90]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

After training a model and exporting it to TFLite and Ultralytics Android format, I tried using the app on my device (OnePlus Nord 2 CE Lite 5G). However, while I was able to sign in without issue, the app doesn't detect anything as it shows a black screen. I checked my permissions, and hub is allowed to use the camera, so I am not sure where the issue is.

**Comment by glenn-jocher** [comment]
@shubham190398 thanks for the bug report! Can you uninstall and re-install the app and double check that you are enabling permissions?

@sergiossm please add a TODO to notify users on declined permissions

**Comment by shubham190398** [comment]
@glenn-jocher I did that yesterday which didn't work, but it is working today! Not sure what the problem was.

**Comment by shubham190398** [comment]
@glenn-jocher Okay, this might be related to the issue above. So the camera functionality stops working if I rapidly shift from one model to another in a short time. Restarting the app doesn't work to fix it, so I had to reinstall it again.

**Comment by glenn-jocher** [comment]
@shubham190398 that's funny, I thought it was too hard to switch between models fast enough so we are working on a refreshed app that allows for much simpler model changing. Are there steps we can take to reproduce the problem?

**Comment by shubham190398** [comment]
@glenn-jocher Sorry for the late reply! An easy way in which I could replicate the bug multiple times is as follows:

1. Sign in to my UH account
2. Choose one of the default models
3. Go to Detect
4. Then go back and choose another one of the default models
5. Again go to Detect
6. Then choose one of my custom models

By this time, the camera screen is black and restarting the app doesn't make a difference. Need to reinstall it.

**Comment by glenn-jocher** [comment]
@shubham190398 got it, thanks!

@sergiossm please try to replicate this and debug if there are any issues.
