### ISSUE TITLE
issue with Ultralytics Dedicated Inference API

### ISSUE THREAD

**Issue by KaramRazooq** [ultralytics/hub#923]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

I have recently generated a new endpoint for my project, but whenever I execute it, I receive a “503 Service Unavailable” error. I have attempted to replicate this issue with other models, and the result is consistent. It is uncertain whether this is an ongoing problem. I have taken the following steps to address the issue:
- Restarting the token
- Turning the endpoint on and off
- Waiting for over a day
- Utilizing different networks and implementing various troubleshooting methods, yet the error persists.

**Comment by UltralyticsAssistant** [comment]
👋 Hello @KaramRazooq, thank you for raising an issue about the [Ultralytics HUB](https://github.com/ultralytics/hub) 🚀! We're sorry to hear you're experiencing issues with the Dedicated Inference API. 

For more information and guidance, you can explore our comprehensive [HUB Docs](https://docs.ultralytics.com/hub) to learn more about setting up and using the platform effectively:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart): Discover how to launch and use HUB efficiently.
- [**Inference API**](https://docs.ultralytics.com/hub/inference-api): Learn how to set up and troubleshoot the Inference API.

As this is a 🐛 Bug Report, we'd greatly appreciate it if you could provide a minimal reproducible example (MRE). This will help our engineers diagnose and resolve the issue more effectively. Please include any relevant code snippets, configurations, and any steps you took that led to this error. You can learn more about creating an MRE [here](https://docs.ultralytics.com/help/minimum_reproducible_example/).

Our dedicated team is here to help, and an Ultralytics engineer will look into your issue shortly. Thank you for your patience and understanding! 😊

**Comment by sergiuwaxmann** [comment]
@KaramRazooq Apologies for the inconvenience.
Can you please share your model ID with us so we can investigate this internally?

CC @yogendrasinghx

**Comment by glenn-jocher** [comment]
@yogendrasinghx @sergiuwaxmann all tests passing for inference API for me, I don't see any errors.

**Comment by glenn-jocher** [comment]
@KaramRazooq I'm able to reproduce this. This is our fault for deploying outdated images, we're working on a fix and should have this resolved soon.

**Comment by glenn-jocher** [comment]
Closing issue as should be resolved now.
