### ISSUE TITLE
Account been deleted

### ISSUE THREAD

**Issue by iEric0228** [ultralytics/hub#926]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### Bug

When I logged in it says the account is been deleted

**Comment by UltralyticsAssistant** [comment]
👋 Hello @iEric0228, thank you for reaching out about an issue with your account on Ultralytics HUB 🚀! We're sorry to hear that you're experiencing this problem. Please ensure you have searched the GitHub issues to see if similar problems have been reported.

If this is a 🐛 Bug Report, could you provide a bit more detail to help us diagnose the issue? Specifically, steps to reproduce the problem and any relevant screenshots would be greatly appreciated. This information helps us get started on a fix as quickly as possible.

If this is a ❓ Question, please provide as much background information as you can, such as your account details, any recent changes you made, and the environment you’re using.

Our team is committed to addressing issues promptly, and an Ultralytics engineer will be with you soon to assist further. Thank you for your patience and understanding! 😊

**Comment by iEric0228** [comment]
I don’t know if I accidentally press the wrong button or it’s a bug. But when I login it says the account is currently being deleted.  It’s there any way to restore it? My email is oiso751230@gmail.com

**Comment by pderrenger** [comment]
@iEric0228 hello,

Thank you for reaching out and bringing this to our attention. It sounds like there might be an issue with your account status. First, please ensure that you are using the latest version of the Ultralytics HUB platform, as updates may resolve unexpected issues.

If the problem persists, I recommend visiting the [Ultralytics HUB Support](https://hub.ultralytics.com/support) page to report this issue. When reporting, please include any relevant details about your environment and actions leading up to the problem, as this will help our team investigate further.

Additionally, you can restore deleted accounts from the [Trash](https://hub.ultralytics.com/trash) page if this feature is available for your account type. If you don't see this option, our support team will be able to assist you further.

For privacy reasons, please avoid sharing personal information like your email in public forums. If you need further assistance, feel free to join our [Discord community](https://discord.com/invite/ultralytics) where you can engage with other users and get support.

We appreciate your patience and understanding. 😊

**Comment by sergiuwaxmann** [comment]
@iEric0228 Hello!
Can you share you account's email?

**Comment by pderrenger** [comment]
Hello @iEric0228,

Thank you for providing your email. To address the issue with your account, please ensure that you are using the latest version of the Ultralytics HUB platform, as updates can often resolve unexpected issues.

If your account is still marked for deletion and you haven't initiated this action, it might be a bug. I recommend reporting this directly on the [Ultralytics HUB Support](https://hub.ultralytics.com/support) page. When submitting your report, include any relevant details about your environment and actions leading up to the issue, as this will assist our team in investigating further.

Additionally, if your account has been moved to the Trash, you might be able to restore it from the [Trash](https://hub.ultralytics.com/trash) page, if this feature is available for your account type.

For privacy and security reasons, please avoid sharing personal information like your email in public forums. If you need further assistance, feel free to join our [Discord community](https://discord.com/invite/ultralytics) where you can engage with other users and get support.

We appreciate your patience and understanding. 😊

**Comment by sergiuwaxmann** [comment]
@iEric0228 Your account was reactivated. Apologies for the inconvenience.
