### ISSUE TITLE
Support for Multi GPU Training

### ISSUE THREAD

**Issue by nicomattes** [ultralytics/hub#93]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar feature requests.

### Description

Being able to select how many GPUs should be used for training like command line YOLOv5

### Use case

It accelerates training a lot

**Comment by glenn-jocher** [comment]
@nicomattes thanks for the feedback! Yes you are right. We will integrate Multi-GPU training in the future, for now we've focused mostly on supporting Colab-like environments.
