### ISSUE TITLE
Account Recovery

### ISSUE THREAD

**Issue by HazwanMohaimin** [ultralytics/hub#936]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Signin

### Bug

Hi Community.
Is there any way to recover back or resuse back my previous account Ultralytics? I accidently delete it, when I try to login it keep mention
'Firebase: The email address is already in use by another account. (auth/email-already-in-use).'

here is my email
hazwanmohaimin@gmail.com

**Comment by sergiuwaxmann** [comment]
@HazwanMohaimin Your account was reactivated.
