### ISSUE TITLE
Android detect mode doesn't work 

### ISSUE THREAD

**Issue by dubrovin-sudo** [ultralytics/hub#98]
Detect mode doesn't work, black screen instead of camera

**Comment by kalenmike** [comment]
Hey @dubrovin-sudo, thanks for raising an issue. Did you accept the camera permissions? Also could you specify which device you are using please?

**Comment by dubrovin-sudo** [comment]
@kalenmike Sure, I accepted the camera permissions. Xiaomi MI 9 and Huawei P30.

**Comment by sergiossm** [comment]
@dubrovin-sudo Thanks for reporting the issue, we'll take a look into it. 

We're working on a major update for the app, we'll make sure the bug is fixed in the new version.

**Comment by smbunn** [comment]
Have same issue on my Huawei P30Pro. Camera permissions are all good

**Comment by glenn-jocher** [comment]
@smbunn thanks for the bug report! 

We should be releasing a new version on both Android and iOS early this week that should address this issue. @sergiossm

**Comment by dubrovin-sudo** [comment]
> @smbunn thanks for the bug report! 
> 
> We should be releasing a new version on both Android and iOS early this week that should address this issue. @sergiossm 

When do you guys expect an update for the Android app?

**Comment by sergiossm** [comment]
@dubrovin-sudo version 0.3.3 is available on [Android](https://play.google.com/store/apps/details?id=com.ultralytics.ultralytics_app). Please, uninstall the previous version before updating the app, and let us know if the issue persists.

Thanks!
