### ISSUE TITLE
Upload yolov5 pt file

### ISSUE THREAD

**Issue by jgoo9410** [ultralytics/hub#99]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Is it possible to upload a yolov5 model I have trained locally to my Ultralytics account in order to run it on my iPhone via the Ultralytics app?

I can't see anywhere that would allow me to do this in my account

**Comment by glenn-jocher** [comment]
@jgoo9410 thanks for the feedback! We've had similar feature requests a few times now, so we have put this in our product roadmap for deployment in the next few months.

**Comment by jgoo9410** [comment]
Thanks @glenn-jocher. I’ve spent the last half an hour trying to trick the colab script into uploading my model instead, to no avail you’ll be pleased to hear 😂

**Comment by jgoo9410** [comment]
Thanks. Just to clarify, if I train using Hub, will my model and dataset remain private to my account, or will it be publicly accessible?
